seqan/seqan3

include/seqan3/alignment/matrix/detail/alignment_matrix_column_major_range_base.hpp, include/seqan3/core/simd/view_to_simd.hpp, include/seqan3/range/views/async_input_buffer.hpp, include/seqan3/range/views/enforce_random_access.hpp, include/seqan3/range/views/interleave.hpp, include/seqan3/range/views/kmer_hash.hpp, include/seqan3/range/views/pairwise_combine.hpp, include/seqan3/range/views/persist.hpp, include/seqan3/range/views/repeat.hpp, include/seqan3/range/views/single_pass_input.hpp, include/seqan3/range/views/take.hpp, include/seqan3/range/views/take_until.hpp, include/seqan3/range/views/translate.hpp, include/seqan3/range/views/translate_join.hpp, test/unit/range/views/view_pairwise_combine_test.cpp, test/unit/range/views/view_persist_test.cpp, test/unit/range/views/view_repeat_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/143 and  https://github.com/seqan/product_backlog/issues/142.
* `cbegin()` and `cend()` are removed from views, because standard views don't have them.
*  For all views `std::ranges::cbegin` and `std::ranges::cend` are used in the const overload of `begin()` and `end()`.
For `persist_view` a const overload of `begin()` and `end()` with return type `auto` were required to make this work.
=> Cbegin cend

test/snippet/io/sequence_file/sequence_file_output_view_pipeline.cpp
Resolves https://github.com/seqan/seqan3/issues/1993
The 93983 was fixed, but the https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96070 is till present.
See also https://github.com/seqan/product_backlog/issues/151
=> [FIX] gcc10.2: workaround for stl defect

CHANGELOG.md, include/seqan3/alignment/configuration/align_config_on_result.hpp, include/seqan3/core/semiregular_box.hpp, include/seqan3/range/views/take_until.hpp, include/seqan3/search/configuration/all.hpp, include/seqan3/search/configuration/detail.hpp, include/seqan3/search/configuration/on_result.hpp, include/seqan3/search/detail/policy_max_error.hpp, include/seqan3/search/detail/policy_search_result_builder.hpp, include/seqan3/search/detail/search_scheme_algorithm.hpp, include/seqan3/search/detail/search_traits.hpp, include/seqan3/search/detail/unidirectional_search_algorithm.hpp, include/seqan3/search/search.hpp, test/snippet/search/configuration_on_result.cpp, test/snippet/search/search_with_user_callback.cpp, test/unit/search/configuration/CMakeLists.txt, test/unit/search/configuration/on_result_test.cpp, test/unit/search/search_configuration_test.cpp, test/unit/search/search_test.cpp
Supersedes #2012 
fixes seqan/product_backlog#169
=> Search confguration/on result release

CHANGELOG.md, doc/tutorial/ranges/index.md, include/seqan3/range/views/all.hpp, include/seqan3/range/views/trim_quality.hpp, test/snippet/range/views/trim_dna5q.cpp, test/snippet/range/views/trim_phred42.cpp, test/unit/range/views/view_trim_test.cpp
Fixes https://github.com/seqan/product_backlog/issues/146.
=> [MISC] rename seqan3::views::trim to seqan3::views::trim_quality

test/unit/range/iterator_test_template.hpp
This PR is collection of changes to the iterator_test_template.
It
* introduces new functions `expect_iter_equal` and `expect_iter_value_equal` which allows to compare the iterator instead of only the value of the iterator.
* improves some tests with regard to C++20 input_iterators.
* improves some tests by testing more cases.
This is part of seqan/product_backlog#62
=> [TEST] iterator_test_template

include/seqan3/alignment/configuration/align_config_aligned_ends.hpp, include/seqan3/alignment/configuration/align_config_alignment_result_capture.hpp, include/seqan3/alignment/configuration/align_config_band.hpp, include/seqan3/alignment/configuration/align_config_debug.hpp, include/seqan3/alignment/configuration/align_config_gap.hpp, include/seqan3/alignment/configuration/align_config_max_error.hpp, include/seqan3/alignment/configuration/align_config_method.hpp, include/seqan3/alignment/configuration/align_config_on_result.hpp, include/seqan3/alignment/configuration/align_config_parallel.hpp, include/seqan3/alignment/configuration/align_config_result.hpp, include/seqan3/alignment/configuration/align_config_scoring.hpp, include/seqan3/alignment/configuration/align_config_vectorised.hpp, include/seqan3/alignment/configuration/all.hpp, include/seqan3/core/all.hpp
=> [FIX] add namespace seqan3::align_cfg::detail

CHANGELOG.md, README.md, include/seqan3/core/platform.hpp, include/seqan3/std/iterator, include/seqan3/std/ranges, include/seqan3/std/span, test/include/seqan3/test/seqan2.hpp
Fixes https://github.com/seqan/product_backlog/issues/170
Fixes https://github.com/seqan/product_backlog/issues/48
=> [INFRA] Update the ranges-v3 library to 0.11.0

.github/workflows/documentation.yaml, .travis.yml
The prebuilt doxygen we use now needs libclang and glib>=2.29 (i.e. ubuntu 20.04).
Technically, focal is only provided as preview for github actions...
Fixes #2015
=> [MISC] Use doxygen 1.8.19

include/seqan3/alignment/all.hpp, include/seqan3/alignment/configuration/align_config_debug.hpp, include/seqan3/alignment/configuration/align_config_gap.hpp, include/seqan3/alignment/configuration/detail.hpp, include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/alignment_result.hpp, test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
Resolves https://github.com/seqan/product_backlog/issues/181
Blocked by #2033
=> [FEATURE] Alignment Configuration: put align_cfg::debug to align_cfg::detail::debug

test/unit/range/views/view_single_pass_input_test.cpp
clang complained:
```c++
error: member access into incomplete type 'single_pass_input<std::__1::vector<char, std::__1::allocator<char>>>'
decltype(std::declval<single_pass_input>().get_data()) data;
^
```
=> [TEST] simplify overly complicated decltype in single_pass_input_test

include/seqan3/core/concept/tuple.hpp
```
/seqan3/include/seqan3/core/concept/tuple.hpp:180:54: error: '&&' within '||' [-Werror,-Wlogical-op-parentheses]
detail::tuple_get<remove_cvref_t<t>> &&
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/seqan3/include/seqan3/core/concept/tuple.hpp:180:54: note: place parentheses around the '&&' expression to silence this warning
detail::tuple_get<remove_cvref_t<t>> &&
^
(
```
=> [FIX] clang: -Wlogical-op-parentheses

include/seqan3/alignment/configuration/align_config_aligned_ends.hpp, include/seqan3/alignment/configuration/align_config_alignment_result_capture.hpp, include/seqan3/alignment/configuration/align_config_gap.hpp, include/seqan3/alignment/configuration/align_config_max_error.hpp, include/seqan3/alignment/configuration/align_config_method.hpp, include/seqan3/alignment/configuration/align_config_scoring.hpp, include/seqan3/alignment/configuration/align_config_vectorised.hpp, include/seqan3/core/algorithm/configuration.hpp, include/seqan3/core/algorithm/configuration_element_debug_mode.hpp, include/seqan3/core/algorithm/pipeable_config_element.hpp, include/seqan3/search/configuration/hit.hpp, include/seqan3/search/configuration/max_error.hpp, include/seqan3/search/configuration/output.hpp, include/seqan3/search/configuration/result_type.hpp, test/snippet/core/algorithm/configuration_get_or.cpp, test/unit/alignment/configuration/align_config_aligned_ends_test.cpp, test/unit/core/algorithm/configuration_mock.hpp, test/unit/core/algorithm/pipeable_config_element_test.cpp, test/unit/core/algorithm/pipeable_config_element_test_template.hpp
Resolves https://github.com/seqan/product_backlog/issues/118
The only class which is allowed to construct `pipeable_config_element<...>{}` is the derived class of `pipeable_config_element<...>{}`. `pipeable_config_element<...>{}` befriends the derived class (this makes private members accessible for the derived class).
=> No base class construction pipeable_config_element

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/scoring/detail/simd_match_mismatch_scoring_scheme.hpp, include/seqan3/alignment/scoring/detail/simd_matrix_scoring_scheme.hpp, include/seqan3/alignment/scoring/scoring_scheme_concept.hpp, test/unit/alignment/scoring/scoring_scheme_test.cpp
Renames the scoring scheme concept to scoring_scheme_for to adhere the standard's naming conventions for concepts with additional template arguments.
resolves seqan/product_backlog#196
=> [API] Rename scoring_scheme to scoring_scheme_for

CHANGELOG.md, include/seqan3/io/alignment_file/format_bam.hpp, include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/output.hpp, include/seqan3/io/stream/iterator.hpp, include/seqan3/range/concept.hpp, include/seqan3/range/views/drop.hpp, include/seqan3/range/views/slice.hpp, include/seqan3/range/views/take.hpp, include/seqan3/range/views/type_reduce.hpp, include/seqan3/std/ranges, include/seqan3/std/span, test/snippet/io/detail/iterator_write_range.cpp
Part of https://github.com/seqan/product_backlog/issues/49
=> [FIX] use std::ranges::borrowed_range instead of seqan3::forwarding_range

include/seqan3/alignment/configuration/align_config_output.hpp
This makes the code already compatible to the master branch which requires the explicit definition of the configurations.
resolves seqan/product_backlog#179
=> [MISC] Add constructors to output configurations.

.github/workflows/ci.yml, README.md
We can set travis to not build on pushed branches and pull requests. 
I would then maybe use travis to run the CI as a nightly on multiple CPU architectures.
Note:
The build-folder of the documentation (containing doc_dev and doc_usr) is provided as an artefact after the job ran. You can download it from the `checks` tab and then click `artifacts` on the top right or `SeqAn3 CI` on the left and find it there.
The artefact is only available after the **whole** (all test suites / compilers - not just the documentation job) GitHub actions run is complete - this is a limitation on GitHub's side.
The artifact will always be zipped (also a limitation on GitHub's side). That means the documentation will be provided as `documentation.tar.gz.zip`.
=> [INFRA] GitHub CI

test/unit/range/views/view_deep_test.cpp
An earlier build of gcc10 had problems with this use case.
=> [TEST] add a regression test to seqan3::views::deep

doc/tutorial/pairwise_alignment/pa_assignment_3_solution.cpp, doc/tutorial/pairwise_alignment/pairwise_alignment_solution_2.cpp, doc/tutorial/pairwise_alignment/pairwise_alignment_solution_4.cpp, doc/tutorial/pairwise_alignment/pairwise_alignment_solution_5.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/read_mapper/read_mapper_step4.cpp, doc/tutorial/search/search_solution5.cpp, test/performance/io/format_sam_benchmark.cpp, test/snippet/alignment/configuration/align_cfg_edit_example.cpp, test/unit/alignment/pairwise/alignment_configurator_test.cpp, test/unit/alignment/pairwise/fixture/semi_global_affine_banded.hpp, test/unit/alignment/pairwise/fixture/semi_global_affine_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp, test/unit/alignment/pairwise/semi_global_affine_banded_test.cpp
=> [Alignment Configuration] Add free end gap configuration to method_global calls.

include/seqan3/alignment/configuration/align_config_method.hpp, test/unit/alignment/configuration/align_config_method_test.cpp
Applies requested change from #2032 in separate PR.
Part of #2032
=> [Alignment Configuration] Change member variables of method_global to booleans.

.github/workflows/ci.yml, test/unit/core/type_traits/range_iterator_test.cpp
Unfortunately, we can't really simplify the matrix.
If we do everything for both OS, we need to exclude the stuff we don't want - which is harder than adding the stuff we want.
You can write:
```yaml
matrix:
os: [ubuntu-20.04, macos-10.15]
```
But not
```yaml
matrix:
include:
- ...
os: [ubuntu-20.04, macos-10.15]
```
Even though both will be available as `matrix.os`. The latter will be interpreted as `ubuntu-20.04, macos-10.15` instead of `ubuntu-20.04` and `macos-10.15`.
=> [INFRA] Add macOS to GitHub actions

.jenkinsfile
Blocked by https://github.com/seqan/seqan3/pull/2071
This skips the execution of the jobs if it is not a nightly build, hence the CI just returns `success`.
Once this is in master, we can disable jenkins for PRs altogether.
=> [INFRA] Deactivate jenkins

include/seqan3/alignment/configuration/align_config_result_type.hpp, include/seqan3/alignment/configuration/align_config_vectorised.hpp, include/seqan3/alignment/configuration/all.hpp, include/seqan3/alignment/configuration/detail.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp, test/performance/alignment/edit_distance_unbanded_benchmark.cpp, test/unit/alignment/configuration/align_config_common_test.cpp, test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
Resolves seqan/product_backlog#183
This moves the alignment_result_capture to a new namespace seqan3::align_cfg::detail and then renames it to result_type.
I needed to specify the whole namespace path seqan3::detail::XX for most of the view files. This is due to the newly created seqan3::align_cfg::detail which had a name clash with seqan3::detail.
Merging this PR closes #2018 because it has the same intention.
Blocked by #2033
=> [Alignment Configuration] Rename align_cfg::alignment_result_capture to align_cfg::detail::result_type

CHANGELOG.md, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/detail/fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_test_template.hpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp, test/unit/search/fm_index_cursor/fm_index_cursor_test_template.hpp
Resolves https://github.com/seqan/seqan3/issues/2044
=> [FEATURE] Serialise index cursor

.github/workflows/ci.yml
Our current maximum workflow time is ~70 minutes for the gcc10/cpp20 build (when built from scratch).
So, if we need more than 2 hours, something went wrong, and we probably don't want to exhaust GitHub's default timeout of 6 hours.
=> [INFRA] Workflow timeout after 120 minutes

.github/workflows/ci.yml
This introduces hierarchical caching:
1. Try to restore cache from current branch.
2. Try to restore cache from base branch, i.e. `release-3.0.2` or `master`.
3. Try to restore any available cache, i.e. from any other branch.
Will look like this:
```console
with:
path: .ccache
key: Unit gcc9 (c++2a) on Linux-ccache-refs/pull/2085/merge-2020-08-31-13;28;29
restore-keys: Unit gcc9 (c++2a) on Linux-ccache-refs/pull/2085/merge
Unit gcc9 (c++2a) on Linux-ccache-release-3.0.2
Unit gcc9 (c++2a) on Linux-ccache-
env:
CMAKE_VERSION: 3.7.2
DOXYGEN_VERSION: 1.8.20
SEQAN3_NO_VERSION_CHECK: 1
TZ: Europe/Berlin
Cache not found for input keys: Unit gcc9 (c++2a) on Linux-ccache-refs/pull/2085/merge-2020-08-31-13;28;29, Unit gcc9 (c++2a) on Linux-ccache-refs/pull/2085/merge, Unit gcc9 (c++2a) on …
```
=> [INFRA] Cache more efficiently

test/include/seqan3/test/seqan2.hpp
When compiling with `-std=c++20`, we need to overload the `indirectly_readable_traits` in both `ranges` and `std` namespace.
The range-v3 lib still uses its own concepts internally which then rely on `ranges::indirectly_readable_traits` being overloaded.
See https://cdash.seqan.de/viewBuildError.php?buildid=43442
=> [FIX] overload ranges::indirectly_readable_traits in cpp20 mode

.github/workflows/documentation.yaml
- Use same style as in the CI workflow
- Cache cmake/doxygen and the documentation
- Add `--omit-dir-times` to the rsync command to not try to adjust the modification time of `./` which requires ownership of the folder
=> [INFRA] Update documentation workflow

test/header/CMakeLists.txt
Fixes https://github.com/seqan/product_backlog/issues/135
=> [INFRA] seqan3/std/* header files MUST NOT include any seqan3 header

.travis.yml
- Actually use the flags I set as env variables :)
- Add `-fcompare-debug-second` to deactivate notes about changed byte alignment of some types starting with GCC5
- Always send notifications. We allow all builds to fail, i.e. we don't get notifications about failing builds
=> [FIX] travis cxx flags and notifications

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp, test/unit/alignment/pairwise/fixture/semi_global_affine_banded.hpp, test/unit/alignment/pairwise/semi_global_affine_banded_test.cpp
Enables the banded global alignment using end-positions. This is a first part of making the banded alignment vectorised.
See seqan/product_backlog#114
=> Optimise alignment/part6 enable banded end position

.codecov.yml
Resolves https://github.com/seqan/product_backlog/issues/205
My goal for now is:
* Complain in PRs about any coverage drop
* Do not complain in master if > 97%
* Make codecov independent of CI (do not fail just because CI failed, do not wait for CI to finish to post the coverage results)
=> [INFRA] Add codecov.yml

test/performance/alignment/global_affine_alignment_simd_benchmark_template.hpp
For example: https://cdash.seqan.de/viewTest.php?onlyfailed&buildid=50873
=> [FIX] Timeout in debug nightlies

include/seqan3/search/search.hpp, test/unit/search/search_collection_test.cpp, test/unit/search/search_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2115
The search algorithm uses the ranks of the given query. If the alphabet type of the query does not equal the alphabet type of the index, hits may be missed.
The index already converts the query, i.e. ,for the given example, `extend_right` on the cursor correctly returned true, but the search did not find the hits, because it used the ranks of the qualified query instead of the normal, unqualified query that the index uses.
The second commit adds a test for debug_streaming, as there was none before and coverage dropped because of this.
=> [FIX] Wrong ranks in search algorithm

include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp
I found another patch I did when investigating the search performance. I think it didn't have an significant impact but either way it is unnecessary to use two transform views if using one is equivalent.
=> [MISC] Remove unnecessary second transform from lazy_locate.

.github/workflows/documentation.yaml
The ctest command has to build the documentation to check for warnings, i.e. we do not need to build it beforehand.
=> [INFRA] Do not deploy docs if faulty

include/seqan3/range/views/async_input_buffer.hpp, include/seqan3/range/views/enforce_random_access.hpp, include/seqan3/range/views/kmer_hash.hpp, include/seqan3/range/views/pairwise_combine.hpp, include/seqan3/range/views/repeat.hpp, include/seqan3/range/views/single_pass_input.hpp, include/seqan3/range/views/take.hpp
Fixes https://github.com/seqan/product_backlog/issues/144.
Templated view iterators are renamed to 'basic_iterator', non-templated ones to 'iterator'
=> [MISC] Rename view::some_iterator_name to view::[basic_]iterator

include/seqan3/alignment/pairwise/alignment_configurator.hpp
Extracted from #2032 
Only the last commit is relevant
=> [Alignment Configuration] Adapt alignment_configurator to use the free end gap configuration from method_global

test/performance/search/search_benchmark.cpp
On my personal laptop (Linux, Ubuntu 18, GCC 7) the search algorithm was not executed in the benchmarks.
=> [TEST] Force compiler to actually execute the search algorithm.

include/seqan3/search/configuration/max_error.hpp, include/seqan3/search/detail/policy_max_error.hpp, test/unit/search/search_configuration_test.cpp
=> [MISC] Update search_cfg::max_error_substitution to recent config design changes.

test/unit/search/search_test.cpp
We have some branches in the search algorithm that are never tested...
This adds two tests that cover the last few lines - after this, the search module has 100% coverage (and currently would be the only one to achieve this....).
One test just uses 4 errors instead of 3. This activates all the cases where a dynamic search scheme is used (up to and including 3 errors we know the optimal search scheme at compile time, i.e. we never use dynamic search schemes for errors <= 3).
Another one adds a test that covers two `if`s very deep inside the algorithm that handle a case where you do deletions at the end of the block after having done substitutions/insertions; I just enumerated over all error type counts from 1 to 5 and over all queries of length 5 and took one that hit the lines.
=> [MISC] Increase search coverage to 100%

CHANGELOG.md, include/seqan3/search/fm_index/detail/fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/snippet/search/fm_index_cursor.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp, test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_test_template.hpp
=> [FEATURE] Node access for fm_index_cursor

CHANGELOG.md, doc/tutorial/argument_parser/index.md, doc/tutorial/read_mapper/read_mapper_indexer_step1.cpp, doc/tutorial/read_mapper/read_mapper_indexer_step2.cpp, doc/tutorial/read_mapper/read_mapper_indexer_step3.cpp, doc/tutorial/read_mapper/read_mapper_step1.cpp, doc/tutorial/read_mapper/read_mapper_step2.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/read_mapper/read_mapper_step4.cpp, include/seqan3/argument_parser/validators.hpp, test/snippet/argument_parser/validators_output_directory.cpp, test/snippet/argument_parser/validators_output_file.cpp, test/snippet/argument_parser/validators_output_file_ext_from_file.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/50.
Please do not merge before the naming discussion of the enum on gitter has ended.
Existing Ideas:
```cpp
enum output_file_open_mode
{
overwritable / rewritable,
exclusive
};
```
There is something in system.io from Microsoft that sounds good: https://docs.microsoft.com/de-de/dotnet/api/system.io.filemode?view=netcore-3.1 :
```cpp
enum FileMode
{
open_or_create,
create_new
};
```
```cpp
enum accept_existing_file
{
true / yes,
false / no
};
```
Rust:
```cpp
enum OpenOptions
{
create,
create_new
};
```
-----
2020-08-31
Discussion result:
```cpp
enum output_file_open_options
{
open_or_create,
create_new
};
```
You call this validator like:
```cpp
seqan3::output_file_validator{seqan3::output_file_open_options::open_or_create});
```
=> [FEATURE] Allow overwrite existing files, add flags for permission handling

include/seqan3/search/detail/search_scheme_algorithm.hpp
AddressSanitizer on macOS sees this, others not....
Can be easily confirmed via using `.at()` instead of `[]`.
=> [FIX] Underflow in search

.github/workflows/ci.yml, .github/workflows/documentation.yaml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
New way: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
=> [INFRA] add-path is deprecated

test/include/seqan3/test/performance/sequence_generator.hpp, test/unit/test/CMakeLists.txt, test/unit/test/sequence_generator_test.cpp
resolves part of https://github.com/seqan/product_backlog/issues/12
The first commit will be done by another PR: https://github.com/seqan/seqan3/pull/1995 ([TEST] Repair seqan2 tests)
=> [TEST] implement sequence generator

include/seqan3/alignment/matrix/detail/affine_cell_proxy.hpp, test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp
Part of #1908
Makes the affine cell proxy fully proxy compatible and applicable to alignment with trace back.
=> Optimise alignment/complete affine cell proxy

include/seqan3/core/detail/int_types.hpp
```c++
/seqan3/include/seqan3/core/detail/int_types.hpp: In instantiation of ‘constexpr const size_t seqan3::detail::size_in_values_v<char>’:
/seqan3/include/seqan3/core/char_operations/transform.hpp:26:38:   required from ‘constexpr char_type seqan3::to_lower(char_type) [with char_type = char]’
/seqan3/include/seqan3/alphabet/aminoacid/aa10li.hpp:138:52:   required from here
/seqan3/include/seqan3/core/detail/int_types.hpp:45:88: error: incomplete type ‘std::numeric_limits<char>’ used in nested name specifier
45 | constexpr size_t size_in_values_v = static_cast<size_t>(std::numeric_limits<int_t>::max()) -
|                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```
=> [FIX] gcc-11: error: incomplete type ‘std::numeric_limits<char>’

build_system/seqan3-package.cmake
Usage:
Make a fresh clone of the repository and create a build folder (out-of-source).
```bash
mkdir package-build
git clone https://github.com/seqan/seqan3.git
cd seqan3
git checkout 3.0.2 # version to pack
git submodule init
git submodule update
cd ../package-build
cmake ../seqan3 # configure
cpack # builds binary package, e.g. seqan3-3.0.2-Linux.tar.xz{,.sha265}
cmake --build . --target package_source # builds source package, e.g. seqan3-3.0.2-Source.tar.xz{,.sha265}
```
Note: Do not do `git clone -recurse-submodules https://github.com/seqan/seqan3.git` because it will recursively
pull sub-submodules which we do not want!
=> [INFRA] configure cpack for source builds

test/documentation/seqan3_doxygen_cfg.in
We introduced some formula with `mathbb` which requires `amsfonts` to be available. (33cc9b012cca3c69d38c1faeff001b6c2b12e2e5)
=> [FIX] missing latex package for docs

.github/workflows/ci.yml
~~Blocked by https://github.com/seqan/seqan3/pull/2205~~ (Works as expected: Failed before #2205 was merged and succeeds now)
For the documentation we do `make` and then `ctest`. This obscures errors that may occur during the build via `make`.
=> [INFRA] build documentation only once

test/unit/alphabet/aminoacid/aminoacid_translation_test.cpp
This fixes the following gcc-11 ICE:
```
In file included from /seqan3/test/unit/alphabet/aminoacid/aminoacid_translation_test.cpp:10:
/seqan3/submodules/range-v3/include/range/v3/view/concat.hpp: In substitution of ‘template<class ... Rngs> template<bool IsConst> template<class T> using constify_if = meta::const_if_c<IsConst, T> [with T = ranges::concat_view<Rngs>; bool IsConst = IsConst; Rngs = {Rngs ...}]’:
/seqan3/submodules/range-v3/include/range/v3/view/concat.hpp:88:58:   required from here
/seqan3/submodules/range-v3/include/range/v3/view/concat.hpp:88:58: internal compiler error: Segmentation fault
88 |             using concat_view_t = constify_if<concat_view>;
|                                                          ^
```
which was also reported by …
=> [FIX] gcc-11 ICE by removing range/v3/view/concat.hpp (#2210)

.github/workflows/ci.yml, .travis.yml, test/performance/CMakeLists.txt
This should decrease the time needed for performance CI. (16m -> 2m)
I added an option to enable/disable this.
=> [INFRA] pass benchmark_min_time to performance tests

test/performance/CMakeLists.txt
When not set, `SEQAN3_BENCHMARK_MIN_TIME ` will be evaluated to `ON` and then passed as `--benchmark_min_time=ON`
=> [FIX] Non boolean option in cmake

CHANGELOG.md, doc/howto/subcommand_argument_parser/subcommand_arg_parse.cpp, include/seqan3/argument_parser/argument_parser.hpp, test/unit/argument_parser/format_parse_test.cpp
=> [FIX] Throw missing subcommand argument on parse() and adapt misleading tutorial.

CHANGELOG.md, include/seqan3/io/alignment_file/format_sam_base.hpp, test/unit/io/alignment_file/format_sam_test.cpp
An error that occurred for @h-2. The offending line was added as a test.
Fixes #2195
=> [FIX] Allow '*' at the beginning of string fields in SAM format.

include/seqan3/core/algorithm/concept.hpp, include/seqan3/core/platform.hpp
Now the config_element_specialisation checks if the class inherits from the pipeable_config_element base class.
First commit of #2198
=> [MISC] Make config_element_specialisation more restrictive.

doc/howto/subcommand_argument_parser/subcommand_arg_parse.cpp, doc/tutorial/argument_parser/disable_version_check.cpp, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/auxiliary.hpp, include/seqan3/argument_parser/detail/version_check.hpp, test/unit/argument_parser/argument_parser_design_error_test.cpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/format_parse_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
This resolves an error I recently encountered, namely that
```cpp
seqan3::argument_parser parser{"test_parser", argc, argv, {"subparser1", "subparser2"}};
```
compiles because the list of subparser is implicitely converted to bool and taken as the version_check boolean parameter. :see_no_evil: 
This is fixed by making the boolean parameter into a proper enum (which should have been done anyway).
=> [FIX] Make argument_parser-ctor boolean parameter into an proper enum.

CHANGELOG.md, include/seqan3/argument_parser/validators.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2214
=> [FIX] fix regex validator for std::filesystem::path

include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/header/CMakeLists.txt, test/header/generate_header_source.cmake, test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test.cpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp
Fixes https://github.com/seqan/product_backlog/issues/232
This PR implements a new `test/header/generate_header_source.cmake` which generates for each given header file (e.g. `include/seqan3/search/fm_index/bi_fm_index_cursor.hpp`) two `.cpp` files.
* `<build_dir>/seqan3_header_test/seqan3/search/fm_index/bi_fm_index_cursor.hpp-header-guard.cpp`
which checks if the header implements a header guard.
This will be checked by including the header twice, if the header guard is missing the second include will produce redeclaration errors, i.e.
```c++
#include <seqan3/search/fm_index/bi_fm_index_cursor.hpp>
#include <seqan3/search/fm_index/bi_fm_index_cursor.hpp>
```
* `<build_dir>/seqan3_header_test/seqan3/search/fm_index/bi_fm_index_cursor.hpp-no-self-include.cpp`
which checks if the header …
=> [INFRA] header test now tests self-includes

build_system/seqan3-install.cmake
Fix CMake version number check to be the minimum version for the features that are in the CMakeFiles.
`install (
FILES
....
TYPE DOC
)`
The use of TYPE was released in cmake 3.14, and will fail on any prior version
Edit (@smehringer): Resolves #2227
=> [INFRA] CMake version number check to be the minimum version

CHANGELOG.md, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, test/snippet/argument_parser/is_option_set.cpp, test/unit/argument_parser/format_parse_test.cpp
Fixes #1741 
Current look:
```cpp
int main(int argc, char ** argv)
{
int i{5}; // default
seqan3::argument_parser parser{"test_parser", argc, argv};
// parser.add_option(i, 'f', "foo", "description");
// parser.parse(); 
// return parser.option_overwritten('f');
// return parser.default_overwritten('f');
// return parser.default_overwridden('f');
// return parser.overwritten_by_user('f');
// return parser.overwritten_on_cmd('f');
// return parser.option_is_set('f'); // tloka's fav
return parser.is_option_set('f');
// return parser.option_is_set_by_user('f');
// return parser.option_is_set_on_cmd('f');
// return parser.set_by_user('f');
}
```
```cpp
int main(int argc, char ** argv)
{
std::optional<int> i{std::nullopt}; // default
seqan3::argument_parser parser{"test_parser", argc, argv}; …
```
=> [FEATURE] Argument Parser: new member function that checks if an option was set.

test/unit/io/sequence_file/sequence_file_format_embl_test.cpp
By changing stuff to Stuff, the do while loop in the embl code runs more than once so the do is covered.
=> Add coverage to embl sequence file test

test/unit/alphabet/cigar/cigar_test.cpp, test/unit/alphabet/composite/semialphabet_any_test.cpp
This removes unused headers and fixes #2234.
=> [FIX] #2234: latest googletest (1.10.0.20201025-1) doesn't like the *test_template.hpp

include/seqan3/core/algorithm/concept.hpp, include/seqan3/core/algorithm/configuration_utility.hpp
This declaration is needed later for the config_element_pipeable_with concept defintion.
second commit of #2198
=> [MISC] Move the  compatibility_table  declaration into the algorithm/concept header.

include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_scoring_scheme.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp, include/seqan3/alignment/pairwise/policy/scoring_scheme_policy.hpp, include/seqan3/alignment/scoring/detail/simd_match_mismatch_scoring_scheme.hpp, include/seqan3/alignment/scoring/detail/simd_matrix_scoring_scheme.hpp, test/unit/alignment/pairwise/fixture/global_affine_unbanded.hpp, test/unit/alignment/pairwise/global_affine_unbanded_aa27_test.cpp, test/unit/alignment/pairwise/global_affine_unbanded_collection_simd_aa27_test.cpp, test/unit/alignment/scoring/simd_match_mismatch_scoring_scheme_test.cpp, test/unit/alignment/scoring/simd_matrix_scoring_scheme_test.cpp
Enables gather based amino acid scoring scheme for faster vectorised alignments using amino acids.
The current implementation uses unoptimised gather and works well for sse4. 
The specific instructions for avx2 and avx512 need to be extended as well. 
Also the current solution is not stable for 8-bit scores.
Here is an initial benchmark for sse4:
```
--------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------------------------------------
// SeqAn3 current
seqan3_affine_accelerated/simd_with_score/0/real_time …
```
=> Protein alignment/part2 gather scoring matrix using gather

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp, include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_affine_gap_with_trace_recursion.hpp, include/seqan3/alignment/pairwise/detail/policy_affine_gap_with_trace_recursion_banded.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp
Implements additional policies for the seqan affine recursion including the trace information.
The overwriting policies do not provide any extra data but merely override the interfaces to compute the cells inside of the alignment matrix. In these functions they use the additional trace values given by the combined score and trace matrix.
A affine policy selector in the configuration makes sure that the algorithm is configured correctly.
These are the first four commits of the original branch: https://github.com/rrahn/seqan3/tree/optimise_alignment/final_alignment_computation
=> Optimise alignment/final alignment computation master

include/seqan3/std/filesystem, test/unit/argument_parser/format_parse_validators_test.cpp, test/unit/test/tmp_filename_test.cpp
Just changing the env variable is not enough, because `std::filesystem::temp_directory_path()` already checks if the returned path exists and is valid. 
That means the `std::filesystem::filesystem_error` was always thrown inside the `temp_directory_path()` instead of inside our `tmp_filename` constructor.
=> [TEST] Increase coverage for tmp_filename

.github/workflows/ci.yml, test/cmake/seqan3_require_benchmark.cmake, test/cmake/seqan3_require_test.cmake
This goes one step into solving https://github.com/seqan/product_backlog/issues/223
FetchContent became now the proper way to include external CMake Project, alongside using a submodule. See https://cliutils.gitlab.io/modern-cmake/chapters/projects/fetch.html
FetchContent has the advantage that it does the download phase at cmake configuration time (this allows the direct usage of defined targets of that cmake project) and the build phase when you are building your binary.
=> [INFRA] cmake: use fetch content

include/seqan3/alphabet/concept.hpp, include/seqan3/alphabet/structure/concept.hpp, include/seqan3/core/platform.hpp
This PR adapts older code to how we handle workarounds now. At some point we started to bundle our workarounds in one place (include/seqan3/core/platform.hpp) and made them available to all header instead of just leaving a comment.
=> [FIX] use proper workaround syntax

.github/workflows/ci.yml
Apparently the image has changed and now the globally installed version of 8.4.0 is used instead of the brew one.
The globally installed one has some errors....
=> [FIX] MacOS gcc8 CI

test/cmake/seqan3_require_benchmark.cmake
See for example https://cdash.seqan.de/viewBuildError.php?buildid=74022
google benchmark cannot be built when `-fconcepts` is passed
After https://github.com/seqan/seqan3/pull/2252, google benchmark is included as target and hence uses the passed `CMAKE_CXX_FLAGS`. Before the PR, it was included as external project and was unaffected by the set flags.
Explicitly setting the cxx_standard prevents the ICE.
=> [FIX] ICE in google benchmark

.travis.yml
We did some changes to how the CI is built in https://github.com/seqan/seqan3/pull/2252 that we need to apply to travis
=> [FIX] travis script

include/seqan3/core/algorithm/concept.hpp
This concept is used generically to test if two given configurations are combinable with each other.
With this concept the pipe-operator can be implemented without converting the configuration elements to the base class.
third commit of #2198
=> [FEATURE] Add config_element_pipeable_with concept.

include/seqan3/contrib/parallel/buffer_queue.hpp
Big thanks to @eseiler for figuring out the actual problem!
When calling the close operation a write lock must be acquired
to prevent concurrent read access on the shared closed_flag by consumer
threads. The atomic used so far was not sufficient enough to prevent
a data race between the closing thread and producers that currently
acquired the shared read lock on the same mutex.
In particular, it could happen that one producer thread adds an
item to the empty queue and closes the queue  immediately. In the
meantime a consumer could have observed the empty queue right before
the element was added and then checked the closed_flag shortly after
it has beend updated by the other thread. In this state the consumer
falsely interprets the queue as empty and closed, while there is
still an item …
=> [FIX] Fixes the spurious fails of the buffer queue.

include/seqan3/contrib/parallel/buffer_queue.hpp, include/seqan3/core/parallel/detail/all.hpp, include/seqan3/core/parallel/detail/latch.hpp, include/seqan3/core/parallel/detail/reader_writer_manager.hpp, include/seqan3/core/parallel/detail/spin_delay.hpp, include/seqan3/utility/parallel/detail/spin_delay.hpp
Part of seqan/product_backlog#160
=> [MISC] Rename {core->utlity}/parallel/detail/spin_delay

include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_alignment_result_builder.hpp
Enables the computation of the begin position inside of the refactored alignment.
Before, only the score and end position could be computed. Now it is also possible to compute the begin positions. 
In the upcoming PRs also the trace computation will be enabled including the logging mechanism.
=> [MISC] Enable computation of begin position in alignment result builder.

include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp, include/seqan3/core/algorithm/detail/execution_handler_parallel.hpp
Resolves https://github.com/seqan/seqan3/issues/2278
We need to fix some things such that `move` works.
* lhs => default constructed => 160 threads
* rhs => custom construced => 4 threads
* lhs = std::move(rhs) => lhs.reset(rhs.release())
* rhs.release() => return ptr to resource and set ptr = nullptr => destructor ist not called, but not a problem here
* lhs.reset(new_ptr) => old_ptr = lhs.ptr; lhs.ptr = new_ptr; lhs.deleter(old_ptr) => problem! The destructor destoys the internal state with the thread pool before alle the threads have been joined since `wait()` hasn't been called.
=> [FIX] parallel config ending up ignored

CHANGELOG.md, include/seqan3/alphabet/quality/all.hpp, include/seqan3/alphabet/quality/phred42.hpp, include/seqan3/alphabet/quality/phred63.hpp, include/seqan3/alphabet/quality/phred94.hpp, test/performance/alphabet/alphabet_assign_char_benchmark.cpp, test/performance/alphabet/alphabet_assign_rank_benchmark.cpp, test/performance/alphabet/alphabet_to_char_benchmark.cpp, test/performance/alphabet/alphabet_to_rank_benchmark.cpp, test/snippet/alphabet/quality/phred63.cpp, test/snippet/alphabet/quality/phred94.cpp, test/snippet/alphabet/quality/phred94_literal.cpp, test/unit/alphabet/composite/composite_integration_test.cpp, test/unit/alphabet/quality/CMakeLists.txt, test/unit/alphabet/quality/phred94_test.cpp, test/unit/alphabet/quality/qualified_test.cpp, test/unit/alphabet/quality/quality_conversion_integration_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/267
The task _'Check if the tutorials need an update.'_ did not require any work, because there is no tutorial yet. I will add a tutorial when solving https://github.com/seqan/product_backlog/issues/266.
For task _'Update the documentation on the quality landing page'_ I left three comments for the reviewer, which I will remove after discussion.
I splittet the PR in several commits and would recommend to review commit wise.
=> [FEATURE] Alphabet: Add the quality alphabet seqan3::phred94

include/seqan3/core/detail/template_inspection.hpp, test/snippet/core/detail/template_inspection_usage_3.cpp, test/unit/core/detail/template_inspection_test.cpp
Resolves partly https://github.com/seqan/product_backlog/issues/259
=> [MISC] Adds new concept template_specialisation_of.

test/snippet/alphabet/quality/phred42.cpp, test/snippet/alphabet/quality/phred63.cpp
This is a follow up of https://github.com/seqan/seqan3/pull/2290
and connected to https://github.com/seqan/product_backlog/issues/266.
The cast to integer is not needed for a better output. This is automaticly done with the debug_stream.
=> [DOC] Refactor phred snippets. The int cast is not needed.

include/seqan3/core/configuration/configuration.hpp, test/unit/core/algorithm/pipeable_config_element_test_template.hpp
The constructor now checks via a concept if the config element can be
constructed from the given configuration element.
This is the first step to remove the crtp-pattern from the base
config element.
=> [MISC] Simplify the configuration constructor.

test/documentation/seqan3_doxygen_cfg.in
@Irallia noticed that our doxygen class list is not well formatted:
https://docs.seqan.de/seqan/3-master-dev/classes.html
After this PR:
See https://www.doxygen.nl/manual/config.html#cfg_cols_in_alpha_index
=> [FIX] too many columns in doxygen class list

include/seqan3/core/detail/pack_algorithm.hpp, include/seqan3/utility/type_list/traits.hpp, include/seqan3/utility/type_list/type_list.hpp, test/unit/utility/type_list/type_list_test.cpp
Resolves partly seqan/product_backlog#259
Blocked by https://github.com/seqan/seqan3/pull/2263
Replace the concept 'type_list_specialisation' with the new more general concept 'template_specialisation_of'.
=> [MISC] Replaces 'type_list_specialisation' with 'template_specialisation_of'.

.github/workflows/ci.yml, test/cmake/diagnostics/list_missing_unit_tests.cmake, test/cmake/include_dependencies/add_include_dependencies.cmake, test/cmake/include_dependencies/generate_include_dependencies.cmake, test/unit/CMakeLists.txt, test/unit/alphabet/composite/composite_integration_test.cpp, test/unit/alphabet/gap/gapped_test.cpp, test/unit/argument_parser/detail/CMakeLists.txt, test/unit/core/algorithm/CMakeLists.txt, test/unit/core/detail/template_inspection_test.cpp, test/unit/io/alignment_file/CMakeLists.txt
This PR introduces `-DSEQAN3_USE_INCLUDE_DEPENDENCIES` which creates a dependency graph by using the include-graph.
The main idea is to have a bi-partite graph where the left nodes are the header and the right nodes the test cases. Each test case is associated with it's corresponding header, e.g. gap_test has a directed edge to include/seqan3/alphabet/gap/gap.hpp. This has the effect that a header can be marked as "known-to-work" if a test case could be built. Furthermore, add an edge for each include a test case uses (from include to test).
For example gap_test uses these headers:
* include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
* include/seqan3/alignment/exception.hpp
* include/seqan3/alphabet/alphabet_base.hpp
* [...]
* include/seqan3/std/concepts.hpp
* …
=> [FEATURE] cmake: specify build-order by include-graph

include/seqan3/core/common_tuple.hpp, include/seqan3/core/tuple/common_tuple.hpp, include/seqan3/range/views/pairwise_combine.hpp, test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp
Part of [seqan/product_backlog#160](https://github.com/seqan/product_backlog/issues/160)
=> [MISC] Move core/common_tuple.hpp -> core/tuple/common_tuple.hpp

include/seqan3/core/algorithm/detail/execution_handler_parallel.hpp, test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp, test/unit/core/algorithm/detail/execution_handler_template.hpp
This sets the default number of threads for the `execution_handler_parallel` to `1`.
All the tests were the handler was expected to use multiple threads were adjusted to explicitly request not more than 4 threads.
The `execution_handler_parallel` is detail and hence not used in public code. It handles the thread pool when, e.g., using the alignment or search algorithms in parallel via the config. This config requires a value (no default), hence the number of threads is always set by the user.
When we use an algorithm in parallel, we also default construct a `execution_handler_parallel` along the way. If the default is set to use all threads, we have to generate the thread pool and a queue. However, this default constructed `execution_handler_parallel` is also moved away and practically …
=> [FIX] too many threads used in unit tests

CHANGELOG.md, include/seqan3/argument_parser/argument_parser.hpp, test/unit/argument_parser/argument_parser_design_error_test.cpp, test/unit/argument_parser/format_parse_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/234
=> Make dash usable for subcommand

.codecov.yml
The patch report is often broken.
It is meant to just look at the changes of commit, but is not very reliant.
Usually we look at the project report which summarizes added/deleted lines and increases/decreases in hit code lines
See https://docs.codecov.io/docs/commit-status
=> [INFRA] Make codecov patch report non-failing

doc/tutorial/alignment_file/index.md, include/seqan3/alignment/all.hpp, include/seqan3/alignment/configuration/align_config_method.hpp, include/seqan3/alignment/configuration/align_config_scoring_scheme.hpp, include/seqan3/alphabet/composite/alphabet_variant.hpp, include/seqan3/core/detail/debug_stream_type.hpp, include/seqan3/core/detail/strong_type.hpp, include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/alignment_file/output.hpp, include/seqan3/io/detail/misc_input.hpp, include/seqan3/io/detail/misc_output.hpp, include/seqan3/range/views/deep.hpp, include/seqan3/range/views/single_pass_input.hpp, test/snippet/core/simd/view_to_simd.cpp
`defaulted` as an adjective means something like `fails to fulfil an obligation`. 
We sometimes do not use this word correctly (since we always mean `set to default`).
Only `to be defaulted` actually means `set to default`. To avoid this possible confusing, some correct sentences were also changed.
=> [DOC] Replace the word 'defaulted' with better/correct alternative.

test/performance/alignment/global_affine_alignment_simd_benchmark_template.hpp, test/performance/io/stream_input_benchmark.cpp, test/performance/search/index_construction_benchmark.cpp, test/performance/search/search_benchmark.cpp
This reduces the set sizes in debug mode and will prevent timeouts in the nightlies.
There does not seem to be a performance regression between 3.0.2 and now, this might have to do something with the new way of fetching google benchmark and propagating our build flags?
=> [INFRA] Reduce benchmark set sizes in debug mode

include/seqan3/alphabet/composite/alphabet_tuple_base.hpp, include/seqan3/alphabet/composite/detail.hpp, include/seqan3/core/configuration/all.hpp, include/seqan3/core/configuration/configuration.hpp, include/seqan3/core/configuration/detail/concept.hpp, include/seqan3/core/configuration/detail/configuration_utility.hpp, include/seqan3/core/detail/strong_type.hpp, test/unit/alignment/configuration/align_config_band_test.cpp, test/unit/alignment/configuration/align_config_common_test.cpp, test/unit/alignment/configuration/align_config_gap_cost_affine_test.cpp, test/unit/alignment/configuration/align_config_min_score_test.cpp, test/unit/alignment/configuration/align_config_parallel_test.cpp, test/unit/alignment/configuration/align_config_scoring_scheme_test.cpp, test/unit/core/algorithm/pipeable_config_element_test_template.hpp, test/unit/core/configuration/configuration_test.cpp, test/unit/core/detail/strong_type_test.cpp, test/unit/search/configuration/parallel_test.cpp, test/unit/search/search_configuration_test.cpp
This PR is part of [seqan/product_backlog/issues/259](https://github.com/seqan/product_backlog/issues/259)
- Renames strong_type_specialisation to derived_from_strong_type
- Renames config_element_specialisation to config_element
- Renames alphabet_tuple_base_specialisation to alphabet_tuple_like
=> [FIX] Renaming [...]_specialisation concepts

include/seqan3/utility/detail/type_name_as_string.hpp
On gcc-9 the following type can't be demangled by type_name_as_string
```c++
inline constexpr auto on_result_caller = [] (auto &&) {};
seqan3::configuration cfg{seqan3::search_cfg::on_result<decltype(on_result_caller)>{}};
std::cout << seqan3::detail::type_name_as_string<decltype(cfg)> << std::endl;
// prints: N6seqan313configurationIJNS_10search_cfg9on_resultIKUlOT_E_EEEEE (abi::__cxa_demangle error status (-2): mangled_name is not a valid name under the C++ ABI mangling rules.)
```
Before this commit `abi::__cxa_demangle` returned a `nullptr` and that will fail to execute the binary, because `std::string` can't be constructed from a nullptr.
This commit will handle `abi::__cxa_demangle` errors and will produce a similar output to the above.
=> [FIX] type_name_as_string: handle nullptr construction if __cxa_demangle fails

include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
The documentation can be left untouched since it was already public before.
fixes #2324
=> [FIX] Make class interleaved_bloom_filter::membership_agent public.

include/seqan3/core/configuration/detail/concept.hpp
PR https://github.com/seqan/seqan3/pull/2255 did the move from core/algorithm into core/configuration, but at the same time PR https://github.com/seqan/seqan3/pull/2247 changed one header.
This seems like a misinterpreted merge conflict and this PR reintroduces the changes from https://github.com/seqan/seqan3/pull/2255. After checking the changes of https://github.com/seqan/seqan3/pull/2255, this seems to be the only missed change.
This partially reverts commit 1ae6a3f9dbd4d494626ed528f0ccbda589fb9a38.
=> [FIX] reintroduce changes lost due to merge conflicts

include/seqan3/core/configuration/detail/concept.hpp
https://github.com/seqan/seqan3/pull/2315 and https://github.com/seqan/seqan3/pull/2322 changed the same file without a merge conflict. This PR fixes the current master fail.
=> [FIX] current master fail, config_element_specialisation was renamed

include/seqan3/std/memory, test/unit/range/container/small_vector_test.cpp, test/unit/range/iterator_test_template.hpp
fixes https://github.com/seqan/product_backlog/issues/94
Adds tests for contiguous iterators to the iterator_test_template.
=> [TEST] Add contigous iterator to iterator_test_template 

include/seqan3/argument_parser/detail/format_help.hpp, include/seqan3/argument_parser/detail/format_html.hpp, include/seqan3/argument_parser/detail/format_man.hpp
Feel free to comment on the name of the function `in_bold`. I didn't think a lot about the naming.
See #2319 for every commit that is planned for some refactoring. It will make it easier to keep the help page export features in synch.
=> Factor out bold formatting of help page export into separate function.

.github/workflows/documentation.yaml
If there is a cache available, the documentation build is not configured with the changed doxygen version
=> [FIX] Use new cache if doxygen version changes

include/seqan3/alignment/matrix/edit_distance_score_matrix_full.hpp, include/seqan3/contrib/parallel/buffer_queue.hpp, include/seqan3/core/bit_manipulation.hpp, include/seqan3/io/alignment_file/format_bam.hpp, include/seqan3/range/container/dynamic_bitset.hpp, include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, include/seqan3/std/bit, include/seqan3/utility/math.hpp, include/seqan3/utility/simd/detail/builtin_simd.hpp, test/performance/core/bit_manipulation_benchmark.cpp, test/snippet/core/detail/count_leading_zeros.cpp, test/snippet/core/detail/count_trailing_zeros.cpp, test/snippet/core/detail/most_significant_bit_set.cpp, test/snippet/core/detail/popcount.cpp, test/unit/core/bit_manipulation_test.cpp, test/unit/range/container/aligned_allocator_test.cpp, test/unit/range/container/dynamic_bitset_test.cpp, test/unit/utility/math_test.cpp
Fixes Partially https://github.com/seqan/product_backlog/issues/199
gcc-9 comparison:
| Benchmark                                                  | gcc-9-before Time | gcc-9-after Time | After-before Time | (After-Before)/Before Time |
| ---------------------------------------------------------- | ----------------- | ---------------- | ----------------- | -------------------------- |
| _is\_power\_of\_two\_popcount\<unsigned>\_median_           | 8.610 ns          | 9.170 ns         | 0.560 ns          | **+6.50%**                 |
| _is\_power\_of\_two\_popcount\<unsigned long>\_median_      | 7.880 ns          | 8.290 ns         | 0.410 ns          | **+5.20%**                 |
| _is\_power\_of\_two\_popcount\<unsigned long long>\_median_ | 9.070 ns          | 8.860 ns         | …
=> Introduce <bit> shim-header

include/seqan3/argument_parser/validators.hpp
This PR reduces dependencies between seqan3 and the argument parser by removing an invocation of `seqan3::pack_traits::front`.
Part of https://github.com/seqan/product_backlog/issues/40
=> [FIX] argument_parser: do not use seqan3::pack_traits::front

include/seqan3/argument_parser/detail/format_help.hpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
The next commit being part of some argument parser refactoring (all changes shown in #2319).
In this commit we reuse member functions of format_help, like `print_line`, that we already have to DRY out code.
=> [MISC] Reuse functionality we already have in format_help.

test/include/seqan3/test/expect_same_type.hpp, test/unit/test/CMakeLists.txt, test/unit/test/expect_same_type_test.cpp
New EXPECT_SAME_TYPE test macro, see seqan/product_backlog#46
```c++
EXPECT_SAME_TYPE(int, float);
```
has the same semantic as writing
```c++
EXPECT_TRUE((std::same_as<int, float>))
```
but it will produce better diagnostics if the test failed:
```
Expected equality of these values:
int
Which is: "int"
float
Which is: "float"
```
=> [TEST] new EXPECT_SAME_TYPE test macro

include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_help.hpp, include/seqan3/argument_parser/detail/format_html.hpp, include/seqan3/argument_parser/detail/format_man.hpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/format_html_test.cpp, test/unit/argument_parser/detail/format_man_test.cpp
This is part of the refactoring shown in #2319 
It removes printing of the version information in the individual formats and instead puts it into `format_help_base`.
This reduces code and avoid inconsistencies between formats (e.g. format man didn't have the version information at all).
=> [MISC] Move printing the version information to format_help_base.

include/seqan3/std/bit, include/seqan3/std/memory, include/seqan3/std/type_traits
This PR fixes the following:
* __cpp_lib_endian is not known for `g++-8 -std=c++2a`, but it still defines `std::endian`
* __cpp_lib_to_address is not known for `g++-8/9 -std=c++2a`, but it still defines `std::to_address`
* further this PR makes the workaround macro names consistent in the naming scheme and behaviour:
* `SEQAN3_CPP_LIB_*` corresponds to the definition of `__cpp_lib_*`
* It always has defined / undefined semantics like the original feature macro `__cpp_lib_*`
* Hence `#ifdef SEQAN3_CPP_LIB_*` means that the functionality is already implemented by the standard library
* Or was disabled by a library user that might have conflicts with our shim/polyfill implementation
* and`#ifndef SEQAN3_CPP_LIB_*` means that the functionality is missing in the standard library
* in this case …
=> __cpp_lib_* fixes

LICENSE.md, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_help.hpp, test/unit/argument_parser/detail/format_help_test.cpp
See #2319 for the full lost of commits.
This PR 
* moves `print_legal()` to format_help_base, s.t. format_man and format_html can use it later on.
* fixes the copyright year to 2021
=> [MISC] Move print_legal() to format_help_base and fix copyright year

include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_help.hpp, include/seqan3/argument_parser/detail/format_html.hpp, include/seqan3/argument_parser/detail/format_man.hpp, test/unit/argument_parser/detail/format_html_test.cpp, test/unit/argument_parser/detail/format_man_test.cpp
Last part of the refactoring.
This PR adds the print legal functionality to html and man output and then moves the function itself to the format_help_base to avoid inconsistencies later on.
=> [MISC] Move print_legal function to format_help_base.

include/seqan3/alignment/band/static_band.hpp
In #2272 only the header was marked as deprecated in doxygen but not the entity itself. This way you don't really see the deprecation in the API documentation.
=> [DOC] Deprecate seqan3::static_band documentation.

include/seqan3/alignment/configuration/align_config_scoring_scheme.hpp
The scoring scheme configuration documentation did not appear in the alignment/configuration module.
=> [DOC] Put scoring scheme config into correct doxygen group.

include/seqan3/argument_parser/validators.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
Part of https://github.com/seqan/product_backlog/issues/246 and https://github.com/seqan/product_backlog/issues/40
This reduces dependencies on seqan3 by removing `seqan3::detail::is_char_adaptation_v`.
Blocked by #2307
=> [FIX] chain_validator: use common_type to chain

include/seqan3/version.hpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/format_html_test.cpp, test/unit/argument_parser/detail/version_check_test.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
- Adjusting seqan3_version to be the constexpr version of SEQAN_VERSION which is
an integer.
- Added SEQAN3_VERSION_CSTRING which is a null terminated string of the version.
- Added seqan3_version_cstring which is a constexpr version of
SEQAN3_VERSION_CSTRING.
- Adjusted all files to use seqan3_version_cstring instead of seqan3_version.
=> [MISC] adjusting seqan3_version semantics

include/seqan3/io/detail/record.hpp, test/unit/io/detail/CMakeLists.txt, test/unit/io/detail/detail_record_test.cpp, test/unit/io/record_test.cpp
The old implementation of seqan3::detail::get_or_ignore seemed to work for
many tuple types, but failed for tuple types that have less template
parameters than tuple elements.
=> [FIX] seqan3::detail::get_or_ignore should accept all tuple-like types

include/seqan3/alignment/matrix/detail/affine_cell_proxy.hpp, include/seqan3/core/platform.hpp, include/seqan3/io/record.hpp, test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp, test/unit/io/record_test.cpp
This PR introduces
* a workaround macro `SEQAN3_WORKAROUND_GCC_94967`
* uses it on known places
* adds a test to check that `seqan3::get<seqan3::field>(record const &&)` works
=> [FIX] gcc7: seqan3::get<seqan3::field>(record const &&)

include/seqan3/core/debug_stream.hpp, include/seqan3/core/detail/debug_stream_byte.hpp, include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/alignment_file/sam_tag_dictionary.hpp, test/unit/core/debug_stream_test.cpp, test/unit/io/alignment_file/alignment_file_format_test_template.hpp, test/unit/io/alignment_file/sam_tag_dictionary_test.cpp
Resolves #1414
This adds the hexadecimal SAM tag to the `sam_tag_dictionary`.
I chose a `std::vector<std::byte>>` since we need to represent bytes and the types in the `std::variant` need to be distinct.
Since the code paths for all variants need to be valid at compile time, it also at some point tries to call `write_field`, hence we need an overload for the `std::byte`; this needs to be adapted once we write hexadecimal flags!
At some point the `value_type` needs to be streamable, so I added an overload for `std::byte` in the `debug_stream`.
=> [FEATURE] Reading hexadecimal SAM tags part 1

include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/snippet/search/dream_index/counting_vector.cpp, test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
Part of https://github.com/seqan/seqan3/pull/1911
#1911 is quite self-contained except the one change in `interleaved_bloom_filter.hpp`, which makes it harder to work with a current seqan version (e.g. when developing the HIBF).
=> [FEATURE] Add counting_vector::operator+=(counting_vector)

test/unit/alignment/configuration/align_config_score_type_test.cpp, test/unit/alignment/matrix/alignment_coordinate_test.cpp, test/unit/alignment/matrix/debug_matrix_test.cpp, test/unit/alignment/pairwise/align_pairwise_test.cpp, test/unit/alignment/pairwise/alignment_configurator_test.cpp, test/unit/alignment/pairwise/alignment_result_test.cpp, test/unit/alignment/pairwise/detail/type_traits_test.cpp, test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp, test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp, test/unit/core/algorithm/pipeable_config_element_test_template.hpp, test/unit/core/configuration/configuration_test.cpp, test/unit/core/detail/iterator_traits_test.cpp, test/unit/io/alignment_file/sam_tag_dictionary_test.cpp, test/unit/io/stream/detail/fast_ostreambuf_iterator_test.cpp, test/unit/range/container/bitcompressed_vector_test.cpp, test/unit/range/container/small_vector_test.cpp, test/unit/range/views/drop_test.cpp, test/unit/range/views/repeat_test.cpp, test/unit/range/views/single_pass_input_test.cpp, test/unit/range/views/slice_test.cpp, test/unit/range/views/take_test.cpp, test/unit/range/views/type_reduce_test.cpp, test/unit/search/configuration/hit_test.cpp, test/unit/test/seqan2_test.cpp, test/unit/utility/type_traits/function_traits_test.cpp
Search and replace with `EXPECT_TRUE\(\(std::same_as<(.+)>\)\);` and `EXPECT_SAME_TYPE($1);`
=> [TEST] use EXPECT_SAME_TYPE macro (oneline regexp)

CHANGELOG.md, doc/howto/write_an_alphabet/index.md, include/seqan3/alphabet/composite/alphabet_variant.hpp, include/seqan3/alphabet/concept.hpp
Resolves https://github.com/seqan/product_backlog/issues/278
=> [MISC] Update writable_alphabet concept

include/seqan3/search/detail/search_configurator.hpp, include/seqan3/search/detail/search_scheme_algorithm.hpp, include/seqan3/search/detail/unidirectional_search_algorithm.hpp, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/concept.hpp, include/seqan3/search/fm_index/detail/fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, include/seqan3/search/search.hpp, test/unit/search/fm_index/fm_index_collection_test_template.hpp, test/unit/search/fm_index/fm_index_test_template.hpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp
This PR is part of [seqan/product_backlog/issues/259](https://github.com/seqan/product_backlog/issues/259)
- Removes concept `fm_index_specialisation` and uses unconstrained types instead
- Removes concept `bi_fm_index_specialisation` and checks for `seqan3::detail::template_specialisation_of<typename mytype::cursor_type, seqan3::bi_fm_index_cursor>` instead
- Removes `concept_check` unit tests for `fm_index_specialisation` and `bi_fm_index_specialisation`
=> [FIX] Removing instances of [...]_index_specialisation

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/alignment/detail/pairwise_alignment_concept.hpp, include/seqan3/core/platform.hpp, include/seqan3/io/alignment_file/detail.hpp, include/seqan3/io/record.hpp, test/unit/alignment/detail/CMakeLists.txt, test/unit/alignment/detail/pairwise_alignment_concept_test.cpp
This PR resolves https://github.com/seqan/product_backlog/issues/60 task
by implementing seqan3::detail::(writable_)pairwise_alignment.
=> [MISC] introduce new concepts seqan3::detail::(writable_)pairwise_alignment

test/include/seqan3/test/cereal.hpp
`EXPECT_EQ` requires the arguments to be printable, `EXPECT_TRUE(x==y)` does not
=> [FIX] do not use EXPECT_EQ in cerealisation test

CHANGELOG.md, include/seqan3/argument_parser/validators.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2353
=> [FIX] Extension with dots not working in validator

CHANGELOG.md, include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/performance/search/dream_index/interleaved_bloom_filter_benchmark.cpp, test/snippet/search/dream_index/counting_agent.cpp, test/snippet/search/dream_index/counting_agent_construction.cpp, test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
See https://github.com/seqan/seqan3/pull/1911#issuecomment-776641004
=> [FEATURE] counting_agent for the interleaved bloom filter

test/documentation/CMakeLists.txt, test/documentation/README.md, test/documentation/doc_dev/CMakeLists.txt, test/documentation/doc_usr/CMakeLists.txt, test/documentation/seqan3-doxygen-package.cmake, test/documentation/seqan3-doxygen.cmake
This PR makes the doc_usr and doc_dev folders explicit folders instead of implicitly generated ones.
We also moved common definitions into seqan3-doxygen.cmake and all parts that were conditionally included by `SEQAN3_USER_DOC` and `SEQAN3_DEV_DOC` were moved into the `doc_{dev,usr}/CMakelists.txt` file.
That means the sub-folders `doc_{dev,usr}` do all necessary definitions of the documentations variants within their subfolder.
This PR also adds the ability to install/package our documentation via cmake. Last but not least I added a README.md to document on how to build, install and package our documentation.
=> [INFRA] cmake: changes to documentation

.github/workflows/ci.yml, doc/setup/quickstart_cmake/index.md, test/external_project/CMakeLists.txt, test/external_project/find-package-diagnostics.cmake, test/external_project/install-seqan3.cmake, test/external_project/seqan3_fetch_content_zip/CMakeLists.txt, test/external_project/seqan3_installed/CMakeLists.txt, test/external_project/seqan3_submodule_add_subdirectory/CMakeLists.txt, test/external_project/seqan3_submodule_find_package/CMakeLists.txt, test/external_project/src/hello_world.cpp, test/external_project/use-cmake3.4.cmake
This PR adds CI tests to ensure that https://github.com/seqan/seqan3/issues/1203 does always work and fixes https://github.com/seqan/product_backlog/issues/140.
=> ci for cmake's many way to use seqan3 as a library

include/seqan3/io/structure_file/input.hpp, include/seqan3/io/structure_file/record.hpp, test/unit/io/structure_file/CMakeLists.txt, test/unit/io/structure_file/format_vienna_test.cpp, test/unit/io/structure_file/structure_file_input_test.cpp, test/unit/io/structure_file/structure_file_record_test.cpp
This implements the Resolution:
* [1. Step one record type with all member functions.](https://docs.google.com/document/d/1EuGAtT0X5tDbBNFdHeuRfU2RRVOne8CSOJt3lI0U5UY/edit#bookmark=id.c1bmao8g76c5)
This implements
* structure_record
* adds member to structure_record, names were decided here: https://docs.google.com/document/d/1EuGAtT0X5tDbBNFdHeuRfU2RRVOne8CSOJt3lI0U5UY/edit#heading=h.vha98e10523x
* and does some infrastructure
=> [FEATURE] seqan3::structure_record

CHANGELOG.md, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/format_parse_test.cpp
In https://github.com/seqan/seqan3/pull/1196, we forgot to allow for, e.g. `std::vector<foo::bar>`, where `foo::bar` is an enum.
=> [FIX] parsing containers of enums not working

include/seqan3/alphabet/aminoacid/aa10li.hpp, include/seqan3/alphabet/aminoacid/aa10murphy.hpp, include/seqan3/alphabet/aminoacid/aa20.hpp, include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/aminoacid/all.hpp, include/seqan3/alphabet/aminoacid/concept.hpp, include/seqan3/alphabet/aminoacid/translation.hpp, include/seqan3/alphabet/aminoacid/translation_details.hpp, include/seqan3/alphabet/aminoacid/translation_genetic_code.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, test/unit/alphabet/aminoacid/aminoacid_translation_test.cpp, test/unit/alphabet/custom_alphabet3_test.cpp
This was decided in the [Core-Meeting 2021-02-15](https://github.com/seqan/product_backlog/issues/269#issuecomment-779182500)
=>  alphabet 02: things that are marked stable / experimental.

CHANGELOG.md, include/seqan3/argument_parser/detail/format_base.hpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/format_html_test.cpp, test/unit/argument_parser/detail/format_man_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2173
=> [FIX] author and email not showing in argument_parser

CHANGELOG.md, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/format_parse_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2393
=> [FIX] default container arguments

include/seqan3/range/views/kmer_hash.hpp, include/seqan3/range/views/minimiser.hpp, include/seqan3/range/views/take.hpp
Changes signature  `some_view::basic_iterator<{range_t->bool}>`
All `some_view::basic_iterator` instances:
asked to skip
[WIP](https://github.com/seqan/seqan3/compare/master...wvandertoorn:backlog168-pairwise_combine)
[WIP](https://github.com/seqan/seqan3/compare/master...wvandertoorn:backlog168-repeat)
asked to skip; needs a different solution. `basic_iterator` is not a sub-class of the view.
[WIP](https://github.com/seqan/seqan3/compare/master...wvandertoorn:backlog168-take_until)
See https://github.com/seqan/product_backlog/issues/168
=> Change signature of some_view::basic_iterator to use bool template param

CHANGELOG.md, include/seqan3/io/sam_file/format_bam.hpp, test/unit/io/sam_file/format_bam_test.cpp
Resolves #2417 
If we do not want to parse the sequence, but still want an alignment, but then have an empty CIGAR, we create a dummy alignment, but we forget to consume the sequence.
=> [FIX] BAM: Not consuming sequence

CHANGELOG.md, include/seqan3/io/sam_file/format_sam_base.hpp, test/unit/io/sam_file/format_bam_test.cpp, test/unit/io/sam_file/format_sam_test.cpp, test/unit/io/sam_file/sam_file_format_test_template.hpp
=> [FIX] Parsing BAM headers with 64 reference sequences

CHANGELOG.md, include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/performance/search/dream_index/interleaved_bloom_filter_benchmark.cpp, test/snippet/search/dream_index/interleaved_bloom_filter_clear.cpp, test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
resolves seqan/product_backlog#296
=> [FEATURE] interleaved_bloom_filter::clear

include/seqan3/alignment/pairwise/policy/all.hpp, include/seqan3/alignment/scoring/gap_scheme.hpp
This adds [DEPRECATE] and \deprecate annotation to gap_scheme or related
classes.
Also removed gap policy "make_cache" since it didn't exist and is using
gap_scheme.
=> [MISC] deprecate gap_scheme

test/scripts/check_include_order.pl
PR #2351 has done some renaming of includes. This messed up the include-order. To find 
most includes that have to be adjusted, I wrote a little script.
I thought this might be a great addition for the CI.
Usage example:
```
$ # finds include blocks that are not correct in seqan3
$ ./test/scripts/checkIncludeOrder.pl $(find include -type f)
$
$ # finds include blocks that have been broken since the origin/master
$ ./test/scripts/checkIncludeOrder.pl $(git diff --name-only HEAD origin/mater)
```
=> [INFRA] adds a helper script to check for missing includes

include/seqan3/range/views/minimiser_hash.hpp
```
seqan3/include/seqan3/range/views/minimiser_hash.hpp:76:49: error: parameter ‘seed’ may not appear in this context
76 |                               seed const seed = seed{0x8F3F73B5CF1C9ADE}) const
|                                                 ^~~~
```
=> [FIX] gcc-11: error: parameter ‘seed’ may not appear in this context

CHANGELOG.md, include/seqan3/alphabet/cigar/cigar.hpp, include/seqan3/alphabet/cigar/cigar_op.hpp
Resolves https://github.com/seqan/product_backlog/issues/294.
=> Cigar operation

include/seqan3/range/views/deep.hpp, test/unit/range/views/deep_test.cpp
... and returns a range_adaptor_closure.
=> [FIX] seqan3::views::deep: range_adaptator works now for function notation

test/unit/range/views/persist_test.cpp, test/unit/range/views/slice_test.cpp, test/unit/range/views/take_line_test.cpp, test/unit/range/views/take_test.cpp, test/unit/range/views/take_until_test.cpp
This exchanges some range-v3 exclusive views by std::views that produce the same result.
Part of https://github.com/seqan/product_backlog/issues/124
=> [TEST] remove some range-v3 ranges

CHANGELOG.md, include/seqan3/argument_parser/validators.hpp
This PR re-introduces a deleted constructor (change made in c94d2514e5295be0e507d4a2638f5c7630962e8e) and properly deprecates it.
This makes the upgrade-path from 3.0.2 to 3.0.3 easier.
=> [MISC] deprecate seqan3::output_file_validator constructor

CHANGELOG.md, include/seqan3/search/fm_index/concept.hpp
This PR re-introduces deleted concepts (810a135b37053940d469a03c62a6ca410865d5c0 and 68b5874b9893cdda3e7baa74c9725d407d03f2d7) and properly deprecates it.
This makes the upgrade-path from 3.0.2 to 3.0.3 easier.
=> [MISC] deprecate seqan3::[bi_]fm_index[_cursor]_specialisation

CHANGELOG.md, include/seqan3/argument_parser/argument_parser.hpp
This PR re-introduces a deleted constructor (change made in 6d2e7635e21597066cbcd3bb1dbcf77aeb7884f1) and properly deprecates it.
This makes the upgrade-path from 3.0.2 to 3.0.3 easier.
=> [MISC] deprecate seqan3::argument_parser constructor

CHANGELOG.md, include/seqan3/io/alignment_file/all.hpp, include/seqan3/io/alignment_file/detail.hpp, include/seqan3/io/alignment_file/format_bam.hpp, include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/alignment_file/format_sam_base.hpp, include/seqan3/io/alignment_file/header.hpp, include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/input_format_concept.hpp, include/seqan3/io/alignment_file/input_options.hpp, include/seqan3/io/alignment_file/misc.hpp, include/seqan3/io/alignment_file/output.hpp, include/seqan3/io/alignment_file/output_format_concept.hpp, include/seqan3/io/alignment_file/output_options.hpp, include/seqan3/io/alignment_file/sam_tag_dictionary.hpp, include/seqan3/io/sam_file/output.hpp
Part of https://github.com/seqan/product_backlog/issues/290
=> [MISC] deprecate seqan3::alignment_file* entities 

include/seqan3/alignment/matrix/detail/affine_cell_proxy.hpp, include/seqan3/alignment/matrix/detail/combined_score_and_trace_matrix.hpp
=> [FIX] use std::remove_cvref instead of seqan3::remove_cvref

CHANGELOG.md, include/seqan3/core/range/type_traits.hpp
This PR makes the old seqan3::range_compatible concept (change made in aa1ed00bd4abf8c74e9df10bf433b9442e6969fd) work again with false inputs (SFINAE-friendly).
Before, `seqan3::range_compatible<int, int>` gave a hard compiler
error.
This makes the upgrade-path from 3.0.2 to 3.0.3 easier.
=> [MISC] seqan3::range_compatible deprecation should be concept-like

include/seqan3/contrib/span/span, include/seqan3/io/detail/magic_header.hpp, include/seqan3/io/detail/misc_input.hpp, include/seqan3/io/detail/misc_output.hpp, test/unit/io/detail/CMakeLists.txt, test/unit/io/detail/misc_output_test.cpp, test/unit/io/detail/misc_test.cpp, test/unit/io/sam_file/sam_file_output_test.cpp, test/unit/io/sequence_file/sequence_file_output_test.cpp, test/unit/io/structure_file/structure_file_output_test.cpp
Documentation will be follow-up PR
=> [FIX] compression streams writing wrong format

doc/setup/library_tests/index.md, doc/setup/quickstart_cmake/index.md
This PR resolves  #2017
- `cmake` options now come before arguments in the example bash commands
- added explanation about `Release` vs `Debug` builds
=> [DOC] beginner friendly cmake documentation

CHANGELOG.md
=> [DOC] Add changelog entry for #2458

test/include/seqan3/test/sandboxed_path.hpp, test/unit/test/sandboxed_path_test.cpp
The old behaviour of `sandboxed_path` resolved symlinks if they existed on
the filesystem. This is not the indented behaviour.
`sandboxed_path` should not change behaviour depending on the physical
existence of symlinks.
This commits also adds a test preventing any regression bugs.
=> [FIX] sandboxed_path shall not resolve symlinks

.github/workflows/ci.yml
The wild coverage change is due to https://docs.codecov.io/docs/fixing-reports now working,
coverage is now not reported for lines like
```cpp
{
```
, i.e., lines only containing a single symbol from `{}()`.
we apparently had 614 such occurrences.
One of them was apparently a miss.
So we "lost" 613 hits and 1 miss.
All in all that means that our coverage did not decrease, because we did not gain any misses.
But from a relative POV, we had `(10867 - 188) / 10867 = 0.9827` coverage before, but now only have `(10254 - 187) / 10254 = 0.9817` coverage.
See also: https://docs.codecov.io/docs/coverage-offset
TLDR; the coverage dropped because our coverage code base shrunk.
=> [FIX] use absolute paths in codecov

include/seqan3/alphabet/quality/concept.hpp
=> [MISC] use new CPO-way to define seqan3::assign_phred_to

include/seqan3/argument_parser/validators.hpp
I want to hand over `sandboxed_path` to the validators. The
file_validator_base accidentally identifies `sandboxed_path` as a
useful forward_range to iterate over. It is sufficient if the
`std::filesystem::path const&` c'tor accepts the `sandboxed_path`.
=> [FIX] argument_parser/file_validator_base accept derivatives of filesystem::path

CHANGELOG.md, doc/cookbook/index.md, doc/tutorial/sequence_file/index.md, include/seqan3/io/record.hpp, include/seqan3/io/sequence_file/format_fastq.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/sequence_file/input_format_concept.hpp, include/seqan3/io/sequence_file/input_options.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/sequence_file/output_format_concept.hpp, test/snippet/io/sequence_file/sequence_file_input_custom_fields.cpp, test/snippet/io/sequence_file/sequence_file_output_fields_trait_1.cpp, test/unit/io/record_test.cpp, test/unit/io/sequence_file/sequence_file_format_test_template.hpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_output_test.cpp
- adds [DEPRECATED] in many places.
- erased mentioning of seq_qual everywhere I could find
- Wrap all usages of seqan3::field::seq_qual
- referenced cookbook to usage of field::seq and field::qual
- referenced cookbook in changelog
=> [MISC] deprecate seqan3::field::seq_qual

include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/std/ranges, test/unit/argument_parser/format_parse_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2464
The resolving test looks like:
```cpp
TEST_F(detect_breakends, test_unknown_argument)
{
cli_test_result result = execute_app("iGenVar",
"-j", data(default_alignment_long_reads_file_path),
fasta_out_file_path,
"-m 9");
std::string expected_err
{
// Old message: "[Error] Value parse failed for -m: Argument 9 could not be parsed as type std::string.\n"
"[Error] Validation failed for value 9.\n"
"Value must be one of (method name or number) [cigar_string,0,split_read,1,read_pairs,2,read_depth,3].\n"
};
EXPECT_EQ(result.exit_code, 65280);
EXPECT_EQ(result.out, std::string{});
EXPECT_EQ(result.err, expected_err);
}
```
=> [FIX] Fix unhelpful message with help_page_message of the validator

include/seqan3/io/sam_file/detail/cigar.hpp, include/seqan3/io/sam_file/detail/format_sam_base.hpp, include/seqan3/io/sam_file/format_bam.hpp, include/seqan3/io/sam_file/format_sam.hpp
Resolves first part of https://github.com/seqan/iGenVar/issues/85
We decided to move `parse_cigar` from `seqan3::detail::format_sam_base` into `seqan3/io/sam_file/detail/cigar.hpp`.
This is still detail, but now you normaly just need to include one header. Apon this, it is also easier to get everything to do with `cigar` out of `detail` later.
=> [MISC] Move `parse_cigar` from `format_sam_base` into `cigar`.

include/seqan3/utility/simd/algorithm.hpp, include/seqan3/utility/simd/detail/simd_algorithm_avx2.hpp, include/seqan3/utility/simd/detail/simd_algorithm_avx512.hpp, include/seqan3/utility/simd/detail/simd_algorithm_sse4.hpp, test/snippet/utility/simd/simd_store.cpp, test/unit/utility/simd/simd_algorithm_test.cpp
Adds special store function to the simd utilities.
This function allows to store a simd vector to some memory region irrespective of the underlying memory alignment.
It wraps the intrinsics for SSE4, AVX2, an AVX512 and defaults to some sequential memory write in case a non builtin simd type is used.
The code is tested and documented. It does not affect any other code so far.
=> [FEATURE] Add simd store function.

.github/ISSUE_TEMPLATE/release-checklist.md, CHANGELOG.md, test/api_stability/3.0.2/0001-NOAPI-Disable-Werror.patch, test/api_stability/3.0.2/0002-NOAPI-DETAIL-MISC-Remove-top-level-scoring-scheme-de.patch, test/api_stability/3.0.2/0003-NOAPI-INCLUDE-add-missing-include-bi_fm_index.patch, test/api_stability/3.0.2/0004-NOAPI-INCLUDE-add-missing-include-gap-gapped.patch, test/api_stability/3.0.2/0005-NOAPI-DETAIL-MISC-rename-detail-char_predicate_-comb.patch, test/api_stability/3.0.2/0006-NOAPI-DETAIL-FIX-renaming-config_element_specialisat.patch, test/api_stability/3.0.2/0007-NOAPI-DETAIL-FIX-renaming-strong_type_specialisation.patch, test/api_stability/3.0.2/0008-NOAPI-INCLUDE-add-missing-include-detail-sizeof_bits.patch, test/api_stability/3.0.2/0009-NOAPI-INCLUDE-add-missing-include-sdsl-bits.patch, test/api_stability/3.0.2/0010-API-WRONG-USAGE-MISC-Simplify-the-pipe-operator-for-.patch, test/api_stability/3.0.2/0011-API-BREAKAGE-MISC-adjusting-seqan3_version-semantics.patch, test/api_stability/3.0.2/0012-NOAPI-INCLUDE-add-missing-include-seqan3-debug_strea.patch, test/api_stability/3.0.2/0013-NOAPI-BREAKAGE-We-changed-the-behaviour-of-seqan3-de.patch, test/api_stability/3.0.2/0014-API-FIX-constructor-will-not-throw-any-more.patch, test/api_stability/3.0.2/0015-API-FIX-subcommand-is-now-allowed-to-contain-a-dash.patch, test/api_stability/3.0.2/0016-API-FIX-std-cout-of-argument_parser-changed.patch, test/api_stability/3.0.2/0017-API-FIX-type-deduction-for-seqan3-value_list_validat.patch, test/api_stability/3.0.2/0018-API-FIX-the-internal-order-of-piping-seqan3-configur.patch, test/api_stability/3.0.2/0019-API-FIX-arithmetic_range_validator-should-take-any-i.patch, test/api_stability/3.0.2/0020-NOAPI-DEPRECATED-MISC-remove-seqan3-stream_REMOVEME.patch, test/api_stability/3.0.2/0021-NOAPI-DETAIL-MISC-introduce-alphabet_variant-rank_to.patch, test/api_stability/3.0.2/0022-API-FIX-compression-streams-writing-wrong-format.patch, test/api_stability/CMakeLists.txt, test/api_stability/README.md
This is a new infrastructure to test API stability on the basis of our tests from our latest stable release.
Most of the included patches are cherry-picked on top of the 3.0.2 release.
=> [INFRA] new api_stability test

.github/ISSUE_TEMPLATE/api_cron_template.md, .github/workflows/api.yml, include/seqan3/core/bit_manipulation.hpp
Resolves https://github.com/seqan/product_backlog/issues/310
Open:
See https://github.com/eseiler/seqan3/issues/7 for example
=> [INFRA] API-Stability cronjob

include/seqan3/range/views/slice.hpp
seqan3::views::slice should as std::views::take use range_difference_t for positions.
=> [FIX] gcc-11: slice should take range_difference_t

include/seqan3/range/views/drop.hpp
```
seqan3/include/seqan3/range/views/drop.hpp:95:49: error: no match for ‘operator|’ (operand types are ‘std::ranges::ref_view<std::__cxx11::list<seqan3::dna4> >’ and ‘std::ranges::views::__adaptor::_Partial<std::ranges::views::_Drop, long unsigned int>’)
95 |             return std::forward<urng_t>(urange) | std::views::drop(drop_size);
|                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [FIX] gcc-11: std::views::drop expects std::ranges::range_difference_t<urng_t>

CHANGELOG.md, doc/cookbook/alphabet_conversion.cpp, doc/cookbook/index.md, include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp, include/seqan3/alphabet/nucleotide/all.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/structure_file/output.hpp, include/seqan3/range/container/bitcompressed_vector.hpp, include/seqan3/range/views/all.hpp, include/seqan3/range/views/convert.hpp, include/seqan3/search/search.hpp, include/seqan3/utility/views/convert.hpp, test/performance/io/format_fasta_benchmark.cpp, test/snippet/alphabet/aminoacid/aa10li.cpp, test/snippet/alphabet/aminoacid/aa10murphy.cpp, test/snippet/alphabet/composite/semialphabet_any.cpp, test/snippet/range/views/range_view_to_rank.cpp, test/snippet/utility/views/convert_15_to_5.cpp, test/snippet/utility/views/convert_int_to_bool.cpp, test/unit/alignment/debug_stream_aligned_sequence_test.cpp, test/unit/io/sam_file/sam_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_format_fastq_test.cpp, test/unit/io/sequence_file/sequence_file_format_test_template.hpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/structure_file/format_vienna_test.cpp, test/unit/io/structure_file/structure_file_input_test.cpp, test/unit/range/views/convert_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/324
=> [MISC] deprecate seqan3::views::convert

CHANGELOG.md, include/seqan3/io/sam_file/format_bam.hpp, test/unit/io/sam_file/format_bam_test.cpp
Resolves https://github.com/seqan/seqan3/issues/1201
=> [FIX] not accepting BAM with empty header

test/documentation/.vercel/install.sh
Sometimes the path is different (some directory in the path is `workpath0` instead of `path0` or vice versa).
If that happens, we clean the build directory and reconfigure.
=> [FIX,INFRA] sporadic vercel build cache failures

CHANGELOG.md, include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/core/platform.hpp, include/seqan3/io/sam_file/format_sam.hpp, include/seqan3/range/views/drop.hpp, include/seqan3/range/views/slice.hpp, include/seqan3/search/detail/unidirectional_search_algorithm.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/performance/range/views/view_drop_benchmark.cpp, test/performance/range/views/view_drop_view_take_benchmark.cpp, test/snippet/utility/views/drop.cpp, test/unit/range/views/drop_test.cpp, test/unit/search/views/minimiser_test.cpp
fixes https://github.com/seqan/product_backlog/issues/325
=> deprecate seqan3::views::drop

include/seqan3/alignment/matrix/detail/coordinate_matrix.hpp, test/unit/alignment/matrix/detail/trace_iterator_banded_test.cpp, test/unit/alignment/matrix/detail/trace_iterator_test.cpp, test/unit/search/views/minimiser_test.cpp
Workaround for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100205
```
seqan3/include/seqan3/alignment/matrix/detail/coordinate_matrix.hpp:198:84: error: invalid use of non-static data member ‘seqan3::detail::coordinate_matrix<index_t>::iterator::column_id’
198 |                               | std::views::transform(convert_to_matrix_coordinate{column_id}));
|                                                                                    ^~~~~~~~~
```
```
seqan3/test/unit/alignment/matrix/detail/trace_iterator_test.cpp:41:73: error: invalid use of non-static data member ‘trace_iterator_fixture::matrix’
41 |     using trace_iterator_type = decltype(seqan3::detail::trace_iterator{matrix.begin()});
|                                                                         ^~~~~~
```
=> [FIX] gcc-11: error: invalid use of non-static data member

CHANGELOG.md, include/seqan3/range/views/to_upper.hpp, test/snippet/range/views/to_upper.cpp, test/unit/range/views/to_upper_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/334
=> [MISC] deprecate seqan3::views::to_upper

CHANGELOG.md, include/seqan3/range/views/to_lower.hpp, test/snippet/range/views/to_lower.cpp, test/unit/range/views/as_const_test.cpp, test/unit/range/views/move_test.cpp, test/unit/range/views/to_lower_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/333
=> [MISC] deprecate seqan3::views::to_lower

include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/search/detail/unidirectional_search_algorithm.hpp
Workaround for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99433#c7
```
seqan3/include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp:265:41: error: no match for ‘operator|’ (operand types are ‘std::vector<__vector(1) int, seqan3::aligned_allocator<__vector(1) int, 4> >’ and ‘std::ranges::views::__adaptor::_Partial<std::ranges::views::_Drop, long unsigned int>’)
265 |         for (auto alphabet1 : sequence1 | std::views::drop(column_size))
|                               ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [FIX] gcc-11: error: no match for ‘operator|’

CHANGELOG.md, include/seqan3/alphabet/quality/all.hpp, include/seqan3/alphabet/quality/phred42.hpp, include/seqan3/alphabet/quality/phred63.hpp, include/seqan3/alphabet/quality/phred68solexa.hpp, include/seqan3/alphabet/quality/phred94.hpp, include/seqan3/alphabet/quality/phred_base.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/range/container/concept.hpp, test/snippet/alphabet/composite/alphabet_tuple_base_subtype_assignment.cpp, test/snippet/alphabet/composite/alphabet_tuple_base_subtype_construction.cpp, test/snippet/alphabet/composite/alphabet_tuple_base_value_assignment.cpp, test/snippet/alphabet/composite/alphabet_tuple_base_value_construction.cpp, test/snippet/alphabet/quality/phred42.cpp, test/snippet/alphabet/quality/phred63.cpp, test/snippet/alphabet/quality/phred94.cpp, test/snippet/alphabet/quality/qualified.cpp, test/snippet/range/views/range_view_to_char.cpp, test/snippet/range/views/range_view_to_rank.cpp, test/snippet/range/views/trim_quality_dna5q.cpp, test/snippet/range/views/trim_quality_phred42.cpp, test/unit/alphabet/composite/composite_integration_test.cpp, test/unit/alphabet/quality/phred_test_template.hpp, test/unit/alphabet/quality/qualified_test.cpp, test/unit/alphabet/quality/quality_conversion_integration_test.cpp, test/unit/range/views/get_test.cpp, test/unit/range/views/trim_quality_test.cpp, test/unit/search/search_collection_test.cpp, test/unit/search/search_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/316
=> [MISC] Alphabet: deprecate phred_type constructor

include/seqan3/alphabet/nucleotide/dna16sam.hpp, include/seqan3/alphabet/nucleotide/sam_dna16.hpp, include/seqan3/alphabet/quality/phred68legacy.hpp, include/seqan3/alphabet/quality/phred68solexa.hpp, include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/api_stability/3.0.2/0023-NOAPI-INCLUDE-add-missing-includes-seqan3-views-pers.patch, test/api_stability/3.0.2/0024-NOAPI-INCLUDE-add-missing-includes-std-isnan.patch
=> [FIX] API stability

CHANGELOG.md, include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/range/decorator/gap_decorator.hpp, test/unit/alignment/aligned_sequence_test_template.hpp
Resolves: https://github.com/seqan/product_backlog/issues/322
=> [MISC] Rename gap_decorator::unaligned_seq_type to gap_decorator::unaligned_sequence_type.

include/seqan3/alignment/configuration/align_config_band.hpp
```
[ 50%] Building CXX object CMakeFiles/align_cfg_band_example_snippet.dir/alignment/configuration/align_cfg_band_example.cpp.o
In file included from src/test/snippet/alignment/configuration/align_cfg_band_example.cpp:1:
src/include/seqan3/alignment/configuration/align_config_band.hpp:75:58: error: incomplete type ‘std::numeric_limits<int>’ used in nested name specifier
75 |     int32_t lower_diagonal{std::numeric_limits<int32_t>::lowest()};
|                                                          ^~~~~~
src/include/seqan3/alignment/configuration/align_config_band.hpp:75:66: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘int32_t’ {aka ‘int’} in initialization
75 |     int32_t lower_diagonal{std::numeric_limits<int32_t>::lowest()};
| …
```
=> [FIX] gcc11: missing include

include/seqan3/io/sequence_file/input.hpp
This PR removes the variant used internally for the sequence file input. The main advantage is that the template list of the input file gets reduced by one parameter. This change does not effect any critical path of the sequence file input, since the mechanism for storing the selected format is completely internal and never exposed to the user. 
Reducing the template parameter also shows that the interface becomes easier to use, because the user does not need to remember to set the correct file format in the template parameter list of the class template, when she calls the interface with a specific format tag.
Note the current change keeps the internal usage of a variant in order to use the currently existing interfaces to extract the format type from the extension of a file path. Thus, …
=> [API] Move the list of file formats into the sequence file input.

CHANGELOG.md, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/range/views/as_const.hpp, test/snippet/range/views/as_const.cpp, test/unit/range/views/as_const_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/323
=> [MISC] deprecate seqan3::views::as_const

CHANGELOG.md, doc/tutorial/sequence_file/index.md, doc/tutorial/sequence_file/sequence_file_solution3.cpp, include/seqan3/range/views/move.hpp, test/snippet/range/views/move.cpp, test/snippet/utility/views/drop.cpp, test/unit/range/views/drop_test.cpp, test/unit/range/views/move_test.cpp
resolve https://github.com/seqan/product_backlog/issues/328
=> [MISC] deprecate seqan3::views::move

.github/ISSUE_TEMPLATE/api_cron_template.md, .github/workflows/api.yml
Resolves https://github.com/seqan/product_backlog/issues/368
No ccache because this action won't run very often and hence almost never have cache hits (also, the run needs to succeed for the cache to be stored).
=> [INFRA] Add GCC 9 and 11 to API

.github/workflows/scripts/process_compiler_error_log.py
* Escape HTML (`<>&`) in the error message summary
* Truncate error message summary such that it fits one line
=> [INFRA] Small log parsing changes

include/seqan3/utility/char_operations/predicate.hpp
```
src/include/seqan3/utility/char_operations/predicate.hpp:577: warning: explicit link request to 'ff9090' could not be resolved
```
https://cdash.seqan.de/testDetails.php?test=43188671&build=146060
=> [DOC] Escape quote in HTML table

include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/alphabet/composite/alphabet_tuple_base.hpp, include/seqan3/alphabet/composite/alphabet_variant.hpp, include/seqan3/core/configuration/detail/concept.hpp, include/seqan3/core/configuration/detail/configuration_utility.hpp, include/seqan3/utility/tuple/concept.hpp, include/seqan3/utility/type_list/traits.hpp, include/seqan3/utility/type_list/type_list.hpp, test/unit/alignment/pairwise/align_pairwise_test.cpp, test/unit/alignment/pairwise/align_result_selector_test.cpp, test/unit/alignment/pairwise/alignment_result_test.cpp, test/unit/alphabet/nucleotide/nucleotide_conversion_integration_test.cpp, test/unit/core/range/range_iterator_test.cpp, test/unit/utility/type_list/type_list_traits_test.cpp, test/unit/utility/type_traits/basic_test.cpp
part of https://github.com/seqan/product_backlog/issues/124
=> remove #include<meta/meta.hpp>

CHANGELOG.md, include/seqan3/alphabet/views/translate_join.hpp, include/seqan3/argument_parser/validators.hpp, include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/utility/views/interleave.hpp, include/seqan3/utility/views/join_with.hpp, test/performance/alphabet/views/view_translate_2D_1D_benchmark.cpp, test/performance/alphabet/views/view_translate_2D_benchmark.cpp, test/performance/search/search_benchmark.cpp
- Deprecates `seqan3::views::join` use `seqan3::views::join_with` or `std::views::join` instead.
- Adds `seqan3::views::join_with`
- Move files from seqan3/ranges/views/join.hpp to seqan3/utility/views/join_with.hpp
resolves https://github.com/seqan/product_backlog/issues/351
=> [MISC] Replace `seqan3::views::join` with `seqan3::views::join_with`

CHANGELOG.md, doc/cookbook/custom_dna4.cpp, include/seqan3/alphabet/nucleotide/dna15.hpp, include/seqan3/alphabet/nucleotide/dna16sam.hpp, include/seqan3/alphabet/nucleotide/dna3bs.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/nucleotide_base.hpp, include/seqan3/alphabet/nucleotide/rna15.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/alphabet/nucleotide/rna5.hpp
Part of https://github.com/seqan/product_backlog/issues/295
=> nucleotide_base complement table static member functions

include/seqan3/alphabet/mask/mask.hpp, include/seqan3/core/detail/debug_stream_alphabet.hpp, test/snippet/alphabet/mask/mask.cpp, test/snippet/alphabet/mask/masked.cpp, test/unit/alphabet/mask/mask_test.cpp, test/unit/core/debug_stream_test.cpp, test/unit/utility/views/elements_test.cpp
Converts `seqan3::mask::(UN)MASKED` to `seqan3::mask::(un)masked`.
As done in the patch in https://github.com/seqan/product_backlog/issues/311 the strings in `seqan3/core/detail/debug_stream_alphabet.hpp` remain uppercase.
Resolves: https://github.com/seqan/product_backlog/issues/311
=> [MISC] Lower case seqan3::mask::(UN)MASKED

include/seqan3/alphabet/aminoacid/translation.hpp, include/seqan3/alphabet/aminoacid/translation_details.hpp
Lowercase `seqan3::detail::translation_table<dna15, gc>::value` and `seqan3::detail::translation_table::value`.
Resolves: https://github.com/seqan/product_backlog/issues/318
=> [MISC] Lower case seqan3::detail::translation_table::value

include/seqan3/alphabet/quality/phred42.hpp, include/seqan3/alphabet/quality/phred63.hpp, include/seqan3/alphabet/quality/phred68solexa.hpp, include/seqan3/alphabet/quality/phred94.hpp, include/seqan3/alphabet/quality/phred_base.hpp
Left over of https://github.com/seqan/product_backlog/issues/358
=> [MISC] deprecate phred_base(phred_type) constructor

include/seqan3/alphabet/mask/all.hpp, include/seqan3/alphabet/mask/mask.hpp, include/seqan3/alphabet/mask/masked.hpp
Resolves https://github.com/seqan/product_backlog/issues/313
Since there was already documentation, I just expanded it a bit and created links. I hope this corresponds to the desired result.
The new documentation looks like:
=> [DOC] Added more documentation for the mask submodule

CHANGELOG.md, doc/tutorial/pairwise_alignment/configurations.cpp, doc/tutorial/pairwise_alignment/pa_assignment_3_solution.cpp, doc/tutorial/pairwise_alignment/pairwise_alignment_solution_3.cpp, include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp, test/performance/alignment/global_affine_alignment_protein_simd_benchmark.cpp, test/snippet/alignment/scoring/aminoacid_scoring_scheme.cpp, test/unit/alignment/pairwise/fixture/global_affine_unbanded.hpp, test/unit/alignment/pairwise/fixture/local_affine_banded.hpp, test/unit/alignment/pairwise/fixture/local_affine_unbanded.hpp, test/unit/alignment/scoring/detail/simd_matrix_scoring_scheme_test.cpp, test/unit/alignment/scoring/scoring_scheme_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/317
=> [MISC] Alignment: aminoacid scoring scheme - lower case member constants

include/seqan3/core/platform.hpp
Part of release checklist (https://github.com/seqan/seqan3/issues/2334)
Go through workarounds and re-evaluate them. This workaround is apparently fixes since gcc-10.3 so let's see :)
=> [MISC] gcc-10.3 supports SEQAN3_WORKAROUND_GCC_99318 now

test/unit/std/charconv_int_test.cpp
Fixes https://cdash.seqan.de/testDetails.php?test=43930535&build=149540
The actual error is:
```
[----------] 10 tests from integral_from_char_test/7, where TypeParam = unsigned long
[ RUN      ] integral_from_char_test/7.postive_number
[       OK ] integral_from_char_test/7.postive_number (0 ms)
[ RUN      ] integral_from_char_test/7.negative_number
[       OK ] integral_from_char_test/7.negative_number (0 ms)
[ RUN      ] integral_from_char_test/7.overflow_error
[       OK ] integral_from_char_test/7.overflow_error (0 ms)
[ RUN      ] integral_from_char_test/7.partial_parsing
[       OK ] integral_from_char_test/7.partial_parsing (0 ms)
[ RUN      ] integral_from_char_test/7.invalid_argument_error
[       OK ] integral_from_char_test/7.invalid_argument_error (0 ms)
[ RUN      ] …
```
=> [FIX] out of bounds in charconv test

.github/workflows/api.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_misc.yml, .github/workflows/documentation.yaml, .github/workflows/latest_libraries.yml, .github/workflows/scripts/configure_apt.sh
This should hopefully prevent spurious fails when running apt-related commands, e.g.
https://github.com/seqan/seqan3/pull/2624/checks?check_run_id=2553996540
```
+ sudo apt-get update
[...]
Ign:28 https://packages.microsoft.com/repos/azure-cli focal InRelease
Ign:29 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Err:30 https://packages.microsoft.com/repos/azure-cli focal Release
Could not connect to packages.microsoft.com:443 (13.82.67.141), connection timed out [IP: 13.82.67.141 443]
Err:31 https://packages.microsoft.com/ubuntu/20.04/prod focal Release
Unable to connect to packages.microsoft.com:https: [IP: 13.82.67.141 443]
Reading package lists...
E: The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' no longer has a Release file.
E: The …
```
=> [INFRA] retry apt

test/unit/alignment/matrix/debug_matrix_test.cpp
See https://cdash.seqan.de/viewBuildError.php?buildid=149537
It gets moved here:
https://github.com/seqan/seqan3/blob/5bf6e251ffb6bcc5ebfd44b0cf502a88b90a359d/test/unit/alignment/matrix/debug_matrix_test.cpp#L404
=> [FIX] uninitialised warning

include/seqan3/argument_parser/detail/format_parse.hpp
Since `enumeration_names` is a map, the order of keys is not defined and may differ across compilers or operating systems.
This makes it hard to, e.g., compare error messages in apps.
Hence, we should sort the keys. I chose to sort them by the order defined in the enum.
=> [MISC] Fix enum order when throwing parser error

include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/format_parse_test.cpp
follow-up of #2642 
In case multiple values are the same, we should use the (always unique) keys as tie-breaker
=> [MISC] improve enum ordering when throwing parser error

include/seqan3/std/ranges, test/unit/std/ranges_test.cpp
https://eel.is/c++draft/ranges.syn defines more views to be `std::ranges::borrowed_range`s.
This PR adds all of them.
Doing this showed that std::views::take isn't a borrowed range in gcc-10, this PR will define that property also for gcc-10.
gcc-10.3 does this anyway.
=> Borrowed range

.github/workflows/api.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_misc.yml, .github/workflows/documentation.yaml, .github/workflows/latest_libraries.yml
This should be cherry-picked into master afterwards
:( 
```
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 40.74.238.15 443]
Hashes of expected file:
- Filesize:73160 [weak]
- SHA512:782bf0315c8de4314049e599009430053b75a5015491b3d383b09239fcf31857d52bac3399cef8e813f7b2131dce09b03eaf89d79c5ebd2849402cee7aa9d228
- SHA256:dbf4bf81b4a0a17dae53f2aff3edd4cf5bb1dcd5dcd216ce5c5c8ab7c507a26a
- SHA1:0e1b47276cae4168a08d8fd981891d4773f053b9 [weak]
- MD5Sum:0fcf3ed335cd4efde65300bb48c05afe [weak]
Release file created at: Sat, 15 May 2021 00:38:08 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead. …
```
=> [INFRA] Ignore apt failures

CHANGELOG.md, include/seqan3/io/alignment_file/output.hpp, include/seqan3/io/record.hpp, include/seqan3/io/sam_file/input.hpp, include/seqan3/io/sam_file/output.hpp, test/api_stability/3.0.2/0038-MISC-deprecate-seqan3-sam_file-output-fields-seqan3-.patch, test/performance/io/format_sam_benchmark.cpp, test/snippet/io/sam_file/sam_file_input_construction_without_automatic_type_deduction.cpp, test/unit/io/sam_file/sam_file_format_test_template.hpp, test/unit/io/sam_file/sam_file_output_test.cpp
sam_file_output does not need the fields ref_seq, evalue, bit_score.
This commit remove those fields from the default-fields and ensures that custom fields don't contain those fields.
This commit also splits ::push_back and ::emplace_back into four versions to deprecate the usage of the old default-fields case.
=> remove ref_seq, evalue, bit_score from sam file output

test/scripts/update_copyright.sh
Helper script to update the copyright years for release #2334
Result of this script can be seen in PR #2673
Example, you want to update all the "Copyright .*-2020" to
"Copyright .*-2021" you can call
`./test/scripts/update_copyright.sh 2020 2021 $(find . -not -path '*/\.*' -type f)`
It will also provide a list of "Copyright" entries that it didn't touch, but had a "Copyright" word in it.
=> [MISC] copyright year update script

include/seqan3/core/bit_manipulation.hpp, test/performance/range/views/view_drop_benchmark.cpp, test/performance/range/views/view_drop_view_take_benchmark.cpp, test/performance/std/bit_benchmark.cpp
Some guards were missing in the benchmarks for `-DSEQAN3_REMOVE_DEPRECATED_310` to work
=> [FIX] some deprecations

test/cmake/seqan3_require_benchmark.cmake
Now that gbenchmark renamed `master` to `main` and deleted `master`, we get errors since the default branch is `master`.
=> [FIX] ExternalProject_Add using wrong gbenchmark tag

.github/workflows/documentation.yaml
When we merge the release branch into master, this is often just a fast-forward.
GitHub Actions won't trigger on such pushes. This is good in the sense that the CI that already ran on the release branch doesn't need to run again on the master branch.
However, for actions that only run on master, i.e. deploying the documentation, this also means that the updated documentation is never deployed.
With this PR, we can manually trigger deploying the documentation if we have such a fast-forward-merge case.
=> [INFRA] Add manual trigger for doc deployment

README.md
The badge still showed the status of our old CI.
GitHub badges are not customisable: [![SeqAn3 CI on Linux](https://github.com/seqan/seqan3/actions/workflows/ci_linux.yml/badge.svg?branch=master)](https://github.com/seqan/seqan3/actions/workflows/ci_linux.yml)
That's why I used a custom badge: [![build status](https://img.shields.io/github/workflow/status/seqan/seqan3/SeqAn3%20CI%20on%20Linux/master?style=flat&logo=github&label=SeqAn3%20CI)](https://github.com/seqan/seqan3/actions?query=branch%3Amaster)
=> [DOCS] Update README badge

test/cmake/seqan3_path_longest_stem.cmake, test/cmake/seqan3_test_component.cmake, test/snippet/release/3.0.0_complement-and-translate-without-copying.cpp, test/snippet/release/3.0.0_file-conversion.cpp, test/snippet/release/3.0.0_read-fasta-and-print-entities.cpp, test/snippet/release/3.0.1_parallel-alignments.cpp, test/snippet/release/3.0.2_dynamic-hit-configuration.cpp, test/snippet/release/3.0.2_lazy-search-result-range.cpp, test/snippet/release/3.0.2_user-callback-in-alignment-and-search.cpp, test/snippet/release/3.0.3_io-record.cpp, test/snippet/release/3.0.3_literals-namespace.cpp, test/snippet/release/README.md
The cmake change will allow dots (i.e. `.`) in test names, e.g. "foo3.3_test.cpp" or "3.0.1_some-message.cpp". Before this change the test names would have been `foo3` and `3` instead of `foo3.3` and `3.0.1_some-message`.
The main part of the PR adds (updated) snippets of our release notes.
=> [TEST] Release snippets

doc/cookbook/compression_threads.cpp, include/seqan3/contrib/stream/bgzf_istream.hpp, include/seqan3/contrib/stream/bgzf_ostream.hpp, include/seqan3/contrib/stream/bgzf_stream_util.hpp, include/seqan3/contrib/stream/bz2_istream.hpp, include/seqan3/contrib/stream/bz2_ostream.hpp, include/seqan3/contrib/stream/gz_istream.hpp, include/seqan3/contrib/stream/gz_ostream.hpp, include/seqan3/io/detail/magic_header.hpp, include/seqan3/io/detail/misc_input.hpp, include/seqan3/io/detail/misc_output.hpp, include/seqan3/io/structure_file/input.hpp, test/performance/io/stream_input_benchmark.cpp, test/performance/io/stream_output_benchmark.cpp, test/unit/io/detail/misc_output_test.cpp, test/unit/io/sam_file/sam_file_input_test.cpp, test/unit/io/sam_file/sam_file_output_test.cpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_output_test.cpp, test/unit/io/structure_file/structure_file_input_test.cpp, test/unit/io/structure_file/structure_file_output_test.cpp
In https://github.com/seqan/seqan3/issues/2726#issuecomment-856603031 we noticed that the current header tests can't be build via
```
cmake -DSEQAN3_NO_ZLIB=1 -DSEQAN3_NO_BZIP2=1 <seqan3>/test/header
```
This PR fixes that.
=> [FIX] properly guard ZLIB and BZIP2 

test/performance/io/detail/view_take_until_benchmark.cpp
This patch addresses the performance regression between 3.0.2 and 3.0.3.
The view_take_until benchmark was refactored after the 3.0.2 release.
The benchmark code was accidentally changed in its semantics, causing
a false indication of increased run time. This patch restores the
benchmark to its original test.
=> [FIX] Adjust benchmark for view_take_until

include/seqan3/argument_parser/validators.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
Part of: https://github.com/seqan/product_backlog/issues/222 
I was not able to close one coverage gap. I think some code blocks will almost never be executed or only if the OS seriously messes something up.
Here is the Codecov report I used: https://codecov.io/gh/seqan/seqan3/src/master/include/seqan3/argument_parser/validators.hpp
=> [MISC] Increase coverage in argument_parser/validator

CHANGELOG.md, include/seqan3/search/fm_index/fm_index.hpp
Fixes unsigned vs signed int bug. This causes to limit the fm_index to
work for any text sizes above 2^31-1 base pairs.
This fix now allows up to 2^32-2 which is required for the human genome.
Correction: it should work with 2^63-2 base pairs.
=> [FIX] Constructing large fm_indices

include/seqan3/utility/bloom_filter/all.hpp, include/seqan3/utility/bloom_filter/bloom_filter.hpp, test/performance/utility/bloom_filter/CMakeLists.txt, test/performance/utility/bloom_filter/bloom_filter_benchmark.cpp, test/snippet/utility/bloom_filter/bloom_filter_clear.cpp, test/snippet/utility/bloom_filter/bloom_filter_constructor.cpp, test/snippet/utility/bloom_filter/bloom_filter_constructor_compressed.cpp, test/snippet/utility/bloom_filter/bloom_filter_contains.cpp, test/snippet/utility/bloom_filter/bloom_filter_count.cpp, test/snippet/utility/bloom_filter/bloom_filter_emplace.cpp, test/snippet/utility/bloom_filter/bloom_filter_reset.cpp, test/unit/utility/bloom_filter/CMakeLists.txt, test/unit/utility/bloom_filter/bloom_filter_test.cpp
Resolves #2490.
Implementation of a simple (not interleaved) bloom filter.  
This is a basic data structure, so I think it makes sense to include it to the library (for discussion, see #2490). It can, e.g., be used as an alternative to a k-mer index if the k-mer size needed is too high. In my application, I use the proposed implementation for the filtering of human reads.
The Bloom Filter was implemented based on the existing code for the Interleaved Bloom Filter with the following modifications:
- All binning-related code was adapted or removed.
- No agents are used for querying and counting, as the return types are native, thus I think there are no advantages when using agents in this case.
- For querying a single hash value, use `bool bloom_filter::contains(value)`
- For counting k-mer …
=> [FEATURE] implementation of a bloom filter

include/seqan3/argument_parser/detail/version_check.hpp
To turn off version check you have to set `--version-check false` on the
command line.
The previous message advised to set it to `--version-check OFF` which
will lead to an invalid argument exception by the argument parser.
=> [FIX] correct message on how to turn off version checks

include/seqan3/io/views/detail/take_until_view.hpp
This simplifies take_until and does two things
* differentiates between basic_iterator and basic_consume_iterator (two different modes of take_until)
* uses `basic_[consume_]iterator/sentinel<bool>` https://github.com/seqan/product_backlog/issues/168
=> Simplify take_until

include/seqan3/std/type_traits
__cpp_lib_type_identity should be determined by the standard library version and not the compiler version, since clang could use the stdlib from gcc.
=> [FIX] __cpp_lib_type_identity should be determined by the standard library version and not the compiler version

include/seqan3/search/detail/search_scheme_precomputed.hpp
```
/seqan3/include/seqan3/search/detail/search_scheme_precomputed.hpp:87:22: error: default initialization of an object of const type 'const int'
inline int constexpr optimum_search_scheme;
^
= 0
```
part of https://github.com/seqan/product_backlog/issues/127
=> [FIX] clang+gcc9: error: default initialization of an object of const type

test/unit/alignment/pairwise/policy/affine_gap_policy_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp, test/unit/search/fm_index_cursor/fm_index_cursor_test_template.hpp
=> [FIX] clang+gcc9: error: constexpr if condition is not a constant expression

include/seqan3/alignment/matrix/detail/coordinate_matrix.hpp
```
/seqan3/include/seqan3/alignment/matrix/detail/coordinate_matrix.hpp:262:9: error: cannot increment value of type 'int __attribute__((ext_vector_type(1)))' (vector of 1 'int' value)
++column_id;
^ ~~~~~~~~~
```
=> [FIX] clang+gcc9: error: cannot increment value of type 'int __attribute__((ext_vector_type(1)))' (vector of 1 'int' value)

include/seqan3/core/algorithm/detail/execution_handler_parallel.hpp
```
/seqan3/include/seqan3/core/algorithm/detail/execution_handler_parallel.hpp:161:23: error: no matching function for call to 'forward'
algorithm(std::forward<forward_input_t>(std::get<0>(input_tpl)), std::move(callback));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [FIX] clang+gcc9: error: no matching function for call to 'forward'

include/seqan3/alignment/matrix/detail/coordinate_matrix.hpp
=> [FIX] clang+gcc9: error: clang frontend command failed with exit code 139 (ICE)

include/seqan3/alphabet/composite/alphabet_tuple_base.hpp, include/seqan3/utility/simd/views/to_simd.hpp
```
/seqan3/include/seqan3/utility/simd/views/to_simd.hpp:97:43: error: variable 'alphabet_size' declared with deduced type 'const auto' cannot appear in its own initializer
static constexpr auto alphabet_size = alphabet_size<std::ranges::range_value_t<inner_range_type>>;
^
```
```
/seqan3/include/seqan3/alphabet/composite/alphabet_tuple_base.hpp:691:46: error: call to non-static member function without an object argument
parent->assign_component_rank<index>(to_rank());
^~~~~~~
```
=> [FIX] clang+gcc9: error: call to non-static member function without an object argument

include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/search/search.hpp
=> [FIX] clang+gcc9: error: reference to local binding 'complete_config' declared in enclosing function 'seqan3::search'

include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp
```
seqan3/include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp:139:16: error: cannot initialize return object of type 'seqan3::detail::trace_iterator_base::pointer' (aka 'seqan3::detail::trace_directions *') with an rvalue of type 'const seqan3::detail::trace_directions *'
return &current_direction;
^~~~~~~~~~~~~~~~~~
```
=> [FIX] clang+gcc9: error: cannot initialize return object of type

include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
```
/seqan3/include/seqan3/search/dream_index/interleaved_bloom_filter.hpp:433:69: error: typename specifier refers to non-type member 'membership_agent' in 'seqan3::interleaved_bloom_filter<seqan3::compressed>'
return typename interleaved_bloom_filter<data_layout_mode>::membership_agent{*this};
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```
```
/seqan3/include/seqan3/search/dream_index/interleaved_bloom_filter.hpp:910:21: error: typename specifier refers to non-type member 'membership_agent' in 'seqan3::interleaved_bloom_filter<seqan3::compressed>'
typename ibf_t::membership_agent membership_agent;
~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```
=> [FIX] clang+gcc9: error: typename specifier refers to non-type member

include/seqan3/std/bit
```
/seqan3/include/seqan3/std/bit:160:33: error: call to 'countl_zero' is ambiguous
return detail::bits_of<T> - countl_zero(x);
^~~~~~~~~~~
```
=> [FIX] clang+gcc9: seqan3/std/bit: use _GLIBCXX_RELEASE for stdlib

include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp, include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp, include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp, include/seqan3/core/platform.hpp, include/seqan3/core/range/detail/random_access_iterator.hpp, include/seqan3/utility/views/pairwise_combine.hpp
Comparing template template?
```
In file included from /seqan3/test/unit/range/detail/random_access_iterator_test.cpp:13:
/seqan3/include/seqan3/range/detail/random_access_iterator.hpp:56:33: error: use of template template parameter 'derived_t_template2' requires template arguments
std::is_same_v<derived_t_template2, derived_t_template>
^
/seqan3/include/seqan3/range/detail/random_access_iterator.hpp:52:70: note: template is declared here
template <typename range_type2, template <typename ...> typename derived_t_template2>
~~~~~~~~~~~~~~~~~~~~~~~          ^
```
clang: Constraining friends is now allowed?
```
In file included from /seqan3/test/unit/range/detail/random_access_iterator_test.cpp:13: …
```
=> clang: error: requires clause differs in template redeclaration

test/unit/range/iterator_test_template.hpp
Paert of https://github.com/seqan/product_backlog/issues/127
```
seqan3/test/unit/range/detail/../iterator_test_template.hpp:335:10: error: 'auto' deduced as 'seqan3::detail::random_access_iterator<std::vector<int>>' in declaration of 'it' and deduced as 'std::__wrap_iter<int *>' in declaration of 'rng_it'
for (auto it = last_it, rng_it = rng_last_it;
^         ~~~~~~~           ~~~~~~~~~~~
```
=> [FIX] clang: error: 'auto' deduced as 'seqan3::detail::random_access_iterator...'

test/unit/range/iterator_test_template.hpp
Iterator have `size + 1` possible positions.
For example:
* an empty range `[]` has 1 iterator position = begin = end. 
* a range of size 3 `[0,1,2]` has 0 = begin, 1, 2, 3 = end; 4 iterator positions
This particular test only operates on the iterator and not the value, so we can reach all possible iterator positions.
=> [TEST] difference_test should include sentinel position

include/seqan3/alignment/pairwise/alignment_algorithm.hpp
```
/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:84:76: error: member access into incomplete type 'seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::method_global, seqan3::align_cfg::scoring_scheme<seqan3::nucleotide_scoring_scheme<>>, seqan3::align_cfg::gap_cost_affine, seqan3::align_cfg::output_score, seqan3::align_cfg::output_begin_position, seqan3::align_cfg::output_end_position, seqan3::align_cfg::output_alignment, seqan3::align_cfg::output_sequence1_id, seqan3::align_cfg::output_sequence2_id, seqan3::align_cfg::detail::result_type<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, unsigned int, int, seqan3::detail::advanceable_alignment_coordinate<seqan3::detail::advanceable_alignment_coordinate_state::no …
```
=> [FIX] clang+gcc9: error: member access into incomplete type

include/seqan3/alignment/decorator/gap_decorator.hpp
```
/seqan3/include/seqan3/alignment/decorator/gap_decorator.hpp:206:46: error: variable has incomplete type 'const seqan3::gap_decorator::const_iterator' (aka 'const seqan3::gap_decorator::gap_decorator_iterator')
iterator insert_gap(const_iterator const it, size_type const count = 1)
^
```
The problem here is that insert_gap is non-dependant (in two-phase lookup) and must be a complete type at that point which it isn't (it is just forward declared and the real definition happens later outside the class).
To fix this we have multiple options:
* define insert_gap, etc functions outside, too (but after const_iterator) (same API!)
* make function dependant by using a defaulted template argument
(semantically the same API, but syntactical more convoluted and harder to understand)
```cpp …
```
=> [FIX] clang+gcc9: error: variable has incomplete type

test/cmake/seqan3_test_files.cmake, test/snippet/CMakeLists.txt
This change allows using `add_subdirectory` in an umbrella `CMakeLists.txt` to combine multiple tests into one.
(See: https://stackoverflow.com/questions/15662497/difference-between-cmake-current-source-dir-and-cmake-current-list-dir)
=> cmake: Use CMAKE_CURRENT_{BINARY,SOURCE}_DIR

build_system/seqan3-config.cmake, test/cmake/seqan3_require_test.cmake, test/seqan3-test.cmake
The main problem with 
```cmake
find_package(SeqAn3)
find_package(SeqAn3)
```
and
```cmake
include (seqan3_require_test.cmake)
include (seqan3_require_test.cmake)
```
is that cmake targets would be re-defined.
This can be fixed by adding an explicit check if the target already exists.
=> Allow including certain cmake files more than once

test/cmake/diagnostics/list_unused_snippets.cmake, test/snippet/CMakeLists.txt
This is an orthogonal feature to https://github.com/seqan/product_backlog/issues/386.
This will list all unused snippets. 
The idea is if you for example move a snippet `my/snippet.cpp`, but forget to move the corresponding output `my/snippet.err`, this will produce a warning.
=> [INFRA] list all unused snippet outputs

test/unit/io/sam_file/sam_file_record_test.cpp
Several fixes to the sam record test.
* Use `""_cigar` literal
* `reference_id` is normally a `std::optional<int>`
* Add some comments to easier identify what the members are.
=> [TEST] sam record

test/coverage/CMakeLists.txt
On some instance I had failing coverage tests, but I didn't get any output what went wrong. This Change will show what went wrong.
=> [TEST] show failure diagnostics in coverage tests

CHANGELOG.md, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/format_parse_test.cpp
Resolves https://github.com/seqan/seqan3/issues/2835
=> [FIX] wrong type name in argument_parser error

test/snippet/CMakeLists.txt
The version checker will output something onto `std::cerr` that makes it "hard" to have deterministic output. This is part of https://github.com/seqan/product_backlog/issues/386.
=> [TEST] snippet: don't call the version checker on snippet

test/cmake/seqan3_require_benchmark.cmake, test/cmake/seqan3_require_test.cmake, test/seqan3-test.cmake
This PR moves out cmake stuff that belongs to the gtest/gbenchmark fall-back solution.
It also enables that directly using 
```cmake
add_library(my_target PUBLIC gtest)
```
adds the include folder of gtest in case of the fallback solution.
=> [INFRA] fix gtest_main target for older cmake version (should propagate include)

test/snippet/CMakeLists.txt, test/snippet/snippet_main.cpp
This has the effect that if a snippet does not define a `int main() {}` function, it will use the fallback main-function from `snippet_main`.
The problem right now is, that `gtest_main` will be used and thus adds output that is unrelated to the snippet.
E.g. `./utility/type_traits/function_traits_snippet` has no `main`-function and thus will output `gtest_main`
https://github.com/seqan/seqan3/blob/e438f79b761de8e834bb90e5941d21f1b4455a6a/test/snippet/utility/type_traits/function_traits.cpp#L1-L17
```
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```
after the change it will not output anything as it uses `snippet_main`:
```
```
=> [TEST] snippet: don't link in the gtest main

include/seqan3/alphabet/composite/alphabet_variant.hpp, include/seqan3/alphabet/composite/detail.hpp
to only accept alphabets with the same underlying char type.
This cannot be tested, since incorrect code would not compile.
since all our alphabets have `char` as underlying type, this did not break anything.
Fixes #2867
=> [FIX] Restrict seqan3::alphabet_variant.

include/seqan3/utility/concept/exposition_only/core_language.hpp, include/seqan3/utility/container/all.hpp, include/seqan3/utility/range/all.hpp, include/seqan3/utility/range/concept.hpp, include/seqan3/utility/tuple/all.hpp, include/seqan3/utility/tuple/pod_tuple.hpp, include/seqan3/utility/type_list/all.hpp, include/seqan3/utility/type_pack/all.hpp, include/seqan3/utility/type_traits/basic.hpp, include/seqan3/utility/views/all.hpp, include/seqan3/utility/views/interleave.hpp
This is my first sweep for https://github.com/seqan/product_backlog/issues/393
I didn't put any `\remark` yet, because most entities are stand-alone and don't really have anything "globally" explained at the submodule page.
Maybe the tuple documentation could have this, but I'm not sure. A draft for this is here: https://github.com/marehr/seqan3/pull/new/doc_utility2
=> [doc] update utility

include/seqan3/core/range/detail/inherited_iterator_base.hpp
This patch addresses the performance regression between 3.0.2 and 3.0.3.
gcc-10 and gcc-11 have different opinions on how this code can be
optimized. Having references instead of copies lead to the lowest run
time overhead.
Closes https://github.com/seqan/seqan3/issues/2675
=> [FIX] Change iteration base return type

test/documentation/seqan3-doxygen.cmake
Updates the remote "html-book.tar.xz" to the newest version.
(It seems like these download haven't been updated for over a year. so the update is still from the year 2020).
=> [DOC] Update the remote "html-book.tar.xz" to the newest version.

doc/fragments/sequence_file_input.md, doc/fragments/sequence_file_output.md, doc/tutorial/introduction/index.md, doc/tutorial/introduction/introduction_file_input.cpp, include/seqan3/io/all.hpp, include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/io/sequence_file/format_fastq.hpp, include/seqan3/io/sequence_file/input_format_concept.hpp, include/seqan3/io/sequence_file/output_format_concept.hpp, include/seqan3/io/structure_file/format_vienna.hpp, test/performance/io/format_fastq_benchmark.cpp, test/snippet/io/sequence_file/sequence_file_input_decomposed.cpp, test/snippet/io/sequence_file/sequence_file_input_record_iter.cpp, test/snippet/io/sequence_file/sequence_file_input_template_deduction.cpp, test/snippet/io/sequence_file/sequence_file_output_template_deduction.cpp, test/snippet/release/3.0.0_read-fasta-and-print-entities.cpp
We mixed spellings like fasta, Fasta, FastA and FASTA (same for FASTQ). I have unified this to complete capital letters, as it is done on wikipedia and other websites.
=> [DOC] unified spelling of FASTA and FASTQ

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/auxiliary.hpp
I'm pretty sure that the `seqan3::is_constexpr_default_constructible_v` requirement is a copy and paste error when the CPO was copied over from alphabets (where we first used CPOs). I'll double check with @h-2.
It reduces the dependency of the argument parser to other seqan3 utilities and is one step further for https://github.com/seqan/seqan3/issues/1272
=> [MISC] Reduces some dependencies of the argument parser to seqan3.

.github/workflows/api.yml, .github/workflows/cancel.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/latest_libraries.yml, .github/workflows/ram_usage.yml, .travis.yml, test/cmake/seqan3_require_benchmark.cmake, test/cmake/seqan3_require_test.cmake, test/seqan3-test.cmake
Update of googlebenchmark to `1.6.0` fixes some missing includes for gcc11
=> [INFRA] CI update

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/concept.hpp, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/detail/CMakeLists.txt, test/unit/argument_parser/detail/concept_is_container_option_test.cpp
This could also be considered a fix, because the `sequence_container` concept is something we shouldn't use anymore. The concept basically requires everything that a resizable vector has, but in most cases you do not need ALL of resizable vector interface but just e.g. `push_back()`.
The concept now is much more light weight and adapted to the needs of the argument parser.
It also reduces the dependency of the argument parser to other seqan3 utilities and is one step further for https://github.com/seqan/seqan3/issues/1272
=> [MISC] Remove dependency on seqan3::sequence_container.

include/seqan3/utility/simd/detail/simd_algorithm_sse4.hpp
See declaration:
https://github.com/seqan/seqan3/blob/66b59a268f5f1645aec1c8bd76b910e06a5a1b18/include/seqan3/utility/simd/detail/simd_algorithm_sse4.hpp#L38
=> [FIX] signature of store_sse4

test/cmake/diagnostics/list_unused_snippets.cmake
This does not affect seqan3 right now because we don't have snippets in `/test/snippet` directly. Reusing the `list_unused_snippets.cmake` in other repos (e.g. argument parser), will fail if snippets are on the `current cmake source dir`.
This PR fixes it in seqan3 so we never run into the problem in case we do have a snippet in `/test/snippet` at some point.
e.g.
if there is a snippet here
```
test/snippet/top_level.cpp
```
then in the script, 
* -> the variable `${source_relative_dir}` would be empty.
* -> the command 
```
list (APPEND test_snippet_output_list "${source_relative_dir}/${source_wle}.err")
```
would then faultily add `/top_level.cpp` to `test_snippet_output_list`
* -> in line (old)44/(new)49
```
list (REMOVE_ITEM test_snippet_output_glob_list ${test_snippet_output_list}) …
```
=> [INFRA] List unused snippets in cmake source dir correctly.

include/seqan3/utility/type_list/traits.hpp, test/unit/utility/type_list/type_list_traits_test.cpp
There might be smarter ways to do this, but this does this job.
=> [feature] add list_traits::repeat

test/snippet/io/sam_file/sam_file_input_construction_without_automatic_type_deduction.cpp
The field `seqan3::field::cigar` was missing from the list of default_fields in the SAM snippet.
=> Missing seqan3::field::cigar.

.github/workflows/README.md, .github/workflows/avx2.yml
This adds a cron job to compiler our tests with AVX2 enabled.
This allows us to notice things like https://github.com/seqan/seqan3/pull/2893
=> [INFRA] Add AVX2 cron

include/seqan3/alphabet/aminoacid/aminoacid_base.hpp, include/seqan3/alphabet/detail/convert.hpp, include/seqan3/alphabet/nucleotide/nucleotide_base.hpp, include/seqan3/io/sam_file/format_bam.hpp
This fixes the in/out parameter order. First all input parameters, than all output parameters.
=> [FIX] the in/out parameter order of convert_through_char_representation

include/seqan3/alignment/pairwise/edit_distance_algorithm.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_policy.hpp, include/seqan3/alignment/pairwise/policy/simd_affine_gap_policy.hpp, include/seqan3/alphabet/container/bitpacked_sequence.hpp, include/seqan3/alphabet/container/concatenated_sequences.hpp, include/seqan3/argument_parser/validators.hpp
See https://cdash.seqan.de/testDetails.php?test=60807415&build=212179
Doxygen-trunk warns when `\returns` is used for a function returning `void`.
=> [FIX,DOC] documented empty return type

include/seqan3/io/sam_file/input_format_concept.hpp, include/seqan3/io/sam_file/output_format_concept.hpp, test/cmake/seqan3_require_benchmark.cmake
Resolves #2913 
The first commit is needed to allow `-DCMAKE_CXX_FLAGS=-std=c++17 -fconcepts` with gcc11.
Previously, we set the `CMAKE_CXX_STANDARD`, which works for some cases but not all.
Clearing `CMAKE_CXX_FLAGS` is more general and equivalent to what happens when using the `ExternalProject` approach/fallback.
The second commit adds two missing includes for gcc11 in cpp17 mode.
After this PR is merged, I can add nightlies for gcc11 cpp17 header tests.
=> [INFRA] Add missing includes for gcc11 -std=c++17

CHANGELOG.md, doc/tutorial/sequence_file/sequence_file_output_record.out, include/seqan3/alphabet/gap/gapped.hpp, include/seqan3/io/sam_file/output.hpp, include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/io/sequence_file/output_options.hpp, test/snippet/io/sequence_file/sequence_file_input_aminoacid.cpp, test/snippet/io/sequence_file/sequence_file_input_auto_ref.cpp, test/snippet/io/sequence_file/sequence_file_input_custom_fields.cpp, test/snippet/io/sequence_file/sequence_file_input_decomposed.cpp, test/snippet/io/sequence_file/sequence_file_input_file_view.cpp, test/snippet/io/sequence_file/sequence_file_input_istringstream.cpp, test/snippet/io/sequence_file/sequence_file_input_record_iter.cpp, test/snippet/io/sequence_file/sequence_file_input_record_move.cpp, test/snippet/io/sequence_file/sequence_file_input_return_record.cpp, test/snippet/io/sequence_file/sequence_file_input_template_specification.cpp, test/snippet/io/sequence_file/sequence_file_input_trait_overwrite.cpp, test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_integration_test.cpp, test/unit/io/sequence_file/sequence_file_output_test.cpp
Most programs output fasta files in this format:
```
>Test1
AACCGGTT
```
By default `seqan3` puts a whitespace in between '>' and 'Test1'. This default is being changed with this PR to meet the standard of most other programs out there.
seqan3 default:
```
> Test1
AACCGGTT
```
=> [MISC] Adjust default options when outputing FastA-Files

include/seqan3/core/all.hpp, include/seqan3/core/detail/iterator_traits.hpp, include/seqan3/core/platform.hpp, include/seqan3/std/bit, include/seqan3/std/concepts, include/seqan3/std/iterator
```
include/seqan3/core/detail/iterator_traits.hpp:50:50: error: extended character ­ is not valid in an identifier
50 |     using iterator_category = MAYBE_PRESENT(std::iterator_­traits<underlying_iterator_t>::​iterator_­category);
|                                                  ^
```
=> [FIX] Remove invisible characters 👻 

test/seqan3-test.cmake
```
include/seqan3/contrib/parallel/buffer_queue.hpp:354:18: error: use of ‘std::hardware_destructive_interference_size’ [-Werror=interference-size]
354 |     alignas(std::hardware_destructive_interference_size) std::shared_mutex mutable mutex{};
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/seqan3/contrib/parallel/buffer_queue.hpp:354:18: note: its value can vary between compiler versions or with different ‘-mtune’ or ‘-mcpu’ flags
include/seqan3/contrib/parallel/buffer_queue.hpp:354:18: note: if this use is part of a public ABI, change it to instead use a constant variable you define
include/seqan3/contrib/parallel/buffer_queue.hpp:354:18: note: the default value for the current CPU tuning is 128 bytes
include/seqan3/contrib/parallel/buffer_queue.hpp:354:18: note: …
```
=> [INFRA] gcc12: Disable warning about ABI

test/include/seqan3/test/tmp_directory.hpp
`build/header_Debug_g++-git_cpp20/seqan3_test_header_test_files/seqan3/test/tmp_directory.hpp-no-self-include.cpp:93:32: error: ‘exchange’ is not a member of ‘std’`
=> [FIX] missing include

CHANGELOG.md, doc/cookbook/compression_threads.cpp, include/seqan3/contrib/stream/bgzf_stream_util.hpp
bgzf_thread_count was declared `inline static` outside of the scope of a
class.
In this case the `inline` allows the variable to break the one
definition rule. Meaning there can be multiple symbols across different
translation that all declare `bgzf_thread_count`. In this case the
linker will choose one of the defined symbols. (Without inline it would
throw a multiple definition error).
The `static` keyword (in this context) means that the created symbol is
only visible inside a current translation unit. Meaning, there are no symbols
for the linker to work with. This will cause every translation unit to have there
own `bgzf_thread_count` variable.
This combination leads to every translation unit having there own
`bgzf_thread_count` variable. The fix is simple, we remove the `static` …
=> [FIX] make a bgzf_thread_count a single variable

include/seqan3/utility/simd/algorithm.hpp, include/seqan3/utility/simd/detail/simd_algorithm_avx512.hpp
This PR adds the missing implementations for the family of extract functions specific to the AVX512 instruction set, as they are much faster then the default implementation. 
A bit on the background: 
These functions allow to extract only a part (half, i.e. 2x256 bit, quarter, i.e. 4x128 bit, or eighth, i.e. 8x64 bit) of the given simd vector and are used in combination with the upcast function in order to sign/zero extend a simd vector to a set of simd vectors with larger operand types, e.g. one vint_8x64_t vector to 2 vint_16x32_t vectors, with 8 (16) being the bit-size of the operands and 64 (32) being the number of operands that fit into a single __m512i vector type.
The extracted bytes will be placed in the lower bits of the target simd vector. There is no dedicated intrinsic to …
=> [FEATURE] Adds missing extract implementations for AVX512.

include/seqan3/search/views/kmer_hash.hpp
The difference operator on iterators only needs the requirement `std::sized_sentinel_for<it_t, it_t>`, i.e. the underlying iterator has a difference operator, instead of the full `std::random_access_iterator`.
The [random_access_iterator](https://en.cppreference.com/w/cpp/iterator/random_access_iterator) requires that as a subclause
```c++
std::totally_ordered<I> &&
std::sized_sentinel_for<I, I> && // here
requires(I i, const I j, const std::iter_difference_t<I> n) {
```
An example from the standard would be here: https://eel.is/c++draft/range.adaptors#range.transform.iterator-22 where it also only requires `std::sized_sentinel_for`.
=> [MISC] relax kmer_hash_view::iterator difference requirement

include/seqan3/search/views/minimiser.hpp, test/unit/search/views/minimiser_test.cpp
This PR adds a `base()` function to `minimiser_view::basic_iterator` which returns the underlying iterator of that view. This is in line with the standard which offers the same `base` function for view iterators, e.g. https://eel.is/c++draft/range.filter#iterator-5.
The use case is that @eaasna needs to know the position of the "minimiser" window and the only viable way was to completely copy the complete class and add a position member (see https://github.com/eaasna/sliding-window/blob/master/include/indexed_minimiser.hpp) as one can't infer from the public API where a certain minimiser value comes from.
This introduces a lot of unnecessary duplicated code. The change allows the following much shorter implementation which only relies on public API:
```c++
std::vector<size_t> …
```
=> [MISC] add minimiser_view::basic_iterator::base

include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
This PR simplifies how the bins of a binning_bitvector are enumerated.
It removes the special case if the bit_sequence is `1 << 63` (most significant bit set) by realizing that the before mentioned UB (undefined behaviour) only happens when shifting by `1 << 64`, any smaller shift value is fine.
This isn't the case here, as `std::countr_zero` will only return `64` for `0`, but this case is checked by the for loop. So we know that the number of zeros is at most `<= 63`. The second insight is to do a second `tmp >>= 1` instead of incrementing `step++` before the actual shift, this will ensure that the shifted by value will be at most `<= 63` and thus eliminating the previous edge case.
```c++
bin += step++;
tmp >>= step;
// is the same as
bin += step;
step++;
tmp >>= step;
// is the same as …
```
=> [MISC] simplify enumerating all bins in a binning_bitvector

include/seqan3/std/ranges
Part of gcc12 support https://github.com/seqan/product_backlog/issues/402
**Problem:** `view_interface` is not derived from `view_base` any more.
See change in stl:
* https://github.com/gcc-mirror/gcc/commit/53b1c382d5a6fe8dec394a7ff820d77cda02af81
* https://cplusplus.github.io/LWG/issue3549
This affects our `enable_view` comptatibility here:
https://github.com/seqan/seqan3/blob/75de3b1df8cf38df521f939e499d84ecf3100d8c/include/seqan3/std/ranges#L49-L51
Workaround:
Set `enable_view` to true if view is derived from `view_interface`.
```cpp
//!\brief std::ranges::views are valid range-v3 views
template<typename T>
requires ::std::derived_from<T, ::std::ranges::view_base> ||
::std::derived_from<T, ::std::ranges::view_interface<T>>
inline constexpr bool enable_view<T> = true;
```
=> [MISC] gcc-12 support: Fix enable_view for ranges-v3 compatibility.

test/unit/utility/views/single_pass_input_test.cpp
single_pass_input_test is derived from `view_interface`, see here 
https://github.com/seqan/seqan3/blob/aee8e49701f9ec31376a609932befda84e6e00ac/include/seqan3/utility/views/single_pass_input.hpp#L41
=> [FIX] single_pass_input_test is derived from view_interface not from view_base.

.cmake-format.yaml, .github/workflows/api.yml, .github/workflows/avx2.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/cmake_format.yml, .github/workflows/documentation.yaml, .github/workflows/latest_libraries.yml, .github/workflows/ram_usage.yml
Adds/Adapts the job requirement to:
```yaml
if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
```
Also adds the `workflow_dispatch` (manual trigger) to all actions that did not have one.
This means that actions run *automatically* only on `seqan/seqan3`. Previously, all workflows (including Crons) were also run on Forks - which is kind of wasteful.
However, the workflows are still able to be triggered manually.
Adds an action to run `cmake-format` and create a PR. The branch is created on the fork of [a machine account](https://github.com/seqan-actions), such that we do not have to create a PR branch on `seqan/seqan3`. It's also a bit more secure because it uses fewer privileges than doing it on the main repo.
The `cmake_format` workflow does have a manual …
=> [INFRA] cmake-format action

include/seqan3/alphabet/container/concatenated_sequences.hpp, test/unit/alphabet/container/container_of_container_test.cpp
This PR simplifies and improves a couple of things:
* change the value_type to be the same as the reference type.
* change the reference type to be whatever slice returns (not some inherited proxy), so you get a `span<>` if the inner_type is a vector which is something you really want.
* remove lots of cruft that is no longer necessary
* add functions for efficiently growing the container by appending stuff to the end – IMHO this is crucial functionality of this data structure!
=> Update concatenated seqs

CHANGELOG.md, include/seqan3/io/sequence_file/format_fasta.hpp, test/performance/io/CMakeLists.txt, test/performance/io/format_fasta_no_performance_benchmark.cpp, test/unit/io/sequence_file/CMakeLists.txt, test/unit/io/sequence_file/sequence_file_integration_no_performance_test.cpp, test/unit/io/sequence_file/sequence_file_integration_test.cpp
Fasta has the following structure:
```
> MyID
MySeq
```
This should be parsed into 'MyID' and 'MySeq' (This works fine).
If the sequence id has '>' as a character, this might fail:
```
> >MyID
MySeq
```
This will be parsed into 'MyId' and 'MySeq', which does not meet the
specification. It should be parsed to '>MyID' and 'MySeq'.
This PR fixes this.
=> [FIX]  correct parsing of IDs in fasta files

.github/workflows/ci_linux.yml
I'll keep an eye on https://github.com/gcovr/gcovr/issues/588
=> [FIX] Coverage CI

include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
Hello seqan3-team,
I need an (efficient) way to remove `minimiser` (= `binning_bitvector` = `ibf.bulk_contains(minimiser)`) from a `counting_vector` again.
Furthermore, I added for symmetry the overload `counting_vector -= counting_vector`, too, but strictly speaking, I don't need it.
This PR adds the necessary overloads.
=> [FEATURE] Allow subtracting from counting vector

test/performance/alphabet/alphabet_to_char_benchmark.cpp, test/performance/alphabet/alphabet_to_rank_benchmark.cpp, test/performance/io/format_vienna_benchmark.cpp, test/performance/search/index_construction_benchmark.cpp
* Avoid `views::persist`
* `std::array<alphabet_t, 256> alphabet_array{};` results in an unused variable warning. We initialize the array, but overwrite the values without using them.
=> [FIX] gcc12: performance tests

include/seqan3/std/charconv, include/seqan3/std/new, include/seqan3/std/ranges
From https://github.com/seqan/seqan3/pull/2954/commits/37a5e79ba7719a46859fedd057bc9d3c26c3c19a
When combining seqan3 and sharg, we have this situation:
```cpp
// seqan3/std/some_struct.hpp
#pragma once
struct some_struct{};
```
and 
```cpp
// sharg-parser/std/some_struct.hpp
#pragma once
struct some_struct{};
```
This will result in multiple definitions of `some_struct` (not allowed).
`#pragma once` only checks that exactly `seqan3/std/some_struct.hpp` is included once.
Hence, we need a header guard that is the same in sharg and seqan3.
=> [INFRA] Replace pragma once with header guards in std module

include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/io/sequence_file/input_options.hpp, test/unit/io/sequence_file/sequence_file_integration_test.cpp
A simple roundtrip through seqan3 (reading and writing a fasta file) should not introduce any changes with the default options
```
auto fout = seqan3::sequence_file_input{std::istringstream{input}, seqan3::format_fasta{}} |
seqan3::sequence_file_output{std::ostringstream{}, seqan3::format_fasta{}};
```
The PR https://github.com/seqan/seqan3/pull/2769 fixes the forced introduction of spaces before the sequence ids.
This PR fixes the removal of whitespaces when reading a fasta file.
This changes the default behavior. To achieve the old behavior a new flag is introduced:
```fin.options.fasta_ignore_blank_before_id``` which is by default `true`.
Example:
File
```
> seq1
ACTG
```
seqan3 now: `id="seq1"`
some others: `id=" seq1"`
=> [FEAT] Option to ignore blanks before ids when reading FastA-Files

test/unit/alignment/pairwise/alignment_configurator_test.cpp, test/unit/std/ranges_test.cpp
This PR does two things:
1. Remove `ranges/v3/take.hpp` by removing an obsolete unit test.
2. Remove an obsolete include of `ranges/v3/single.hpp` which wasn't used.
This is part of https://github.com/seqan/product_backlog/issues/124
-A life Without Range-v3-
=> Remove range-v3 `take` and `single`

test/documentation/CMakeLists.txt, test/documentation/DoxygenLayout.xml, test/documentation/seqan3-doxygen-layout.cmake, test/documentation/seqan3_doxygen_cfg.in
When working on #2954 and replacing the documentation, I think it's important that we can include stuff like howtos and tutorials automatically. Otherwise we will have trouble to keep everything up to date.
For this purpose I tried to work out a cmake script that adds a reference for the Tutorial/How-To pages automatically to the `DoxygenLayout.xml` (while generating a new one in the build folder).
Take a look at the vercel preview to see the difference. All tutorials/how_tos/about pages should be present but might have a different name now. If you think the titles are too verbose, we can change the titles. (IMHO verbose titles are good)
=> [INFRA] Automatically add doc pages to layout.

test/unit/alphabet/views/translate_join_test.cpp
Code example for #1520
This small test case leads to a very complex build failure on GCC7 and to an ICE on GCC9.
It is triggered e.g. when wanting to create a bidirectional index using `views::translate_join` which is arguably a very useful use-case.
I have spent several hours trying to get to the bottom of this, but was not successfull. I recommend opening an issue with GCC.
Here are my notes:
*  It is neither specific to `views::deep` (you can trigger it by doing a std::views::transform on the outer range and manually calling `std::views::reverse` inside)
* nor is it specific to `std::views::reverse`. I implemented an entire custom `seqan3::views::reverse` to verify this, it also triggers the problem and also a few other views that I tested (but not all of them).
* Surprisingly it is …
=> [TEST] Add regression test for `views::translate_join`

.github/workflows/api.yml, .github/workflows/avx2.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_misc.yml, .github/workflows/cmake_format.yml, .github/workflows/documentation.yaml, .github/workflows/latest_libraries.yml, .github/workflows/ram_usage.yml, .github/workflows/scripts/install_cmake.sh, .github/workflows/scripts/install_doxygen.sh, CHANGELOG.md, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/core/platform.hpp, include/seqan3/utility/container/small_vector.hpp, test/documentation/.vercel/install.sh, test/unit/alphabet/container/container_concept_test.cpp, test/unit/search/helper_search_scheme.hpp, test/unit/search/search_scheme_test.cpp
Not yet available for homebrew (macOS)
[It was just packaged for Ubuntu 22.04](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa)
=> [INFRA] Add gcc12 Linux CI

test/documentation/seqan3-doxygen.cmake
I also replaced `DOXYGEN_DOT_FOUND` with `DOXYGEN_HAVE_DOT` because `DOXYGEN_DOT_FOUND` is deprecated since CMake 3.9: https://cmake.org/cmake/help/latest/module/FindDoxygen.html#variable:DOXYGEN_DOT_FOUND
=> [INFRA,DOC] Use mathjax to render formulas when latex is missing

.github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/clang_format.yml
See https://github.com/eseiler/seqan3/pull/35
Workflow:
```
* PR created
* Lint starts
* Lint adds clang-format label
* Lint might push new commit with changes
* Lint removes label
* Linux, macOS, misc CI start
```
Additionally, pushing a new commit will re-trigger the Lint.
The Lint will cancel running Linux/macOs/misc CI.
Lint action needs to run as `pull_request_target` to be allowed to push to PR branches
=> [INFRA] auto clang-format

include/seqan3/core/detail/all_view.hpp, include/seqan3/utility/tuple/common_pair.hpp, include/seqan3/utility/tuple/common_tuple.hpp, include/seqan3/utility/views/detail/helper.hpp, include/seqan3/utility/views/zip.hpp, test/documentation/seqan3_doxygen_cfg.in, test/unit/utility/views/zip_test.cpp
Follow-up:
* Benchmark [here](https://github.com/seqan/seqan3/pull/1264/files#diff-fb6fd04039e36143b92a22798127df445e280333415c750de1ff59efd0d7569f)
* More tests
* Conditional `explicit` and `noexcept` specifiers for `common_pair` and `common_tuple`
=> [FEATURE] views::zip

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
Resolves https://github.com/seqan/seqan3/issues/2905
=> [FIX] Ignore bogus memcpy warning on gcc12

.github/workflows/clang_format.yml
=> [INFRA] Always use upstream .clang-format

.github/workflows/ci_misc.yml
gcc12 is stricter than gcc11 regarding includes, so it should be fine to just replace it. the gcc10 header test should take care of the other stuff.
=> [INFRA] header test: gcc11 -> gcc12

include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp, include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp, include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp, include/seqan3/alignment/pairwise/alignment_result.hpp, include/seqan3/alignment/pairwise/detail/policy_alignment_result_builder.hpp, include/seqan3/core/platform.hpp, include/seqan3/core/range/detail/random_access_iterator.hpp, include/seqan3/search/detail/policy_search_result_builder.hpp, include/seqan3/search/search_result.hpp, include/seqan3/utility/views/pairwise_combine.hpp, include/seqan3/utility/views/type_reduce.hpp, test/include/seqan3/test/fixture/io/sam_file/simple_three_verbose_reads_fixture.hpp, test/include/seqan3/test/fixture/io/sequence_file/standard_fixture.hpp, test/unit/std/ranges_test.cpp
I checked which workarounds are still necessary and updated them.
I had to do a small change in `views::type_reduce` such that we reduce it the way we actually want (we can only test this now with gcc12).
=> [MISC] cleanup compiler support

include/seqan3/utility/views/chunk.hpp, test/unit/range/iterator_test_template.hpp
https://cdash.seqan.de/test/29778657
<details><summary>Log</summary>
```
[==========] Running 56 tests from 7 test suites.
[----------] Global test environment set-up.
[----------] 20 tests from iterator_fixture/iterator_fixture/0, where TypeParam = seqan3::detail::chunk_view<std::ranges::ref_view<std::vector<int, std::allocator<int> > > >::basic_iterator<false>
[ RUN      ] iterator_fixture/iterator_fixture/0.concept_check
[       OK ] iterator_fixture/iterator_fixture/0.concept_check (0 ms)
[ RUN      ] iterator_fixture/iterator_fixture/0.const_non_const_compatibility
[       OK ] iterator_fixture/iterator_fixture/0.const_non_const_compatibility (0 ms)
[ RUN      ] iterator_fixture/iterator_fixture/0.dereference
[       OK ] iterator_fixture/iterator_fixture/0.dereference (0 ms)
[ RUN …
```
=> [FIX] chunk_view operator+=

include/seqan3/core/semiregular_box.hpp, include/seqan3/utility/concept/exposition_only/core_language.hpp
The `WhitespaceSensitiveMacros` setting doesn't seem to work when the macro uses more than 2 lines.
=> [FIX] clang-format: SEQAN3_DEPRECATED_HEADER

include/seqan3/alignment/matrix/detail/alignment_matrix_column_major_range_base.hpp, include/seqan3/alignment/matrix/detail/alignment_score_matrix_one_column_banded.hpp, include/seqan3/contrib/parallel/buffer_queue.hpp, include/seqan3/contrib/parallel/suspendable_queue.hpp, include/seqan3/contrib/stream/bgzf_ostream.hpp, include/seqan3/contrib/stream/bgzf_stream_util.hpp, include/seqan3/core/algorithm/algorithm_result_generator_range.hpp, include/seqan3/core/detail/persist_view.hpp, include/seqan3/io/sam_file/detail/format_sam_base.hpp, include/seqan3/io/views/async_input_buffer.hpp, include/seqan3/utility/views/interleave.hpp, include/seqan3/utility/views/single_pass_input.hpp, include/seqan3/utility/views/zip.hpp
Part of https://github.com/seqan/seqan3/pull/2998
This adds missing includes that arise when switching from `seqan3/std/ranges` to `ranges`
=> [MISC] Adapt includes for range-v3 removal

README.md
=> [INFRA] Update dependencies

include/seqan3/utility/views/chunk.hpp, test/unit/utility/views/chunk_test.cpp
```
[...]: warning: conversion from ‘long long unsigned int’ to ‘uint16_t’ {aka ‘short unsigned int’} changes value from ‘10485760’ to ‘0’ [-Woverflow]
65 |     for (auto && chunked_records : fin | seqan3::views::chunk((1ULL<<20)*10))
```
[The draft](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2442r0.html#chunk-view-range.chunk) says that `chunk_size` should be of type `std::ranges::range_difference_t<rng_t>` (it was also in range-v3), i.e., usually signed. This is probably for conversion signed<->unsigned.
It also states that `chunk_size` must be positive, though.
=> [FIX] chunk_view using 16 bit integers

.github/workflows/ci_coverage.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/clang_format.yml
Not sure if it does what I indent it to.
Idea is:
* Never cancel coverage builds on pushes to master. This should improve codecov reports because the base is always analysed.
* Determine the fetch depth of the PR. This should improve codecov because the base is always visible.
=> [INFRA] Refactor coverage builds

include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/dssp9.hpp, include/seqan3/alphabet/structure/wuss.hpp
=> [MISC] fix clang-format on structures

include/seqan3/alphabet/mask/masked.hpp
=> [MISC] fix clang-format on masked

include/seqan3/utility/parallel/detail/latch.hpp
It might need to spin or not. It's rather random whether it will be free in the tests. Causes spurious coverage drops when there was no need to wait.
=> [FIX] coverage report on atomic lock

include/seqan3/alphabet/nucleotide/dna15.hpp, include/seqan3/alphabet/nucleotide/dna16sam.hpp, include/seqan3/alphabet/nucleotide/dna3bs.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/nucleotide_base.hpp, include/seqan3/alphabet/nucleotide/rna15.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/alphabet/nucleotide/rna5.hpp
Apparently, constexpr immediately invoked initializing lambda expressions are clang-format's bane of existence.
I moved the `char_to_rank_table` down because clang-format only bounces back when the class is over (`};` of the class).
Alternatively, I could also exclude everything in between...
Other alphabets will follow this one.
```cpp
static constexpr std::array<rank_type, 256> char_to_rank_table
{
```
or
```cpp
static constexpr std::array<rank_type, 256> char_to_rank_table{
```
?
=> [MISC] fix clang-format on nucleotides

.gitmodules, build_system/seqan3-config.cmake
Since the sharg parser is good to go, this PR will included is submodule s.t. we can try it out. 
Once several apps use sharg and the API is tested, we will release sharg and update the seqan3 master branch to the release.
=> [FEATURE] Add sharg-parser submodule.

.github/workflows/api.yml, .github/workflows/avx2.yml, .github/workflows/ci_coverage.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/cmake_format.yml, .github/workflows/documentation.yaml, .github/workflows/latest_libraries.yml, .github/workflows/ram_usage.yml, CHANGELOG.md, test/cmake/include_dependencies/generate_include_dependencies.cmake, test/cmake/seqan3_require_benchmark.cmake, test/cmake/seqan3_require_ccache.cmake, test/cmake/seqan3_require_test.cmake, test/header/CMakeLists.txt
Resolves https://github.com/seqan/product_backlog/issues/422
Resolves #2747
=> [INFRA] Bump CMake for tests

test/unit/io/sam_file/format_sam_test.cpp
The string `verbose_reads_input` is the same as `simple_three_reads_input` (line 34) with some extra information but the hard-clipping information at the end of the cigar string of read2 was missing (`H2`). 
This went by unnoticed because currently the tests read in an alignment and in an alignment hard-clipping is lost. When we read in a cigar instead, this will cause an error in the tests but should not. 
Since we will remove the `field::alignment` this is a pre-commit that reduces complexity of the large PR that will remove the `field::alignment`.
=> [TEST] Add missing hard-clipping to be consistent.

.github/workflows/scripts/install_via_brew.sh
(macOS) Reduces install time of, e.g., `ccache` from 6 minutes to 20 seconds.
=> [INFRA] Disable automatic updates when using brew

test/cmake/seqan3_macro_benchmark.cmake, test/cmake/seqan3_require_benchmark.cmake, test/include/seqan3/test/literal/bytes.hpp, test/macro_benchmark/example/memcpy_macro_benchmark.cpp
=> [INFRA] macro_benchmark flags

.github/workflows/clang_format.yml
`COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}` means that I compare the base of the PR with the head of the PR. This is the number of commits in the PR (the same as `${{ github.event.pull_request.commits }}`).
I actually want to compare the base of the PR (where did it branch from master/the base ref) to the current master/base ref. This will tell me how many commits the branch point lacks behind the current base ref.
=> [FIX] clang-format fetch depth

include/seqan3/alphabet/container/bitpacked_sequence.hpp
which is a copy-paste error from seqan3::concatenated_sequences.
Part of #1027
=> [DOC] Fix doc of seqan3::bitpacked_sequence.

CHANGELOG.md, include/seqan3/alphabet/alphabet_base.hpp, include/seqan3/alphabet/aminoacid/aminoacid_base.hpp, test/performance/range/CMakeLists.txt, test/performance/range/container_assignment_benchmark.cpp, test/unit/alphabet/aminoacid/aminoacid_test_template.hpp, test/unit/alphabet/nucleotide/nucleotide_test_template.hpp, test/unit/alphabet/quality/phred_test_template.hpp
`std::vector` optimizes assignments to `std::copy` (basically memcpy) iff the value_type is trivial. If not, it will use `std::unintialized_copy` which will use placement-new and is around 2-3 times slower.
| Method                         | Container         | Alphabet           | Iterations before | Iterations after |
|--------------------------------|-------------------|--------------------|-------------------|------------------|
| **_tag::assignment_operator_** | **_std::vector_** | **_seqan3::aa27_** | **_705_**         | **_1853_**       |
| **_tag::assignment_operator_** | **_std::vector_** | **_seqan3::dna4_** | **_741_**         | **_1869_**       |
| **_tag::assignment_operator_** | **_std::vector_** | **_seqan3::dna5_** | **_744_**         | **_1879_**       |
| tag::std_copy …
=> [FEATURE] Make alphabets trivial

include/seqan3/alphabet/container/bitpacked_sequence.hpp, test/performance/range/container_push_back_benchmark.cpp, test/performance/range/container_seq_read_benchmark.cpp, test/performance/range/container_seq_write_benchmark.cpp, test/performance/range/views/CMakeLists.txt, test/performance/range/views/view_filter_benchmark.cpp
Supersedes #1448 
I'm not sure about this commit: [89872e6568d8389e9bbb993e5a0b9ec3f518bed7](https://github.com/seqan/seqan3/pull/1448/commits/89872e6568d8389e9bbb993e5a0b9ec3f518bed7)
=> [TEST] Add more benchmarks

CHANGELOG.md, include/seqan3/alignment/cigar_conversion/alignment_from_cigar.hpp
You might have read a CIGAR string from elsewhere, used our IO with a std::string as type for `field::cigar` or want to get the alignment for a secondary alignment which is stores as a string in the tag dictionary.
In all those cases, you want to create an alignment from a CIGAR string not a vector, so I added an overload.
Note that the overload currently is not the most efficient one, because it allocates a `std::vector<seqan3::cigar>` for convenient use of the other overload. This can be improved by directly parsing the CIGAR string.
Alternatively, we could make the function `detail::parse_cigar` (not a good name right now), which creates a CIGAR vector out of a CIGAR string, public.
=> [FEATURE] Add std::string overload for alignment_from_cigar.

CHANGELOG.md, include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/snippet/search/dream_index/interleaved_bloom_filter_constructor_uncompress.cpp, test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
=> [FEATURE] IBF decompression

include/seqan3/io/sam_file/format_bam.hpp
See https://cdash.seqan.de/viewBuildError.php?buildid=10781
=> [FIX] std::ostringstream::view() does not exist in pre-cxx11-abi

doc/tutorial/10_sam_file/index.md, include/seqan3/io/sam_file/detail/format_sam_base.hpp, include/seqan3/io/sam_file/format_bam.hpp, include/seqan3/io/sam_file/format_sam.hpp, include/seqan3/io/sam_file/input.hpp, include/seqan3/io/sam_file/input_format_concept.hpp, include/seqan3/io/sam_file/output.hpp, include/seqan3/io/sam_file/output_format_concept.hpp, include/seqan3/io/sam_file/record.hpp, test/include/seqan3/test/fixture/io/sam_file/simple_three_verbose_reads_fixture.hpp, test/performance/io/format_sam_benchmark.cpp, test/snippet/io/sam_file/sam_file_input_construction_without_automatic_type_deduction.cpp, test/unit/io/sam_file/format_sam_test.cpp, test/unit/io/sam_file/sam_file_format_test_template.hpp, test/unit/io/sam_file/sam_file_input_test.cpp, test/unit/io/sam_file/sam_file_output_test.cpp, test/unit/io/sam_file/sam_file_record_test.cpp, test/unit/io/sam_file/sam_file_seek_test.cpp
=> [MISC] Remove field::offset from sam_file_[in/out]put.

include/seqan3/io/sam_file/input.hpp, include/seqan3/io/sam_file/output.hpp
I forgot to add the static assert to the output file :see_no_evil:
=> [MISC] Add field::alignment deprecation to sam_file_output.

include/seqan3/utility/views/chunk.hpp
```
[ RUN      ] chunk_view_test/5.underlying_input_range_test
../../../../../../../develop/seqan3/test/unit/utility/views/chunk_test.cpp:157: Failure
Expected equality of these values:
*v_it
Which is: [1,4,10,2,7]
*expected_it
Which is: [1,4]
```
The `input_helper_iterator::operator==`, when following the usual definitions in the STL, should be a `friend` function. However, it is not because in GCC<13 friend functions cannot access members of classes their befriended class befriended.
It is an open [question](https://cplusplus.github.io/CWG/issues/1699.html) whether hidden friends are class members when it comes to friendship.
[Godbolt example](https://godbolt.org/z/oe8f7ej9a)
LLVM views hidden friends as memberly enough, GCC did not. …
=> [FIX] Workaround for gcc13

include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/utility/views/chunk.hpp
I had this lying around when cleaning up my branches.
On my PC with GCC 11.3 in was a noisy 5% performance gain on reading FASTA from stream.
I still think it's fine to merge, as it's a small change and makes sense. It avoids an if clause in case the character is an alphabet character, which in a normal FASTA file is most often the case.
=> [FEATURE] Minor increase in FASTA performance.

CHANGELOG.md, include/seqan3/io/detail/misc_input.hpp, include/seqan3/io/sam_file/detail/cigar.hpp, include/seqan3/io/sam_file/detail/format_sam_base.hpp, include/seqan3/io/sam_file/format_bam.hpp, include/seqan3/io/sam_file/format_sam.hpp, include/seqan3/io/stream/detail/fast_istreambuf_iterator.hpp, test/include/seqan3/test/literal/cigar_literal.hpp, test/include/seqan3/test/streambuf.hpp, test/unit/io/sam_file/format_bam_test.cpp, test/unit/io/sam_file/format_sam_test.cpp, test/unit/io/sam_file/sam_file_format_test_template.hpp, test/unit/io/stream/detail/fast_istreambuf_iterator_test.cpp
:crossed_fingers: 
Benchmark a small SAM file (`/group/ag_abi/gene/benchmark-files/io-test.bam` as SAM):
Before: `Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.33`
After:  `Elapsed (wall clock) time (h:mm:ss or m:ss): 0:07.60`
Seqan2: `Elapsed (wall clock) time (h:mm:ss or m:ss): 0:06.19`
Benchmark a small BAM file (`/group/ag_abi/gene/benchmark-files/io-test.bam`):
Before: `Elapsed (wall clock) time (h:mm:ss or m:ss): 0:07.42`
After:  `Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.66`
Seqan2: `Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.47`
Looks like I need to make this pretty s.t. it can be merged.
=> Io bam performance

include/seqan3/io/sam_file/output.hpp, test/unit/io/sam_file/sam_file_output_test.cpp
– The passed value needs to be forwarded since it can be an rvalue reference.
=> [FIX] Forward ref_ids to initialise_header_information() in constructors

include/seqan3/io/sequence_file/format_fasta.hpp, test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
This error was introduced by https://github.com/seqan/seqan3/pull/3104
Fixes #3126
=> [FIX] skip newlines when reading FASTA with char.

include/seqan3/utility/parallel/detail/spin_delay.hpp
Current assembler is wrong for Darwin PPC, it won’t work and even build. In addition to accommodate ppc64 on Darwin, `__ppc64__` should be added (or otherwise `__POWERPC__`).
=> spin_delay.hpp: fix for Darwin PPC

test/performance/alphabet/alphabet_assign_char_benchmark.cpp, test/performance/alphabet/alphabet_assign_rank_benchmark.cpp, test/performance/alphabet/alphabet_to_char_benchmark.cpp, test/performance/alphabet/alphabet_to_rank_benchmark.cpp, test/performance/alphabet/views/view_translate_1D_benchmark.cpp, test/performance/alphabet/views/view_translate_2D_1D_benchmark.cpp, test/performance/alphabet/views/view_translate_2D_benchmark.cpp, test/performance/range/container_assignment_benchmark.cpp, test/performance/range/gap_decorator_rand_read_benchmark.cpp, test/performance/range/gap_decorator_seq_read_benchmark.cpp, test/performance/std/bit_benchmark.cpp, test/performance/utility/bloom_filter/bloom_filter_benchmark.cpp
Resolves #2747 
Change: https://github.com/google/benchmark/commit/53df805dc820d720734d6538032f6b73f31f13ba
Example of fix: https://github.com/google/benchmark/commit/f15f332fd1ae10ae6d13d816af9bcf3b196974cc
=> [FIX] deprecated const& version of benchmark::DoNotOptimize

.travis.yml
Jammy for now is only available for amd64 on the Travis CI platform.
Supersedes #3122, because I can't push.
=> [INFRA] Update .travis.yml

test/unit/alignment/matrix/detail/debug_matrix_test.cpp
Part of https://github.com/seqan/seqan3/issues/3138
Locally,
```
global_affine_banded_collection_simd_test.cpp
global_affine_unbanded_collection_simd_test.cpp
global_affine_unbanded_collection_simd_aa27_test.cpp
```
still fail with ICE:
```
/seqan3/test/unit/alignment/pairwise/global_affine_unbanded_collection_simd_aa27_test.cpp:64:96: error: type variant with ‘TYPE_ALIAS_SET_KNOWN_P’
64 |                                pairwise_collection_simd_global_affine_unbanded_testing_types, );
|                                                                                                ^
<vector_type 0x7f349293cb28
type <integer_type 0x7f349ba255e8 int sizes-gimplified asm_written public type_6 SI
size <integer_cst 0x7f349ba27210 constant 32>
unit-size <integer_cst 0x7f349ba27228 constant 4> …
```
=> [MISC] gcc 13: silence bogus warnings

include/seqan3/io/sam_file/header.hpp, test/unit/io/sam_file/sam_file_output_test.cpp
=> [IO] Make seqan3::sam_file_header::program_info_t easier to copy

include/seqan3/io/sequence_file/input.hpp, test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
`explicitly_convertible_to<typename t::sequence_legal_alphabet, typename t::sequence_alphabet>` is meant for allowing, e.g.:
```cpp
using sequence_alphabet = seqan3::dna4;
using sequence_legal_alphabet = seqan3::dna15; // or even seqan3::rna15
```
but not stuff like
```cpp
using sequence_alphabet = seqan3::dna4;
using sequence_legal_alphabet = seqan3::aa27;
```
However, this constraint is also checked for `using sequence_alphabet = char`. Our alphabets are not (explicitly/implicitly) convertible to char.
The rationale of the alphabets being compatible doesn't apply for `sequence_alphabet = char`, so we should just allow it.
```cpp
using sequence_alphabet = char;
using sequence_legal_alphabet = seqan3::dna4;
```
means: Only allow characters of `seqan3::dna4`, but store them as `char`.
=> [FIX] Relax sequence_file_input_traits

.github/workflows/latest_libraries.yml
Resolves #2747 
gcc12.3 does not fix the bogus warnings
https://github.com/eseiler/seqan3/actions/runs/4966778387
`-Wno-restrict` can't be a private compile option of gtest, because the error is emitted in the stl, not the gtest Header. So, it needs to be global.
=> [INFRA] ignore bogus warnings in latest googletest

.github/workflows/api.yml, .github/workflows/avx2.yml, .github/workflows/ci_coverage.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/latest_libraries.yml, .github/workflows/ram_usage.yml
=> [INFRA] Use seqan2 main branch

test/coverage/CMakeLists.txt
=> [INFRA] gcovr: Use --exclude-noncode-lines

test/external_project/install-sharg.cmake
=> [INFRA] Use Sharg 1.1.1 for integration test

.github/workflows/cron_latest_libraries.yml, test/cmake/seqan3_require_benchmark.cmake, test/cmake/seqan3_require_test.cmake, test/documentation/seqan3-doxygen.cmake
https://salsa.debian.org/med-team/seqan3/-/tree/40f5a781a90f31c0fd7df199405e4f9bb3989a0a/debian/patches
Commit 1 makes `find_package` accept any Google Test and Google Benchmark version.
`find_package(GTest)` ignores the version specifier anyway.
[Relevant patch](https://salsa.debian.org/med-team/seqan3/-/blob/40f5a781a90f31c0fd7df199405e4f9bb3989a0a/debian/patches/better_gtest_benchmark_finding)
Commit 2 adds an option to pass a path to a tag file, which is then copied.
[Relevant patch](https://salsa.debian.org/med-team/seqan3/-/blob/40f5a781a90f31c0fd7df199405e4f9bb3989a0a/debian/patches/debian_cppreference)
CMake solution:
```bash
cmake [...] -DSEQAN3_DOXYGEN_STD_TAGFILE=/usr/share/devhelp/books/cppreference-doxygen-web.tag.xml
```
Other patches:
* [Doxygen config …
=> [INFRA] Make CMake more flexible

include/seqan3/contrib/std/chunk_view.hpp, include/seqan3/contrib/std/join_with_view.hpp, include/seqan3/contrib/std/zip_view.hpp
=> [INFRA] Update contrib

include/seqan3/alignment/matrix/detail/trace_directions.hpp, include/seqan3/alphabet/views/translate.hpp, include/seqan3/core/add_enum_bitwise_operators.hpp, include/seqan3/core/debug_stream/debug_stream_type.hpp, include/seqan3/core/detail/strong_type.hpp, include/seqan3/io/sam_file/sam_flag.hpp
=> [FIX] Duplicate symbols

include/seqan3/io/views/detail/take_until_view.hpp
deprecated since c++17, removed in c++20
=> [FIX] std::result_of_t

.github/workflows/ci_linux.yml, include/seqan3/core/debug_stream.hpp, include/seqan3/core/debug_stream/debug_stream_type.hpp, include/seqan3/io/sam_file/format_bam.hpp, include/seqan3/io/sequence_file/format_embl.hpp, include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/io/sequence_file/format_fastq.hpp, include/seqan3/io/sequence_file/format_genbank.hpp, include/seqan3/io/stream/detail/fast_istreambuf_iterator.hpp, include/seqan3/search/configuration/parallel.hpp, include/seqan3/search/detail/search_configurator.hpp, test/unit/alignment/pairwise/edit_distance/proxy_reference_test.cpp, test/unit/alphabet/views/char_strictly_to_test.cpp, test/unit/alphabet/views/validate_char_for_test.cpp, test/unit/core/debug_stream_test.cpp, test/unit/io/sequence_file/sequence_file_format_genbank_test.cpp, test/unit/test/expect_same_type_test.cpp, test/unit/test/sequence_generator_test.cpp, test/unit/utility/container/aligned_allocator_test.cpp, test/unit/utility/detail/type_name_as_string_test.cpp
=> [FEATURE] libc++ support

test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp
=> [FIX] Disable SeqAn2 OpenMP benchmark on clang

doc/fragments/io_sam_file_input.md
The fragment is included by multiple files.
Removing the link for now.
Alternative would be to use `MARKDOWN_ID_STYLE = GITHUB` and `TOC_INCLUDE_HEADINGS = 3`, but this requires a bit more work:
* Adapting markdown header depths
* Changing links to use github-markdown-references
=> [DOC] multiple use of section label

include/seqan3/core/platform.hpp
=> fix: workaround compiling with debug mode

.github/workflows/ci_linux.yml, .github/workflows/ci_misc.yml, include/seqan3/io/detail/magic_header.hpp, test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp, test/seqan3-test.cmake
Second commit:
The result of
```cpp
to_little_endian(*reinterpret_cast<uint16_t const *>(&header[10]))
```
is erroneous due to some optimization (the Intel compiler uses some more aggressive optimization by default). The cast is probably undefined (or at least unspecified) behavior.
Usually, this is because the value is not properly bound to `in` in
```cpp
template <std::integral type>
constexpr type to_little_endian(type const in) noexcept
```
This also occasionally happens with other compilers.
My solution is to either use the left or right byte, depending on the endianness. Since we cast to `uint16_t`, and only compare one byte, the correct byte should be either of the two. Currently, we do not officially support / test big endian archs.
=> [INFRA] Add IntelLLVM CI

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/release-checklist.md, .github/pull_request_template.md, .github/workflows/README.md, .github/workflows/ci_cmake.yml, .github/workflows/ci_coverage.yml, .github/workflows/ci_documentation.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/deploy_documentation.yaml, .github/workflows/license_check.yaml, .github/workflows/update_cookbook.yml, .travis.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, doc/howto/porting/index.md, doc/howto/write_a_view/index.md, doc/setup/quickstart_cmake/index.md, doc/tutorial/01_introduction/index.md, doc/tutorial/03_concepts/index.md, include/seqan3/alphabet/all.hpp, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/core/platform.hpp, test/scripts/check_include_order.pl, test/scripts/create_all_hpp.sh
What I usually do for my fork:
* Go to the fork, settings, and rename the default branch to `main`
* Locally (upstream is seqan, origin is my fork):
```
git branch -m master main
git fetch upstream
git branch -u upstream/main main
git remote set-head upstream -a
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
git fetch upstream --prune
git fetch origin --prune
```
=> [INFRA] Rename master to main

test/documentation/seqan3_footer.html.in, test/documentation/version.js, test/documentation/version.php
=> [DOC] Improve version selector

include/seqan3/contrib/stream/bgzf.hpp
Fixes #3237
Changes in the definition of bgzf_thread_count in PR #3042 introduced the difference of documentation and actual code.
=> doc,fix: variable bgzf_thread_count is no longer static

include/seqan3/core/platform.hpp, include/seqan3/io/record.hpp, include/seqan3/search/detail/search_scheme_precomputed.hpp, test/documentation/seqan3_doxygen_cfg.in
I don't know why the nightlies only fail now, even though these changes have been in GCC for a few months :)
https://cdash.seqan.de/index.php?project=SeqAn3
Things like [std::apply](https://en.cppreference.com/w/cpp/utility/apply) require [tuple-like](https://en.cppreference.com/w/cpp/utility/tuple/tuple-like).
It also kinda means that CPP23 breaks most of our custom tuple stuff; at least when you want to use it like a `std::tuple`. In the future, `std::get` is supposed to get a CPO.
```cpp
#include <vector>
#include <seqan3/alphabet/nucleotide/dna5.hpp>
#include <seqan3/alphabet/quality/phred42.hpp>
#include <seqan3/io/record.hpp>
#include <seqan3/utility/tuple/pod_tuple.hpp>
#include <seqan3/utility/type_list/type_list.hpp>
// Would work, but not allowed.
// namespace std
// {
// …
```
=> [FIX] CPP23

include/seqan3/search/views/kmer_hash.hpp
Addresses a documentation issue that showed up in issue: #3242
The Attention box describes the number of 1s inside an shape. The condition is the wrong way. They described the
rejection criteria, not the accept criteria: 
https://docs.seqan.de/seqan3/3.4.0/group__search__views.html#ga6e598d6a021868f704d39df73252974f
=> fix,doc: condition of the max number of 1s inside a shape.

include/seqan3/alignment/configuration/detail.hpp, include/seqan3/core/platform.hpp, include/seqan3/search/configuration/detail.hpp, include/seqan3/search/detail/search_scheme_precomputed.hpp
=> [MISC] Remove gcc14 workaround

include/seqan3/search/views/kmer_hash.hpp, test/include/seqan3/test/expect_throw_msg.hpp, test/unit/search/views/kmer_hash_test.cpp
Related to #3242 and #3243 
Example output:
```
terminate called after throwing an instance of 'std::invalid_argument'
what():  The shape is too long for the given alphabet.
Alphabet: seqan3::dna4
Maximum shape count: 32
Given shape count: 33
Aborted
```
=> [MISC] Improve error message when using kmer_hash_view with invalid shapes

include/seqan3/contrib/parallel/buffer_queue.hpp, include/seqan3/core/detail/template_inspection.hpp, include/seqan3/io/sam_file/format_sam.hpp
I'll update the CI later. 
These are some errors I encountered when updating raptor.
=> [FIX] clang-18

include/seqan3/utility/simd/views/to_simd.hpp, test/unit/utility/simd/views/to_simd_test.cpp
Instead of using the value type of the underlying range we use the reference type, such that in case the original range is passed in as const it is correctly propagated to the inner range type. Otherwise, we might end in the situation that we want to assign a const iterator to a non-const iterator which is not allowed.
=> [FIX] Correctly propagate the constness of the inner range type.

include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp, test/unit/alignment/pairwise/global_affine_banded_test.cpp
In case the sequences are sliced by cutting off a prefix of the original seuence due to the band configuration, the relative positions of the sliced sequences was reported inside of the alignment result.
However, this slicing happens only internally and thus the positions reported should correspond to the ones of the original sequences.
We fix this by tracking the offset of the prefix that was cut off and add this to the relative positions during result creation to get the absolute positions.
=> Fixes #3266: Incorrect begin/end of alignment for banded alignment

.codecov.yml
* Missing character in codecov.yaml
* ~~Looks like we need one successful deployment such that the new yml is used, hence re-adding the secret~~
=> [FIX] Codecov

include/seqan3/alignment/matrix/detail/score_matrix_single_column.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
~~This partially reverts https://github.com/seqan/seqan3/commit/33f3eba4ffb7aaabf77f11af767a3ef840bba2ba~~
~~It fixes a new bogus memcpy error with gcc-15 (fedora build).
But this one had a better stacktrace and also happens to fix the one from the linked commit.~~
~~From what I can tell, the compiler is confused by the `optimal_column.clear()` (but not `horizontal_column.clear()`). Seems like, for the diagnostic, it forgets that it was cleared and then weird stuff happens in `resize()` - only affects diagnostics, not the actual compiled code.~~
=> [FIX] gcc-15: Better bogus memcpy fix

include/seqan3/alphabet/adaptation/char.hpp
=> Adds missing char8_t type to list of viable char types for which char adaption works.

.github/ISSUE_TEMPLATE/cron_comment_template.md, .github/workflows/cron_api.yml, .github/workflows/scripts/process_compiler_error_log.py, test/api_stability/3.3.0/0001-FIX-take_until_view_test.patch, test/api_stability/3.3.0/0002-FIX-Change-constexpr-test.patch, test/api_stability/3.3.0/0003-API-hamming-scoring-scheme.patch, test/api_stability/3.3.0/0003-API-hamming-scoring-scheme.patch.license, test/api_stability/3.3.0/0004-FIX-Unsupported-SAM-header.patch, test/api_stability/3.3.0/0004-FIX-Unsupported-SAM-header.patch.license, test/api_stability/CMakeLists.txt, test/api_stability/README.md
This fixes the API Stability tests.
It also reworks the CRON such that it will updated comments instead of posting new ones.
=> [INFRA] API Stability

include/seqan3/alignment/aligned_sequence/debug_stream_alignment.hpp, include/seqan3/alignment/matrix/detail/advanceable_alignment_coordinate.hpp, include/seqan3/alignment/matrix/detail/debug_matrix.hpp, include/seqan3/alignment/matrix/detail/trace_directions.hpp, include/seqan3/alignment/pairwise/alignment_result.hpp, include/seqan3/alphabet/cigar/cigar.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/alphabet/detail/debug_stream_alphabet.hpp, include/seqan3/argument_parser/auxiliary.hpp, include/seqan3/core/debug_stream/byte.hpp, include/seqan3/core/debug_stream/debug_stream_type.hpp, include/seqan3/core/debug_stream/default_printer.hpp, include/seqan3/core/debug_stream/optional.hpp, include/seqan3/core/debug_stream/range.hpp, include/seqan3/core/debug_stream/tuple.hpp, include/seqan3/core/debug_stream/variant.hpp, include/seqan3/core/detail/strong_type.hpp, include/seqan3/io/sam_file/sam_flag.hpp, include/seqan3/io/structure_file/detail.hpp, include/seqan3/search/search_result.hpp, include/seqan3/utility/container/dynamic_bitset.hpp, include/seqan3/utility/simd/detail/debug_stream_simd.hpp, test/unit/alignment/matrix/detail/debug_stream_debug_matrix_test.cpp, test/unit/alignment/matrix/detail/debug_stream_trace_directions_test.cpp, test/unit/io/record_test.cpp, test/unit/test/pretty_printing_test.cpp
This PR builds upon the original proposal of @marehr (#3227).
I changed from the `print` static member function to overloading the function call operator of the printer classes. 
Using this idea, we can now test wether a printer is invocable for a given output stream and the streamable argument.
I also refactored some of the original default_printer code to simplify it.
Among others, the is_printer is not needed anymore as we can use the invocable concept.
For investigating errors I kept the concept `printable_with` which is basically just an alias for the `invocable` concept. 
In addition, I added documentation.
Once this is done, we can look for more debug_stream instances that can be replaced with the printer mechanism.
=> Updated PR for the printer design proposal

include/seqan3/utility/simd/detail/simd_algorithm_avx512.hpp
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77633 for discussion.
=> Use explicit _MM_PERM_ENUM type for intrinsics.

.github/workflows/ci_macos.yml, include/seqan3/utility/simd/detail/builtin_simd_intrinsics.hpp, test/seqan3-test.cmake, test/unit/alphabet/container/debug_stream_container_of_container_test.cpp
macos-12 is EOL. macos-14 also uses M1 (arm64) runners.
=> [INFRA] Use macos-14

.github/workflows/ci_coverage.yml, .github/workflows/ci_documentation.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml
=> [INFRA] Fail CI if ctest finds no tests

include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp, include/seqan3/utility/detail/type_name_as_string.hpp, test/seqan3-test.cmake
=> [MISC] Add -Wnrvo warning

cmake/package-lock.cmake
The GIT_TAG is ignored, but it causes CPM to expect a git repository. When using CPM_SOURCE_CACHE, this leads to a warning, because CPM wants to run `git status` in the cached directory.
=> [INFRA] Remove GIT_TAG for URL download

.github/workflows/ci_linux.yml, .github/workflows/ci_macos.yml, .github/workflows/ci_misc.yml, .github/workflows/cron_avx2.yml, .github/workflows/cron_latest_libraries.yml
=> [INFRA] Add clang-19

include/seqan3/core/platform.hpp
https://github.com/gcc-mirror/gcc/commit/5c34f02ba7ebe0dfec5595ebc8298c47d5f65e6e#diff-62a23e8a5ebebf0690390ca9d369d4a79f6e85ffc00712f521ebcd0206a62dbc
```cpp
#if __cplusplus >= 202002L && ! _GLIBCXX_USE_DEPRECATED
#elif __cplusplus >= 201703L && defined __DEPRECATED
#endif
```
Errors on nightly gcc trunk builds
`<version>` makes both `__GLIBCXX__` and `_LIBCPP_VERSION` available
=> [FIX] ciso646 is deprecated

test/unit/contrib/parallel/buffer_queue_parallel_test.cpp
Otherwise this is what happens:
```
The following tests FAILED:
5762 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.spmc_sum (Failed)
5763 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.mpsc_sum (Failed)
5764 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.mpmc_sum (Failed)
5767 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.spmc_dynamicsize (Failed)
5768 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.spmc_fixedsize (Failed)
5769 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.mpsc_dynamicsize (Failed)
5770 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.mpsc_fixedsize (Failed)
5771 - contrib/parallel/buffer_queue_parallel_test::buffer_queue.mpmc_dynamicsize (Failed)
5772 - …
```
=> [TEST] Skip parallel tests on machines having a single CPU

.github/workflows/ci_codeql.yml, test/analyse/CMakeLists.txt
=> [INFRA] Add CodeQL CI

include/seqan3/search/detail/search_scheme_algorithm.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/unit/utility/math_test.cpp
These are all `Comparison of narrow type with wide type in loop condition`
=> [FIX] CodeQL reports

include/seqan3/version.hpp
Forgot to bump after the last RC 🙈
=> [INFRA] Bump RC

cmake/package-lock.cmake, test/documentation/seqan3-doxygen.cmake, test/documentation/seqan3_doxygen_cfg.in, test/header/CMakeLists.txt, test/seqan3-test.cmake
Some stuff I found while building the debian package
=> [INFRA] Make packaging easier

include/seqan3/utility/concept.hpp, include/seqan3/utility/tuple/pod_tuple.hpp, test/snippet/utility/tuple/pod_tuple.cpp, test/unit/alphabet/adaptation/char_test.cpp, test/unit/alphabet/adaptation/uint_test.cpp, test/unit/alphabet/aminoacid/aminoacid_test_template.hpp, test/unit/alphabet/nucleotide/nucleotide_test_template.hpp, test/unit/alphabet/quality/phred_test_template.hpp, test/unit/utility/tuple/pod_tuple_test.cpp
use 'is_trivially_default_constructible_v && is_trivially_copyable_v' instead
=> [FIX] cpp26: std::is_trivial_v is deprecated

test/include/seqan3/test/zlib_skip.hpp, test/unit/io/sam_file/sam_file_output_test.cpp, test/unit/io/sequence_file/sequence_file_output_test.cpp, test/unit/io/stream/ostream_test_template.hpp, test/unit/io/structure_file/structure_file_output_test.cpp
=> [FIX,TEST] Do not check zlib output for alternative implementations

include/seqan3/contrib/std/LICENSE.md, include/seqan3/contrib/std/detail/exposition_only.hpp, include/seqan3/contrib/std/detail/movable_box.hpp, include/seqan3/contrib/std/enumerate_view.hpp
=> [INFRA] Update stl

test/documentation/seqan3-doxygen.cmake
=> [INFRA,DOC] Update doxygen webtags

test/unit/search/search_scheme_algorithm_test.cpp
=> [FIX] CodeQL warnings

.github/workflows/cron_debian.yml
This builds the Debian package on the main branch.
It's basically an API-Stability check for our package builds.
Errors either mean that something was overlooked when changing code or that the Debian package would need patches. In the latter case, it's nice to see that before an RC is released because there are way fewer commits between cron runs than between a stable release and the first release candidate of the next version.
=> [INFRA] Debian cron

include/seqan3/contrib/sdsl-lite.hpp, test/scripts/amalgamate-sdsl.sh
It's not included via `-isystem` anymore, so we see the deprecation warning.
Note that we could add a `#pragma GCC system_header` to mark it as system header.
This is also accepted by Clang.
=> [FIX] std::is_trivial is deprecated (sdsl)

.github/workflows/ci_coverage.yml, .github/workflows/ci_linux.yml, .github/workflows/ci_misc.yml, cmake/package-lock.cmake
=> [INFRA] SeqAn2 release and cache action

CMakeLists.txt, cmake/seqan3-config.cmake
CPM usually does a find_package redirect.
If `find_package` is called for some package added via CPM, it is redirected to CPM.
Before CPM 0.40.6, there was a bug that prevented this redirection from working properly.
If Seqan3 is added via CPM, CPM will call seqan3's `CMakeLists.txt`.
Because we use `find_package` there, it is redirected and results in seqan3 not being available.
=> [FIX] Do not find_package yourself

doc/tutorial/01_introduction/index.md, doc/tutorial/02_argument_parser/index.md, doc/tutorial/03_concepts/index.md, doc/tutorial/04_alphabet/index.md, doc/tutorial/05_ranges/index.md, doc/tutorial/06_minimisers/index.md, doc/tutorial/07_sequence_file/index.md, doc/tutorial/08_pairwise_alignment/index.md, doc/tutorial/09_search/index.md, doc/tutorial/10_sam_file/index.md, doc/tutorial/11_read_mapper/index.md
=> [DOC] Tutorial typos and codeblocks

include/seqan3/contrib/stream/bgzf_istream.hpp, include/seqan3/contrib/stream/bgzf_ostream.hpp, include/seqan3/contrib/stream/bgzf_stream_util.hpp, include/seqan3/contrib/stream/bz2_istream.hpp, include/seqan3/contrib/stream/bz2_ostream.hpp, include/seqan3/contrib/stream/gz_istream.hpp, include/seqan3/contrib/stream/gz_ostream.hpp, test/unit/io/stream/ostream_test_template.hpp
And also run clang-format on contrib
=> [FIX] compressed stream's overflow

test/unit/search/search_scheme_algorithm_test.cpp
=> [FIX] Bogus warning on gcc-15 with hardened flags

include/seqan3/contrib/sdsl-lite.hpp
Update to latest SDSL-lite master branch, which includes fixes for EPR when using not the complete alphabet
=> patch: Update SDSL to latest master

test/analyse/CMakeLists.txt, test/snippet/CMakeLists.txt
=> [INFRA] Set default SEQAN3_GENERATE_SNIPPETS to OFF

doc/tutorial/08_pairwise_alignment/pairwise_alignment_solution_4.err, doc/tutorial/08_pairwise_alignment/pairwise_alignment_solution_5.err, include/seqan3/core/debug_stream.hpp, test/snippet/alignment/cigar_conversion/alignment_from_cigar.err, test/snippet/alignment/cigar_conversion/alignment_from_cigar_io.err, test/snippet/alignment/configuration/align_cfg_output_examples.err, test/unit/utility/views/chunk_test.cpp
includes the debug_stream_alignment.hpp in debug_stream.hpp for proper printing. see #3309 for more details on the issue.
=> fix: include alignment printer in debug_stream.h

include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, include/seqan3/utility/bloom_filter/bloom_filter.hpp, include/seqan3/utility/bloom_filter/bloom_filter_strong_types.hpp
Such that including the bloom_filter does not trigger deprecation warnings
=> [MISC] Separate Bloom Filter strong types

include/seqan3/io/views/detail/take_exactly_view.hpp, include/seqan3/io/views/detail/take_until_view.hpp, include/seqan3/utility/views/single_pass_input.hpp, test/unit/io/views/detail/take_exactly_view_test.cpp, test/unit/io/views/detail/take_until_view_test.cpp
gcc15 now implements `std::ranges::to`
For `std::string` (as example), the call is delegated to `std::string(std::from_range, R &&)`.
This then will use `std::ranges::data` to get the data pointer and just copy the data.
This happens, for example, in format_sam's `id | detail::take_until_and_consume(is_space) | ranges::to<id_type>()`. 
Since the view is not an lvalue, it needs to be a borrowed_range for `std::ranges::data` to work.
Similar to std::views, we make (some of) our views conditionally borrowed if the underlying range is borrowed.
=> [FIX] gcc15: conditionally borrowed_range views

.github/workflows/cron_debian.yml, cmake/package-lock.cmake
Forced cache will cause the variable to be always set to the value defined in the package lock.
We actually want to be able to overwrite this.
Preferably, we would like to
* Overwrite if given on CLI. Otherwise, use default.
* On reconfigure, revert to default if not given.
* Have the variables available in the parent project (CPM version update script).
This doesn't really seem possible, see https://github.com/eseiler/misc/tree/main/cmake_set for some examples.
The drawback of `CACHE` is that changed default versions are not honored on a simple reconfigure.
=> [FIX,INFRA] cmake: version variables cannot be forced

.github/workflows/draft_release.yml
=> [INFRA] Draft release on tag
