seqan/seqan3

include/seqan3/alphabet.hpp, include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/aminoacid/aa27_container.hpp, include/seqan3/alphabet/composition.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/alphabet/gap/gap.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna4_container.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/dna5_container.hpp, include/seqan3/alphabet/nucleotide/nucl16.hpp, include/seqan3/alphabet/nucleotide/nucl16_container.hpp, include/seqan3/alphabet/quality/aliases.hpp, include/seqan3/alphabet/quality/concept.hpp, include/seqan3/alphabet/quality/illumina18.hpp, include/seqan3/alphabet/range.hpp, include/seqan3/alphabet/union_alphabet.hpp, test/alphabet/quality/composition_test.cpp, test/alphabet/quality/illumina18_test.cpp
@rrahn can you do a quick review of this soon?
It's just two renames and adding the meta header. The reason for the renames is to avoid `alphabet/alphabet_something.hpp` and just have `alphabet/something.hpp`.
Also the structure of the alphabet module is now in general
```
alphabet/concept.hpp             general concepts
alphabet/range.hpp               free function overloads on ranges of the general concept
alphabet/composition.hpp         alphabet composition
alphabet/quality/concept.hpp        quality concept
alphabet/quality/range.hpp          free function overloads on ranges of the quality concept (doesn't exist yet)
alphabet/quality/composition.hpp    the quality composition
....
```
I will adapt the nucleotide and aminoacid submodules in seperate PRs, but since this potentially …
=> add alphabet meta header, clean-up

include/seqan3/alphabet.hpp, test/alphabet/alphabet_test.cpp, test/alphabet/composition/union_composition_test.cpp
* `alphabet/composition/cartesian.hpp`
* don't test `_value`
* tests may only depend on previously tested behaviour, there must be no
circular dependencies
* `alphabet/composition/cartesian.hpp`
resolves #69
=> cleanup test cases of union_composition

include/seqan3/alphabet/aminoacid/aa27.hpp
Includes should never be inside the seqan3 namespace. The problem was seqan3::seqan3::alphabet_concept and this pr fixes this.
=> fix error with include inside namespace (aa27)

include/seqan3/alphabet/all.hpp, include/seqan3/alphabet/gap/all.hpp, include/seqan3/alphabet/gap/gap.hpp, include/seqan3/alphabet/gap/gapped.hpp, test/alphabet/alphabet_test.cpp, test/alphabet/gap/CMakeLists.txt, test/alphabet/gap/gapped_test.cpp
resolves #59 
* deduplicate the test cases, add to the generic test cases
* add `noexcept` where adequate
* streamline documentation, in particular add `\param` documentation to functions and `\ingroup` to everything
* add gap submodule meta-header, either `alphabet/gap.hpp` or `alphabet/gap/all.hpp` depending or where the library is then
* remove `set_gap` and `is_gap` since one can now just do `= gap::GAP` and `== gap::GAP` in constant time
* rename `gapped_alphabet<>` to `gapped<>` (it will be `gapped<dna4>` for example so it is clear)
=> Gap cleanup

include/seqan3/alphabet/concept_pre.hpp, include/seqan3/alphabet/detail/member_exposure.hpp, include/seqan3/alphabet/nucleotide/all.hpp, include/seqan3/alphabet/nucleotide/concept.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/nucl16.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/alphabet/nucleotide/rna5.hpp, include/seqan3/alphabet/quality/quality_composition.hpp, include/seqan3/range/view/complement.hpp, test/alphabet/nucleotide_test.cpp, test/range/view/CMakeLists.txt, test/range/view/view_complement_test.cpp
also update the nucleotide concept to be defined as alphabet+complement() and clean up the documentation big time.
=> add complement() and view::complement

README.md, include/seqan3/alphabet/aminoacid/translation.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/core/concept/cereal.hpp, include/seqan3/core/platform.hpp, include/seqan3/range/container/concatenated_sequences.hpp, test/CMakeLists.txt, test/alphabet/alphabet_test.cpp, test/alphabet/quality/quality_composition_test.cpp, test/alphabet/structure_test.cpp, test/core/pod_tuple_test.cpp, test/range/container/container_of_container_test.cpp, test/range/detail/random_access_iterator_test.cpp
This adds proper serialisation support. It is completely optional so SeqAn will build with and without Cereal. You don't have to do macro voodoo when adding serialisation functions as the serialisation functions are templates.
Have a look at f13d7db how easy this for specific types.
Generic versions are more difficult, but we won't need to implement them often.
This PR also adds `-pedantic` to our tests, because I was having warnings and fixing them anyway.
Please also note the changes here:
* https://github.com/seqan/seqan3/wiki/File-structure-and-naming#contents (order of includes, optional deps go **after SeqAn**)
* https://github.com/seqan/seqan3/wiki/Documentation#configuration (some changes to doxygen config)
=> Add serialisation support to SeqAn3

include/seqan3/alphabet/adaptation/all.hpp, include/seqan3/alphabet/all.hpp, include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/aminoacid/all.hpp, include/seqan3/alphabet/composition/all.hpp, include/seqan3/alphabet/concept_pre.hpp, include/seqan3/alphabet/gap/all.hpp, include/seqan3/alphabet/gap/gap.hpp, include/seqan3/alphabet/nucleotide/all.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/nucl16.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/alphabet/nucleotide/rna5.hpp, include/seqan3/alphabet/quality/illumina18.hpp, include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/dssp9.hpp, include/seqan3/alphabet/structure/wuss.hpp, include/seqan3/container.hpp, include/seqan3/core/concept/core_detail.hpp, include/seqan3/core/pod_tuple.hpp, include/seqan3/io/alignment/align_file.hpp, include/seqan3/io/alignment/align_file_detail.hpp, include/seqan3/io/alignment/align_file_in.hpp, include/seqan3/io/alignment/align_file_out.hpp, include/seqan3/io/sequence/sequence_file_format.hpp, include/seqan3/io/sequence/sequence_file_format_fasta.hpp, include/seqan3/io/sequence/sequence_file_in.hpp, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/range/view/trim.hpp
Fix doxygen warnings that are not due to being undocumented.
=> Fix some doxygen warnings

include/seqan3/alphabet/aminoacid/translation_details.hpp, include/seqan3/alphabet/detail/member_exposure.hpp, include/seqan3/alphabet/quality/concept.hpp, include/seqan3/alphabet/quality/illumina18.hpp, include/seqan3/core/pod_tuple.hpp
The only warning left is
seqan3/include/seqan3/range/container/concatenated_sequences.hpp:1313: warning: unable to resolve reference to `serialisation' for \ref command
as already mentioned in #127
=> [DOC] Fix some more doxygen warnings

include/seqan3/alphabet/adaptation/all.hpp, include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/composition/union_composition.hpp, include/seqan3/alphabet/gap/gap.hpp, include/seqan3/alphabet/gap/gapped.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/nucl16.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/alphabet/nucleotide/rna5.hpp, include/seqan3/alphabet/quality/aliases.hpp, include/seqan3/alphabet/quality/illumina18.hpp, include/seqan3/alphabet/quality/quality_composition.hpp, include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/dssp9.hpp, include/seqan3/alphabet/structure/structured_aa.hpp, include/seqan3/alphabet/structure/structured_rna.hpp, include/seqan3/alphabet/structure/wuss.hpp, test/alphabet/alphabet_test.cpp, test/alphabet/quality/illumina18_test.cpp
See #145 
As it seems, all static asserts are already tested.
For adaptation, quality_composition and structured_aa we might want to refactor some tests:
- e.g. alphabet_concept gets tested by testing the single conditions instead of ``EXPECT_TRUE(alphabet_concept<TypeParam>);`` or something similar
- Not all types get tested, e.g. in quality_composition
=> [INTERNAL, TEST] Remove static_assert from alphabet code

.gitmodules, README.md, build_system/seqan3-config.cmake, include/seqan3/core/platform.hpp, test/CMakeLists.txt
According to issue #149 I add the LEMON graph library as a submodule. 
Readme files and config.h are adapted and I also started to define macros in platform.h. With the latter I need a little help - where do I get the macro values from?
I tested a little graph example within SeqAn3 and it worked on my system. I would also like to test other platforms as soon as platform.h is updated properly. 
In the SeqAn code: Do I always have to test `#ifdef SEQAN3_WITH_LEMON` before using (even including) a graph or is there a better solution? Code might get messy with all the preprocessor commands.
=> add LEMON submodule

include/seqan3/alphabet/aminoacid/translation_details.hpp, include/seqan3/alphabet/nucleotide/all.hpp, include/seqan3/alphabet/nucleotide/dna15.hpp, include/seqan3/alphabet/nucleotide/rna15.hpp, include/seqan3/alphabet/quality/aliases.hpp, include/seqan3/range/view/convert.hpp, test/alphabet/alphabet_test.cpp, test/alphabet/aminoacid_test.cpp, test/alphabet/nucleotide_test.cpp
replace the nucl16 alphabet (with distinct T and U values) with dan15 and rna15. This removes ambiguity on conversions and creates consistency with the other dna and rna alphabets.
=> nucl16 → dna15 and rna15

include/seqan3/alphabet/composition/union_composition.hpp, include/seqan3/core/detail/int_types.hpp, test/alphabet/alphabet_test.cpp, test/alphabet/composition/union_composition_detail_test.cpp, test/alphabet/composition/union_composition_test.cpp, test/core/detail/int_types_test.cpp
* don't use `namespace seqan3::detail::union_alphabet` since it doesn't
appear in doxygen
* don't use `\privatesection` and `\publicsection` outside of class
scope (it doesn't have any effect there)
* add `\ingroup composition` where needed!
* fix testcases of union_composition
* add \param documentation to union_composition
resolves #68 and resolves #60
=> [INTERNAL] rework documentation of union_composition

include/seqan3/alphabet/gap/gapped.hpp, test/alphabet/alphabet_test.cpp
=> Document gap alphabet and add tests

.travis.yml, benchmark/CMakeLists.txt, benchmark/alphabet/CMakeLists.txt, benchmark/alphabet/alphabet_benchmark.cpp, benchmark/example/CMakeLists.txt, benchmark/example/example_benchmark.cpp
This provides a basic structure for (micro-)benchmarks.
The underlying benchmark framework is https://github.com/google/benchmark that will be automatically downloaded and built when building `seqan3/benchmark`.
=> [FEATURE] added benchmark folder and an example benchmark

include/seqan3/alphabet/structure/wuss.hpp
using internal type in lambda function instead of `.to_rank()`
fixes issues with Ubuntu
=> fix wuss alphabet

test/io/util/CMakeLists.txt
* The (empty) content from `test/io/util/CMakeLists.txt` was moved to `test/unit/io/util/CMakeLists.txt`
* The content is empty, because there is no `output_iterator_test.cpp` file
* Thus, `test/io/util/CMakeLists.txt` was deleted without any changes
=> remove test/io/util/CMakeLists.txt

test/include/CMakeLists.txt, test/include/seqan3/CMakeLists.txt, test/include/seqan3/test/CMakeLists.txt, test/include/seqan3/test/tmp_filename_test.cpp
See #125
I'm not really sure about this, so any feedback is welcome.
I'd argue that we do not need to explicitly test the correct deletion of multiple temporary files since it's already implicitly guaranteed by the different file paths for each temporary file and the correct deletion of one temporary file.
I don't know if you can test whether something is not copy constructable, because it already throws during compiling.
=> [FEATURE] Add test for tmp_file_name

include/seqan3/range/container/concatenated_sequences.hpp
quick bug-fix, required for #225
=> [FIX] use non-const iterators internally to workaround bug in gcc-7.2.*

include/seqan3/alphabet/nucleotide/rna15.hpp
rna15 is already marked as implementing nucleotide_concept because it inherits from dna15. Removing this explicit "implem,ents" removes a double link in the inheritance graph and brings it inline with rna4 and rna5
=> remove one line from documentation

include/seqan3/core/concept/cereal.hpp, test/unit/core/concept/CMakeLists.txt, test/unit/core/concept/cereal_test.cpp
:new:  test cases for /include/core/concept/cereal.hpp
:new: seqan3::cerealisable_concept
> This concept checks whether a given type is serialisable with cereal.
=> Cerealisable concept

include/seqan3/core/detail/reflection.hpp, test/unit/core/detail/reflection_test.cpp
As you can see, gcc-8 changed the output of `__PRETTY_FUNCTION__`.
The `[with type = int]` part is now missing; therefore, `get_size()` skipped over all characters until after `\0`
resolves #262
=> [FIX] #262: gcc8 fails to compile reflection_test.cpp

include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/nucleotide/dna15.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/nucleotide/rna15.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/alphabet/nucleotide/rna5.hpp, include/seqan3/alphabet/quality/illumina18.hpp, include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/dssp9.hpp, include/seqan3/alphabet/structure/wuss.hpp
Addresses issue #141 where unsigned chars are used in char_to_value. Using index_t defined as std::make_unsigned_t<char_type>, this casts the char to type index_t, resolving it to an unsigned char so that no negative values are used to index.
=> [FIX] Cast signed chars to unsigned chars.

include/seqan3/core/metafunction/template_inspection.hpp, test/unit/core/metafunction/template_inspection_test.cpp
Fixes the following issue: 
When using our template inspection with non-template types the compiler will emit an error, rather than having a negative result.
=> [FIX] Fixes template inspection for non template source types.

include/seqan3/alphabet/quality/qualified.hpp
=> [INTERNAL] Slacken the restriction on the qualified class from nucleotide_concept to alphabet_concept.

include/seqan3/alphabet/composition/union_composition.hpp, test/unit/alphabet/composition/union_composition_test.cpp
Make cartesian composition constructable, assignable and comparable from one of it's compostie types or accepted subtypes.
Fixes #366
=> [INTERNAL, TEST] union_composition adjustments

.travis.yml
high priority because the build failures on travis are annoying as hell and our builds are too long to profit from the short boot-up-time of the containers anyway.
=> re-activate fully virtualised builds because they have more memory

include/seqan3/alphabet/composition/union_composition.hpp, include/seqan3/alphabet/gap/gapped.hpp
Since missing default constructors caused trouble in the cartesian composition (PR #372) this adds them for the gapped union composition for consistency and to avoid future errors.
=> [INTERNAL] Add default constructors explicelty to gapped composition.

include/seqan3/alphabet/composition/cartesian_composition.hpp, include/seqan3/alphabet/composition/union_composition.hpp, include/seqan3/alphabet/gap/gap.hpp, test/unit/alphabet/alphabet_test.cpp, test/unit/alphabet/composition/CMakeLists.txt, test/unit/alphabet/composition/cartesian_composition_test.cpp, test/unit/alphabet/composition/composition_test.cpp
… the only important change is the change of:  friend comparison operator -> free functions.
And the GCC bug workaround in gap.hpp
=> [FIX, TEST] Fixed cartesian and union composition comparison on compex types.

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/alignment/aligned_sequence/all.hpp, include/seqan3/alignment/exception.hpp, test/unit/alignment/CMakeLists.txt, test/unit/alignment/aligned_sequence_test.cpp
fixes #352 
and introduces global functions `insert_gap` and `erase_gap` as well as a typed test.
=> Alignment io aligned sequence concept

test/performance/example/example_benchmark.cpp
Recent travis and jenkings builds have been failing with:
```cpp
/home/travis/build/seqan/seqan3/test/performance/example/example_benchmark.cpp:56:34: error: ‘void benchmark::State::SetBytesProcessed(int64_t)’ is deprecated: The SetItemsProcessed()/items_processed()/SetBytesProcessed()/bytes_processed() will be removed in a future release. Please use custom user counters. [-Werror=deprecated-declarations]
state.SetBytesProcessed(bytes);
^
In file included from /home/travis/build/seqan/seqan3/test/performance/example/example_benchmark.cpp:38:0:
/home/travis/build/seqan/seqan3-build/vendor/benchmark/include/benchmark/benchmark.h:549:8: note: declared here
void SetBytesProcessed(int64_t bytes) { bytes_processed_ = bytes; }
^~~~~~~~~~~~~~~~~
```
This PR fixes the behaviour.
@marehr Can you …
=> [FIX] track changes in google testing framework

test/seqan3-test.cmake
Resolves #410 
This pins googletest to `v1.8.1` and googlebenchmark to `v1.4.1`.
In the latest googletest release, the CMakeLists.txt is changed from
```cmake
if(BUILD_GMOCK)
add_subdirectory( googlemock )
elseif(BUILD_GTEST)
add_subdirectory( googletest )
endif()
```
to
```cmake
if(BUILD_GMOCK)
add_subdirectory( googlemock )
else()
add_subdirectory( googletest )
endif()
```
so `BUILD_GTEST` needs to be removed from our config as well.
=> Pin googletest and benchmark to latest release

include/seqan3/io/alignment/all.hpp, include/seqan3/io/alignment/detail.hpp, test/unit/alignment/aligned_sequence_test.cpp
replaces #414 until we decide what to do with the cigar string/alphabet/sequence in general.
=> [INTERNAL] get cigar string from alignment.

include/seqan3/range/view/persist.hpp
Resolves #435 
In
https://github.com/seqan/seqan3/blob/a1f818df3cb778ae074804a889d61167194037ea/include/seqan3/range/view/persist.hpp#L190-L199
and the corresponding overload, we require the `container_concept`, but the `ranges::back_inserter(ret)` will eventually call `push_back` on something of the `container_t` type.
So, I think, we should actually require the `sequence_container_concept` (or maybe just add a requires for the `push_back` functionality?) to ensure the type provides a `push_back` function.
I did some debugging with @smehringer and we saw that apparently GCC7 resolves to `container_t = std::string` and GCC8 resolves to `container_t = std::string_view` (🤷‍♂️) - which does not provide `push_back`.
=> [FIX] GCC8 compiler error

include/seqan3/core/metafunction/template_inspection.hpp, test/unit/core/metafunction/template_inspection_test.cpp
If one tries to use transfer_template_vargs_onto for two different types with two different enum values, the compiler will emit a hard error. 
This is problematic if one wants to use the is_specialization metafunction, as it does not compile. 
The fix, uses the SFINAE trick to check if the expression actually is valid and if not evaluates to void.
=> [FIX] Fixes template inspection for enum values.

include/seqan3/argument_parser/detail/format_help.hpp
now prints the name and hline instead of two empty lines
=> [FIX] fix short help printing.

include/seqan3/search/fm_index/concept.hpp, test/unit/search/fm_index_test.cpp
The fm_index concept tests for 
https://github.com/seqan/seqan3/blob/41b42cc5d45c544a427ed079af957ad4366ea9e6/include/seqan3/search/fm_index/concept.hpp#L162
We should actually check for the underlying `char_type` instead of `dna4` .
And since we only test the concepts for `dna4`, the concept tests will pass ...
=> Generalize fm index concept

include/seqan3/argument_parser/argument_parser.hpp
=> [DOC] Add missing throws documentation to argument_parser::parse().

include/seqan3/alignment/matrix/alignment_trace_matrix.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp, test/unit/alignment/pairwise/fixture/alignment_fixture.hpp, test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
Changes:
* computes begin_position
* `edit_distance{}(result_type)` supports now all `result_type` modes and properly sets the return values
* `align_result` expects now the `alignment_coordinate` type
* `alignment_trace` won't use `lists` anymore
=> edit_distance now computes begin position

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, test/snippet/argument_parser/argument_parser_1.cpp, test/snippet/argument_parser/argument_parser_2.cpp, test/snippet/argument_parser/argument_parser_3.cpp, test/unit/argument_parser/format_parse_test.cpp
It is indirectly tested in the snippets that now mirror the "usual" main function parameters.
Fixes #388 and can be checked off in #471 after merging.
=> [INTERNAL] argument_parser now accepts also non-const char **.

include/seqan3/alphabet/aminoacid/aa20.hpp, include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/composition/cartesian_composition.hpp, include/seqan3/alphabet/composition/union_composition.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/alphabet/gap/gap.hpp, include/seqan3/alphabet/mask/mask.hpp, include/seqan3/alphabet/mask/masked.hpp, include/seqan3/alphabet/nucleotide/dna15.hpp, include/seqan3/alphabet/nucleotide/dna4.hpp, include/seqan3/alphabet/nucleotide/dna5.hpp, include/seqan3/alphabet/quality/phred42.hpp, include/seqan3/alphabet/quality/phred63.hpp, include/seqan3/alphabet/quality/phred68legacy.hpp, include/seqan3/alphabet/quality/qualified.hpp, include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/structured_aa.hpp, include/seqan3/alphabet/structure/structured_rna.hpp, include/seqan3/alphabet/structure/wuss.hpp, include/seqan3/core/metafunction/function.hpp, test/unit/alphabet/alphabet_test.cpp, test/unit/alphabet/mask/mask_test.cpp, test/unit/core/metafunction/CMakeLists.txt, test/unit/core/metafunction/function_test.cpp
All our alphabets are `constexpr` safe and some functionality (e.g. in the compositions) depends on this. But we require it nowhere (and it shouldnt be required in general).
Unfortunately there is no concept checking syntax for checking the constexpr'ness of a function, but I found a great hack on how to do it.
I have subsequently added constexpr concepts for alphabet and semi_alphabet and changed the requirements for the compositions. Currently these concepts reside in detail.
=> constexpr_invocable check and constexpr alphabets

include/seqan3/argument_parser/argument_parser.hpp, test/unit/argument_parser/argument_parser_design_error_test.cpp
This fixes #469 and will check off one issue in #471
=> [INTERNAL] Prohibit calling argument_parser::parse more than once.

include/seqan3/alphabet/composition/union_composition.hpp
=> [NOOP] fix typo in union alphabet

include/seqan3/core/metafunction/iterator.hpp, include/seqan3/core/metafunction/range.hpp
minor changes to not make these depend on range-v3 counterparts. They do however depend on ranges::begin, ranges::end, ranges::size and ranges::iter_move which should be available in our `std` module.
=> [INTERNAL] make the metafunctions not redirect to range-v3 metafunctions

include/seqan3/range/view/persist.hpp, include/seqan3/range/view/take.hpp, include/seqan3/range/view/take_line.hpp, include/seqan3/range/view/take_until.hpp, test/unit/range/view/view_take_test.cpp
Fixes a bug that prevented multiple instances of `view::take`, `view::take_until` and `view::take_line` (and their `_or_throw` versions to be chained.
The problem was found by @joshuak94 but I don't think there was an issue.
=> [FIX] ambigious constructors of specialised inherited_iterator_base

include/seqan3/std/charconv, include/seqan3/std/charconv_detail.hpp, test/performance/std/CMakeLists.txt, test/performance/std/charconv_from_chars_benchmark.cpp, test/performance/std/charconv_to_chars_benchmark.cpp, test/unit/std/CMakeLists.txt, test/unit/std/charconv_test.cpp
This PR introduces the std::from_chars functionality because
1. In gcc7 none of the std::from_chars overloads are implemented
2. In gcc8 only the **integral** std::from_chars overloads are implemented
For 1) The code of LLVM was copied and documented as such.
For 2) The functions `strto[f/d/ld]` were used as a workaround to provide the std::from_chars functionality for floating point values.
* The return type: The return type of std::from_chars is a struct containing an error code and a char pointer. The char pointer is documented to be set to the position where a character is NOT matching the correct parsing pattern (e.g. illegal character, or wrong format). As the functions  `strto[f/d/ld]` do not provide this functionality, this behaviour could only be mimiced by extensive string …
=> [FEATURE] std::from_char and std::to_char functions, tests and benchmarks.

include/seqan3/io/stream/debug_stream.hpp
clang complains with:
```
seqan3/include/seqan3/io/stream/debug_stream.hpp:112:5: error: defaulted definition of copy assignment operator is not constexpr
constexpr debug_stream_type & operator= (debug_stream_type const &) = default;
^
seqan3/include/seqan3/io/stream/debug_stream.hpp:113:5: error: defaulted definition of move assignment operator is not constexpr
constexpr debug_stream_type & operator= (debug_stream_type &&) = default;
^
```
=> [fix] debug_stream_type should not be constexpr

include/seqan3/core/detail/strong_type.hpp
```c++
constexpr derived_t operator<<(std::Integral const shift)
```
is not allowed in the current concept-ts.
=> [fix] dont use concepts as type replacement

include/seqan3/alphabet/gap/gap.hpp, test/snippet/alphabet/gap/gap.cpp, test/unit/alphabet/gap/gap_test.cpp
The gap alphabet does not use `alphabet_concept`, so we should not include it.
=> [task] gap: remove unnecessary include

test/unit/std/charconv_test.cpp
```c++
/seqan3/test/unit/std/charconv_test.cpp:88:36: error: constant expression evaluates to -123 which cannot be narrowed to type 'integral_from_char_test_negative_number_Test<unsigned long>::TypeParam' (aka 'unsigned long') [-Wc++11-narrowing]
EXPECT_EQ(value, TypeParam{-123});
^~~~
```
=> [fix] clang: constant expression evaluates to -123 which cannot be narrowed to type 'unsigned long'

include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp
```c++
/seqan3/test/unit/alignment/matrix/alignment_matrix_formatter_test.cpp:16:1: error: 'matrix_formatter_test' defined as a struct here but previously declared as a class [-Werror,-Wmismatched-tags]
struct matrix_formatter_test : public ::testing::Test
^
/seqan3/include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp:395:12: note: did you mean struct here?
friend class matrix_formatter_test;
^
```
=> [fix] clang: 'matrix_formatter_test' defined as a struct here but previously declared as a class

include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp
```c++
seqan3/include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp:361:34: error: 'auto' not allowed in function prototype
static std::string as_string(auto && entry) noexcept
^~~~
```
=> [fix] clang: 'auto' not allowed in function prototype

include/seqan3/io/stream/parse_condition_detail.hpp
clang can't use requires in a CRTP base class if the condition in the requires involves the derived class which is not fully defined yet.
Tries to define `is_char_type` (still incomplete) -> tries to define `parse_condition_base<is_char_type>` (still incomplete) -> tries to define `message` (still incomplete) which has a requires on `is_char_type` (circular dependency on a still incomplete type).
```c++
In file included from /seqan3/test/unit/io/stream/parse_condition_test.cpp:35:
In file included from /seqan3-build/clang-6-concepts/vendor/googletest/googletest/include/gtest/gtest.h:55:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/ostream:38:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/ios:39: …
```
=> [fix] clang: incomplete type 'seqan3::detail::is_char_type<-1>' used in type trait expression

include/seqan3/io/detail/record.hpp
```
/seqan3/include/seqan3/io/detail/record.hpp:212:1: error: 'decltype(auto)' cannot be combined with other type specifiers
decltype(auto) const get_or(record<field_types, field_ids> const & r, or_type && or_value)
^
```
See https://stackoverflow.com/questions/27766601/why-cannot-form-reference-to-decltypeauto/27766740#27766740
=> [fix] clang: 'decltype(auto)' cannot be combined with other type specifiers

test/unit/range/detail/inherited_iterator_base_test.cpp
```c++
/seqan3/test/unit/range/detail/inherited_iterator_base_test.cpp:59:5: error: defaulted definition of copy assignment operator is not constexpr
constexpr skip_odd_numbers_it & operator=(skip_odd_numbers_it const & rhs) = default;
^
```
=> [fix] clang: defaulted definition of copy assignment operator is not constexpr

test/unit/range/container/aligned_allocator_test.cpp, test/unit/range/detail/random_access_iterator_test.cpp
```c++
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:82:66: error: unused variable 'it' [-Werror,-Wunused-variable]
seqan3::detail::random_access_iterator<std::vector<uint8_t>> it;
^
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:83:72: error: unused variable 'it2' [-Werror,-Wunused-variable]
seqan3::detail::random_access_iterator<std::vector<uint8_t> const> it2;
^
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:128:66: error: unused variable 'it_derivate' [-Werror,-Wunused-variable]
seqan3::detail::random_access_iterator<std::vector<uint8_t>> it_derivate(it_base);
^
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:131:72: error: unused variable 'it_derivate2' [-Werror,-Wunused-variable] …
```
=>  [fix] clang: unused variables 

test/unit/range/detail/random_access_iterator_test.cpp
```c++
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:220:5: error: variable 'it_ptr' is uninitialized when used here [-Werror,-Wuninitialized]
it_ptr->iterator_type::~iterator_type();
^~~~~~
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:219:27: note: initialize the variable 'it_ptr' to silence this warning
iterator_type * it_ptr;
^
= nullptr
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:225:5: error: variable 'it_ptr2' is uninitialized when used here [-Werror,-Wuninitialized]
it_ptr2->iterator_type2::~iterator_type2();
^~~~~~~
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:224:29: note: initialize the variable 'it_ptr2' to silence this warning
iterator_type2 * it_ptr2;
^
= nullptr
```
=> [fix] clang: variable is uninitialized when used here

include/seqan3/core/metafunction/range.hpp
fixes #524; a problem with normalization of constaints
=> [fix] clang: use source-level subsumption

include/seqan3/alignment/scoring/scoring_scheme_base.hpp
Some minor fix for scoring schemes.
Currntly the size type for the scoring scheme matrix is fixed to uint8_t, which won't work for char alphabets. 
To make it generic the matrix size type should be dependent to the size type that can hold the size of the alphabet. While char adaptions already exposed a type in the alphabet_size value meta function, the other alphabets did not. 
This fix adds the type alias for the alphabet_size value meta function.
=> [FIX] Fixes scoring scheme matrix size type.

.travis.yml, test/coverage/CMakeLists.txt, test/seqan3-test.cmake
This introduces code coverage testing:
* `cd /seqan3 && mkdir -p build/coverage  && cmake ../../test/coverage -DCMAKE_BUILD_TYPE=Debug`
* `make` or `make coverage` will generate coverage reports
* `make coverage_html` will generate a graphical report
This CMakeScript uses under-the-hood `g++ --coverage` and `lcov` (which uses `gcov`).
`lcov` is used to merge coverage reports and also to filter out `/usr/*` and some other directories.
The script was adopted from https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake (author was included into the copyright)
Disclaimer: g++-8 seems to have a broken `lcov`, reports generated with g++-7 seems to be fine.
partially resolves (#167)
Resources:
* http://ltp.sourceforge.net/coverage/lcov.php
* …
=> Feature: code coverage test

test/documentation/CMakeLists.txt
This small fix makes the difference between
```c++
/seqan3/include/seqan3/core/metafunction/template_inspection.hpp:48: warning: explicit link request to 'testing::Types' could not be resolved /seqan3/include/seqan3/core/metafunction/template_inspection.hpp:48: warning: explicit link request to 'testing::Types' could not be resolved /seqan3/include/seqan3/core/metafunction/template_inspection.hpp:48: warning: explicit link request to 'testing::Types' could not be resolved /seqan3/include/seqan3/core/metafunction/template_inspection.hpp:48: warning: explicit link request to 'testing::Types' could not be resolved /seqan3/include/seqan3/core/metafunction/template_inspection.hpp:50: warning: Found unknown command `\detail' /seqan3/include/seqan3/core/metafunction/template_inspection.hpp:54: …
```
=> [fix] documentation test should preserve newlines

test/unit/alphabet/adaptation/char_test.cpp, test/unit/alphabet/alphabet_test_template.hpp
Part of #607, fixes mainly `signed` != `unsigned` warnings.
=> [fix] warnings in alphabet tests

include/seqan3/core/simd/simd_algorithm.hpp, test/unit/core/algorithm/configuration_test.cpp, test/unit/core/bit_manipulation_test.cpp, test/unit/core/tuple_utility_test.cpp
Part of #607, fixes mainly `signed` != `unsigned` warnings.
=> [fix] warnings in core tests

test/unit/range/container/aligned_allocator_test.cpp, test/unit/range/view/view_char_to_test.cpp, test/unit/range/view/view_complement_test.cpp, test/unit/range/view/view_deep_test.cpp, test/unit/range/view/view_take_test.cpp
Part of #607, fixes mainly `signed` != `unsigned` warnings.
=> [fix] warnings in range tests

include/seqan3/core/metafunction/all.hpp, include/seqan3/core/metafunction/deferred_crtp_base.hpp, test/snippet/core/metafunction/deferred_crtp_base.cpp, test/unit/core/metafunction/CMakeLists.txt, test/unit/core/metafunction/deferred_crtp_base_test.cpp
This helper meta-function allows augmentation of crtp classes with traits before the derived type is known.
At the moment I will use it for the alignment configuration but I saw it as general enough to put it into core metafunction.
=> [FEATURE] Adds metafunction to defer instantiation of crtp_base classes.

include/seqan3/core/algorithm/all.hpp, include/seqan3/core/algorithm/parameter_pack.hpp, test/snippet/core/algorithm/for_each_type.cpp, test/snippet/core/algorithm/for_each_type_list.cpp, test/snippet/core/algorithm/for_each_value.cpp, test/unit/core/algorithm/CMakeLists.txt, test/unit/core/algorithm/parameter_pack_test.cpp
Allow applying a function to each argument of a parameter pack.
An example:
```c++
#include <iostream>
#include <string>
#include <seqan3/core/algorithm/parameter_pack.hpp>
#include <seqan3/io/stream/debug_stream.hpp>
using namespace seqan3;
int main()
{
auto fn = [](auto && a)
{
debug_stream << a;
};
// prints each argument, i.e. "0, 1, 2, 3\n"
detail::parameter_pack_for_each(fn, 0, ", ", 1.0, ", ", std::string{"2, 3"}, '\n');
// is the same as explicitly writing
fn(0);
fn(", ");
fn(1.0);
fn(", ");
fn(std::string{"2, 3"});
fn('\n');
return 0;
}
```
=> [feature] for_each on parameter packs

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, test/unit/alignment/aligned_sequence_test.cpp
This PR adds debug_stream's `operator<<` for alignments, which are represented as tuple or pair of aligned sequences. Should I add support for std::vector of aligned sequences as well? 
Due to our file output policy of not checking user variables before printing, the output may be corrupted, if the sequences do not have equal length. 
The documentation of how to use zip_view as a column iterator for alignments will come in a separate PR. 
replaces PR #233 and #20
=> Stream sequence alignments in multi-line representation

include/seqan3/contrib/stream/bz2_istream.hpp, include/seqan3/contrib/stream/bz2_ostream.hpp, include/seqan3/contrib/stream/gz_istream.hpp, include/seqan3/contrib/stream/gz_ostream.hpp, test/documentation/seqan3_doxygen_cfg.in, test/performance/io/CMakeLists.txt, test/performance/io/stream_input_benchmark.cpp, test/performance/io/stream_output_benchmark.cpp, test/unit/contrib/CMakeLists.txt, test/unit/contrib/stream/CMakeLists.txt, test/unit/contrib/stream/bz2_istream_test.cpp, test/unit/contrib/stream/bz2_ostream_test.cpp, test/unit/contrib/stream/gz_istream_test.cpp, test/unit/contrib/stream/gz_ostream_test.cpp, test/unit/io/stream/istream_test_template.hpp, test/unit/io/stream/ostream_test_template.hpp
resolves #610 
no bgzf for now, because it has additional requirements
not tied into any of the files, yet
Benchmarks have high variance on my system, but here is one:
```
-------------------------------------------------------------------------------------
Benchmark                                              Time           CPU Iterations
-------------------------------------------------------------------------------------
uncompressed                                           6 ns          6 ns  144466035
compressed<contrib::gz_ostream>                        8 ns          8 ns   90665658
compressed<contrib::bz2_ostream>                     529 ns        520 ns    1807077
compressed_type_erased<contrib::gz_ostream>            8 ns          8 ns   92377217 …
```
=> gzip and bzip2 stream

include/seqan3/argument_parser/validators.hpp, test/snippet/argument_parser/validators_chaining.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
Fixes #192 
You can now do this
```
parser.add_option(..., validator1 | validator2);
```
=> [FEATURE] Enable chaining of validators.

include/seqan3/io/stream/debug_stream.hpp, test/unit/io/stream/debug_stream_test.cpp
This adds printing for objects that fulfil the `tuple_like_concept`.
Open questions:
- Where to put the code and/or the `detail` namespace?
- ~~Any way to avoid const and non-const overload? The member function for `operator<<` is templatized and it won't resolve to `tuple_t const` if `tuple_t` is used in the function call.~~ done
- ~~Currently breaks some alphabet tests and the `simd_debug_stream_test` because of ambiguous overloads (the debug_stream for simd creates an `std::array` which then also fulfils the `tuple_like_concept`)~~
- <details><summary>Additional requirements (click me)</summary><p>
We could add:
```cpp
template <typename ...elems>
inline bool constexpr all_streamable = false;
template <typename T>
concept debug_streamable =
requires (T t)
{
debug_stream << t;
}; …
```
=> Print tuple_like objects to debug_stream

include/seqan3/core/metafunction/template_inspection.hpp, test/unit/core/metafunction/template_inspection_test.cpp
This fixes hard compiler errors that occur, when the transferred type is ill-formed due to constraints on the template arguments of the target type. This happens especially when trying to use `is_type_specialization_of` as it uses this meta-function internally.
=> [FIX] Fixes transfer_template_args_onto when the transferred type would be ill-formed.

include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp, include/seqan3/alignment/pairwise/execution/alignment_range.hpp, test/unit/alignment/pairwise/alignment_selector_test.cpp
```
In file included from /seqan3/test/unit/alignment/pairwise/alignment_selector_test.cpp:35:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/alignment/pairwise/alignment_selector_test.cpp:73:9:   required from here …
```
=> [fix] warnings in alignment tests

include/seqan3/io/stream/parse_condition_detail.hpp, test/unit/io/structure_file/format_vienna_test.cpp
```
In file included from /seqan3/test/unit/io/structure_file/format_vienna_test.cpp:40:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/io/structure_file/format_vienna_test.cpp:138:13:   required from here …
```
=> [fix] warnings in io tests

include/seqan3/alignment/configuration/align_config_max_error.hpp, test/unit/alignment/configuration/align_config_max_error_test.cpp, test/unit/alignment/matrix/alignment_matrix_formatter_test.cpp, test/unit/alignment/pairwise/alignment_result_test.cpp
Part of #607, fixes mainly `signed` != `unsigned` warnings.
=> [fix] some warnings in alignment tests

build_system/seqan3-config.cmake, include/seqan3/search/algorithm/detail/search.hpp, include/seqan3/search/fm_index/bi_fm_index_iterator.hpp, test/seqan3-test.cmake
We observed the problem that warnings weren't triggered in our tests.
After some investigation, we figured out that seqan3 was included as `-isystem` in the unit tests.
After some more digging, I found out that this is due to using `add_library(name INTERFACE IMPORTED)`.
This PR changes the cmake script in such a way that seqan3 will always be included via `-I`, but our external dependencies will be still included as system libraries, i.e. `-isystem`.
This resolves #606.
-----
This PR only makes the changes in cmake, the following PRs fix the code:
* ~#616~ 
* ~#617~
* ~#618~
* ~#619~ 
* ~#627~
* ~#628~
* ~#629~
=> [fix] cmake uses -isystem and not -I for seqan3 include path

include/seqan3/range/view/persist.hpp
Since we are always delegating to the underlying range's non-const iterator/sentinel, we don't need to check for const-iterability.
=> [FIX] minor fixes to view::persist

include/seqan3/io/all.hpp, include/seqan3/io/detail/misc_input.hpp, include/seqan3/io/detail/misc_output.hpp, include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/io/sequence_file/format_fastq.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/stream/concept.hpp, include/seqan3/io/stream/parse_condition_detail.hpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_integration_test.cpp, test/unit/io/sequence_file/sequence_file_output_test.cpp
resolves #611 
~~blocked by #610 (new commits begin at [MISC] ...)~~
----
In addition to the planned changes this also makes sequence_file cope with streams that have other char-types than `char`, like `wchar_t`.
@rrahn I have added some single-arguments concepts to the stream_concepts and we can discuss what to do about it long-term.
=> add compression and decompression support to sequence_file_*

include/seqan3/argument_parser/all.hpp, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/validators.hpp, test/snippet/argument_parser/validators_1.cpp, test/unit/argument_parser/argument_parser_design_error_test.cpp, test/unit/argument_parser/format_parse_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
1. Update integral_range_validator to arithmetic_range_validator, so that non-integer types (double, etc.) can still be validated. Also updates the snippet, and adds test cases for successful and unsuccessful uses of double.
=> [FEATURE] Updates different aspects of argument_parser

include/seqan3/std/span.hpp
Fixes
```
[ 28%] Building CXX object CMakeFiles/seqan3_header_seqan3_std_span_2.dir/header_test_src/seqan3_std_span_2.cpp.o
/home/travis/build/seqan/seqan3-build/header_test_src/seqan3_std_span_2.cpp:7:2: error: #error "Your header file is missing #include<seqan3/core/platform.hpp>"
#error "Your header file is missing #include<seqan3/core/platform.hpp>"
^~~~~
CMakeFiles/seqan3_header_seqan3_std_span_2.dir/build.make:62: recipe for target 'CMakeFiles/seqan3_header_seqan3_std_span_2.dir/header_test_src/seqan3_std_span_2.cpp.o' failed
make[2]: *** [CMakeFiles/seqan3_header_seqan3_std_span_2.dir/header_test_src/seqan3_std_span_2.cpp.o] Error 1
make[2]: Target 'CMakeFiles/seqan3_header_seqan3_std_span_2.dir/build' not remade because of errors.
CMakeFiles/Makefile2:9132: recipe for target …
```
=> [FIX] Include platform.hpp in span.hpp

include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/dssp9.hpp, include/seqan3/alphabet/structure/wuss.hpp, test/snippet/alphabet/structure/dot_bracket3.cpp, test/snippet/alphabet/structure/dssp9.cpp, test/snippet/alphabet/structure/structured_aa.cpp, test/snippet/alphabet/structure/structured_rna.cpp, test/snippet/alphabet/structure/wuss.cpp, test/unit/alphabet/composition/cartesian_composition_test.cpp, test/unit/alphabet/structure/dot_bracket3_test.cpp, test/unit/alphabet/structure/dssp9_test.cpp, test/unit/alphabet/structure/wuss51_test.cpp
Adds char literals to the following alphabets and removes the enum interface.
solves #644
=> [FEATURE] Char literals for structure alphabets

include/seqan3/std/charconv_detail.hpp, test/unit/std/charconv_test.cpp
Treat the second parameter as the end of the sequence to parse.
=> [FIX] Fix from_chars for float 

include/seqan3/io/sequence_file/output.hpp, test/unit/io/sequence_file/sequence_file_output_test.cpp
Caught by @joshuak94 when going through the snippets. This was never tested so it was never caught. I added tests for it.
=> [FIX] fix sequence_file_output writing of SEQ_QUAL field.

test/coverage/CMakeLists.txt
=> [INFRA] Exclude std and contrib from coverage tests

include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_init_policy.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_policy.hpp, include/seqan3/alignment/pairwise/policy/all.hpp, include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp, include/seqan3/alignment/pairwise/policy/unbanded_dp_matrix_policy.hpp, test/unit/alignment/pairwise/fixture/global_affine_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_affine_unbanded.hpp, test/unit/alignment/pairwise/global_affine_unbanded_test.cpp
Supersedes #674 
* Adapts the configurator to reslolve the aligned_ends configuration.
* Adds a traits class to the affine_gap_init_policy to select the proper initiailisation.
* Implements a find_optimum_policy which tracks the optimal score depending on the aligned_ends configuration.
* Adapts the alignment algorithm to check for the optimal score.
* Fixes the CRTP-Base class pattern using private member and befirending the derived class.
* Fixes the CRTP-Base class declaration.
* Fixes some minor warnings.
* Updates documentation of the classes.
=> [FEATURE] Adapts the alignment algorithm to work with the aligned_ends configuration.

include/seqan3/alignment/scoring/gap_scheme.hpp, include/seqan3/alignment/scoring/scoring_scheme_base.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/core/algorithm/all.hpp, include/seqan3/core/algorithm/concept.hpp, include/seqan3/core/algorithm/configuration.hpp, include/seqan3/core/algorithm/configuration_utility.hpp, include/seqan3/core/concept/cereal.hpp, include/seqan3/range/container/bitcompressed_vector.hpp, include/seqan3/range/container/concatenated_sequences.hpp, test/unit/alignment/configuration/align_config_band_test.cpp, test/unit/alignment/configuration/align_config_common_test.cpp, test/unit/alignment/configuration/align_config_gap_test.cpp, test/unit/alignment/configuration/align_config_max_error_test.cpp, test/unit/alignment/configuration/align_config_mode_test.cpp, test/unit/alignment/configuration/align_config_result_test.cpp, test/unit/alignment/configuration/align_config_scoring_test.cpp, test/unit/core/algorithm/configuration_test.cpp, test/unit/core/concept/cereal_test.cpp, test/unit/search/search_configuration_test.cpp
#520
Some renamings for core.
Renames:
config_element_concept -> ConfigElement
cereal_archive_concept -> CerealArchive
cereal_output_archive_concept-> CerealOutputArchive
cereal_input_archive_concept -> CerealInputArchive
cerealisable_concept -> Cerealisable
=> Rename Core Concepts

test/performance/io/CMakeLists.txt, test/performance/io/format_fasta_benchmark.cpp
As you can see in the benchmark, I compare reading and writing of fasta files in seqan2 and seqan3. The results for the same input are (write2 and read2 are referring to seqan2):
write 31715 ns 31715 ns 19368
write2 506 ns 506 ns 1361641
read 38040 ns 38039 ns 18167
read2 2368 ns 2367 ns 300955
So, it looks like seqan3 is slower.
=> Comparison seqan2 and seqan3 for fasta I/O

test/documentation/seqan3_doxygen_cfg.in
For our convenience :nail_care: 
This will enable us to write
```
\tutorial_head{Easy, 30-60 min, @ref setup\, @ref setup,}
```
displaying:
as well as 
```
\assignment{Assignment 2}
1. Extend the minimal example from assignment 1 by a function
`void initialize_argument_parser(seqan3::argument_parser & parser)`.
2. Whithin this function, customize the parser with the following information:
* set the author to your favourite Game of Thrones character (don't have one? really? take "Cercei")
* set the short description to "Aggregate average US. Game of Thrones viewers by season."
* set the version to 1.0.0
* ... set some more if you want to
Hint: Check out the API documentation for seqan3::argument_parser_meta_data and seqan3::argument_parser::info.
3. Try out calling `--help` again and see …
```
=> [DOC] Add custom doxygen commands for the tutorial header, as well as assignment and solution boxes.

test/snippet/CMakeLists.txt
Is this ok?
It works for me and creates targets "[cpp_file_name]_snippet" and the binaries are stored in the directory structure of /doc/. E.g. `doc/tutorial/arg_parse/sol1.cpp` adds the target `sol1_snippet` and the binary appears in the current build directory under `tutorial/arg_parse/sol1_snippet`.
=> [TEST] Add all cpp file in seqan3/doc/ to snippet tests.

include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/std/charconv_detail.hpp, test/unit/argument_parser/format_parse_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp, test/unit/std/charconv_test.cpp
long overdue and also has better handling for "out of range" errors.
=> [MISC] Replace stream operator by std::from_chars for Integral types.

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/argument_parser/exceptions.hpp
From
To
`--export-help` was wrongly documented in one place. 
We need `<b><\b>` tags in a few places since `**\--something**` is not parsed correctly.
=> [DOC,FIX] escape double dash

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/alphabet/gap/gapped.hpp, include/seqan3/range/decorator/gap_decorator_anchor_set.hpp, test/unit/alignment/aligned_sequence_test_template.hpp
Also adds (individual commits)
* is_gapped_alphabet helper and constrains the container functions to the ones with value type seqn3::gapped
* the ungapped sequence_type metafunction
* The assign_ungapped_sequence free function for containers over gapped alphabets.
=> Aligned_sequence_concept - add the assign_ungapped_sequence function

test/documentation/seqan3_doxygen_cfg.in
This PR increases the font size in the doxygen documentation for formulas. 
Currently, their size is significantly lower than the standard font.
=> [DOC] Larger font size for formulas

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/format_parse_test.cpp
The test I added formerly would throw a `cast_conversion` error because it would recognize `--` as the long identifier for the `i` option and then parse `unknown` as the option value.
=> [FIX] argument parsing of option with empty long identifier.

include/seqan3/search/algorithm/detail/search.hpp, include/seqan3/search/fm_index/concept.hpp, test/unit/search/CMakeLists.txt, test/unit/search/fm_index/bi_fm_index_dna4_test.cpp, test/unit/search/fm_index/fm_index_collection_test_template.hpp, test/unit/search/fm_index/fm_index_dna4_test.cpp, test/unit/search/fm_index/fm_index_test_template.hpp, test/unit/search/search_collection_test.cpp
- Indices do not work on `std::string`, but they should (adapt concept to check that the text is a sequence container)
- Search does not work for text collections (define type of results as `size_t` or `std::pair<size_t, size_t>` depending on whether the index is built over a single text or text collection)
Todo:
=> [FIX] Index and Search

include/seqan3/search/fm_index/fm_index.hpp
We also need to store/load the data structures that enable the determination of the position in a text collection
This will be hopefully soon replaced by a way shorter code with cereal
=> [FIX] Also serialise support structures

doc/tutorial/sequence_file/index.md, doc/tutorial/sequence_file/sequence_file_snippets.cpp, doc/tutorial/sequence_file/sequence_file_solution2.cpp, doc/tutorial/sequence_file/sequence_file_solution3.cpp, doc/tutorial/sequence_file/sequence_file_solution4.cpp, doc/tutorial/sequence_file/sequence_file_solution5.cpp, include/seqan3/range/view/get.hpp
Changes to the sequence io tutorial:
- switched the order of the first two sequence file sections -> file formats first, fields second
- removed the all mentions and assignments to "custom fields" (`file{"file.fa", fields<field::ID>}`) 
-> This will be moved to the alignment IO tutorial.
- Introduced a section for the `record _type`. How to access the type member and how to store the records in a vector
- Made the assignments 3, 4 and 5 less time consuming (less not-sequence-file-related c++ coding necessary)
- Added a nice "files as ranges" example: You can easily read paired-end data with a zip view :sparkles:
=>  [DOC] Sequence tutorial 2.0 

doc/tutorial/pairwise_alignment/index.md, doc/tutorial/pairwise_alignment/pa_assignment_2_solution.cpp, doc/tutorial/pairwise_alignment/pa_assignment_3_solution.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/read_mapper/read_mapper_step4.cpp, doc/tutorial/search/search_solution5.cpp, include/seqan3/alignment/configuration/align_config_aligned_ends.hpp, include/seqan3/alignment/configuration/align_config_edit.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, test/snippet/alignment/configuration/align_cfg_aligned_ends_example.cpp, test/snippet/alignment/configuration/align_cfg_edit_example.cpp, test/unit/alignment/configuration/align_config_aligned_ends_test.cpp, test/unit/alignment/configuration/align_config_common_test.cpp, test/unit/alignment/pairwise/alignment_configurator_test.cpp, test/unit/alignment/pairwise/fixture/semi_global_affine_banded.hpp, test/unit/alignment/pairwise/fixture/semi_global_affine_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
Before construction of the end_gaps from lvalues of the end gap specified was not working because of explicit rvalue semantics in the constructor.
Also renames the end gap specifiers and the predefined end gap values to be more consistent with the general naming scheme of the alignment module.
=> [FIX] Fixes construction of end_gaps from lvalues.

test/header/CMakeLists.txt
This is achieved by only testing seqan3 headers by default.
One can enable header tests of external libraries by calling
```
cmake -DSEQAN3_FULL_HEADER_TEST .../seqan3/test/header
```
Which could be used in nightlies.
=> reduce compile time on travis for header tests

test/performance/range/view/view_drop_benchmark.cpp, test/performance/range/view/view_drop_view_take_benchmark.cpp, test/performance/range/view/view_take_benchmark.cpp
I broke the documentation debug nightly builds yesterday 🏆
=> [FIX] out-of-range in random access benchmarks

include/seqan3/range/view/complement.hpp, test/unit/range/view/view_complement_test.cpp
We need to *really* strip the const when checking for the `NucleotideAlphabet` concept.
=> [FIX] Allow view::complement on const containers

include/seqan3/search/algorithm/configuration/max_error.hpp, include/seqan3/search/algorithm/configuration/max_error_rate.hpp, include/seqan3/search/algorithm/detail/search.hpp, include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp, include/seqan3/search/algorithm/detail/search_trivial.hpp, include/seqan3/search/algorithm/search.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, include/seqan3/std/ranges, test/unit/search/search_collection_test.cpp, test/unit/search/search_test.cpp
* Removes deprecated includes
* Switches to range version of `size`, `begin`, `end`
* Adds static_assert to check for compatibility of index and query alphabet (60 lines of trace with a meaningful message in the beginning vs. 600 lines with no clear message)
* Adds overloads for `char const * const` and `std::initializer<char const * const>` that allow searches on string indices for, e.g., `"query"` or `{"query1", "query2"}`
* Adds tests for the overloads
=> [MISC,FEATURE] Allow char* searches in string indices

include/seqan3/search/algorithm/configuration/max_error.hpp, include/seqan3/search/algorithm/configuration/max_error_common.hpp, include/seqan3/search/algorithm/configuration/max_error_rate.hpp, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/concept.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp
This would fix all the warnings for the search module.
* How do we want to document the rule of six? Inline? Or an extra line per element?
* Any special way we want to document type deduction guides? Or do we want to exclude them from the docs?
=> [DOC,FIX] Search module with doxygen 1.8.15

include/seqan3/io/sequence_file/format_fasta.hpp, include/seqan3/io/sequence_file/format_fastq.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/structure_file/format_vienna.hpp, include/seqan3/io/structure_file/input.hpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/structure_file/structure_file_input_test.cpp
=> [FIX] empty sequence files are valid files that result into an empty range.

include/seqan3/argument_parser/auxiliary.hpp, include/seqan3/argument_parser/detail/format_help.hpp, include/seqan3/argument_parser/detail/format_html.hpp, include/seqan3/argument_parser/detail/format_man.hpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/format_html_test.cpp
Instead, the name of the binary has to be set manually in the synopsis definition.
This is necessary for a distinction between app name and binary name which are usually different.
For printing on command line, man or HTML, the first word of the synopsis (detected by the first ' ' or '\t') is still displayed in bold font.
=> argument_parser no longer uses app_name for synopsis.

include/seqan3/argument_parser/validators.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
Created case insensitivity option (optional construction parameter) for file_ext_validator using to_lower view.
Introduced tests for file_ext_validator including case (in-)sensitivity tests.
=> Case (in-)sensitive file extension validator

include/seqan3/core/metafunction/iterator.hpp, include/seqan3/range/detail/inherited_iterator_base.hpp, include/seqan3/range/view/pairwise_combine.hpp, include/seqan3/range/view/take.hpp, include/seqan3/range/view/take_line.hpp, include/seqan3/range/view/take_until.hpp
Resolves #791 
This adds a `iterator_tag_t` metafunction that returns the correct iterator_tag depending on the modelled concept.
This can be used instead of `std::iterator_traits<it_t>::iterator_category` and allows us to use our views (which expect a `iterator_category` and now can automatically deduce it with `iterator_tag_t`) in combination with views from the range library that do not set the `iterator_tag` iff concept support is detected (this is a C++20 behaviour).
=> [FEATURE] iterator_tag_t

include/seqan3/alignment/band/static_band.hpp, include/seqan3/alignment/configuration/align_config_aligned_ends.hpp, include/seqan3/alignment/matrix/alignment_coordinate.hpp, include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp, include/seqan3/alignment/matrix/alignment_trace_matrix.hpp, include/seqan3/alignment/matrix/row_wise_matrix.hpp, include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp, include/seqan3/alignment/pairwise/execution/alignment_range.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_banded_init_policy.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_banded_policy.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_init_policy.hpp, include/seqan3/alignment/pairwise/policy/affine_gap_policy.hpp, include/seqan3/alignment/pairwise/policy/banded_score_dp_matrix_policy.hpp, include/seqan3/alignment/pairwise/policy/banded_score_trace_dp_matrix_policy.hpp, include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp, include/seqan3/alignment/pairwise/policy/unbanded_score_dp_matrix_policy.hpp, include/seqan3/alignment/pairwise/policy/unbanded_score_trace_dp_matrix_policy.hpp
Fix doxygen warnings due to constructor comments for alignment, part I.
=> [MISC] Fix constructor warnings from doxygen alignment I

test/header/CMakeLists.txt, test/include/seqan3/test/performance/units.hpp, test/performance/example/example_benchmark.cpp, test/performance/io/format_fasta_benchmark.cpp, test/seqan3-test.cmake
This introduces convenient functions to represent common measurable units in google/benchmark.
An example is bytes/s, which is introduced in this PR.  We introduce this, because SetBytesProcessed was marked as deprecated in favour for a more general benchmark::Counter approach. (see https://github.com/google/benchmark/pull/654)
In a later PR I will introduce CUPS (cell updates per second) for alignment benchmarks as another common benchmark unit.
=> performance units in benchmarks

include/seqan3/io/alignment_file/format_sam.hpp
Fixes
```
/Users/enricoseiler/git/seqan3/include/seqan3/io/alignment_file/format_sam.hpp:668:54: error: '*((void*)&<anonymous> +4)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
stream << (get<1>(mate).value() + 1) << separator; // SAM is 1 based
```
=> [FIX] Uninitialised warning in SAM format

doc/tutorial/read_mapper/index.md, doc/tutorial/read_mapper/read_mapper_indexer_step3.cpp, doc/tutorial/read_mapper/read_mapper_step2.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/read_mapper/read_mapper_step4.cpp, doc/tutorial/search/index.md, doc/tutorial/search/search_small_snippets.cpp, doc/tutorial/search/search_solution1.cpp, include/seqan3/core/concept/cereal.hpp, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/concept.hpp, include/seqan3/search/fm_index/detail/csa_alphabet_strategy.hpp, include/seqan3/search/fm_index/fm_index.hpp, test/include/seqan3/test/cereal.hpp, test/unit/alignment/gap_scheme_test.cpp, test/unit/alignment/scoring_scheme_test.cpp, test/unit/alphabet/alphabet_test_template.hpp, test/unit/range/container/container_of_container_test.cpp, test/unit/range/container/container_test.cpp, test/unit/search/fm_index/fm_index_collection_test_template.hpp, test/unit/search/fm_index/fm_index_test_template.hpp
Adds cereal support (and equality comparison) for SDSL data structures.
* Adds a test header for cereal tests
* Enables tests for containers using cereal (bitcompressed_vector)
* Enables serialisation via cereal for FM-Index
* Removes `load`/`store` function from FM-Index and FM-Index concept
**TODO**
* Would be nice to have a cereal tutorial or dedicated page on the documentation (other PR)
=> [FEATURE] cereal

test/include/seqan3/test/performance/sequence_generator.hpp, test/include/seqan3/test/performance/units.hpp, test/include/seqan3/test/seqan2.hpp, test/performance/alignment/affine_alignment_benchmark.cpp, test/unit/test/CMakeLists.txt, test/unit/test/seqan2_test.cpp
This PR
* introduces CUPS unit for alignment benchmark
```
2019-02-20 03:19:45
Running ./affine_alignment_benchmark
Run on (8 X 3900 MHz CPU s)
CPU Caches:
L1 Data 32K (x4)
L1 Instruction 32K (x4)
L2 Unified 256K (x4)
L3 Unified 8192K (x1)
Load Average: 1.97, 1.91, 1.75
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------
seqan3_affine_dna4                547784 ns       545909 ns         1122 CUPS=459.786M/s cells=251.001k
seqan2_affine_dna4 …
```
=> Display CUPS in alignments benchmarks

include/seqan3/alphabet/aminoacid/aa20.hpp, include/seqan3/alphabet/aminoacid/aa27.hpp, include/seqan3/alphabet/aminoacid/aminoacid_base.hpp, include/seqan3/alphabet/composition/cartesian_composition.hpp, include/seqan3/alphabet/composition/union_composition.hpp, include/seqan3/alphabet/detail/alphabet_base.hpp, include/seqan3/alphabet/detail/alphabet_proxy.hpp, include/seqan3/alphabet/gap/gap.hpp, include/seqan3/alphabet/mask/mask.hpp, include/seqan3/alphabet/mask/masked.hpp
Fixes for doxygen warning due to uncommented default construction in alphabet part I.
There are some empty constructors, I commented them with empty, hope that is okay.
=> [MISC] Doxygen warning construction fix alphabet I

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/argument_parser/validators.hpp
Missing default comments in argument parser. For deletions, I just added Deleted, if a more specific comment is wanted please tell me what kind of comment in a code review.
=> [MISC] Fix doxygen warnings for default construction argument parser

test/unit/io/stream/debug_stream_test.cpp
At least I did not manage to do it :grimacing: 
Resolves #894 
cppreference says
> A variant may become valueless in the following situations:
>*   (guaranteed) an exception is thrown during the move initialization of the contained value from the temporary in copy assignment
>*   (guaranteed) an exception is thrown during the move initialization of the contained value during move assignment
> *   (optionally) an exception is thrown when initializing the contained value during a type-changing assignment
> *   (optionally) an exception is thrown when initializing the contained value during a type-changing emplace 
I tried this, which from my understanding models the first "guaranteed to be valueless" but it isn't. Did I do somehting wrong?
```cpp
struct make_variant_valueless_helper
{ …
```
=> [FIX] On GCC9 it is not possibly to guarantee to create a valueless variant.

doc/howto/write_a_view/solution_view.cpp, include/seqan3/range/concept.hpp, include/seqan3/range/detail/inherited_iterator_base.hpp, include/seqan3/range/view/drop.hpp, include/seqan3/range/view/slice.hpp, include/seqan3/range/view/take.hpp, include/seqan3/range/view/take_until.hpp, include/seqan3/range/view/view_all.hpp, include/seqan3/search/algorithm/detail/search_trivial.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, include/seqan3/std/span, test/unit/range/view/view_all_test.cpp, test/unit/range/view/view_drop_test.cpp, test/unit/range/view/view_slice_test.cpp, test/unit/range/view/view_take_test.cpp, test/unit/range/view/view_take_until_test.cpp
supersedes #852 
fixes:
* view::drop and view::take only return sub-ranges on ForwardingRanges
* our inherited_iterator_base can now inherit from iterators that are actually pointers (by wrapping them instead of inheriting from them)
* switch more code to use our view::slice instead of ranges::view::slice
=> fixes some issues with view::take / view::drop / view::slice

test/include/seqan3/test/pretty_printing.hpp, test/unit/range/view/view_pairwise_combine_test.cpp, test/unit/test/pretty_printing_test.cpp
I had the problem that defined types in `seqan3::detail` did not use the correct debug_stream overload if they appeared on the right hand side in 
```c++
EXPECT_EQ(seqan3::detail::my_struct{}, seqan3::detail::my_struct{});
```
The left hand side of `EXPECT_EQ` printed fine.
Putting `PrintTo` into the detail namespace solved the problem for me.
=> [fix] make data structures defined in seqan3::detail always pretty printable (in test cases)

include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp
I found an example where local alignments are extended too long, because the optimal score appeared again later and the algorithm chose the long version. This PR fixes this behaviour, such that always the shorter alignment is returned.
=> [FIX] in DP alignment: keep old optimum if current cell score is equal

include/seqan3/io/alignment_file/format_sam.hpp
Resolves #893 
A maybe-uninitialized error only occurs on GCC-8 in release with -fsanitize=undefined
The same code works fine with GCC7 (same flags) and with GCC8 in debug (also with -fsanitize=undefined)...
The following PR is a workaround that make the error vanish.
Do not merge yet, I'll file a bug report and add a link as a commment
=> [FIX] GCC8 bug workaround.

include/seqan3/alphabet/aminoacid/aa10murphy.hpp, include/seqan3/alphabet/aminoacid/all.hpp, test/snippet/alphabet/aminoacid/aa10murphy.cpp, test/unit/alphabet/aminoacid/CMakeLists.txt, test/unit/alphabet/aminoacid/aa10murphy_test.cpp, test/unit/alphabet/aminoacid/aminoacid_conversion_integration_test.cpp
The documentation could still be improved, I guess. Could you maybe take a closer look here and we can then discuss what information needs to be provided for the usage of this alphabet (especially when it comes to the grouping of amino acids and why)?
Besides, I was not sure about the initialization amino acid and whether it is the same as for aa20, so maybe we check this again as well.
=> [FEATURE] Add murphy aa10 alphabet

include/seqan3/alignment/matrix/matrix_concept.hpp
This fixes a doc problem where `relates` makes `seqan3::detail::matrix_inf` not linkable within the documentation.
=> [DOC] correct documentation of seqan3::detail::matrix_inf

include/seqan3/alphabet/cigar/all.hpp, include/seqan3/alphabet/cigar/cigar_op.hpp, test/snippet/alphabet/cigar/cigar_op.cpp, test/unit/alphabet/cigar/CMakeLists.txt, test/unit/alphabet/cigar/cigar_op_test.cpp
Adds the cigar alphabet, starting with cigar_op.
Fixes #887
=> Cigar alphabet

include/seqan3/core/metafunction/iterator.hpp, include/seqan3/std/iterator, include/seqan3/std/ranges
Moves std::ranges::iter_move to iterator header and also adds some documentation for other iterator access functions. 
Adds std::ranges::iter_swap to iterator header.
=> [MISC] Some cleanup of std/ranges and std/iterator header

.jenkinsfile
Hopefully fixes daily crashes of the Docker server.
Alternative is to cancel the old running job:
https://stackoverflow.com/questions/46041579/jenkins-pipeline-milestone-not-cancelling-previous-ongoing-build/48956042#48956042
=> [FEATURE?] Only one build per branch concurrently

.gitmodules
I am not sure why we didn't detect this in travis. Is travis built without cereal in general?
=> [HOTFIX] unbreak master; forgot to change remote for cereal

include/seqan3/core/concept/cereal.hpp, include/seqan3/core/simd/concept.hpp, include/seqan3/core/simd/simd_algorithm.hpp, include/seqan3/core/simd/simd_debug_stream.hpp, include/seqan3/core/simd/simd_traits.hpp, include/seqan3/core/type_list.hpp, include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/output.hpp, include/seqan3/io/detail/record.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/structure_file/input.hpp, include/seqan3/io/structure_file/output.hpp, test/include/seqan3/test/simd_utility.hpp, test/unit/core/concept/cereal_test.cpp, test/unit/core/simd/detail/builtin_simd_test.cpp, test/unit/core/simd/simd_test.cpp
Some concepts which I forgot to change before.
structure_file_input_traits_concept -> StructureFileInputTraits
fields_concept -> Fields
cereal_text_archive_concept -> CerealTextArchive
type_list_concept -> TypeList
simd_concept -> Simd
=> Concept renaming missing II

include/seqan3/range/view/take_until.hpp, test/unit/range/view/view_take_line_test.cpp
=> [FIX] make view::take consume also at the very beginning.

include/seqan3/io/detail/magic_header.hpp, include/seqan3/io/detail/misc_input.hpp
This adds magic header variables for our compression streams. The main reason why we need this is that we need to access the bgzf header at multiple places. Hence, it is safer to bring it into a global variable. Since it would be weird to have this only for bgzf_compression but not the others, I decided to add it for all compression formats.
=> [FEATURE] Adds magic_header to disambiguate compression streams.

include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
It turns out that we don't need this case.
=> [FIX] prev_last_active_cell does not need special attention on score_mask

include/seqan3/alignment/pairwise/edit_distance_fwd.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
Only a small PR that extracts some declarations / definitions out of a file. This is needed, because a next PR will introduce a score and trace matrix class, which need a forward declaration of  the edit distance algorithm.
=> [FEATURE] add forwards for edit_distance

include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
This makes the return type part of the class declaration, and makes the call interface more similar  to the general alignment algorithm.
=> [MISC] make result_value_type a type within the class; edit_distance

include/seqan3/search/algorithm/configuration/max_error_rate.hpp, test/header/CMakeLists.txt
<s>**Blocked by** https://github.com/xxsds/sdsl-lite/pull/66</s>
Now that the SDSL passes the header tests, we can re-enable the header tests for the search module.
=> [INFRA] Enable header tests for search module

include/seqan3/alphabet/composite/alphabet_variant.hpp, include/seqan3/alphabet/gap/gapped.hpp, test/snippet/alphabet/composite/alphabet_variant.cpp, test/unit/alphabet/gap/gapped_test.cpp, test/unit/range/decorator/gap_decorator_anchor_set_test.cpp
The current behaviour of the alphabet variant for assigning characters was to only query the `rank_to_char` table and leave all other characters to rank 0. Ambiguous character representations were resolved to the first alphabet.
This caused unintuitive behaviour for e.g. `gapped<dna15>`: assigning an unknown character resolved to `gap` (which resolves to `N` for dna15 otherwise) and `a` is treated as an unknown character although it is usually converted to the uppercase character for the other nucleotides.
This PR fixes this behaviour by using the rank_to_char behaviour of the first alphabet.
=> Fix alphabet_variant behaviour of from_char()

include/seqan3/alignment/pairwise/alignment_configurator.hpp
@h-2 You are first to review; @rrahn is second to review!
With this alignment compiles with gcc9 with and without `-std=c++2a`
=> [FIX] alignment_configurator for gcc9

include/seqan3/core/algorithm/concept.hpp, include/seqan3/core/algorithm/configuration.hpp, include/seqan3/core/platform.hpp, include/seqan3/core/pod_tuple.hpp, include/seqan3/core/tuple_utility.hpp
This PR improves the SeqAn documentation in the core module and removes all 61 warnings from the doxygen build.
=> [FIX] Doxygen warnings in Core Module

include/seqan3/range/view/take.hpp, test/unit/range/view/view_take_test.cpp
=> [FIX] make take_exactly shrink on pur input ranges.

build_system/seqan3-config.cmake
The idea is to add extra code to the feature detection of the file system that creates symbols that are unknown during linkage if `-lstdc++fs` is not set.
=> [INFRA] fix filsystem issues with gcc-8 on travis

include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/input_format_concept.hpp, include/seqan3/io/alignment_file/output.hpp, include/seqan3/io/alignment_file/output_format_concept.hpp, include/seqan3/io/detail/ignore_output_iterator.hpp, include/seqan3/io/detail/in_file_iterator.hpp, include/seqan3/io/detail/out_file_iterator.hpp, include/seqan3/io/record.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/sequence_file/input_format_concept.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/sequence_file/output_format_concept.hpp, include/seqan3/io/stream/concept.hpp, include/seqan3/io/structure_file/input.hpp, include/seqan3/io/structure_file/input_format_concept.hpp, include/seqan3/io/structure_file/output.hpp, include/seqan3/io/structure_file/output_format_concept.hpp
This PR improves the SeqAn documentation in the io module and removes all 383 warnings from the doxygen build.
=> [FIX] Doxygen warnings in I/O Module

include/seqan3/range/container/aligned_allocator.hpp, include/seqan3/range/container/bitcompressed_vector.hpp, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/range/container/small_vector.hpp, include/seqan3/range/decorator/gap_decorator_anchor_set.hpp, include/seqan3/range/detail/inherited_iterator_base.hpp, include/seqan3/range/detail/misc.hpp, include/seqan3/range/detail/random_access_iterator.hpp, include/seqan3/range/view/pairwise_combine.hpp, include/seqan3/range/view/repeat.hpp, include/seqan3/range/view/take.hpp, include/seqan3/range/view/take_until.hpp
This PR improves the SeqAn documentation in the range module and removes all 134 warnings from the doxygen build.
=> [FIX] Doxygen warnings in Range Module

include/seqan3/range/view/persist.hpp, include/seqan3/range/view/take.hpp, include/seqan3/range/view/take_until.hpp, include/seqan3/std/ranges, test/unit/range/view/view_char_to_test.cpp, test/unit/range/view/view_complement_test.cpp, test/unit/range/view/view_convert_test.cpp, test/unit/range/view/view_deep_test.cpp, test/unit/range/view/view_drop_test.cpp, test/unit/range/view/view_get_test.cpp, test/unit/range/view/view_kmer_hash_test.cpp, test/unit/range/view/view_persist_test.cpp, test/unit/range/view/view_rank_to_test.cpp, test/unit/range/view/view_slice_test.cpp, test/unit/range/view/view_take_line_test.cpp, test/unit/range/view/view_take_test.cpp, test/unit/range/view/view_take_until_test.cpp, test/unit/range/view/view_to_char_test.cpp, test/unit/range/view/view_to_lower_test.cpp, test/unit/range/view/view_to_rank_test.cpp, test/unit/range/view/view_to_upper_test.cpp, test/unit/range/view/view_translation_test.cpp, test/unit/range/view/view_trim_test.cpp
fixes #915 
Since the views from the range library are still implicitly convertible, I might have missed a case or two, but we can fix that when upstream changes or we have a C++20 implementation to test against.
None of our views are implicitly convertible anymore.
=> [FEATURE] introduce ranges::to; remove implicit conversions

include/seqan3/range/container/concept.hpp, test/unit/range/container/container_concept_test.cpp
This reverts commit 5ba75261f785259adf8b49e0cf41ce818f481e8a.
And resolves #264 
---
Edit:// this is still failing: The reason is that gcc-7 for 14.04 is compiled with disabling dual abi, see #264 for more information.
Edit:// rechecked 2019-06-05
=> Partially Revert "[FIX] travis/ubuntu16.04: gcc-7.2 bug"

test/documentation/seqan3.css
@h-2 This improves the is_char table and multiple `#include ...` at the top of the file.
You may want to check out the branch and see if this also fixes stuff for FreeBSD.
=> [DOC] Adapt doxygen css for inline code.

include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp, include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/alignment/pairwise/align_result_selector.hpp, include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/alignment_result.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, include/seqan3/range/decorator/gap_decorator.hpp, test/unit/alignment/pairwise/align_result_selector_test.cpp, test/unit/alphabet/gap/gapped_test.cpp, test/unit/range/decorator/gap_decorator_test.cpp
To prevent copies for the returned alignment, we now use the gap decorator to store only the positions of the gaps. This is possible if the input sequences model `SizedRange` and `RandomAccessRange`. If these requirements are not met, we instead copy the sequences into vectors of gapped sequence (as before).
Fixes #888
=> [FEATURE] use gap decorator as alignment return type whenever possible

include/seqan3/alphabet/detail/alphabet_proxy.hpp, include/seqan3/alphabet/nucleotide/rna4.hpp, include/seqan3/core/platform.hpp, include/seqan3/range/container/bitcompressed_vector.hpp, test/unit/range/container/container_concept_test.cpp
fixes #764 
added a fix to #679 as well
=> [FIXES-#764] bitcompressed_vector's reference type should always be a proxy

include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, test/unit/alignment/pairwise/align_pairwise_test.cpp, test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
@rrahn I already talked this over with you, that the general pairwise algorithm returns non-inclusive `back_coordinate`s and that the edit distance returns inclusive `back_coordinate`s.
It is desirable to have non-inclusive back coordinates and inclusive front coordinates, because with that one can express empty intervals. This PR makes `back_coordinate`s non-inclusive and resolves a discrepancy between the general and edit alignment algorithm.
As an example for non-inclusive:
https://github.com/seqan/seqan3/blob/81a1cb9f7ec99d1f87b88213bc959bb5b81f416a/test/unit/alignment/pairwise/fixture/global_affine_banded.hpp#L48-L58
And an example for inclusive:
https://github.com/seqan/seqan3/blob/81a1cb9f7ec99d1f87b88213bc959bb5b81f416a/test/unit/alignment/pairwise/fixture/global_edit_distance_unba …
=> [FIX] edit distance returns correct back coordinate

include/seqan3/argument_parser/detail/version_check.hpp
=> [FIX] Pressing return should default the version check.

include/seqan3/range/view/take.hpp, test/unit/range/view/view_take_test.cpp
Tests for this bug(-fix) will come with @smehringer 's generic iterator tests or we will decide to remove const-iterability for view altogether.
=> [FIX] take_view should be Sized if underlying range is Sized

include/seqan3/argument_parser/detail/version_check.hpp
Currently, the version server is offline. This leads to timeouts of the version_debug|release_test.
In general I think the server request should not take longer than 10s. So I set a timeout on the request call.
fixes #1091
=> [MISC] Add 10s timeout to server calls.

include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/fm_index.hpp, test/unit/search/fm_index/fm_index_collection_test_template.hpp
=> [FIX] Incorrect copy/move of fm_index

include/seqan3/alphabet/detail/convert.hpp, include/seqan3/io/alignment_file/format_bam.hpp, include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/alignment_file/header.hpp, include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/output.hpp, test/unit/io/alignment_file/alignment_file_format_test_template.hpp, test/unit/io/alignment_file/format_bam_test.cpp, test/unit/io/alignment_file/format_sam_test.cpp
1. BAM needs to write `*\0` for empty read ids (not `\0` like right now, which did not impede our files since they are equivalent but for samtools those are not equivalent)
2. SAM should not have requirements on types it does not use. (This way you could also pass std::ignore to the file)
3. The read id alphabet should not be modifiable by the traits object since there is no use case other than `char` (container is modifiable) and char is required by BAM. (Is this an API break?)
=> [FIX] 3 minor changes in alignment IO

include/seqan3/alphabet/concept.hpp, include/seqan3/alphabet/nucleotide/concept.hpp
For usability reasons I chose to implement some contraints in the CPO definitions as static_asserts. This has turned out to be a mistake, because it means that checking `seqan3::Alphabet` will result in a hard error if one of the constraints are satisfied, but the static_assert fails.
I have also simplified some of the documentation.
@joergi-w Once this is merged, could you perform similar changes for quality and structure?
=> [FIX] include all constraints in CPO definitions

doc/tutorial/alphabet/alphabet_gc_content.cpp, doc/tutorial/argument_parser/basic_parser_setup.cpp, doc/tutorial/argument_parser/disable_version_check.cpp, doc/tutorial/argument_parser/small_snippets.cpp, doc/tutorial/argument_parser/solution1.cpp, doc/tutorial/argument_parser/solution3.cpp, doc/tutorial/argument_parser/solution4.cpp, doc/tutorial/argument_parser/solution5.cpp, doc/tutorial/argument_parser/solution6.cpp, doc/tutorial/concepts/custom_validator_solution2.cpp, doc/tutorial/introduction/introduction_argument_parser.cpp, doc/tutorial/introduction/introduction_read_fasta.cpp, doc/tutorial/ranges/range_solution4.cpp, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/auxiliary.hpp, include/seqan3/argument_parser/detail/version_check.hpp, test/unit/argument_parser/argument_parser_design_error_test.cpp
Addresses several things of #1101 
Best reviewd commit by commit.
=> Fix security issues of the argument parser

include/seqan3/alignment/matrix/edit_distance_score_matrix_full.hpp, include/seqan3/core/bit_manipulation.hpp, test/snippet/core/detail/count_leading_zeros.cpp, test/snippet/core/detail/count_trailing_zeros.cpp, test/snippet/core/detail/most_significant_bit_set.cpp, test/snippet/core/detail/popcount.cpp, test/unit/core/bit_manipulation_test.cpp
~~The SDSL functions are not constexpr yet. Since we only support GCC they are currently never used.~~
[~~SDSL PR~~](https://github.com/xxsds/sdsl-lite/pull/68) - merged
=> [FEATURE] Add lzcnt, tzcnt, popcount

README.md
Alternatively we could also link to `https://github.com/seqan/seqan3/blob/master/LICENSE.md`
The [provided link](https://github.com/seqan/seqan3/LICENSE.md) doesn't work
=> [FIX] License link in README

test/unit/range/iterator_test_template.hpp
Uses the iterator type returned from the test range instead of
TypeParam. It cannot always be ensured that the TypeParam is the
iterator type to test.
=> [MISC] Update iterator test template

include/seqan3/contrib/stream/bgzf_stream_util.hpp, include/seqan3/core/char_operations/predicate_detail.hpp, include/seqan3/core/platform.hpp, include/seqan3/io/detail/magic_header.hpp, test/seqan3-test.cmake
Resolves #1096
Unit tests with GCC9 Debug and -funsigned-char work for me 
Building on ppc (Debug, GCC8) also works
---
We add `-DNO_WARN_X86_INTRINSICS` for tests to silence the following error from a system header:
```
#ifndef NO_WARN_X86_INTRINSICS
/* This header is distributed to simplify porting x86_64 code that
makes explicit use of Intel intrinsics to powerpc64le.
It is the user's responsibility to determine if the results are
acceptable and make additional changes as necessary.
Note that much code that uses Intel intrinsics can be rewritten in
standard C or GNU C extensions, which are more portable and better
optimized across multiple targets.
In the specific case of X86 SSE (__m128) intrinsics, the PowerPC
VMX/VSX ISA is a good match for vector float SIMD operations.
However …
```
=> [FIX, FEATURE] Add PPC Support

test/coverage/CMakeLists.txt
This stackoverflow post suggest that ubuntu16.04 has problems with non-absolute paths https://stackoverflow.com/questions/37675961/error-while-code-coverage-report-using-lcov
This error was fixed upstreams https://github.com/linux-test-project/lcov/commit/632c25a0d1f5e4d2f4fd5b28ce7c8b86d388c91f.
But it seem to be fixed between version 1.13 and 1.14. Ubuntu 16.04 still has 1.12 so it might fix our sporadic problem.
=> [INFRA] attempt to fix coverage failings on travis

include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/argument_parser/detail/version_check.hpp, test/unit/argument_parser/argument_parser_design_error_test.cpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/format_html_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
1. Windows command was not terminated by a semicolon :see_no_evil: 
2. The following is invalid should throw directly when calling `add_positional_option` not when calling `parse()`.
```cpp
std::vector<int> listA;
whatever_type optionB;
myparser.add_positional_option(listA, ...);
myparser.add_positional_option(optionB, ...); // only the last positional option may be a list (ambigiousness)
myparser.parse() // current implementation throws an design_error here, not when adding the option
```
3. Options that are set as `option_spec::REQUIRED` should not print a default value on the help page. Since positional_options are always required, they should never have a default. Except the very last positional option that might be a list and can be empty (thus is not required).
@h-2 I think we …
=> 5 small argument parser fixes

test/unit/io/alignment_file/alignment_file_format_test_template.hpp, test/unit/io/alignment_file/format_bam_test.cpp, test/unit/io/alignment_file/format_sam_test.cpp
This also drastically reduces LOC and makes the test more readable.
=> [TEST] alignment file io: make detail test public tests.

include/seqan3/alphabet/nucleotide/all.hpp, include/seqan3/alphabet/nucleotide/dna3bs.hpp, test/snippet/alphabet/nucleotide/dna3bs.cpp, test/snippet/alphabet/nucleotide/dna3bs_literal.cpp, test/unit/alphabet/nucleotide/CMakeLists.txt, test/unit/alphabet/nucleotide/dna3bs_test.cpp
This PR introduces the reduced nucleotide alphabet dna3bs that can be used when working with bisulfite converted data. The alphabet has only three letters (A, G and T) where every C gets treated as a T.
This produces of course ambiguities when thinking about the complement. Practically, it is anyways not recommended to use the complement of this alphabet (as explained in the docs). However, for completeness and in order to fulfill the nucleotide concept we introduced a complement here were T is the complement of both A and G.
=> [Feature] Add dna3bs alphabet

build_system/seqan3-config.cmake
fixes #1193 #1199
It's strange that we didn't see this earlier. I know that for macOS we don't need to explicitly add it. Apparently FreeBSD also doesn't need it, but we should have seen this on Debian, or not? Maybe not all Linuxes are affected. In any case, the proposed fix is the recommended way of doing it with CMake nowadays.
=> [FIX] fix detection of pthread on some linuxes

CHANGELOG.md, include/seqan3/alignment/pairwise/align_result_selector.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/core/algorithm/configuration.hpp, include/seqan3/core/algorithm/configuration_utility.hpp, include/seqan3/core/all.hpp, include/seqan3/core/concept/tuple.hpp, include/seqan3/core/tuple_utility.hpp, include/seqan3/core/type_list.hpp, include/seqan3/core/type_list/all.hpp, include/seqan3/core/type_list/traits.hpp, include/seqan3/core/type_list/type_list.hpp, include/seqan3/io/alignment_file/input_format_concept.hpp, include/seqan3/io/alignment_file/output_format_concept.hpp, include/seqan3/io/detail/misc.hpp, include/seqan3/io/record.hpp, include/seqan3/io/sequence_file/input_format_concept.hpp, include/seqan3/io/sequence_file/output_format_concept.hpp, include/seqan3/io/structure_file/input_format_concept.hpp, include/seqan3/io/structure_file/output_format_concept.hpp, test/documentation/DoxygenLayout.xml, test/documentation/seqan3_doxygen_cfg.in, test/snippet/core/algorithm/for_each_type_list.cpp, test/unit/alignment/scoring_scheme_test.cpp, test/unit/alphabet/aminoacid/aminoacid_conversion_integration_test.cpp, test/unit/alphabet/nucleotide/nucleotide_conversion_integration_test.cpp, test/unit/core/algorithm/parameter_pack_test.cpp, test/unit/core/simd/detail/builtin_simd_test.cpp, test/unit/core/type_list_test.cpp, test/unit/core/type_traits/template_inspection_test.cpp
This is our own meta library with almost identical interfaces for dealing with seqan3::type_list, but also parameter packs (it's usually faster to work on the latter).
Currently available:
* at (linear-time)
* front
* back
* concat
* drop (linear-time)
* drop_front (constant)
* drop_last (linear-time)
* take (linear-time)
* take_last (linear-time)
* take (linear-time)
* split_after (linear-time)
Notably absent:
* drop_back because it's not possible to do in constant time without integer_sequence and a whole lot instantiaten. Actually, back was already tricky! @rrahn: You could have a look at this after we merge this, or you could just use drop_front on your example and move the `void` to the top and the commas to the front.
=> [FEATURE] our own meta library

include/seqan3/alphabet/detail/hash.hpp, include/seqan3/range/container/dynamic_bitset.hpp
This moves `operator()` into the `hash` struct.
E.g. [this one](https://docs.seqan.de/seqan/3-master-dev/group__alphabet.html#ga71cc78e9e1652f0a8b92a70726775b57).
=> [DOCS] Small fix to std::hash docs

README.md, doc/setup/quickstart_cmake/index.md
`--recursive` is deprecated.
The [git docs](https://git-scm.com/docs/git-clone/2.22.0) list `--recurse-submodules` as only option since 2.13.2 (about two years ago).
=> [DOCS] Encourage use of --recurse-submodules over --recursive

.jenkinsfile
In order to avoid eating up the memory of the docker host.
=> [INFRA] Delete workspace at end of build.

CHANGELOG.md, include/seqan3/range/container/bitcompressed_vector.hpp, include/seqan3/range/container/concatenated_sequences.hpp, test/unit/range/container/container_of_container_test.cpp
* Adds `raw_data()` for `bitcompressed_vector` and allows access of the underlying SDSL vector.
* Renames `data()` to `raw_data()` in `concatenated_sequences` since `data()` implies contiguous memory locations.
* `small_vector` and `small_string` have `data()` and are contiguous, ergo no changes here.
=> [FIX] Add data access for containers

test/unit/argument_parser/format_parse_validators_test.cpp
Resolves #1211
Ping @mr-c
You can read/write/execute files as root user even if all permissions are revoked.
E.g.
```bash
sudo bash
touch file
chmod 000 file
echo "Hello World" >> file
cat file
```
=> [FIX] Do not test file permissions when running as root

CHANGELOG.md, doc/tutorial/read_mapper/read_mapper_step2.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/read_mapper/read_mapper_step4.cpp, doc/tutorial/search/search_small_snippets.cpp, doc/tutorial/search/search_solution1.cpp, include/seqan3/search/algorithm/detail/search.hpp, include/seqan3/search/algorithm/detail/search_trivial.hpp, include/seqan3/search/algorithm/search.hpp, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/concept.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/unit/search/fm_index/bi_fm_index_aa27_test.cpp, test/unit/search/fm_index/bi_fm_index_char_test.cpp, test/unit/search/fm_index/bi_fm_index_dna4_test.cpp, test/unit/search/fm_index/fm_index_collection_test_template.hpp, test/unit/search/fm_index/fm_index_dna4_test.cpp, test/unit/search/fm_index/fm_index_test_template.hpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test.cpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp, test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp, test/unit/search/search_collection_test.cpp, test/unit/search/search_test.cpp
=> [MISC] Add alphabet type template to fm_index

include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/detail/in_file_iterator.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/structure_file/input.hpp, test/unit/io/alignment_file/alignment_file_format_test_template.hpp, test/unit/io/alignment_file/format_bam_test.cpp, test/unit/io/alignment_file/format_sam_test.cpp, test/unit/io/detail/in_file_iterator_test.cpp, test/unit/io/sequence_file/sequence_file_input_test.cpp
Resolves #1232
I included a test in sequence file input. 
Alignment file cannot be tested since there are no input options yet.
Structure file already has a test for truncate_ids which would fail if the public API is tested instead of the detail test with format. This will be changed in the next PR so I would refrain from already changing it now.
=> [FIX] Buffer the first record when calling begin instead of at construction.

include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/detail/CMakeLists.txt, test/unit/argument_parser/detail/format_man_test.cpp
Adds two tests, one for a bare bones parser and another for a fully fleshed parser.
=> [TEST] Add coverage tests for format_man.hpp

CHANGELOG.md, doc/howto/subcommand_argument_parser/index.md, doc/howto/subcommand_argument_parser/subcommand_arg_parse.cpp, doc/tutorial/argument_parser/index.md, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_help.hpp, include/seqan3/argument_parser/detail/format_html.hpp, include/seqan3/argument_parser/detail/format_man.hpp, test/documentation/DoxygenLayout.xml, test/unit/argument_parser/argument_parser_design_error_test.cpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/version_check_test.hpp, test/unit/argument_parser/format_parse_test.cpp
=> [FIX, FEATURE] Fix initialising the version_check_option. Add multi-level argument parsing.

include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp, include/seqan3/alignment/matrix/debug_matrix.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, test/unit/alignment/matrix/debug_matrix_test.cpp, test/unit/alignment/pairwise/edit_distance/global_edit_distance_max_errors_unbanded_test.cpp, test/unit/alignment/pairwise/edit_distance/global_edit_distance_unbanded_test.cpp, test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp, test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_unbanded_test.cpp, test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
This PR will fix
* don't seg-fault on empty sequences (resolves #1111)
* Fixes and tests some bugs with debug_matrix where you can't combine transformation-operations.
=> [FIX] empty sequences for edit_distance

.travis.yml, include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp, include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp, include/seqan3/alphabet/alphabet_base.hpp, include/seqan3/alphabet/aminoacid/translation.hpp, include/seqan3/alphabet/composite/alphabet_tuple_base.hpp, include/seqan3/alphabet/composite/alphabet_variant.hpp, include/seqan3/alphabet/detail/alphabet_proxy.hpp, include/seqan3/alphabet/mask/mask.hpp, include/seqan3/alphabet/structure/dot_bracket3.hpp, include/seqan3/alphabet/structure/dssp9.hpp, include/seqan3/alphabet/structure/structured_rna.hpp, include/seqan3/alphabet/structure/wuss.hpp, include/seqan3/argument_parser/validators.hpp, include/seqan3/core/char_operations/predicate_detail.hpp, include/seqan3/core/pod_tuple.hpp, include/seqan3/core/simd/view_to_simd.hpp, include/seqan3/range/container/bitcompressed_vector.hpp, include/seqan3/range/views/kmer_hash.hpp, include/seqan3/search/fm_index/fm_index.hpp
Resolves #754
The more esoteric stuff:
* After opening a group, there usually needs to be a new line unless the documentation comment style changes from line (`//!`) to block (`/*!`) or vice versa. A member also cannot be documented in the same documentation block as the group was opened in.
* If an entire function is excluded via `//!\cond`, we cannot `//!\cond` the requires clause since we did not close the last `//!\cond` block that uses the same condition (in this case no condition).
* In `alphabet/aminoacid/translation.hpp` I needed to change the template parameter name to help doxygen resolve the function signature. Otherwise there would be two functions with the same signature (parameter name does not count, parameter template does count) and it would only take the last overload …
=> [FIX,DOC] Doxygen 1.8.16 warnings

include/seqan3/core/type_list/traits.hpp, test/unit/core/type_list_test.cpp
These should help you replace the meta:: stuff.
Note that our `find_if` behaves like our `find` and not like `meta::find_if`, i.e. it returns the position of the first type that matches. 
So the following:
```cpp
using component_type = meta::front<meta::find_if<component_list, detail::implicitly_convertible_from<indirect_component_type>>>;
```
would be replaced by 
```cpp
static constexpr bool pos =
list_traits::find_if<detail::implicitly_convertible_from<indirect_component_type>::invoke,
component_list>;
using component_type = list_traits::at<pos, component_list>;
```
possibly:
```cpp
static constexpr bool pos =
list_traits::find_if<detail::implicitly_convertible_from<indirect_component_type>::template invoke,
component_list>;
using component_type = list_traits::at<pos, component_list>; …
```
=> [FEATURE] more type list algorithms

include/seqan3/search/algorithm/detail/search_trivial.hpp, test/unit/search/search_scheme_algorithm_test.cpp, test/unit/search/search_test.cpp
2019-03-26 16:23:30
Running ./search_benchmark
Run on (4 X 3400 MHz CPU s)
CPU Caches:
L1 Data 32K (x2)
L1 Instruction 32K (x2)
L2 Unified 256K (x2)
L3 Unified 4096K (x1)
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
Benchmark | Time | CPU | Iterations
-- | -- | -- | --
  |   |   |  
old trivial_search |   |   |  
unidirectional_search_sim_e1/1 | 25852 ns | 25861 ns | 26683
unidirectional_search_sim_e1/2 | 278612 ns | 278715 ns | 2587
unidirectional_search_sim_e1/3 | 3190970 ns | 3192138 ns | 219
unidirectional_search_e3/1 | 3199463 ns | 3200661 ns | 217
unidirectional_search_e3/2 | 2908445 ns | 2909513 ns | 229
unidirectional_search_e3/3 | 2852047 ns | 2853116 ns | 218
  |   |   |  
modified trivial_search |   |   | …
=> [FEATURE] Improve trivial_search

include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/sequence_file/format_genbank.hpp, include/seqan3/io/sequence_file/format_sam.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/structure_file/format_vienna.hpp, test/performance/io/format_fasta_benchmark.cpp, test/unit/io/alignment_file/format_sam_test.cpp, test/unit/io/sequence_file/sequence_file_format_embl_test.cpp, test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp, test/unit/io/sequence_file/sequence_file_format_fastq_test.cpp, test/unit/io/sequence_file/sequence_file_format_genbank_test.cpp, test/unit/io/sequence_file/sequence_file_format_sam_test.cpp, test/unit/io/sequence_file/sequence_file_format_test_template.hpp, test/unit/io/structure_file/format_vienna_test.cpp
The restructuring "detail -> public" and a test template **halved the LOC** !
---
* **commit 1: Fix truncate_id option for genbank format.**
The genebank format did not handle the truncate_ids option correctly (It always truncated ids after the first space).
* **commit 2: Fix structured_seq handling to also throw if sequence and structure differ in length..**
The vienna format did only check for equal length in sequence and structure if the seq_type did not decay to std::ignore. It is legal though to read in a structured_seq object (alphabet tuple) in which case seq_type decays to ignore but the same length should still be checked.
* **commit 3: sequence file sam format now truncates ids if specified..**
The sequence file sam format did not handle the truncate_ids option correctly (It …
=> [FIX, FEATURE] Fixes some formats and restructures test: detail -> public

test/unit/alphabet/alphabet_constexpr_test_template.hpp
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91607
=> [FIX] ICE in constexpr alphabet tests

include/seqan3/std/span
=> [FIX] visibility errors on gcc - std

CHANGELOG.md, doc/tutorial/argument_parser/solution6.cpp, include/seqan3/argument_parser/validators.hpp, test/snippet/argument_parser/validators_2.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
Part of #1196 
I noticed that you cannot construct a value_list_validator from a simple range (only from a vector or initialiser list). I added construction from a range, as well as construction from a parameter pack which makes initialiser lists obsolete, but this is an API break. @seqan/core Should I still provide an initialiser list constructor?
Also: where in the changelog did we report API changes?
```cpp
// What worked before and still works now:
std::vector<int> v{0, 1, 2};
seqan3::value_list_validator{v}; // l/rvalue std::vector 
// What works now that hasn't worked before:
seqan3::value_list_validator{0, 1, 2}; // parameter pack
seqan3::value_list_validator{v | views::take(2)}; // ranges/views
// What worked before but does not work anymore:
seqan3::value_list_validator{{0, 1, …
```
=> [MISC] Change value_list_validator construction.

test/include/seqan3/test/simd_utility.hpp
If the surrounding context of this macro adds a variable called left or right an internal compiler error will be triggered. So we rename the variables to reduce the chance that this occurs.
=> [MISC] Change the naming of the  structured binding variables

include/seqan3/range/views/translate.hpp, test/unit/range/views/view_translate_test.cpp
fixes #1339
(does this need double review?)
=> [FIXES-1339] avoid underflow for input of size 0 and 1

include/seqan3/io/alignment_file/format_sam.hpp, test/unit/io/alignment_file/format_sam_test.cpp
=> [FIX] Wrong soft clipping values for short cigar strings of length two was fixed.

include/seqan3/alignment/pairwise/execution/execution_handler_parallel.hpp, include/seqan3/alignment/pairwise/execution/execution_handler_sequential.hpp
Resolves  Issue #1308
Added interface that takes underlying range of sequence pairs and executes a callback on the results.
The proposed function`execution_handler.execute(config, start_id, [(s1,s2),...],callback)` was changed to 
`execution_handler.execute(config, [(id, s1,s2),...],callback)` to simply the usage of this function.
in execution_handler_sequential.
Example call for this function in include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp can be found here:
https://github.com/svnbgnk/seqan3/tree/range_for_execution_handler_test
=> Range awareness for execution handler.

CHANGELOG.md, include/seqan3/search/fm_index/fm_index.hpp, test/unit/search/search_collection_test.cpp
=> [FIX] Missing queries in single element text collections

include/seqan3/alignment/pairwise/execution/execution_handler_parallel.hpp, include/seqan3/alignment/pairwise/execution/execution_handler_sequential.hpp, test/unit/alignment/pairwise/execution/execution_handler_template.hpp
=> [FEATURE] Forward call of indexed sequence pairs to alignment algorithm.

include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/std/algorithm
The builder can be used iff
* You know the bitvector size
* You know the number of `1`s you want to set
* The positions of the `1`s are in a strictly increasing order
Since we actually fulfil all these requirements, we can use the builder.
This already reduces the memory footprint by a little bit - you do not need to allocate a bitvector of size `text_size` ( a vector using `text_size/8` many bytes).
This may be more noticeable for bigger texts since the allocation will take longer. Since I only measured memory peak, it's hard to tell exactly (the other steps use way more memory).
We can get rid of the copy from `std::vector<uint8_t>` to `sdsl::int_vector<8>`.
Note that we need to do a `std::ranges::reverse(tmp_text);` afterwards.
The alternative would be to do a …
=> [FEATURE] Reduce memory footprint of FM-indices over text collections

include/seqan3/alignment/scoring/detail/simd_matrix_scoring_scheme.hpp, test/unit/alignment/scoring/CMakeLists.txt, test/unit/alignment/scoring/simd_matrix_scoring_scheme_test.cpp
Along with appropriate test file.
Follows similar structure to #1332.
Does not yet fully satisfy #1352. Still need to use gather in score and other optimizations.
Resolves #1352
=> [FEATURE] Add a simd vectorised scoring scheme which uses scoring matricies

test/include/seqan3/test/tmp_filename.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
MSys64-MinGW-gcc8.3 comes with a working filesystem. No more need of Boost (https://github.com/seqan/seqan3/pull/515).
Still some problems: 
```
template <typename T>
class istream : public ::testing::Test
{};
inline std::string const uncompressed{"The quick brown fox jumps over the lazy dog"};
TYPED_TEST_CASE_P(istream);
TYPED_TEST_P(istream, concept_check)
{
EXPECT_TRUE((IStream<TypeParam, char>));
}
```
produce:
```
[ 44%] Built target gz_ostream_test
[ 44%] Building CXX object core/CMakeFiles/tuple_utility_test.dir/tuple_utility_test.cpp.obj
In file included from C:/Prog/ExtLib/cmake-seqan3-unit-build-release/vendor/googletest/googletest/include/gtest/gtest.h:67,
from C:\Prog\ExtLib\seqan3\test\unit\contrib\stream\gz_istream_test.cpp:8: …
```
=> Testing with MSys64-MinGW-gcc8.3

include/seqan3/range/container/aligned_allocator.hpp, test/unit/range/container/aligned_allocator_test.cpp
* Uses operator new and delete instead of aligned_alloc.
=> [FIX] Fixes aligned allocator issue for non posix implementation of aligned_alloc.

include/seqan3/range/container/aligned_allocator.hpp
[N3536](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3536.html#new.delete.single) states 
> Requires: size shall equal that used to allocate ptr.
Hence, we deallocate only `1/sizeof(value_type)` of the bytes
```
[ RUN      ] aligned_allocator.memory_alignment
=================================================================
==20221==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x6040000008d0 in thread T0:
object passed to delete has wrong type:
size of the allocated type:   40 bytes;
size of the deallocated type: 10 bytes.
```
=> [FIX] Memory leak in aligned_allocator

include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp, test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp
**TASK: check if value type `simd_type` is working in two_dimensional_matrix**
----
Fixes #1300 .
=> Test that two-dimensional matrix is simd aware.

test/performance/io/CMakeLists.txt, test/performance/io/format_vienna_benchmark.cpp
Adds performance tests for the Vienna structure format.
Note: The run time for SeqAn2 is significantly slower, because the structure representation is a graph instead of a string over the wuss alphabet.
Resolves #1392.
=> [TEST] Performance test for Vienna format

CHANGELOG.md, doc/tutorial/concepts/custom_validator_solution1.cpp, doc/tutorial/concepts/custom_validator_solution2.cpp, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/validators.hpp
You may not do the things you are doing in the signature of the requires expression, because their validity depends on the result of the requires expression.
This leads to hard-failure for types that would normally soft-fail. Since the concept is checked on globally defined `operator|` this can lead to all sorts of view-resolution failures to land here and hard-fail.
@sarahet Please check if this removes the first error.
=> [FIX] don't hard-fail on concept check

include/seqan3/core/simd/simd.hpp
It makes more sense to give the backend without any template parameters, because they are independent of them.
This PR affects no tests, because we don't test the backend feature, yet.
=> [MISC] make simd_backend a template template in simd_type defintion.

include/seqan3/core/simd/view_to_simd.hpp, test/performance/core/simd/view_to_simd_chunk_benchmark.cpp, test/snippet/core/simd/view_to_simd.cpp, test/unit/core/simd/view_to_simd_test.cpp
Before this change the last chunk always had a size of simd_traits<simd_t>::length, which caused some issues when dealing with the last chunk, since the last elements in the transformed sequence might not have carried any information anymore if the size of the longest sequence was not a multiple of the simd size. Instead, the new code tracks the end of the last column in the final chunk and returns a span that only covers the sequences.
=> [FEATURE] Make the final chunk only as long as the longest sequence in the collection.

build_system/seqan3-install.cmake, build_system/seqan3-package.cmake
This PR adds a description of which files should be installed and packaged.
We use the structure as proposed in debian, that means
* install documentation in `/share/doc/seqan3/*`
* install cmake scripts in `/share/cmake/seqan3/*`
* install seqan3 header files in `/include/seqan3/*`
* install external header (submodules) in `/include/seqan3/submodules/<submodule>/include/*`
This PR fixes #1387
*/CC:* @mr-c
=> [INFRA] automate installing and packaging of seqan3

test/unit/alignment/pairwise/fixture/global_affine_unbanded.hpp, test/unit/alignment/pairwise/global_affine_unbanded_collection_simd_test.cpp, test/unit/alignment/pairwise/global_affine_unbanded_collection_test.cpp, test/unit/alignment/pairwise/global_affine_unbanded_test.cpp, test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
* Adds more tests for the global alignment. These tests will be reused to test collections with parallel and vectorised execution.
* Adds tests for corner cases, e.g. aligning against empty sequences.
* Renamed the test fixtures to better compare them.
* Removed the global using declaration for seqan3 namespaces.
=> [DOC] Add more tests for global alignment.

test/performance/core/bit_manipulation_benchmark.cpp, test/performance/core/char_operations/char_predicate_benchmark.cpp, test/performance/example/example_benchmark.cpp, test/performance/range/gap_decorator_seq_write_benchmark.cpp, test/performance/range/views/view_all_benchmark.cpp, test/performance/range/views/view_drop_benchmark.cpp, test/performance/range/views/view_drop_view_take_benchmark.cpp, test/performance/range/views/view_take_until_benchmark.cpp
Through copy-paste `State&` instead of `State &` is found in many benchmarks.
=> Adjustment to style guide (space before &)

CHANGELOG.md, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/concept.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/unit/search/fm_index/fm_index_collection_test_template.hpp, test/unit/search/fm_index/fm_index_test_template.hpp
=> [MISC] Rename the index char_type to alphabet_type.

include/seqan3/range/views/take_until.hpp
This adaptor wrongly defined two operators. This led to amiguity because subsumption between view and viewable_range does not work right with the Concepts TS.
=> [FIX] overload ambiguity

include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp, include/seqan3/alignment/pairwise/policy/all.hpp, include/seqan3/alignment/pairwise/policy/simd_find_optimum_policy.hpp, include/seqan3/alignment/scoring/detail/simd_match_mismatch_scoring_scheme.hpp, include/seqan3/alignment/scoring/detail/simd_matrix_scoring_scheme.hpp, test/unit/alignment/pairwise/alignment_configurator_test.cpp, test/unit/alignment/pairwise/global_affine_unbanded_collection_simd_test.cpp
Fixes #1443
Allows the computation of the vectrorised global alignment score and end coordinate when the sequences in one batch have a different size.
Adds a new find_optimum policy that is simd aware and uses an additional state to find the optimum for each algorithm.
=> [FEATURE] Enable vectorised alignment for different sized sequences.

include/seqan3/core/platform.hpp, include/seqan3/core/simd/detail/builtin_simd_intrinsics.hpp, include/seqan3/core/simd/detail/simd_algorithm_avx2.hpp, include/seqan3/core/simd/detail/simd_algorithm_avx512.hpp, include/seqan3/core/simd/detail/simd_algorithm_sse4.hpp, include/seqan3/core/simd/simd_algorithm.hpp, test/seqan3-test.cmake
This fixes the platform issues when x86 intrinsics (#1381) are not available, like on arm or powerpc.
The main idea is to always forward declare each simd_algorithm for each instruction set, e.g. load_sse4, load_avx2, load_avx512.
If the instruction set is available we define the forward declared algorithm, e.g. load_avx2.
Note: We forward declare for example load_avx2 s.t. we can use the name load_avx2 inside of the simd::load function regardless of whether avx2 intrinsics are available or not. We guarantee in simd::load that load_avx2 will only be invoked if the instruction set provides avx2 or higher (via constexpr, but each constexpr branch needs to contain valid c++ code).
=> [MISC] Do not use x86 intrinsics if not available.

CHANGELOG.md, build_system/seqan3-config.cmake
This PR improves two things:
* Accept any case in find_package(seqAN3)
* We now use the standard way (`find_package_handle_standard_args`) to tell `find_package` if the package was found or not (code reduction).
=> [INFRA] accept any case in find_package(sEqAn3)

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp
use `insert_gap` in alignment_trace_algorithms correctly since it didn't work for `gap_decorators`
This may be an example for a `[[nodiscard]]` attribute :)
=> [FIX] use insert_gap correctly

test/performance/io/CMakeLists.txt, test/performance/io/lowlevel_stream_input_benchmark.cpp
benchmarks our low-level stream iterators.
Results on my machine:
```
--------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations
--------------------------------------------------------------------------------
consume_all<tag::std_stream_it>         19824654 ns     19824114 ns           35
consume_all<tag::std_streambuf_it>       4323320 ns      4322811 ns          164
consume_all<tag::seqan3_streambuf_it>    1343993 ns      1343994 ns          522
consume_all<tag::seqan2_stream_it>       1112598 ns      1112590 ns          637
```
=> [TEST] add benchmarks for stream iterators

include/seqan3/range/views/async_input_buffer.hpp
noexceptness depends on the value_type, because a value of the value_type is held as member. This also means that only value_types are supported that are default-constructible, maybe it would be better to wrap the member into a semiregular-optional-thingy.
I have made a card for this.
=> [FIX] remove explicit noexcept from rule-of-5

test/seqan3-test.cmake, test/unit/alignment/pairwise/alignment_range_test.cpp
```
/home/travis/build/seqan/seqan3/test/unit/alignment/pairwise/alignment_range_test.cpp:68:37: error: ‘constexpr bool testing::internal::InstantiateTypedTestCase_P_IsDeprecated()’ is deprecated: INSTANTIATE_TYPED_TEST_CASE_P is deprecated, please use INSTANTIATE_TYPED_TEST_SUITE_P [-Werror=deprecated-declarations]
68 | INSTANTIATE_TYPED_TEST_CASE_P(alignment_range_iterator,
|                                     ^~~~~~~~~~~~~~~~~~~
In file included from /home/travis/build/seqan/seqan3-build/vendor/googletest/googletest/include/gtest/gtest.h:62,
from /home/travis/build/seqan/seqan3/test/unit/alignment/pairwise/alignment_range_test.cpp:8:
/home/travis/build/seqan/seqan3-build/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:1230:16: note: declared here
1230 | constexpr …
```
=> [FIX] deprecation warning

include/seqan3/core/detail/type_inspection.hpp, test/unit/core/detail/type_inspection_test.cpp
It was broken for const-ness and references which both weren't tested...
=> [FIX] type printing for references

include/seqan3/argument_parser/detail/version_check.hpp, test/unit/argument_parser/detail/version_check_debug_test.cpp, test/unit/argument_parser/detail/version_check_release_test.cpp, test/unit/argument_parser/detail/version_check_test.hpp
In #1428 we hit a limit with the current way of handling parallel executions of the version checker. This PR should once for all solve this problem.
=> Allow parrallel execution of version checker test

include/seqan3/core/simd/detail/builtin_simd_intrinsics.hpp
#1407 solved the issue not to use x86 intrinsics if they aren't available. One part of the fix was to detect if the `x86intrin.h` header can be included.
It turns out that on powerpc this `x86intrin.h` header is defined to make porting form x86 more easy and triggers a warning when included. In our case this is not good, because warnings are hard failures in our setup. 
This PR should fix that once for all :sunglasses: 
```log
from /scratch/local/seiler/nightly-builds/src/include/seqan3/alignment/pairwise/policy/all.hpp:17,
from /scratch/local/seiler/nightly-builds/src/include/seqan3/alignment/pairwise/alignment_configurator.hpp:25,
from /scratch/local/seiler/nightly-builds/src/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
from …
```
=> [FIX] don't include x86intrin.h on powerpc

include/seqan3/io/alignment_file/format_bam.hpp
The header has a well defined byte size and is not appended with a \0 character.
The tests will follow with the PR #1470. This is a cerry-pick of one commit within.
=> [FIX] Fixes read header in bam format.

include/seqan3/io/alignment_file/format_bam.hpp
The l_read_name size needs to be truncated at byte 254 to reserve one byte for the trailing '\0' character. This was hard to read from the code before. In addition, this refactoring removes one max computation. 
The tests will follow with the PR #1470. This is a cerry-pick of one commit within.
=> [MISC] Improve the l_read_name size computation.

include/seqan3/io/alignment_file/format_bam.hpp
When the quality string has not the same size as the sequence a format_error should be thrown instead of an assertion.
Cherry-picked from #1470
=> [FIX] Throw exception instead of assertion

CHANGELOG.md, README.md, include/seqan3/core/platform.hpp, include/seqan3/std/span
=> Update range library to 0.10.0

build_system/seqan3-config.cmake
Handle `CMAKE_REQUIRED_QUIET` like most other `FindMyModule.cmake` do and follow naming scheme used in cmake.
=> [INFRA] some cmake maintenance 

test/unit/argument_parser/detail/format_html_test.cpp
This needs to be merged before bumping the version s.t. no test breaks
=> [MISC] Exchange hard coded seqan version in html test with seqan3::seqan3_version.

include/seqan3/range/views/kmer_hash.hpp
Appeared when using kmer hash on a span
=> [FIX] Fix member difference_type for views::kmer_hash to use a type trait.

doc/tutorial/pairwise_alignment/index.md, include/seqan3/alignment/matrix/all.hpp, include/seqan3/alphabet/adaptation/char.hpp, include/seqan3/alphabet/adaptation/uint.hpp, include/seqan3/alphabet/all.hpp, include/seqan3/io/alignment_file/header.hpp, include/seqan3/io/alignment_file/input.hpp
Resolves all ticked parts of #1027 (#1424 is resolving two of these):
Resolves:
Resolved by #1424:
Additionally:
(cherry picked from commit 0fdbfc142daaa17da7a94bfacb6e7dd4e7464516)
=> [DOC] fix documentation issues #1027

test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp
```
/seqan3/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp: In instantiation of ‘std::vector<T> create_matrix_storage() [with score_type = __vector(1) int; seqan3::detail::matrix_major_order order = seqan3::detail::matrix_major_order::row]’:
/seqan3-build/gcc-10-std17-debug/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:460:40:   recursively required from ‘gtest_suite_iterator_fixture_::compare_geq<seqan3::detail::two_dimensional_matrix<__vector(1) int, std::allocator<__vector(1) int>, seqan3::detail::matrix_major_order::column> >::compare_geq()’
/seqan3-build/gcc-10-std17-debug/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:460:40:   required from ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() …
```
=> [TEST] two_dimensional_matrix_test use original fix again

include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp, include/seqan3/alignment/pairwise/policy/simd_find_optimum_policy.hpp
```
/seqan3/test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp:76:38:   required from ‘void gtest_suite_pairwise_alignment_collection_test_::front_coordinate<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = pairwise_alignment_fixture<(& seqan3::test::alignment::collection::global::affine::unbanded::dna4_01)>]’
/seqan3/test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp:66:1:   required from here
/seqan3/include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp:95:53: error: declaration of template parameter ‘class score_t’ with different constraints
95 |     template <typename other_alignment_algorithm_t, typename score_t, typename is_local_t>
|                                                     ^~~~~~~~
In file included …
```
=> [FIX] forward declare must use the same declaration

include/seqan3/search/fm_index/concept.hpp
```
In file included from /seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp:22,
from /seqan3-build/header-git-std17/seqan3_header_test_files/seqan3/search/algorithm/detail/search_scheme_algorithm-2.cpp:2:
/seqan3/include/seqan3/search/fm_index/concept.hpp:158:74: error: expected ‘;’ before ‘}’ token
158 |     requires requires (typename t::index_type const index) { { t(index) } };
|                                                                          ^~
|                                                                          ;
```
=> [FIX] add ; after requires expression

include/seqan3/alignment/matrix/alignment_coordinate.hpp
```
In file included from /seqan3/include/seqan3/alignment/pairwise/align_result_selector.hpp:20,
from /seqan3/include/seqan3/alignment/pairwise/edit_distance_fwd.hpp:17,
from /seqan3/include/seqan3/alignment/matrix/edit_distance_trace_matrix_full.hpp:18,
from /seqan3/test/unit/alignment/matrix/edit_distance_trace_matrix_full_test.cpp:10:
/seqan3/include/seqan3/alignment/matrix/alignment_coordinate.hpp:92:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T, class U> concept const bool std::same_as<T, U>’
92 |         requires !std::same_as<other_state, state>
|                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [FIX] enums shouldn't be used with same_as

include/seqan3/alignment/scoring/scoring_scheme_concept.hpp
Fixes gcc10 error:
```
In file included from /seqan3/include/seqan3/alignment/configuration/align_config_scoring.hpp:18,
from /seqan3/include/seqan3/alignment/configuration/align_config_edit.hpp:17,
from /seqan3/test/unit/alignment/configuration/align_config_edit_test.cpp:10:
/seqan3/include/seqan3/alignment/scoring/scoring_scheme_concept.hpp:61:16: error: a variable concept cannot be constrained
61 | SEQAN3_CONCEPT scoring_scheme = requires (t scheme,
|
```
=> [MISC] scoring scheme: concept template paramater can't be constrained

include/seqan3/range/container/small_vector.hpp, test/unit/range/container/small_string_test.cpp
Fixes
```
/seqan3/test/unit/range/container/small_string_test.cpp: In member function ‘virtual void small_string_equality_Test::TestBody()’:
/seqan3/test/unit/range/container/small_string_test.cpp:249:49: error: no match for ‘operator==’ (operand types are ‘seqan3::small_string<4>’ and ‘seqan3::small_string<5>’)
249 |     constexpr bool cmp3 = small_string{"hell"}  == small_string{"hello"};
|                           ~~~~~~~~~~~~~~~~~~~~  ^~ ~~~~~~~~~~~~~~~~~~~~~
|                           |                        |
|                           small_string<4>          small_string<5>
In file included from /seqan3/include/seqan3/range/container/small_string.hpp:15,
from /seqan3/test/unit/range/container/small_string_test.cpp:14: …
```
=> [MISC] remove restraints on comparison operators of small string

test/snippet/alignment/matrix/debug_matrix_score.cpp, test/snippet/alignment/matrix/debug_matrix_trace.cpp, test/snippet/alignment/matrix/detail/alignment_matrix_column_major_range_base.cpp, test/snippet/alphabet/nucleotide/sam_dna16.cpp, test/snippet/alphabet/quality/phred42_literal.cpp, test/snippet/alphabet/quality/phred63_literal.cpp, test/snippet/alphabet/quality/phred68legacy_literal.cpp, test/snippet/alphabet/structure/structured_rna.cpp, test/snippet/argument_parser/argument_parser_1.cpp, test/snippet/argument_parser/argument_parser_2.cpp, test/snippet/core/simd/simd_extract.cpp, test/snippet/core/simd/simd_load.cpp, test/snippet/core/simd/simd_transpose.cpp, test/snippet/core/simd/simd_upcast.cpp, test/snippet/range/container/small_string.cpp
& replace std::endl with ‘\n‘.
Resolves #1466 .
=> [TEST] Remove 'using namespace seqan3' from test/snippet

include/seqan3/std/charconv
`charconv` uses `std::ostringstream`, but does not include it's header, see https://en.cppreference.com/w/cpp/io/basic_ostringstream.
https://github.com/seqan/seqan3/blob/979df093f202e14253df48fd489d70e3162362a5/include/seqan3/std/charconv#L875-L877
=> [FIX] add sstream to charconv

include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp
```
In file included from /seqan3/include/seqan3/alignment/matrix/detail/trace_iterator.hpp:15,
from /seqan3/test/unit/alignment/matrix/detail/trace_iterator_test.cpp:13:
/seqan3/include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp: In instantiation of ‘class seqan3::detail::trace_iterator_base<seqan3::detail::trace_iterator<seqan3::detail::two_dimensional_matrix<seqan3::detail::trace_directions>::iterator_type<seqan3::detail::two_dimensional_matrix<seqan3::detail::trace_directions> > >, seqan3::detail::two_dimensional_matrix<seqan3::detail::trace_directions>::iterator_type<seqan3::detail::two_dimensional_matrix<seqan3::detail::trace_directions> > >’:
/seqan3/include/seqan3/alignment/matrix/detail/trace_iterator.hpp:32:7:   required from ‘class …
```
=> [FIX] trace_iterator_base: use same constraints

include/seqan3/core/char_operations/predicate_detail.hpp
```
seqan3/include/seqan3/core/char_operations/predicate_detail.hpp:162:1: error: 'char_predicate_base' defined as a struct template here but previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
struct char_predicate_base
^
seqan3/include/seqan3/core/char_operations/predicate_detail.hpp:94:1: note: did you mean struct here?
class char_predicate_base;
^~~~~
struct
```
Part of `clang10-support` #1556
=> [FIX] clang10: struct / class should be the same in all declarations

test/unit/argument_parser/argument_parser_design_error_test.cpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/detail/format_html_test.cpp, test/unit/argument_parser/detail/format_man_test.cpp, test/unit/argument_parser/detail/version_check_test.hpp, test/unit/argument_parser/format_parse_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
& replace std::endl with ‘\n‘.
Resolves #1514
=> [MISC] Remove 'using namespace seqan3' from test/unit/argument_parser

test/documentation/seqan3.css
Resolves #1567
**FROM**
**TO**
But also
**FROM**
**TO**
=> [DOC] Allow linebreaks in long template parameters

CHANGELOG.md, CMakeLists.txt, doc/setup/quickstart_cmake/index.md
Add a top-level CMakeLists.txt which exposes seqan3 targets (by calling `find_package(SeqAn3)`), defines `make install` of the seqan3 header-only library and defines how to package seqan3.
This resolves #1387.
=> [INFRA] Add top level CMakeLists.txt

include/seqan3/core/type_list/traits.hpp
Part of `clang10-support` #1556
=> [FIX] initialise std::type_identity in type_list traits

.travis.yml, include/seqan3/alphabet/composite/alphabet_tuple_base.hpp, include/seqan3/alphabet/structure/structured_aa.hpp, include/seqan3/io/stream/iterator.hpp
Resolves #1499 :
- Doxygen warnings fixed triggered by version update 1.8.16 -> 1.8.17.
- Removed gbump, because it is never used.
=> [FIX] Doxygen warnings fixed triggered by version update to 1.8.17

test/unit/range/iterator_test_template.hpp
Original gcc 10 error:
```
In file included from /seqan3/test/unit/alignment/matrix/detail/alignment_score_matrix_one_column_test.cpp:17:
/seqan3/test/unit/alignment/matrix/detail/../../../range/iterator_test_template.hpp: In instantiation of ‘void gtest_suite_iterator_fixture_::concept_check<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = inner_iterator]’:
/seqan3/test/unit/alignment/matrix/detail/../../../range/iterator_test_template.hpp:64:1:   required from here
/seqan3/test/unit/alignment/matrix/detail/../../../range/iterator_test_template.hpp:70:28: error: static assertion failed: The reference types of begin_iterator and expected_range must be equality comparable. If they are not, you may specify a custom void expect_eq(i1, r2) function in the fixture.
70 | …
```
=> [TEST] Fix concept of HasExpectEqualMemberFunction in iterator_test_template

include/seqan3/std/algorithm, test/include/seqan3/test/performance/sequence_generator.hpp, test/performance/search/CMakeLists.txt, test/performance/search/index_construction_benchmark.cpp
benchmark construction of fm- and bi-fm-index and compare with seqan2
resolves #1566
=> [TEST] Index Benchmark

include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp, test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp
One step to fix issue #1598.
The sequence builder uses internally a pair to represent a sequence alignment that will be implicitly converted to a std::tuple in the final returned result.
=> [MISC] aligned_sequence_builder should use std::tuple instead of std::pair

CHANGELOG.md, include/seqan3/search/dream_index/all.hpp, include/seqan3/search/dream_index/interleaved_bloom_filter.hpp, test/include/seqan3/test/cereal.hpp, test/performance/search/CMakeLists.txt, test/performance/search/dream_index/CMakeLists.txt, test/performance/search/dream_index/interleaved_bloom_filter_benchmark.cpp, test/snippet/search/dream_index/interleaved_bloom_filter_bulk_contains.cpp, test/snippet/search/dream_index/interleaved_bloom_filter_constructor.cpp, test/snippet/search/dream_index/interleaved_bloom_filter_constructor_compressed.cpp, test/snippet/search/dream_index/interleaved_bloom_filter_emplace.cpp, test/snippet/search/dream_index/interleaved_bloom_filter_increase_bin_number_to.cpp, test/unit/search/dream_index/CMakeLists.txt, test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
Blocked by ~#933~
Resolves #1562
TODO:
=> [FEATURE] binning_directory

doc/tutorial/alignment_file/index.md, doc/tutorial/alphabet/index.md, doc/tutorial/concepts/index.md, doc/tutorial/introduction/index.md, doc/tutorial/ranges/index.md, doc/tutorial/read_mapper/index.md, doc/tutorial/sequence_file/index.md
Fixes https://github.com/seqan/seqan3/issues/1608 1.0.1
Makes is easier for the user to keep well-arranged notes on where exactly that useful information is explained / snippet can be found.
=> [DOC] Use consistent naming/numbering of assignments in tutorial

test/unit/alignment/matrix/alignment_coordinate_test.cpp, test/unit/alignment/matrix/alignment_optimum_test.cpp, test/unit/alignment/matrix/debug_matrix_test.cpp, test/unit/alignment/matrix/debug_stream_alignment_coordinate_test.cpp, test/unit/alignment/matrix/debug_stream_debug_matrix_test.cpp, test/unit/alignment/matrix/debug_stream_trace_directions_test.cpp, test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp, test/unit/alignment/matrix/detail/alignment_matrix_base_test_template.hpp, test/unit/alignment/matrix/detail/alignment_matrix_column_major_range_test.cpp, test/unit/alignment/matrix/detail/alignment_score_matrix_one_column_banded_test.cpp, test/unit/alignment/matrix/detail/alignment_score_matrix_one_column_test.cpp, test/unit/alignment/matrix/detail/alignment_trace_matrix_full_banded_test.cpp, test/unit/alignment/matrix/detail/alignment_trace_matrix_full_test.cpp, test/unit/alignment/matrix/detail/simulated_alignment_test_template.hpp, test/unit/alignment/matrix/detail/trace_iterator_banded_test.cpp, test/unit/alignment/matrix/detail/trace_iterator_test.cpp, test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp, test/unit/alignment/matrix/edit_distance_matrix/edit_distance_score_matrix.hpp, test/unit/alignment/matrix/edit_distance_matrix/edit_distance_trace_matrix.hpp, test/unit/alignment/matrix/edit_distance_matrix/trace_matrix_unbanded_global_max_errors_test.cpp, test/unit/alignment/matrix/edit_distance_matrix/trace_matrix_unbanded_global_test.cpp, test/unit/alignment/matrix/edit_distance_matrix/trace_matrix_unbanded_semi_global_max_errors_test.cpp, test/unit/alignment/matrix/edit_distance_matrix/trace_matrix_unbanded_semi_global_test.cpp
Resolves #1623. 
I could not remove
```cpp
using namespace seqan3::test::alignment::fixture;
```
, because it would have become very confusing. I moved and commented the line instead. If you have a better idea, I'll be happy to take it.
=> [MISC] Remove 'using namespace seqan3' from test/unit/alignment/matrix.

include/seqan3/search/configuration/all.hpp, include/seqan3/search/configuration/detail.hpp, include/seqan3/search/configuration/max_error.hpp, include/seqan3/search/configuration/max_error_rate.hpp, include/seqan3/search/configuration/mode.hpp, include/seqan3/search/fm_index/all.hpp, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/fm_index.hpp
Some small fixes for the search documentation, some spelling errors, some formatting (table correctly aligned), some missing definitions added and death links corrected.
=> [DOC] Fixes in doc

include/seqan3/std/charconv, include/seqan3/std/concepts
This PR imports `std::floating_point` into `seqan3/std/concepts`. We use that
concept in `seqan3/std/charconv` to remove dependencies of seqan3 in the std
headers.
Our `seqan3/std/*` headers (shim/polyfill headers) should not include anything
from seqan3 to avoid build failures like missing includes if the standard
headers are available.
Fixes partially #1678
=> [FIX] use std::floating_point instead of seqan3::floating_point

test/unit/argument_parser/format_parse_validators_test.cpp
In these case it is not necessary to use `seqan3::views::take`.
=> [TEST] use std::views::take instead of seqan3::views::take

CHANGELOG.md, include/seqan3/argument_parser/argument_parser.hpp, include/seqan3/argument_parser/detail/format_base.hpp, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/detail/format_help_test.cpp, test/unit/argument_parser/format_parse_validators_test.cpp
Fixes  #1175
The following functions accept a `seqan3::argument_parser::option_spec::ADVANCED` to control what is displayed on the (advanced) help page:
* `seqan3::argument_parser::add_section`
* `seqan3::argument_parser::add_subsection`
* `seqan3::argument_parser::add_line`
* `seqan3::argument_parser::add_list_item`
Note that other `seqan3::argument_parser::option_spec`s like `REQUIRED` are ignored.
=> [FEATURE] Adding information only to the advanced help pages is now possible.  

include/seqan3/argument_parser/detail/format_parse.hpp, include/seqan3/io/stream/iterator.hpp, include/seqan3/std/charconv
Our `seqan3/std/*` headers (shim/polyfill headers) should not include anything
from seqan3 to avoid build failures like missing includes if the standard
headers are available.
Fixes partially #1678
=> [FIX] don't use seqan3::is_char in std/charconv

include/seqan3/io/alignment_file/all.hpp, include/seqan3/io/sequence_file/all.hpp, include/seqan3/io/sequence_file/input.hpp, include/seqan3/io/sequence_file/output.hpp, include/seqan3/io/structure_file/input.hpp, include/seqan3/io/structure_file/output.hpp, test/unit/range/container/container_of_container_test.cpp
These changes resolve issue #[1610](https://github.com/seqan/seqan3/issues/1610).
I removed all 
- #pragma GCC diagnostic push
- #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
- #pragma GCC diagnostic pop
In the file seqan3/test/unit/range/container/container_of_container_test.cpp, I removed the whole paragraph although I'm not 100% sure if that was right.
All tests ran properly.
=> [I/O,MISC] Remove #pragma GCC diagnostics

doc/tutorial/alignment_file/alignment_file_snippets.cpp, include/seqan3/core/debug_stream.hpp
This commit adds `aligned_sequence_concept.hpp` to`debug_stream.hpp` and removes unnecessary includes of `aligned_sequence_concept.hpp` in snippets and Documentation.
Due to problems with the Documentationtests on my laptop, I did not check if the Documentationtests still work properly.
Fixes #1647
=> [DOC,MISC] add aligned_sequence_concept.hpp to debug_stream.hpp

include/seqan3/search/algorithm/detail/search.hpp
Small refactoring that removes unnecessary code and thereby avoids possible inconsistencies between types.
=> [MISC] search: Use decltype on result_type to avoid inconsistencies.

include/seqan3/search/algorithm/detail/search.hpp
Instead of sorting and "uniquifying" the added locations from each cursor. All result are uniquifying at once.
=> [FIX] sort all hits and remove duplicates once

doc/tutorial/alignment_file/index.md, include/seqan3/io/alignment_file/all.hpp, include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/output.hpp
These were hard to keep consistent
=> [DOC] io: DRY doc of shared content between alignment input and output.

include/seqan3/range/views/detail.hpp, test/unit/range/views/adaptor_base_test.cpp
Fixes the constructor of the combined range adaptor closure object. Before it could not be called in a constexpr context, even though it should. Also the forward declarations where useless  because the tempalte parameters came from the class defintion and not the constructor so if the type was not explicitly set to an reference type (which I don't see how it should happen) it was always a copy of the closure objects. Which is also fine in this context I believe.
=> [FIX] Fixes the constructor of the combined range closur adaptor.

include/seqan3/core/type_traits/basic.hpp, include/seqan3/core/type_traits/function.hpp, test/unit/core/type_traits/function_test.cpp
There are some cyclic dependencies when function pulls in some other headers from core type traits.
Since the macro works in general for all expressions it is better suited in the basic header of type_traits.
Part of #1692
=> [MISC] Move is_constexpr into type_traits basic.

test/include/seqan3/test/performance/sequence_generator.hpp, test/performance/alignment/CMakeLists.txt, test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
Resolves #1574 
Adds benchmarks for vectorised global alingment.
Here are the results from my local benchmark with SSE4.
```console
Running ./alignment/global_affine_alignment_simd_benchmark
Run on (8 X 2600 MHz CPU s)
CPU Caches:
L1 Data 32K (x4)
L1 Instruction 32K (x4)
L2 Unified 262K (x4)
L3 Unified 6291K (x1)
Load Average: 2.92, 2.99, 3.08
----------------------------------------------------------------------------------------------------------------------
Benchmark                                                            Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------------------
seqan3_affine_dna4_simd<score>/0/real_time                     7600672 ns      7558451 ns …
```
=> [TEST] Adds performance test for vectorised global alingment.

test/unit/range/views/adaptor_base_test.cpp
Minor fix to resolve to correct include. The error was not seen, since `views/detail.hpp` also pulls in `type_traits/basic.hpp` but this should be fixed in order to prevent issues later.
=> [FIX] Correct header include in adaptor_base_test

include/seqan3/alignment/pairwise/align_result_selector.hpp, include/seqan3/alignment/pairwise/alignment_algorithm.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp
Some minor change to be more consistent with naming style.
=> [MISC] Use more appropriate suffix _type for type aliases defined in alignment traits.

test/unit/search/search_configuration_test.cpp, test/unit/search/search_test.cpp
The search test was often just testing if two configurations which are semantically the same also result in the same `search()` result. This is a lot of overhead in the search test. 
Instead, I added configuration tests and removed the redundant search tests.
=> [TEST] Add max_error(_rate) configuration test and remove redundant search tests

include/seqan3/alignment/pairwise/alignment_result.hpp, test/unit/alignment/pairwise/alignment_result_test.cpp
Adds a transformation trait to access the result value type of the alingment result class.
This change is part of seqan3 #1692.
In addition it fixes the documentation of the alignment result class.
=> Pass result to alignment/add transformation trait to get alignment result value type

test/unit/alphabet/adaptation/char_test.cpp, test/unit/alphabet/adaptation/uint_test.cpp, test/unit/alphabet/alphabet_cereal_test.cpp, test/unit/alphabet/alphabet_hash_test.cpp, test/unit/alphabet/aminoacid/aa10li_test.cpp, test/unit/alphabet/aminoacid/aa10murphy_test.cpp, test/unit/alphabet/aminoacid/aa20_test.cpp, test/unit/alphabet/aminoacid/aa27_test.cpp, test/unit/alphabet/aminoacid/aminoacid_conversion_integration_test.cpp, test/unit/alphabet/aminoacid/aminoacid_test_template.hpp, test/unit/alphabet/aminoacid/aminoacid_translation_test.cpp, test/unit/alphabet/cigar/cigar_op_test.cpp, test/unit/alphabet/cigar/cigar_test.cpp, test/unit/alphabet/cigar/debug_stream_cigar_test.cpp, test/unit/alphabet/composite/alphabet_tuple_base_test.cpp, test/unit/alphabet/composite/alphabet_tuple_base_test_template.hpp, test/unit/alphabet/composite/alphabet_variant_detail_test.cpp, test/unit/alphabet/composite/alphabet_variant_test.cpp, test/unit/alphabet/composite/composite_integration_test.cpp, test/unit/alphabet/quality/qualified_test.cpp
=> [MISC] remove using namespace seqan3/test/unit/alphabet/a*-c*

include/seqan3/range/views/kmer_hash.hpp
For the minimiser view (#1654) I had problems preserving the forward_range properties, changing the tag in the kmer hash from input range to iterator_tag solved this problem.
=> [FIX] Iterator Tag in kmer_hash

include/seqan3/core/type_traits/function.hpp, test/snippet/core/type_traits/function_traits.cpp, test/unit/core/type_traits/basic_test.cpp, test/unit/core/type_traits/function_test.cpp
Adds a traits class to evaluate properties of std::function objects such as the return type or the type of the arguments. 
This is a part of #1692, which will in the end remove the dependency to call make_result_type at various different places with potentially different types and thereby causing unforseen issues.
=> Pass result to alignment/add function traits

include/seqan3/alignment/pairwise/align_result_selector.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp, include/seqan3/alignment/pairwise/edit_distance_fwd.hpp, include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, test/performance/alignment/edit_distance_unbanded_benchmark.cpp, test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
So it works to pass in the callback function.
Part of #1692
This change has no further implications as only an internal implementation is adapted which is wrapped by a specific calling interface.
=> [MISC] Disable auto deduction of traits type in unbanded edit distance algorithm

include/seqan3/alignment/pairwise/detail/type_traits.hpp, test/unit/alignment/pairwise/detail/CMakeLists.txt, test/unit/alignment/pairwise/detail/type_traits_test.cpp
Part of #1692 
Allows to extract the respective parameters for the returned function object wrapping the alignment algorithm. This allows later to determine the actual result type from the passed callback and decouples the configuration from the implementation of the algorithm.
=> Pass result to alignment/add alignment function traits

doc/tutorial/sequence_file/index.md, doc/tutorial/sequence_file/sequence_file_snippets.cpp, test/snippet/io/sequence_file/sequence_file_input_record_iter.cpp
Resolves part of #1608
Combination of small fixes:
[DOC] 1.6.1 Remove 'TODO' in warning.
[DOC] 1.6.2 fix typo in file extension member 'file_extensions'
[DOC] 1.6.3 Remove "using seqan3::get;"
[DOC] 1.6.4 Use 'std::accumulate' in snippet
=> [DOC] Improve tutorial section 'Sequence file I/O'

doc/tutorial/pairwise_alignment/index.md, doc/tutorial/pairwise_alignment/pairwise_alignment_solution_3.cpp
Resolves part of #1608 
Combination of small fixes:
- [DOC] 1.7.1 Fix grammar error
- [DOC] 1.7.2 Use consistent naming of variables
- [DOC] 1.7.4 Improve working of task description Assignment 2
- [DOC] 1.7.5 Use the same variable in task and solution
- [DOC] 1.7.8 Change name of second Assignment 5 to Assignment 6
- [DOC] 1.7.6 Remove unnecessary utility include
- [DOC] 1.7.7 Be more explicit on header includes
- [DOC] 1.7.0 Fix width of image "align_transcript.png"
For "1.7.0 Fix width of image 'align_transcript.png' ":
Before:
After:
=> [DOC] Improve tutorial section 'Computing pairwise alignments'

include/seqan3/search/configuration/max_error.hpp, include/seqan3/search/detail/search.hpp, include/seqan3/search/detail/search_common.hpp, test/unit/search/search_configuration_test.cpp
This also gets rid of dependencies on ranges.
=> [MISC] Remove unnecessary template arguments from search_cfg::max_error.

include/seqan3/argument_parser/validators.hpp, test/unit/argument_parser/format_parse_validators_test.cpp
=> [MISC] argument parser: Move get_help_message to file_validator_base.

include/seqan3/io/detail/magic_header.hpp, include/seqan3/std/span
Extracted from PR #1702 to make this change better trackable.
Do we need a changelog entry for this?
=> [MISC] Use correct definition of std::span<T, E> (extent should be std::size_t)

include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/snippet/search/bi_fm_index_cursor_cycle.cpp, test/snippet/search/bi_fm_index_cursor_extend_left_seq.cpp, test/snippet/search/bi_fm_index_cursor_to_fwd_cursor.cpp, test/snippet/search/bi_fm_index_cursor_to_rev_cursor.cpp
Resolves #1646
I made the change for fm_index_cursor and bi_fm_index_cursor. 
I also fixed a snippet and corrected some snippet comments.
=> [FIX] fm_index_cursor::path_label for 2D texts should not return views::join | views::slice

include/seqan3/range/decorator/gap_decorator.hpp, test/unit/io/alignment_file/alignment_file_format_test_template.hpp
`constexpr`:
Since the gap_decorator contains a set which cannot be constexpr
constructed, the gap_decorator itslef can also not be constexpr
constructed. If it cannot be constructed, none of the member functions
can be constexpr. And since the gap_decorator_iterator stores a pointer
to the non-constexpr gap_decorator it cannot be constexpr itself. 
`noexcept`:
```
gap_decorator::size() is only noexcept iff the underlying view is noexcept.
gap_decorator::operator[]() is only noexcept iff dereferencing the gap_decorator_iterator is noexcept.
gap_decorator::operator==() isn't noexcept because gap_decorator_iterator::operator++() isn't.
gap_decorator::operator!=() isn't noexcept because gap_decorator::operator==() isn't.
gap_decorator::operator<() isn't noexcept because …
```
=> [FIX] Fix constexpr and noexcept usage in the gap_decorator

test/unit/core/type_traits/range_iterator_test.cpp
Resolves part of #1549.
Split into two commits for readability.
=> [MISC] Replace seqan3::const_reference_t with std one

test/unit/alignment/debug_stream_aligned_sequence_test.cpp
In https://github.com/ericniebler/range-v3/pull/1455 the range-v3 library
harmonises range-v3 with C++20's `std::ranges`. One of these changes is
the behaviour of `std::ranges::enable_view`.
This change is needed for #1680 that will simplify code regarding the
`seqan3::gap_decorator`.
=> [MISC] Update range library

include/seqan3/alignment/configuration/align_config_alignment_result_capture.hpp, include/seqan3/alignment/configuration/all.hpp, include/seqan3/alignment/configuration/detail.hpp, test/unit/alignment/configuration/align_config_common_test.cpp
Part of #1692 
This change allows to capture the configured alignment result in the alignment configuration object that is passed to the alignment result. Thus, the algorithm can ensure that it uses the same alignment algorithm as it was originally configured and avoids possible incompatibilities that are hard to track.
=> [FEATURE] Add internal alignment configuration to capture alignment result from algorithm configuration

include/seqan3/io/alignment_file/input.hpp
This one is quite hard to understand:
Before it slowly build up the required expression
```c++
alphabet<std::ranges::range_reference_t<std::ranges::range_reference_t<typename t::ref_sequences>>>
// the given ref_sequences are ranges of sequences (a sequence is a range over an alphabet)
```
and had fallbacks if one of those steps failed in that expression, such that the whole line
is ALWAYS a valid expression what-so-ever happens.
I moved the expression into a requires(), because this has the property
if anything fails or is not defined the whole requires() expression will
evaluate to false. Exactly the same semantics as before, but a bit
better readable.
Fixes part of #1549
=> [MISC] use std::ranges::range_reference_t

doc/tutorial/alphabet/alphabet_gc_content.cpp
Resolves part of #1608 (1.4)
In the tutorial chapter on Alphabets, the assignment solution makes use of `views` but `views` were not introduced yet.
The proposed change uses a simple for loop with assignments from `char`. The `views` method is mentioned as "optional".
=> [DOC] change tutorial/alphabet solution snippet

CHANGELOG.md, doc/tutorial/alignment_file/alignment_file_read_cigar.cpp, doc/tutorial/alignment_file/index.md, include/seqan3/io/alignment_file/format_bam.hpp, include/seqan3/io/alignment_file/format_sam.hpp, include/seqan3/io/alignment_file/input.hpp, include/seqan3/io/alignment_file/output.hpp, test/unit/io/alignment_file/alignment_file_format_test_template.hpp, test/unit/io/alignment_file/alignment_file_input_test.cpp, test/unit/io/alignment_file/alignment_file_output_test.cpp
Resolves #1616 
~Blocked by #1697~ 
The `seqan3::field::cigar` was added to the default fields for reading and writing alignment files.
This has the following impact:
1. Reading and writing in one line is now possible without additional reference information:
`seqan3::alignment_file_output{"foo.sam"} = seqan3::alignment_file_input{"bar.sam"};`
2. The `seqan3::alignment_file_output` now accepts `seqan3::field::cigar` and `seqan3::field::alignment`
although they store redundant information. For the SAM/BAM format, this ambiguity is handled by favoring the CIGAR
information at all times if present.
Afterwards, we can discuss if we want to discard the dummy sequence and only allow reading the alignment field if the reference information is present.
=> [I/O] Small fix when reading field::cigar and changing the alignment default fields.

test/unit/alphabet/debug_stream_alphabet_test.cpp, test/unit/alphabet/detail/alphabet_proxy_test.cpp, test/unit/alphabet/gap/gap_test.cpp, test/unit/alphabet/gap/gapped_test.cpp, test/unit/alphabet/mask/mask_test.cpp, test/unit/alphabet/mask/masked_test.cpp, test/unit/alphabet/nucleotide/dna15_test.cpp, test/unit/alphabet/nucleotide/dna4_test.cpp, test/unit/alphabet/nucleotide/dna5_test.cpp, test/unit/alphabet/nucleotide/nucleotide_conversion_integration_test.cpp, test/unit/alphabet/nucleotide/nucleotide_test_template.hpp, test/unit/alphabet/nucleotide/rna15_test.cpp, test/unit/alphabet/nucleotide/rna4_test.cpp, test/unit/alphabet/nucleotide/rna5_test.cpp, test/unit/alphabet/nucleotide/sam_dna16_test.cpp, test/unit/alphabet/structure/dot_bracket3_test.cpp, test/unit/alphabet/structure/dssp9_test.cpp, test/unit/alphabet/structure/structured_aa_test.cpp, test/unit/alphabet/structure/structured_rna_test.cpp, test/unit/alphabet/structure/wuss_test.cpp
Resolves #1746
test/unit/alphabet/a*-c* https://github.com/seqan/seqan3/pull/1657 and test/unit/alphabet/quality https://github.com/seqan/seqan3/pull/1638 are already done.
=> [MISC] Remove 'using namespace seqan3' from test/unit/alphabet/*.

include/seqan3/range/views/take.hpp, include/seqan3/range/views/take_until.hpp, test/unit/range/views/view_take_test.cpp, test/unit/range/views/view_take_until_test.cpp
This fixes part of seqan/product_backlog#51 and fixes also part of #1549.
=> [MISC] remove unused associated types in take view(|_until)

include/seqan3/range/container/concatenated_sequences.hpp
This fixes part of #1549. I'm not sure why this version works, but I
tested it for gcc 7, 8 and 9 and it worked.
The main problem I had was to allow the syntax:
```c++
// this should call the constructor which takes two iterators
concatenated_sequences seqs{iterator, sentinel};
```
https://github.com/seqan/seqan3/blob/75f934f1886ee225fb1bad01b9c9f474caf4c508/include/seqan3/range/container/concatenated_sequences.hpp#L299-L307
In many versions I tried, this call instead tried
https://github.com/seqan/seqan3/blob/75f934f1886ee225fb1bad01b9c9f474caf4c508/include/seqan3/range/container/concatenated_sequences.hpp#L321-L328
This caused some issues, because the template also tried to instantiate
those constructors with not-yet defined class types (like for example the
iterator type within the …
=> [MISC] use std::(ranges::range|iter)_(value|reference)_t

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp, test/unit/alignment/pairwise/alignment_configurator_test.cpp
Part of #1692 
Adds a type definition for the alignment result type inside of the alignment configuration traits. This allows to get the result type in a centralised way that is available to all algorithms and the result type needs to be defined only in one place during the configuration phase.
~### Note for the reviewer:~
~This PR is based on #1740 and only the last commit is relevant for this change.~
=> Pass result to alignment/enable alignment result type in alignment configurations

test/unit/range/decorator/gap_decorator_test.cpp
Something appears to have gone wrong in the removal of  `using namespace seqan3` from `test/unit/range/gap_decorator_test.cpp`. The seqan3 namespace identifier were missing. This PR adds them.
Edit (@eseiler):
The `gap_decorator_test` has `#include "../../alignment/aligned_sequence_test_template.hpp"`, this file had an `using namespace seqan3;`. 
So in the `unit/range` PR (#1766) , the gap_decorator` still worked because it had an `using namespace` in an include. 
With the `unit/alignment` PR (#1749) this was removed, but because the latter PR (#1766) was not rebased on master, the error did not occur in the PR but the following master branch build
=> [FIX] Missing seqan3 namespace identifier in gap_decorator_test.cpp

include/seqan3/alignment/pairwise/execution/execution_handler_parallel.hpp, include/seqan3/alignment/pairwise/execution/execution_handler_sequential.hpp
As one step towards an uniform execution design for different algorithms this commit removes the constraints on the sequence types that need to be passed to the alignment, because other algorithms might have different requirements on this type.
=> [MISC] Remove specific alignment constraints from execution handler.

test/unit/core/type_traits/range_iterator_test.cpp
We defined seqan3::size_type on iterators, but it actually makes no sense.
The standard defines `std::ranges::range_size_t` if the range is sized.
We don't use it internally except for tests, so removing the test makes
it possible to deprecate it (which is the task #1549).
=> [TEST] remove test of seqan3::size_type on iterators

include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp, test/unit/alignment/pairwise/execution/alignment_executor_two_way_test.cpp
Part of #1692
Makes the two executor more flexible by providing the actual algorithm result type from outside.
Later we could merge this with some restructering for the search execution model as well.
Only the last commit is relevant
=> Pass result to alignment/pass in alignment result type in two executor

include/seqan3/range/container/bitcompressed_vector.hpp, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/range/decorator/gap_decorator.hpp, include/seqan3/range/views/interleave.hpp, include/seqan3/range/views/translate.hpp, include/seqan3/range/views/translate_join.hpp, include/seqan3/std/ranges, test/snippet/core/type_traits/lazy.cpp, test/unit/core/type_traits/range_iterator_test.cpp
Resolves part of #1549
Replaces occurrences of `seqan3::size_type_t` with `std::ranges::range_size_t` as part of the deprecation of `type_traits/iterator.hpp`
=> [MISC] replace seqan3::size_type_t with std::ranges::range_size_t

test/include/seqan3/test/expect_range_eq.hpp, test/include/seqan3/test/pretty_printing.hpp, test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp, test/unit/io/alignment_file/alignment_file_format_test_template.hpp, test/unit/io/alignment_file/format_bam_test.cpp, test/unit/io/record_test.cpp, test/unit/io/structure_file/format_vienna_test.cpp, test/unit/range/container/container_of_container_test.cpp, test/unit/range/views/view_async_input_buffer_test.cpp, test/unit/range/views/view_enforce_random_access_test.cpp, test/unit/range/views/view_istreambuf_test.cpp, test/unit/range/views/view_repeat_n_test.cpp, test/unit/range/views/view_repeat_test.cpp, test/unit/range/views/view_take_test.cpp, test/unit/range/views/view_take_until_test.cpp, test/unit/range/views/view_translate_join_test.cpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp, test/unit/search/fm_index_cursor/bi_fm_index_cursor_test_template.hpp, test/unit/test/CMakeLists.txt, test/unit/test/expect_range_eq_test.cpp
Part of seqan/product_backlog#46
Add a new test macro `EXPECT_RANGE_EQ`.
It works for all ranges because we are copying them into std::vectors;
We might want to optimize this for large ranges, because the copy is not necessary if the given range is a forward range.
=>  [FEATURE] new test macro EXPECT_RANGE_EQ

test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
In the upcoming PRs I will step-by-step the implementation of the alignment algorithm which will run in the expected performance we'd like to see. This will enable the test for this new branch. Also it is redundant to test the trace and score matrix as they are tested once in the traceback test.
=> [MISC] Remove debug requirement for score, end_position and begin_position test in pairwise alignment test template.

CHANGELOG.md, include/seqan3/range/views/kmer_hash.hpp, test/unit/range/views/view_kmer_hash_test.cpp
Add a typed_test to kmer_hash to reduce code lines, while testing more. Found and solves the bug #1719.
=> Add typed test to kmer_hash

include/seqan3/alignment/matrix/detail/affine_cell_proxy.hpp, test/unit/alignment/matrix/detail/CMakeLists.txt, test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp
Adds a wrapper type for the affine cell type in the new alignment algorithm. The simplified score matrix will return a transformed zip view over the different score matrices needed to compute the affine gap cost (optimal score, horizontal score and vertical score). The new matrix does not add any perfromance penalties but the tuple interface is hard to use inside of the algorithm. Therefor, the proxy just inherits from the actual tuple type and adds named accessor functions that can be used inside of the alignment. 
You can see the usage in the reference implementation in the draft PR #1761.
=> [MISC] Add a proxy type for an affine matrix cell.

CHANGELOG.md, include/seqan3/range/views/kmer_hash.hpp, test/unit/range/views/view_kmer_hash_test.cpp
When introducing the iterator test template to the kmer_view, the following does not compile:
1. iterator urng_t const vs non-const comparison
```cpp
EXPECT_TRUE(std::ranges::begin(this->test_range) == std::ranges::cbegin(this->test_range));
```
2. iterator const urng_t from iterator urng_t construction 
```cpp
const_iterator_type it{std::ranges::begin(this->test_range)};
```
This PR introduces a custom constructor from the non-const version that fixes both problems.
.
=> [FIX] Fix const compatibility for the shape_iterator of the kmer_hash view.

include/seqan3/core/concept/cereal.hpp, test/performance/alignment/edit_distance_unbanded_benchmark.cpp, test/performance/alignment/global_affine_alignment_benchmark.cpp, test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp, test/performance/alignment/global_affine_alignment_simd_benchmark.cpp, test/performance/alignment/local_affine_alignment_benchmark.cpp, test/performance/example/example_benchmark.cpp, test/performance/io/format_fasta_benchmark.cpp, test/performance/io/format_vienna_benchmark.cpp, test/performance/range/views/view_translate_1D_benchmark.cpp, test/performance/range/views/view_translate_2D_1D_benchmark.cpp, test/performance/range/views/view_translate_2D_benchmark.cpp, test/performance/search/dream_index/interleaved_bloom_filter_benchmark.cpp, test/performance/search/search_benchmark.cpp, test/snippet/alignment/matrix/detail/alignment_matrix_column_major_range_base.cpp
This should be the last PR for this topic.
Found and removed:
- One comment in the `include` directory,
- some last `using namespace seqan3::test` in `test/performance`,
- And one `using namespace seqan3::detail` in `test/snippet`.
(Resolves ... Is there any issue for the whole task?)
=> [MISC] Cleanup for the refactoring task: Remove 'using namespace seqan3'

include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp
Adds a new refurbished policy for the affine gap cost functions.
It is not a CRTP class anymore and combines the interfaces for the initialisation and the standard recursion. The new layout allows that policies can simply inherit from this policy to overload specific behavior, e.g. using a different initialisation scheme. Since they are anyway coupled to the same computation methods they should be together or in a direct relation. This was not the case before and complicated things. It also moves the initialisation of the policy into the constructor since the gap costs are coupled with the configuration and therefor directly tied to the configured alignment algorithm.
You can see the usage in the reference implementation in the draft PR #1761.
=> [FEATURE] Add refurbished policy for affine gap costs.

include/seqan3/core/type_traits/template_inspection.hpp, test/unit/core/type_traits/template_inspection_test.cpp
=> [FIX] transfer_template_args_onto and transfer_template_vargs_onto should not instantiate every type!

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp
* Chooses the optimised alignment implementation over the old one as long as the new implementation can compute the requested features.
* Enables the score matrix and new affine recursion policy inside of the new alignment algorithm.
Resolves seqan/product_backlog#58
=> [MISC] Enable score matrix and affine recursion policy

include/seqan3/std/ranges
This one was a bit unexpected, but ranges and std::ranges define there own `view_base` class and they both say, if my own version of that class is a base class then it is a view.
This fix makes views of these two worlds interoperable.
There is also an open issue in range-v3: ericniebler/range-v3#1470
Part of seqan/product_backlog#61
---
There is no `std::ranges::all_view`
* which should have been in `std::views`
* and was renamed to `std::views::all_t` (https://eel.is/c++draft/ranges).
This PR adds this view into the std ranges namespace, but a later PR should
remove all usage of this.
Part of seqan/product_backlog#61
=> gcc-10 --std=c++2a ranges

test/unit/alignment/configuration/align_config_mode_test.cpp, test/unit/core/algorithm/pipeable_config_element_test_template.hpp
When we will tackle the configuration stuff (I was updating my PR #1639), it will reduce a lot of testing code if we use a test template. Especially because none of the search configurations has an individual test yet.
=> [TEST] Introduce a config element test template.

include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp, test/unit/alignment/pairwise/execution/alignment_executor_two_way_test.cpp
This is a first step to generalise the two way executor for any algorithm.
Thus, the executor is not alignment specific anymore and can be used for the search algorithm as well. This commit only contains the structural changes. The documentation and relocation will happen in separate commits.
This way the reviewer can focus on the non-trivial changes.
Changes include:
* removing of the chunking within the two way executor and the chunk related interfaces
* introducing a bucket structure for storing all results per invocation
* Allowing to have invocations without producing results at all.
Note, later in the alignment but also within the search a single algorithm invocation can produce multiple results. How many is not known before. So the result of every invocation is buffered dynamically …
=> [FEATURE] Generalise the two way executor for other algorithms.

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp, test/performance/alignment/global_affine_alignment_benchmark.cpp
In the new alignment implementation we let the alignment algorithm decide when to check for the new alignment optimum. This removes the dependency between the recursion policy and the tracker policy as we used it before. This in turn allows us to remove the CRTP design from the alignment algorithm. The performance is still very competitive as the microbenchmark shows below. My macrobenchmarks on this design confirmed this as well.
This includes only the pre-work and does only work for the global alignment so far. My goal is to get as quickly as possible all minimal requirements into the new alignment design to provide a working vectorised version which has the optimal runtime of SeqAn2. For this I need to provide a special tracker that overloads the current one in order to check the end …
=> Optimise alignment/part2 optimum tracker policy

include/seqan3/std/concepts
There is no `std::detail::weakly_equality_comparable_with` concept.
The standard introduces a exposition-only concept named `weakly-equality-comparable-with`
(https://eel.is/c++draft/concept.equalitycomparable#1).
This PR adds this concept into the std namespace, but a later PR should
remove all usage of this exposition-only concept or we should move that
concept into the seqan namespace.
Part of seqan/product_backlog#61
---
There is no `std::boolean` concept.
The standard introduces a exposition-only concept named `boolean-testable`
(https://eel.is/c++draft/concepts#concept.booleantestable-1).
This PR adds this concept into the std namespace, but a later PR should
remove all usage of this exposition-only concept or we should move that
concept into the seqan namespace.
Part of …
=> gcc-10 --std=c++2a concepts

CHANGELOG.md, include/seqan3/argument_parser/detail/format_parse.hpp, test/unit/argument_parser/format_parse_test.cpp
For example, given the long option name "--opt", then "--optValue" was
possible. This caused ambiguities if one long option name is the prefix
of another. We now only allow "--opt Value" and "--opt=value".
Fixes #1544
=> [FIX] Prohibit long-option value pairs without a separation.

test/snippet/core/type_traits/lazy.cpp
Part of https://github.com/seqan/seqan3/issues/1549
=> [FIX] snippet: replace seqan3::size_type_t with std::ranges::range_size_t

include/seqan3/range/views/minimiser.hpp, include/seqan3/range/views/minimiser_hash.hpp, test/include/seqan3/test/performance/naive_minimiser_hash.hpp
Part of https://github.com/seqan/seqan3/issues/1549
=> [FIX] minimiser should use std::ranges::range_reference_t

include/seqan3/std/iterator
* gcc10-std2a add readable = indirectly_readable to std namespace (for now)
* gcc10-std2a add writable = indirectly_writable to std namespace (for now)
The standard has renamed `std::readable` to `std::indirectly_readable` and
`std::writable` to `std::indirectly_writable`, but we internally use the old names.
To make `-std=c++2a` work, we import the names into the standard namespace.
In a later PR we should do the renaming.
Part of seqan/product_backlog#61
----
We falsely use
* `std::ranges::back_inserter` that is actually in `std::back_inserter`
* `std::ranges::default_sentinel` that is actually in `std::default_sentinel`
* `std::ranges::default_sentinel_t` that is actually in `std::default_sentinel_t`
To make `-std=c++2a` work, we import the names into the standard ranges namespace.
In …
=> gcc-10 --std=c++2a iterators

test/unit/CMakeLists.txt
I ran in a situation where I had an infinite loop and the CI job had to
force quite after one hour of execution. This ensures that every test is
only allowed to execute for 30s.
The 10 longest test run (debug build gcc9) with `-j 8`:
```
> ctest -j 8 > test.output
> awk '{match($0,/[[:digit:]]+.[[:digit:]]+ sec/,a)}{print substr(a[0], 1, length(a[0])-2),$0}' test.output | sort -nk1 -r | cut -f2- -d ' ' | head -n 10
100% tests passed, 0 tests failed out of 6661
s Total Test time (real) =  32.12 sec
s 3486/6661 Test #6195: search/search_scheme_algorithm_test::search_scheme_test.search_scheme_hamming ................................................................................................................................................................................................... …
```
=> [TEST] limit test execution to 30s

include/seqan3/search/detail/policy_result_builder.hpp
Prior to C++20 and gcc 10 [partial ordering of the constraints]
(https://en.cppreference.com/w/cpp/language/constraints#Partial_ordering_of_constraints)
was allowed for any expression that was the same. Starting with gcc10
this ordering is only allowed on actual `concept` definitions.
For example:
```c++
// without concepts
template <int b>
requires (b >= 1)
constexpr int foo()
{
return 1;
}
template <int b>
requires (b >= 1) && (b == 2)
constexpr int foo()
{
return 10;
}
static_assert(foo<1>() == 1); // always unambiguous
// static_assert(foo<2>() == 10); // ambiguous gcc >= 10
```
`b=2` satisfies the require clauses for both definitions. This means that
both definitions are viable. Before gcc10 it used partial ordering on
expression level that made this construct unambiguous.
A solution …
=> [FIX] cxx20: policy_result_builder::make_results is ambigious

include/seqan3/alphabet/concept.hpp
```c++
/scratch/local/seiler/nightly-builds/src/include/seqan3/alphabet/concept.hpp:759:39: error: comparison is always true due to limited range of data type [-Werror=type-limits]
759 |     requires seqan3::alphabet_size<t> >= 0;
|              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors
```
with `gcc10  -std=c++17 -fconcepts`
=> [FIX] ppc64le: warning with alphabets [-W=type-limits]

include/seqan3/range/views/interleave.hpp, include/seqan3/range/views/pairwise_combine.hpp, include/seqan3/range/views/persist.hpp, include/seqan3/range/views/repeat.hpp, include/seqan3/range/views/translate_join.hpp
This fixes part of seqan/product_backlog#51 and fixes also part of seqan#1549.
Previous PRs of the same kind #1734.
- (1) If you can remove it, remove it.
- (2) If something uses it and does not compile anymore, leave it
- (3) Try to make the associated types of ranges private
- (4) If it does not work, leave it
- (5) Document places where you had problems.
Searching for "associate" in `include/seqan3/range/views`. Hits in:
no associated types in view class, only in iterator class.
**edit** 28.04.20:  befriending the inherited iterator allowed making the associated types private
~~removing not possible~~
~~replacing, no coresponding iterator types.~~
~~private? Also not possible, results in build errors in `random_access_iterator.hpp`~~
no associated types in view class, only in iterator …
=> [MISC] Remove 'Associated type' in views

build_system/seqan3-config-version.cmake
We currently disallow `find_package(SeqAn3)` on 32 bit architectures.
This PR will relax that constraint that `find_package(SeqAn3)` is
now working for every architecture, but issues a warning if we know that
this platform has problems or is unsupported.
=> [INFRA] seqan3-config-version.cmake should not disallow 32bit

include/seqan3/core/char_operations/predicate_detail.hpp
Fixes 
```
/dev/shm/tmp/seqan3/include/seqan3/core/char_operations/predicate_detail.hpp:206:49: error: comparison is always false due to limited range of data type [-Werror=type-limits]
206 |                (static_cast<decltype(EOF)>(val) == EOF)                ? derived_t::data[256]                  : false;
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```
The problem here is that `value_t` is `char16_t` - a 16 bit **unsigned** integer - but `EOF` is a 32 bit **signed** integer.
Any number that this `char16_t` may represented is cast to `int32_t` and compared to `EOF` (with a value of `-1`). Hence this is a contradiction (the bit representations of the number will never be the same).
The solution is to get the proper EOF value for the given char_type.
=> [FIX] ppc64le: Compare to proper EOF value

include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp
Fixes
```console
/dev/shm/tmp/seqan3/include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp:193:31: error: comparison of unsigned expression in ‘>= 0’ is always true [-Werror=type-limits]
193 |         assert(coordinate.col >= 0u);
```
=> [FIX] ppc64le: remove tautology

test/seqan3-test.cmake
We override CMAKE_CXX_COMPILER_LAUNCHER in our tests. This is bad if you want to use different `COMPILER_LAUNCHER` such as [distcc](https://github.com/distcc/distcc).
=> [INFRA] don't override CMAKE_CXX_COMPILER_LAUNCHER

include/seqan3/core/type_traits/range.hpp, test/unit/core/type_traits/range_iterator_test.cpp
This only changes the semantics part of issue https://github.com/seqan/product_backlog/issues/86
and is also part of https://github.com/seqan/seqan3/issues/1549 by using
`std::ranges::range_value_t`.
=> [FIX] Allow dimension, compatible and innermost_value only on ranges

include/seqan3/range/views/minimiser.hpp, include/seqan3/std/algorithm, include/seqan3/std/iterator, include/seqan3/std/ranges, test/snippet/range/views/move.cpp
With this PR the std headers have the same entities defined for `-std=c++17` as well as `-std=c++2a`.
We once decided that we will "import" things from the ranges library on demand, this PR comments in ranges stuff that we actually use.
I prefixed all names with `::ranges::cpp20::`, but be aware that this does not mean that each of those names really exist in the ranges library.
This is PART of seqan/product_backlog#49
=>  [FIX] explicitly import cxx20 things into std namespace

.travis.yml
Some stuff we are doing in the `travis.yml` has no effect anymore or is deprecated.
See https://github.com/seqan/app-template/blob/master/.travis.yml for an up to date `travis.yml`
Since we build everything except coverage in Release mode, I didn't put Release/Debug in the name. 
If you click a job on the overview page, you will still see the flags used for this job.
If we are not running the snippet tests, we can also run `ctest` with 2 threads. Since the snippets create and delete files and some separate tests create/delete the same files, they are not safe to run in parallel. Anyway, the snippets only take a few seconds to run.
=> [INFRA] Update travis.yml

include/seqan3/range/views/kmer_hash.hpp, test/unit/range/views/view_kmer_hash_test.cpp
Kmer_hash view now accepts not const_iterable ranges like the combination of take_until with reverse
Part of #1754
=> [FIX] Remove const from static assert

include/seqan3/core/algorithm/configuration.hpp, test/unit/core/algorithm/configuration_test.cpp
This will make it easy to remove a dynamic configuration selector (see #1580 for details on the naming) and replace it with a static configuration.
E.g.
```cpp
seqan3::configuration user_cfg = seqan3::search_cfg::mode{seqan3::search_cfg::hit_all};
// somewhere over the rainbow
auto mode_selection = get<seqan3::search_cfg::mode>(user_cfg).selection;
auto stripped_cfg = user_cfg.template remove<seqan3::search_cfg::mode>(); // remove dynamic mode
// select static config
if (mode_selection == seqan3::search_cfg::hit_all)
return  | seqan3::search_cfg::hit_all;
else if (...)
// ...
```
=> [FEATURE] Add function remove to seqan3::configuration.

include/seqan3/core/type_traits/range.hpp, include/seqan3/io/alignment_file/header.hpp, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/range/views/translate.hpp, include/seqan3/range/views/translate_join.hpp, include/seqan3/search/fm_index/bi_fm_index.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, include/seqan3/search/search.hpp, test/performance/search/index_construction_benchmark.cpp, test/snippet/core/type_traits/range.cpp, test/unit/core/type_traits/range_iterator_test.cpp
This PR fixes https://github.com/seqan/product_backlog/issues/86. 
It renames: 
`constexpr size_t dimension_v = 1;`
to
`constexpr size_t range_dimension_v = 1;`
`struct innermost_value_type`
to 
`struct range_innermost_value`
`using innermost_value_type_t = typename innermost_value_type<t>::type;`
to
`using range_innermost_value_t = typename range_innermost_value<t>::type;`
`concept compatible`
to
`concept range_compatible`
=> [MISC] Renaming seqan3::dimension_v, innermost_value_type, innermost_value_type_t and concept compatible 

include/seqan3/core/simd/detail/simd_algorithm_avx2.hpp, include/seqan3/core/simd/detail/simd_algorithm_avx512.hpp, include/seqan3/core/simd/detail/simd_algorithm_sse4.hpp, include/seqan3/core/simd/simd_algorithm.hpp, include/seqan3/core/simd/view_to_simd.hpp, test/snippet/core/simd/simd_extract.cpp, test/unit/core/simd/simd_algorithm_test.cpp
Adds avx2 intrinsic implementations for transpose and extract. 
This makes the transformation of the sequence batches to simd vectors faster.
Part of #1804
=> Optimise alignment/part2 avx2 optimisations

include/seqan3/core/detail/strong_type.hpp, test/unit/core/detail/strong_type_test.cpp
This comes in very handy in a lot of cases.
E.g. consider 
```cpp
using t = std::variant<my_strong_type1, my_strong_type2>;
t v1{my_strong_type1{2}};
t v2{my_strong_type1{3}};
```
you can neither do 
```cpp
v1 == v2 // error, no comparison operator for my_strong_type1
```
nor
```cpp
v1.get() == v2.get() // error, variant has no member get
```
You would need some nested std::visit for the two variants which is ugly.
=> [FEATURE] Add comparability skill to strong type.

CHANGELOG.md, doc/cookbook/index.md, doc/main_page.md, test/documentation/DoxygenLayout.xml
This resolves seqan/product_backlog/issues/87
Objective:
* Provide an easy overview to find snippets back.
* Help users to improve: from beginner to confident user!
Idea:
* One-page cookbook
* TOC on top of page with links to the different recipes.
* Remarks such as "For this, have a look at this section of the tutorial/at this submodule" and hyperlinks to the tutorial should be included. This improves using the tutorial as documentation for users with a moderate knowledge of the library (not currently doing the tutorial, but having a question).
=> [DOC] Add cookbook

include/seqan3/core/pod_tuple.hpp, test/snippet/core/pod_tuple.cpp
```c++
seqan3/include/seqan3/core/pod_tuple.hpp:57:24: error: ‘std::is_pod_v<int>’ is deprecated: use is_standard_layout_v && is_trivial_v instead [-Werror=deprecated-declarations]
57 |     static_assert(std::is_pod_v<type0>, SEQAN_NOT_POD);
|                   ~~~~~^~~~~~~~~~~~~~~
```
=> [FIX] cxx20: std::is_pod_v<int> is deprecated

include/seqan3/range/views/minimiser.hpp
The expression `std::ranges::begin(this->test_range) == std::ranges::cend(this->test_range)`
for `this->test_range = seqan3::detail::minimiser_view` did not compile.
I tried to find out, but ultimately could only figure out that
the left hand side was
* `lhs_iterator = std::ranges::begin(this->test_range)`
* `lhs_iterator == minimiser_view<rng>::window_iterator<rng>`
* with `rng = non-const std::ranges::transform_view` internally defined as
* `lhs_iterator::sentinel == std::ranges::end(rng)` and
* `std::ranges::end(rng) == std::ranges::transform_view::sentinel<false>`
Whereas the right side was
* `rhs_sentinel = std::ranges::cend(this->test_range)`
* `rhs_sentinel == std::ranges::cend(rng)`
* with `rng = non-const std::ranges::transform_view`
* `rhs_sentinel == …
=> [FIX] cxx20: use std::default_sentinel_t on minimiser view

.travis.yml
This allows the coverage build to be cached
The main time sinks are now running the tests in debug mode (coverage) and running the benchmarks (performance).
Going from xenial (16.04) to bionic (18.04) also upgrades the ccache package, which is quite an old version on xenial.
The default cache size for ccache is 5G on newer versions, the default for the old version is 500M.
The coverage build needs around 5.1G (~50G HDD available on travis).
=> [INFRA,FIX] Increase ccache size in travis

include/seqan3/std/iterator
This is a left-over of #1828
I forgot that `gcc-10 -std=c++2a` needs to define the std 20 version of `std::back_inserter` in our `std::cpp20` namespace.
=> [FIX] cxx20: import std::cpp20::back_inserter

.github/workflows/documentation.yaml
My latest change to the documentation ci did not work https://github.com/seqan/seqan3/pull/1816.
It says
> The --contimeout option may only be used when connecting to an rsync daemon.
https://github.com/seqan/seqan3/runs/720168867?check_suite_focus=true#step:9:14
Since `--contimeout` is not working this PR removes that command again.
=> [CI] action-rsyncer can't handle --contimeout=60, remove it again

doc/cookbook/index.md, test/documentation/DoxygenLayout.xml, test/documentation/seqan3.css
The cookbook link in the left hand side tree view of our docs is not bold.
The first commit fixes the bold issue, the second commit fixes some typos in the cookbook.
=> [DOC,FIX] Make cookbook entry bold

.github/workflows/documentation.yaml
I often check the timestamp of the docs to see if something was already deployed or when the docs were last updated and find it rather confusing that the time is off by a few hours.
=> [FIX] Timezone in deployed docs

CHANGELOG.md, doc/tutorial/search/index.md, include/seqan3/core/platform.hpp, include/seqan3/search/configuration/all.hpp, include/seqan3/search/configuration/detail.hpp, include/seqan3/search/configuration/hit.hpp, include/seqan3/search/configuration/max_error_rate.hpp, include/seqan3/search/configuration/output.hpp, include/seqan3/search/configuration/result_type.hpp, include/seqan3/search/detail/policy_max_error.hpp, include/seqan3/search/detail/policy_search_result_builder.hpp, include/seqan3/search/detail/search_configurator.hpp, include/seqan3/search/detail/search_scheme_algorithm.hpp, include/seqan3/search/detail/search_traits.hpp, include/seqan3/search/detail/unidirectional_search_algorithm.hpp, include/seqan3/search/search.hpp, include/seqan3/search/search_result.hpp, test/snippet/search/dynamic_hit_configuration_example.cpp, test/unit/search/configuration/hit_test.cpp, test/unit/search/search_configuration_test.cpp, test/unit/search/search_scheme_algorithm_test.cpp, test/unit/search/search_test.cpp
Sometimes a program needs to support different hit strategies based on some user input. Since these are mostly runtime decisisons the code can become quite cumbersome to handle the static hit configurations. Instead, one can use the dynamic hit configuration element seqan3::search::cfg::hit. This configuration element allows to set one of the above mentioned hit configurations at runtime. Later during the configuration phase of the search algorithm the selected search configuration is used for the final search algorithm. If the dynamic hit configuration is default constructed it does not hold any hit configuration. If you call search with the dynamic configuration in this state an exception will be thrown.
Also note that using the dynamic configuration might have implications on the …
=> Search config/main dynamic hit config

include/seqan3/core/algorithm/configuration.hpp, include/seqan3/core/platform.hpp
```c++
core/algorithm/configuration_test.cpp:209:72: internal compiler error: Segmentation fault
209 |         EXPECT_TRUE((std::same_as<decltype(cfg.template remove<foobar>()), seqan3::configuration<foo, bar>>));
|                                                                        ^
```
Fixes partially #1877
=> [FIX] gcc-10.1: workaround for ICE

include/seqan3/search/search_result.hpp
```c++
seqan3/include/seqan3/search/search_result.hpp:100:44: error: declaration of template parameter ‘class query_range_t’ with different constraints
100 |     template <typename search_algorithm_t, typename query_range_t>
|                                            ^~~~~~~~
seqan3/include/seqan3/search/search_result_range.hpp:36:40: note: original declaration appeared here
36 | template <typename search_algorithm_t, std::ranges::view query_range_t>
|                                        ^~~
```
Fixes #1877
=> [FIX] cxx20: concepts in forward declaration must be the same

doc/howto/write_an_alphabet/dna2_alphabet.cpp, doc/howto/write_an_alphabet/dna2_semialphabet.cpp, include/seqan3/alignment/configuration/align_config_aligned_ends.hpp, include/seqan3/alignment/matrix/detail/alignment_trace_matrix_proxy.hpp, include/seqan3/alignment/pairwise/alignment_result.hpp, include/seqan3/alphabet/alphabet_base.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/argument_parser/auxiliary.hpp, include/seqan3/core/detail/debug_stream_optional.hpp, include/seqan3/core/detail/debug_stream_variant.hpp, include/seqan3/core/detail/int_types.hpp, include/seqan3/core/math.hpp, include/seqan3/core/parallel/detail/reader_writer_manager.hpp, include/seqan3/core/simd/detail/simd_algorithm_avx2.hpp, include/seqan3/core/simd/detail/simd_algorithm_avx512.hpp, include/seqan3/core/simd/detail/simd_algorithm_sse4.hpp, include/seqan3/range/container/concept.hpp, include/seqan3/range/views/pairwise_combine.hpp, test/performance/range/views/view_all_benchmark.cpp, test/snippet/core/type_traits/function_traits.cpp, test/unit/range/iterator_test_template.hpp
* cxx20: missing include <array>
* cxx20: missing include <cassert>
* cxx20: missing include <optional>
* cxx20: missing include <stdexcept>
* cxx20: missing include <unordered_map>
* cxx20: missing include <range/v3/view/all.hpp>
* cxx20: missing include platform.hpp
* cxx20: missing include type_traits/basic.hpp
```c++
seqan3/include/seqan3/core/parallel/detail/reader_writer_manager.hpp:317:10: error: ‘function’ in namespace ‘std’ does not name a template type
317 |     std::function<void()>                                               completion_fn;
|          ^~~~~~~~
```
```c++
include/seqan3/core/detail/int_types-1.cpp:8:2: error: #error "Your header file is missing #include <seqan3/core/platform.hpp>"
8 | #error "Your header file is missing #include <seqan3/core/platform.hpp>"
| …
```
=> [FIX] cxx20: add missing includes

include/seqan3/alignment/matrix/detail/matrix_coordinate.hpp, include/seqan3/alignment/pairwise/detail/type_traits.hpp
part of #1804 
Allows to use matrix_coordinate with simd types such that we can have a simd coordinate matrix. Updates the alignment configuration traits to provide correct simd coordinate types and index types. Note, that the index type is the unsigned version of the original score type but needs some extra handling of floating-point types.
=> Optimise alignment/part2 simd matrix coordinate

doc/tutorial/alignment_file/alignment_file_solution2.cpp, doc/tutorial/read_mapper/read_mapper_step2.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/sequence_file/sequence_file_solution3.cpp, doc/tutorial/sequence_file/sequence_file_solution4.cpp, doc/tutorial/sequence_file/sequence_file_solution5.cpp, include/seqan3/core/platform.hpp, test/snippet/io/alignment_file/alignment_file_input_reading_filter.cpp, test/snippet/io/alignment_file/alignment_file_output_io_pipeline.cpp, test/snippet/io/sequence_file/sequence_file_input_file_view.cpp, test/snippet/io/sequence_file/sequence_file_output_view_pipeline.cpp, test/snippet/io/structure_file/structure_file_input_filter_criteria.cpp, test/snippet/io/structure_file/structure_file_output_pipeline.cpp, test/snippet/range/views/async_input_buffer.cpp, test/unit/io/alignment_file/alignment_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_input_test.cpp, test/unit/io/sequence_file/sequence_file_integration_test.cpp, test/unit/io/structure_file/structure_file_input_test.cpp
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93983 has the consequences
that a view with a custom constructor of std::filesystem::path produces
an infinite loop.
=> [FIX] workaround gcc10: view + std::filesystem:path constructor = bad

doc/tutorial/sequence_file/index.md, doc/tutorial/sequence_file/sequence_file_snippets.cpp, include/seqan3/io/sequence_file/format_genbank.hpp, include/seqan3/io/structure_file/format_vienna.hpp, include/seqan3/range/container/concatenated_sequences.hpp, include/seqan3/range/views/interleave.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, test/include/seqan3/test/performance/naive_kmer_hash.hpp, test/include/seqan3/test/performance/naive_minimiser_hash.hpp, test/unit/alphabet/aminoacid/aminoacid_translation_test.cpp, test/unit/range/views/view_drop_test.cpp, test/unit/range/views/view_persist_test.cpp, test/unit/range/views/view_slice_test.cpp, test/unit/range/views/view_take_line_test.cpp, test/unit/range/views/view_take_test.cpp, test/unit/range/views/view_take_until_test.cpp
This commit resolves https://github.com/seqan/product_backlog/issues/91 . 
The namespace ranges::view is deprecated and should be replaced by ranges::views.
=> [MISC] Renames ranges::view to ranges::views

include/seqan3/core/simd/view_to_simd.hpp
Add explicit empty() since the implicit definition from view_interface
requires std::ranges::forward_range, but view_to_simd is only an input range.
See https://eel.is/c++draft/view.interface#1
=> [FIX] cxx20: view_to_simd add explicit empty()

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_concept.hpp, include/seqan3/alignment/matrix/matrix_concept.hpp, include/seqan3/alphabet/concept.hpp, include/seqan3/argument_parser/validators.hpp, include/seqan3/core/char_operations/predicate_detail.hpp, include/seqan3/core/concept/tuple.hpp, include/seqan3/core/platform.hpp, include/seqan3/core/simd/concept.hpp, include/seqan3/io/alignment_file/output_format_concept.hpp, include/seqan3/io/sequence_file/input_format_concept.hpp, include/seqan3/io/sequence_file/output_format_concept.hpp, include/seqan3/io/stream/concept.hpp, include/seqan3/io/structure_file/input_format_concept.hpp, include/seqan3/io/structure_file/output_format_concept.hpp, include/seqan3/range/container/concept.hpp, include/seqan3/range/detail/inherited_iterator_base.hpp, include/seqan3/search/fm_index/concept.hpp, test/unit/range/iterator_test_template.hpp
This PR fixes https://github.com/seqan/product_backlog/issues/88, please
see further explanations in that issue.
This is one of the most important PRs to get `-std=c++2a` support.
With regex: "\{[ ]*(.+?)\s*\}\s*->\s*(.+);" and replace "requires std::same_as<decltype($1), $2>;"
=> [FIX] cxx20: return-type-requirement is not a type-constraint

CHANGELOG.md, include/seqan3/alignment/configuration/align_config_result.hpp, test/snippet/alignment/configuration/align_cfg_result_example.cpp
=> [FIX] Alignment score types should be signed

include/seqan3/range/container/small_vector.hpp
‘seqan3::small_string<2>’ is not a valid type for a template non-type parameter because it is not structural
Definition of structural type: https://wg21.link/p1907
```c++
In file included from seqan3/test/unit/io/alignment_file/sam_tag_dictionary_test.cpp:12:
seqan3/include/seqan3/io/alignment_file/sam_tag_dictionary.hpp:64:27: error: ‘seqan3::small_string<2>’ is not a valid type for a template non-type parameter because it is not structural
64 | template <small_string<2> str> // TODO: better handling if too large string is provided?
|                           ^~~
In file included from seqan3/include/seqan3/io/alignment_file/sam_tag_dictionary.hpp:21,
from seqan3/test/unit/io/alignment_file/sam_tag_dictionary_test.cpp:12:
seqan3/include/seqan3/range/container/small_string.hpp:42:7: note: …
```
=> [FIX] cxx20: make small_string a proper structural type

include/seqan3/range/views/repeat.hpp, test/unit/range/views/view_repeat_test.cpp
```c++
/seqan3/include/seqan3/range/views/repeat.hpp:178:100: error: no matching function for call to ‘std::ranges::single_view<std::_Swallow_assign>::single_view(<brace-enclosed initializer list>)’
178 |     constexpr explicit repeat_view(value_t const & value) : single_value{ranges::single_view{value}}
|
```
=> [FIX] cxx20: repeat_view uses single_view wrong?!

include/seqan3/search/search_result.hpp
Fixes seqan/product_backlog#119
Edit (@eseiler):
Note that this works because the member function body is only instantiated/evaluated if the function is actually called at some point in the code.
See https://godbolt.org/z/W25LV3
=> [MISC] Replace throw statements with static_asserts for search_result.

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/alignment_result.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/policy_alignment_result_builder.hpp
Adds result builder policy to new alignment result implementation.
This will replace the result value mechanism as we used it before in the future.
part of seqan/product_backlog#74
=> Optimise alignment/part 4 result builder

include/seqan3/core/platform.hpp, test/include/seqan3/test/expect_range_eq.hpp, test/unit/std/CMakeLists.txt, test/unit/std/algorithm_test.cpp
This is a gcc10.1 regression and is fixed for gcc10.2.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95578
=> [FIX] cxx20: std::ranges::copy does not work on any range

include/seqan3/range/detail/inherited_iterator_base.hpp, include/seqan3/range/views/async_input_buffer.hpp, include/seqan3/range/views/enforce_random_access.hpp, include/seqan3/range/views/pairwise_combine.hpp, test/unit/range/views/view_enforce_random_access_test.cpp
If we want to declare a random_access_iterator as a bidirectional_iterator,
it is not enough to set the iterator_tag, iterator_concept is also needed
to be set.
https://eel.is/c++draft/iterator.concept.bidir#1 says:
```c++
template<class I>
concept bidirectional_iterator =
forward_iterator<I> &&
derived_from<ITER_CONCEPT(I), bidirectional_iterator_tag> &&
requires(I i) {
{ --i } -> same_as<I&>;
{ i-- } -> same_as<I>;
};
```
where `ITER_CONCEPT` is defined as:
> * If the qualified-id `ITER_TRAITS(I)::iterator_concept` is valid and names a type, then `ITER_CONCEPT(I)` denotes that type.
> * Otherwise, if the qualified-id `ITER_­TRAITS(I)::iterator_­category` is valid and names a type, then `ITER_­CONCEPT(I)` denotes that type.
> * Otherwise, if `iterator_­traits<I>` names a specialization …
=> [FIX] cxx20: add iterator_concept

include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp, include/seqan3/alphabet/all.hpp, include/seqan3/core/detail/debug_stream_range.hpp, include/seqan3/range/concept.hpp
Part of seqan/product_backlog#60
=> Range sequence concept

include/seqan3/range/views/translate.hpp, include/seqan3/range/views/translate_join.hpp, include/seqan3/std/ranges
Part of https://github.com/seqan/product_backlog/issues/124
=> [FIX] use std::ranges::view_base instead of ranges one

include/seqan3/core/simd/view_to_simd.hpp, include/seqan3/core/type_traits/iterator.hpp, include/seqan3/io/sequence_file/output_format_concept.hpp, include/seqan3/io/structure_file/input_format_concept.hpp, include/seqan3/io/structure_file/output_format_concept.hpp, include/seqan3/range/detail/inherited_iterator_base.hpp, include/seqan3/range/views/async_input_buffer.hpp, include/seqan3/range/views/single_pass_input.hpp, include/seqan3/range/views/take.hpp, include/seqan3/range/views/take_until.hpp, test/unit/alphabet/custom_alphabet3_test.cpp
Similar to `std::iter_value_t` we need a `seqan3::detail::iter_pointer` type trait to get the pointer-type of an iterator.
The problem that `std::iterator_traits` will not be defined for some `std::*iterator`'s, because it is only defined (automatically) for legacy input iterators. This means the most generic way to access the value-type of an iterator is `std::iter_value_t`, because `std::iterator_traits::value_type` might not be defined for it.
Normally (C++20) views don't define `pointer`, because it is a thing of the past, but as long as we support older gcc versions we need a universal way to access the pointer type.
=> [FEATURE] add seqan3::detail::iter_pointer[_t]

include/seqan3/search/detail/policy_max_error.hpp
Fixes #1930 
closes #1932 as they are the same
=> [HOTFIX] Use get_or instead of value_or.

include/seqan3/alignment/matrix/detail/score_matrix_single_column.hpp, include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp, include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion_banded.hpp, include/seqan3/range/views/drop.hpp, test/unit/alignment/pairwise/fixture/global_affine_banded.hpp, test/unit/alignment/pairwise/global_affine_banded_test.cpp
Adds banded alignment implementation.
~Blocked by #1873~
=> banded alignment implementation in optimised implementation

include/seqan3/std/ranges, test/unit/range/views/view_single_pass_input_test.cpp
The C++20 definition of basic_istream_view requires three template arguments, the ranges library only provides one.
See https://eel.is/c++draft/range.istream#view
=> [FIX] cxx20: single_input_test, basic_istream_view is not known

include/seqan3/range/views/pairwise_combine.hpp, include/seqan3/range/views/repeat.hpp, include/seqan3/range/views/take.hpp
This solves https://github.com/seqan/product_backlog/issues/141 . The iterator class is now defined outside of the belonging view.
=> [MISC] Define iterators from a view outside a view.

test/include/seqan3/test/performance/naive_minimiser_hash.hpp
Naive approach of minimisers considers now reverse strand, which makes it already comparable with seqan2 and can be used in the future for comparison of seqan3's minimiser_hash, once minimiser_hash handles reverse as well.
=> [TEST] Add reverse to naive minimiser view

include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/core/algorithm/configuration_element_parallel_mode.hpp, include/seqan3/search/configuration/all.hpp, test/snippet/search/configuration_parallel.cpp, test/unit/alignment/configuration/align_config_parallel_test.cpp, test/unit/alignment/pairwise/align_pairwise_test.cpp, test/unit/search/configuration/CMakeLists.txt, test/unit/search/configuration/parallel_test.cpp
This PR adds a member variable `thread_count` to the parallel config (it replaces the old value member). It influences both `seqan3::align_cfg::parallel` and `seqan3::search_cfg::parallel`.
Documentation and tests are included in the second commit.
Closes https://github.com/seqan/product_backlog/issues/68 and contributes to https://github.com/seqan/product_backlog/issues/131.
=> [MISC] Config parallel with member thread_count

include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp, include/seqan3/range/detail/random_access_iterator.hpp, test/unit/range/iterator_test_template.hpp
Part of https://github.com/seqan/product_backlog/issues/62
---
If ranges were not correctly implemented, the tests
* move_forward_pre_test
* move_forward_post_test
* move_backward_pre_test (split from move_backward_test)
* move_backward_post_test (split from move_backward_test)
could have an infinite loop, if the iterators didn't move to their end.
We now iterate over the expected range to make sure the test terminates.
This commit further adds the test case `difference_sentinel` which tests
`begin - end` and `end - begin` with all const/non-const combinations.
=> [TEST] add new test case and make existing ones more fool-proof

include/seqan3/range/views/pairwise_combine.hpp, include/seqan3/range/views/repeat.hpp, include/seqan3/range/views/take.hpp
It seems that https://github.com/seqan/seqan3/pull/1914 unfortunately didn't start from a fresh checkout of `upstream/master`. It seems that some of my previous changes / fixes got lost due to merge-conflicts.
This PR is re-applying fix
* https://github.com/seqan/seqan3/pull/1900 and
* https://github.com/seqan/seqan3/pull/1885.
Furthermore, I did some code clean-up.
=> [FIX] Reapply some changes that got lost due to seqan/seqan3#1914

CHANGELOG.md, include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/alignment/pairwise/detail/concept.hpp, test/snippet/alignment/pairwise/align_pairwise.cpp, test/unit/alignment/pairwise/align_pairwise_test.cpp
=> [FEATURE] Allow to pass pairs to pairwise alignment

include/seqan3/io/detail/misc.hpp
Our PPC CI uses 10.1.0 release from source and it triggered an error
which most distros seems to have hot-patched.
I encountered that problem in the past and used this workaround, but the
problem was fixed in the meantime so that I did not need to submit this
patch.
The patch is confirmed to work by @eseiler
=> [FIX] gcc10: use std::variant::emplace instead of implicit assignment

include/seqan3/alignment/matrix/detail/score_matrix_single_column.hpp
Part of #1908 
When the return type for the lambda is not given the entire body must be evaluated in the overload resolution of the transform view.
There also the const qualified version is checked by the compiler. If inside the body of the lambda function is
an expression that results in a constraint error the compiler will omit an hard error because he cannot deduce the return type.
To fix this, the return type is given explicitly in order to allow SFINAE friendly substituion errors due to incomplete types in the return type.
=> [FIX] Explicit return type in transform lambda to avoid hard compiler error.

include/seqan3/std/iterator
Part of https://github.com/seqan/product_backlog/issues/107
See also `std/ranges` where it is done correclty
https://github.com/seqan/seqan3/blob/8c2d524207be3ff8029801551e78c8a5b0fa0777/include/seqan3/std/ranges#L62-L66
=> [FIX] undocumented macro

include/seqan3/alphabet/nucleotide/concept.hpp, test/unit/range/container/CMakeLists.txt, test/unit/range/container/bitcompressed_vector_test.cpp, test/unit/range/container/container_test_template.hpp, test/unit/range/container/small_vector_test.cpp
Fixes #1743 
Before this was not possible (now it is):
```cpp
seqan3::bitcompressed_vector<seqan3::dna4> v{seqan3::dna4{}, seqan3::dna4{}};
auto proxy = *v.begin();
auto complement = seqan3::complement(proxy);
// or working with views:
auto complement = v | seqan3::views::complement; 
```
**Reason**: The `seqan3::complement` cpo had the requirement that the return type is the same as the type of the parameter. But the complement of the proxy returned a `seqan3::dna4` again.
I removed this requirement from the concept.
I also thought about making the complement of a proxy return a proxy again but then where would this proxy point to?
So I think changing the requirement of the concept was the right way.
mentioning @h-2, just in case you want to take a look.
=> [FIX] seqan3::complement cannot require std::same_as on the input and return type.

include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
part of #1908 
Rebases the banded alignment on the current master using the alignment result policy.
=> [MISC] Use alignment builder policy in banded alignment algorithm.

CHANGELOG.md, include/seqan3/search/configuration/all.hpp, include/seqan3/search/configuration/default_configuration.hpp, include/seqan3/search/configuration/detail.hpp, include/seqan3/search/configuration/output.hpp, include/seqan3/search/detail/policy_search_result_builder.hpp, include/seqan3/search/detail/search_configurator.hpp, include/seqan3/search/detail/search_traits.hpp, include/seqan3/search/search_result.hpp, test/snippet/search/configuration_default.cpp, test/snippet/search/configuration_output.cpp, test/unit/search/search_configuration_test.cpp, test/unit/search/search_scheme_algorithm_test.cpp
Fixes seqan/product_backlog#67
The configuration element `seqan3::search_cfg::output` does not exist anymore. 
It has been replaced by individual configuration elements
* `seqan3::search_cfg::output_query_id`
* `seqan3::search_cfg::output_reference_id`
* `seqan3::search_cfg::output_reference_begin_pos`
* `seqan3::search_cfg::output_index_cursor`
**Note**: Before you could only either output text positions or cursors. Now you can output both. I updated the documentation with a note about this.
=> Search configuration: output

include/seqan3/alignment/matrix/detail/affine_cell_proxy.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp, test/unit/alignment/matrix/detail/affine_cell_proxy_test.cpp, test/unit/alignment/matrix/detail/score_matrix_single_column_simd_test.cpp, test/unit/alignment/matrix/detail/score_matrix_single_column_test.cpp
part of #1908 
Some preparations before we add the pairwise matrix which is a combination of the score and the trace matrix. 
The proxy will then be extended to model both versions: only the score matrix and the combined score and trace matrix.
=> Refactor affine cell proxy

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_alignment_result_builder.hpp, include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp
part of #1908 
resolves seqan/product_backlog#73
Enables the computation of the end position in the new optimised alignment algorithm.
=> Optimise alignment/part4 enable computation of end position

include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp, include/seqan3/search/search.hpp, test/unit/search/search_collection_test.cpp, test/unit/search/search_test.cpp
Resolves https://github.com/seqan/seqan3/issues/1962
When the parallel search was added in #1880, no tests were added. Consequently, #1917 did not trigger errors for the wrong config.
=> [FIX] Broken parallel search

include/seqan3/range/views/kmer_hash.hpp, test/unit/range/views/view_kmer_hash_test.cpp
=> [FIX] kmer_hash size works even with take_until | reverse

include/seqan3/alignment/configuration/align_config_band.hpp, test/snippet/alignment/configuration/align_cfg_band_example.cpp
Just came across this while checking the documentation on banded alignments.
I guess before this was inlcuded via `\snippet` where the wird try catch did not show. Now it shows int he documentation but the band does not throw anyway.
=> [MISC] Remove weird try catch block.

test/cmake/add_subdirectories.cmake, test/cmake/seqan3_require_benchmark.cmake, test/cmake/seqan3_require_ccache.cmake, test/cmake/seqan3_require_test.cmake, test/cmake/seqan3_test_component.cmake, test/cmake/seqan3_test_files.cmake, test/performance/CMakeLists.txt, test/seqan3-test.cmake
We want to add more features via cmake to our build infrastructure and want to re-use it in our application template that it makes sense to split out functionality of our cmake-infrastructure into an own dedicated folder.
@mr-c This might have implications for your debian packages.
=> [INFRA] modularise cmake scripts

include/seqan3/alphabet/composite/alphabet_variant.hpp, test/unit/alphabet/composite/alphabet_variant_test.cpp, test/unit/core/char_operations/char_predicate_test.cpp
Fixes #1972 
Note that `char_is_valid` is public in all other alphabets. I double checked.
=> [FIX] Make char_is_valid member function public for alphabet_variant.

include/seqan3/alignment/pairwise/alignment_range.hpp, include/seqan3/range/detail/misc.hpp, include/seqan3/range/detail/random_access_iterator.hpp
With cpp20 support, we do not use our `seqan3/std/...` headers but the stl headers.
This may lead to missing `seqan3/core/platform.hpp` includes if nothing else from seqan3 is included.
=> [FIX] header test: missing includes for cpp20 gcc10

include/seqan3/alignment/pairwise/alignment_configurator.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp, include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp, include/seqan3/alignment/pairwise/detail/policy_alignment_matrix.hpp
part of #1908 
Introduces a policy to configure and acquire the alignment matrices. 
It also unifies the initialisation interface for the banded and unbanded alignment algorithm.
This prepares the code to allow different alignment matrix implementations later. Thus, if the alignment is required the alignment matrix will be augmented with the trace matrix to store the trace pointer. Later we want to have different trace pointer implementations, for example to only store the trace checkpoints in the wavefront execution mode.
=> Optimise alignment/part4 introduce alignment matrix policy

test/performance/range/views/view_all_benchmark.cpp
This adds a missing include.
In cpp20 mode, we do not include the ranges header, but use the STL `<ranges>`, so we need to explicitly include the ranges header.
With this, unit, snippet and performance tests work in cpp20 mode.
=> [FIX] performance test: missing include for cpp20 gcc10

doc/tutorial/introduction/introduction_align.cpp, doc/tutorial/pairwise_alignment/configurations.cpp, doc/tutorial/pairwise_alignment/index.md, doc/tutorial/pairwise_alignment/pairwise_alignment_solution_6.cpp, doc/tutorial/read_mapper/read_mapper_step3.cpp, doc/tutorial/read_mapper/read_mapper_step4.cpp, doc/tutorial/search/search_solution5.cpp, include/seqan3/alignment/all.hpp, include/seqan3/alignment/configuration/align_config_edit.hpp, include/seqan3/alignment/configuration/align_config_max_error.hpp, include/seqan3/alignment/pairwise/align_pairwise.hpp, include/seqan3/core/algorithm/configuration.hpp, test/performance/alignment/edit_distance_unbanded_benchmark.cpp, test/snippet/alignment/configuration/align_cfg_edit_example.cpp, test/snippet/alignment/pairwise/align_pairwise.cpp, test/snippet/alignment/pairwise/alignment_configurator.cpp, test/snippet/alignment/pairwise/parallel_align_pairwise_with_callback.cpp, test/unit/alignment/configuration/align_config_edit_test.cpp, test/unit/alignment/pairwise/align_pairwise_test.cpp, test/unit/alignment/pairwise/align_result_selector_test.cpp, test/unit/alignment/pairwise/alignment_configurator_test.cpp, test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp, test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp, test/unit/core/algorithm/pipeable_config_element_test.cpp
This PR does the following (one commit per bullet point)
* Introduces a test for the pipe operator in `configuration_test.cpp` which wasn't tested before
* Fixes the pipe operator for configurations to allow `config_element | config` (Before only `config | config`, `config | config_element`, and `config_element | config_element` were allowed).
* Removes the `method_global` config from the edit config and adjusts all code parts where edit was used.
=> [FIX,MISC] Fix configuration pipe operator and remove method global from edit config.

include/seqan3/search/all.hpp, include/seqan3/search/configuration/all.hpp, include/seqan3/search/configuration/default_configuration.hpp, include/seqan3/search/kmer_index/all.hpp, include/seqan3/search/kmer_index/shape.hpp
I fixed some inconsistencies and missing documentation in the search module. 
Closes https://github.com/seqan/product_backlog/issues/30.
=> [DOC] Improve search documentation

test/performance/alignment/edit_distance_unbanded_benchmark.cpp, test/performance/alphabet/alphabet_assign_char_benchmark.cpp, test/performance/alphabet/alphabet_assign_rank_benchmark.cpp, test/performance/alphabet/alphabet_to_char_benchmark.cpp, test/performance/alphabet/alphabet_to_rank_benchmark.cpp, test/performance/range/container_seq_read_benchmark.cpp, test/performance/range/views/view_kmer_hash_benchmark.cpp, test/performance/range/views/view_minimiser_hash_benchmark.cpp, test/performance/search/search_benchmark.cpp, test/unit/alignment/aligned_sequence_test.cpp, test/unit/alignment/aligned_sequence_test_template.hpp, test/unit/alignment/pairwise/align_result_selector_test.cpp, test/unit/alphabet/alphabet_cereal_test.cpp, test/unit/alphabet/alphabet_constexpr_test_template.hpp, test/unit/alphabet/composite/alphabet_variant_test.cpp, test/unit/alphabet/composite/composite_integration_test.cpp, test/unit/alphabet/custom_alphabet2_test.cpp, test/unit/alphabet/detail/alphabet_proxy_test.cpp, test/unit/alphabet/nucleotide/dna3bs_test.cpp, test/unit/alphabet/nucleotide/nucleotide_test_template.hpp, test/unit/alphabet/semi_alphabet_constexpr_test_template.hpp, test/unit/alphabet/semi_alphabet_test_template.hpp, test/unit/core/algorithm/detail/execution_handler_template.hpp, test/unit/core/char_operations/char_predicate_test.cpp, test/unit/core/type_traits/range_iterator_test.cpp, test/unit/io/record_test.cpp, test/unit/range/container/container_concept_test.cpp, test/unit/range/decorator/gap_decorator_test.cpp, test/unit/range/views/view_persist_test.cpp, test/unit/std/concept/auxiliary_iterator.hpp
Please double check that I have not deleted too much. (I've also renamed a few variables, but I'm not sure if they were meant aswell.)
I don't know if there are "other common prefixes".
I left the prefix `global_` if there was also a `local_` prefix.
=> [TEST] Remove prefixes / suffices in test suites that are not necessary

include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp, include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp, include/seqan3/alignment/scoring/scoring_scheme_base.hpp, include/seqan3/io/detail/in_file_iterator.hpp, include/seqan3/io/detail/out_file_iterator.hpp, include/seqan3/range/views/persist.hpp, include/seqan3/range/views/repeat.hpp, include/seqan3/range/views/take.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp
Fixes part of https://github.com/seqan/product_backlog/issues/124
A step closer towards A Life Without range-v3: replaces range-v3 headers by <seqan3/std/xxx> where possible/removes unnecessary imports.
=> [MISC] Use <seqan3/std/xxx> instead of range-v3 header

test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp, test/performance/alignment/local_affine_alignment_benchmark.cpp, test/performance/range/views/view_translate_1D_benchmark.cpp, test/performance/range/views/view_translate_2D_1D_benchmark.cpp
This PR is part of https://github.com/seqan/product_backlog/issues/12.
It resolves the errors with seqan2, such as
```bash
.../seqan3/test/performance/range/views/view_translate_2D_1D_benchmark.cpp: In function 'void copy(benchmark::State&)':
.../seqan3/test/performance/range/views/view_translate_2D_1D_benchmark.cpp:195:38: error: 'generate_sequence_seqan' was not declared in this scope; did you mean 'seqan3::test::generate_sequence_seqan2'?
195 |         dna_sequence_collection[i] = generate_sequence_seqan2<seqan::Dna>(100, 0, 0);
|                                      ^~~~~~~~~~~~~~~~~~~~~~~~
|                                      seqan3::test::generate_sequence_seqan2
```
and
```bash
.../seqan3/test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp: In function 'void …
```
=> [TEST] Repair seqan2 tests

include/seqan3/alignment/matrix/alignment_coordinate.hpp, include/seqan3/alignment/matrix/debug_matrix.hpp, include/seqan3/core/detail/debug_stream_alphabet.hpp, include/seqan3/core/detail/debug_stream_optional.hpp, include/seqan3/core/detail/debug_stream_range.hpp, include/seqan3/core/detail/debug_stream_type.hpp, include/seqan3/core/detail/debug_stream_variant.hpp, include/seqan3/core/simd/debug_stream_simd.hpp, include/seqan3/search/fm_index/bi_fm_index_cursor.hpp, include/seqan3/search/fm_index/fm_index_cursor.hpp, include/seqan3/search/search.hpp, test/unit/core/debug_stream_test.cpp, test/unit/test/pretty_printing_test.cpp
Fixes #1993
A change to the standard [1] seems to disallow the following, at least gcc [2] interprets it this way:
```c++
template <typename T> int f(T);
template <typename T> requires true int f(T const&);
int i = f(42);
```
That means constraint functions are only more specialised if they have the same argument "structure".
If you changed the first signature to "int f(T const &);", it would compile again.
This PR unifies the argument "structure"
* for `operator<<(debug_stream, any_type)`,
* for `[bi_]fm_index_cursor::extend_(left|right)`, and
* for `seqan3::search`.
[1] - http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2113r0.html
[2] - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96333
=> [TASK] support gcc10.2
