seqan/seqan3

- include/seqan3/core/platform.hpp
see discussion http://stackoverflow.com/questions/38456127/what-is-the-value-of-cplusplus-for-c17
> [Bug] __cplusplus flag for GCC7 supporting all needed features is 201500

- test/CMakeLists.txt
- test/alphabet/CMakeLists.txt
- test/alphabet/aminoacid/CMakeLists.txt
- test/alphabet/gap/CMakeLists.txt
- test/alphabet/nucleotide/CMakeLists.txt
- test/alphabet/quality/CMakeLists.txt
- test/core/CMakeLists.txt
- test/core/detail/CMakeLists.txt
Introduce `seqan3_test(testcase.cpp)` syntax
> [INTERNAL] simplify test cases

- include/seqan3/alphabet/nucleotide.hpp
- include/seqan3/alphabet/nucleotide/concept.hpp
- include/seqan3/alphabet/nucleotide/dna4.hpp
- include/seqan3/alphabet/nucleotide/dna5.hpp
- include/seqan3/alphabet/nucleotide/nucl16.hpp
- include/seqan3/alphabet/nucleotide/rna4.hpp
- include/seqan3/alphabet/nucleotide/rna5.hpp
- include/seqan3/core.hpp
* global documentation of namespaces (is really important, otherwise the content of the namespaces won't appear in doxygen)
* nucleotide submodule
> add documentation

- include/seqan3/alphabet/composition.hpp
- include/seqan3/alphabet/detail/convert.hpp
- include/seqan3/alphabet/gap/gap.hpp
- include/seqan3/alphabet/quality/illumina18.hpp
- include/seqan3/alphabet/union_alphabet.hpp
- test/CMakeLists.txt
- test/alphabet/alphabet_test.cpp
- test/alphabet/aminoacid_test.cpp
- test/alphabet/nucleotide_test.cpp
- test/alphabet/quality/illumina18_test.cpp
- test/alphabet/quality/quality_composition_test.cpp
- test/alphabet/union_alphabet_detail_test.cpp
- test/alphabet/union_alphabet_test.cpp
- test/core/pod_tuple_test.cpp
> Remove release mode and enable warnings

- include/seqan3/alphabet/composition/union_composition.hpp
review and merge after #84 
resolves #70
> add noexcept to union_composition

- include/seqan3/range/container/all.hpp
- include/seqan3/range/container/concatenated_sequences.hpp
- include/seqan3/range/container/concept.hpp
- include/seqan3/range/detail/random_access_iterator.hpp
- include/seqan3/range/metafunction.hpp
- test/range/container/CMakeLists.txt
- test/range/container/container_of_container_test.cpp
@mariehoffmann could you review this? Especially the part concerning the iterator, but also everything else would be cool, if you want to work on a container next ;-)
@rrahn Can you have a look as well?
> The new ConcatDirect StringSet

- include/seqan3/core/concept/iterator_detail.hpp
One commit of #127 that I forgot to push.
> Fix some doxygen warnings

- include/seqan3/alphabet/aminoacid/aa27.hpp
- include/seqan3/alphabet/concept.hpp
- include/seqan3/alphabet/nucleotide/dna15.hpp
- include/seqan3/alphabet/nucleotide/dna4.hpp
- include/seqan3/alphabet/nucleotide/dna5.hpp
- include/seqan3/alphabet/nucleotide/rna4.hpp
- include/seqan3/alphabet/nucleotide/rna5.hpp
- include/seqan3/alphabet/structure/dot_bracket3.hpp
- include/seqan3/alphabet/structure/dssp9.hpp
- include/seqan3/alphabet/structure/wuss.hpp
- test/alphabet/aminoacid_test.cpp
- test/alphabet/nucleotide_test.cpp
- test/alphabet/structure_test.cpp
> Remove string typedefs and literals from Alphabet module

- include/seqan3/range/view/detail.hpp
- test/range/view/CMakeLists.txt
- test/range/view/declare_view_functor_type_test.cpp
> view functor generation

- include/seqan3/alphabet/all.hpp
- include/seqan3/alphabet/concept.hpp
- include/seqan3/alphabet/concept_pre.hpp
> [DOC] add main alphabet module documentation

- include/seqan3/io/all.hpp
Fixes dev docu issue with unknown reference to serialisation.
The serialisation page must be written though (#187).
> [DOC] Added template page for serialisation.

- include/seqan3/core/filesystem.hpp
- include/seqan3/core/platform.hpp
- include/seqan3/io/filesystem.hpp
- test/include/seqan3/test/tmp_filename.hpp
#155 
If I understood it right, that's it. Not sure if I'm using the sub-namespaces correctly. Since I'm doing it without much context, please double check :)
> create filesystem.hpp, check filesystem lib on plataform.hpp

- README.md
> [DOC] Adapted readme for ranges-v3 0.3.5

- include/seqan3/core/detail/terminal.hpp
Requirement for #88 to work correctly. Must be merged before #88.
> [FEATURE] Some terminal functionality that will be needed for the argument parser help page printing.

- include/seqan3/range/detail/random_access_iterator.hpp
- test/unit/range/detail/random_access_iterator_test.cpp
seperated this out from #104 
@rrahn can you review this asap? thx!
> [INTERNAL] make the random_access_iterator be a CRTP-base

- include/seqan3/core/all.hpp
- include/seqan3/core/detail/all.hpp
- include/seqan3/core/detail/reflection.hpp
- include/seqan3/range/container/constexpr_string.hpp
- test/io/CMakeLists.txt
- test/unit/core/detail/CMakeLists.txt
- test/unit/core/detail/reflection_test.cpp
- test/unit/range/container/CMakeLists.txt
- test/unit/range/container/constexpr_string_test.cpp
Adds a static_string string class and functionality for reflection of types at compile time.
This is the result from  #131 and the discussion from #136.
> [FEATURE] Initial commit to add static_string type.

- include/seqan3/io/detail/in_file_iterator.hpp
- include/seqan3/io/detail/out_file_iterator.hpp
- test/unit/io/detail/CMakeLists.txt
- test/unit/io/detail/in_file_iterator_test.cpp
- test/unit/io/detail/out_file_iterator_test.cpp
The single-pass iterators for file-io.
> io: file iterators

- include/seqan3/core/all.hpp
- include/seqan3/core/type_list.hpp
- include/seqan3/io/detail/record.hpp
- include/seqan3/io/record.hpp
- test/unit/core/CMakeLists.txt
- test/unit/core/type_list_test.cpp
- test/unit/io/CMakeLists.txt
- test/unit/io/record_test.cpp
this is a break-out-PR from #183
> io: field, fields and record

- include/seqan3/core/detail/strong_type.hpp
- test/unit/core/detail/CMakeLists.txt
- test/unit/core/detail/strong_type_test.cpp
Finally the first PR for this.
Adds strong_types and skills for strong_types.
> [FEATURE] Add strong type.

- include/seqan3/range/view/detail.hpp
this partially resolves (#261)
> gcc8: fix declare_view_functor_type error

- .jenkinsfile
please review!
Adds a '.jenkinsfile' file to trigger continuous integration and continuous delivery pipeline.
The pipeline will remove the separate CI tests currently running on Jenkins.
@marehr @h-2 please review
> [FEATURE] Add Jenkins pipeline script

- include/seqan3/argument_parser/all.hpp
- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/auxiliary.hpp
- include/seqan3/argument_parser/detail/format_base.hpp
- include/seqan3/argument_parser/detail/format_help.hpp
- include/seqan3/argument_parser/detail/format_html.hpp
- include/seqan3/argument_parser/detail/format_man.hpp
- include/seqan3/argument_parser/detail/format_parse.hpp
- include/seqan3/argument_parser/exceptions.hpp
- include/seqan3/argument_parser/validators.hpp
- test/unit/argument_parser/CMakeLists.txt
- test/unit/argument_parser/argument_parser_design_error_test.cpp
- test/unit/argument_parser/format_parse_test.cpp
- test/unit/argument_parser/format_parse_validators_test.cpp
Some TODOs are left but you can start attacking the code and documentation
Naming conventions: option? parameter? argument? whatever?
> [FEATURE] The Argument Parser

- include/seqan3/core/platform.hpp
> [FIX] SDSL dependency check fixed (see #284)

- include/seqan3/alphabet/aminoacid/aa20.hpp
- include/seqan3/alphabet/aminoacid/aa27.hpp
- include/seqan3/alphabet/aminoacid/all.hpp
- include/seqan3/alphabet/aminoacid/concept.hpp
- test/unit/alphabet/aminoacid_test.cpp
Addresses issue #294.
Adds a new 20 letter amino acid alphabet. Also adds a new aminoacid_concept file, which defines
any amino acid to have all 27 letters of the alphabet.
> Add aa20.hpp and aminoacid_concept

- include/seqan3/alphabet/adaptation/char.hpp
- test/unit/alphabet/adaptation/char_test.cpp
Fix for #231 by adding wchar_t.
> Adding wchar_t to char adaptation

- .jenkinsfile
> [FEATURE] Adds header tests to jenkins pipeline

- include/seqan3/range/container/constexpr_string.hpp
- test/unit/core/metafunction/range_iterator_test.cpp
> make SeqAn3 build and pass unit tests on OpenBSD

- include/seqan3/alignment/all.hpp
> [DOC] Introduce namespace seqan3::align.

- include/seqan3/alphabet/quality/qualified.hpp
- test/unit/alphabet/quality/qualified_test.cpp
> [FEATURE] Equality comparators for qualified composition against either of it's inner types.

- include/seqan3/io/structure_file/input.hpp
omit concept checks with nested templates
> reduce complexity of RNA I/O

- test/snippet/CMakeLists.txt
This file will automatically/recursively add new snippet files to be built and made.
> [FEATURE] adds the CMakeLists.txt file for snippets

- .travis.yml
so we can make sure that @joshuak94 snippets are working :grin: 
part of #83
> add snippet tests to travis

- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/auxiliary.hpp
- include/seqan3/io/detail/output_iterator_conversion_adaptor.hpp
- include/seqan3/io/sequence/sequence_file_format_fasta.hpp
- include/seqan3/io/sequence/sequence_file_format_fastq.hpp
- include/seqan3/io/sequence/sequence_file_in.hpp
- include/seqan3/io/sequence/sequence_file_out.hpp
- include/seqan3/io/stream/all.hpp
- include/seqan3/io/stream/concept.hpp
- include/seqan3/io/stream/parse_condition.hpp
- include/seqan3/io/stream/parse_condition_detail.hpp
- include/seqan3/io/structure_file/format_vienna.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
- test/performance/io/CMakeLists.txt
- test/performance/io/parse_condition_benchmark.cpp
- test/snippet/io/stream/parse_condition.cpp
- test/unit/io/concept_test.cpp
- test/unit/io/stream/parse_condition_test.cpp
parse conditions now all evaluate in constant time and via table look-up instead of if checks.
> cleanup stream and improve parse_conditions

- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/detail/format_help.hpp
- include/seqan3/argument_parser/detail/format_html.hpp
- include/seqan3/argument_parser/detail/format_man.hpp
- include/seqan3/argument_parser/detail/format_parse.hpp
> [FIX] doxygen warnings in argument parser

- include/seqan3/alphabet/concept_pre.hpp
- include/seqan3/alphabet/detail/member_exposure.hpp
- include/seqan3/alphabet/structure/dot_bracket3.hpp
- include/seqan3/alphabet/structure/rna_structure_concept.hpp
- include/seqan3/alphabet/structure/structured_rna.hpp
- include/seqan3/alphabet/structure/wuss.hpp
- include/seqan3/io/structure_file/detail.hpp
- test/snippet/alphabet/concept_pre.cpp
- test/unit/alphabet/structure_test.cpp
> [FIX, TEST] fix a wrong constexpr condition and add a test

- include/seqan3/alphabet/aminoacid/aa27.hpp
- include/seqan3/alphabet/gap/gapped.hpp
- include/seqan3/alphabet/nucleotide/dna15.hpp
- include/seqan3/alphabet/nucleotide/dna4.hpp
- include/seqan3/alphabet/nucleotide/dna5.hpp
- include/seqan3/alphabet/nucleotide/rna15.hpp
- include/seqan3/alphabet/nucleotide/rna4.hpp
- include/seqan3/alphabet/nucleotide/rna5.hpp
> Rephrase documentation in alphabet module

- include/seqan3/alignment/configuration/align_config_sequence_ends.hpp
- include/seqan3/alignment/configuration/all.hpp
- include/seqan3/alignment/configuration/utility.hpp
- test/unit/alignment/configuration/CMakeLists.txt
- test/unit/alignment/configuration/align_config_sequence_ends_test.cpp
- test/unit/alignment/configuration/utility_test.cpp
>  free ends alignment configuration

- include/seqan3/alignment/aligned_sequence/all.hpp
- include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp
- include/seqan3/alignment/pairwise/execution/alignment_range.hpp
- include/seqan3/alignment/pairwise/execution/all.hpp
- include/seqan3/alignment/pairwise/execution/execution_handler_sequential.hpp
- test/unit/alignment/pairwise/CMakeLists.txt
- test/unit/alignment/pairwise/execution/CMakeLists.txt
- test/unit/alignment/pairwise/execution/alignment_executor_two_way_test.cpp
Adds an executor and steaming interface for range based iteration over a set of pairwise alignments.
The code is tested with a branch of the Myers and some integration test.
I will add more. in the future, but for now, I want to bring everything together. 
So also documentation is yet minimal but will be upgraded as soon as possible.
> [FEATURE] Adds alignment stream and two way alignment executor.

- include/seqan3/io/record.hpp
- include/seqan3/io/sequence_file/all.hpp
- include/seqan3/io/sequence_file/format_fasta.hpp
- include/seqan3/io/sequence_file/format_fastq.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/input_format_concept.hpp
- include/seqan3/io/sequence_file/input_options.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/sequence_file/output_format_concept.hpp
- include/seqan3/io/sequence_file/output_options.hpp
- test/unit/io/sequence_file/CMakeLists.txt
- test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
- test/unit/io/sequence_file/sequence_file_format_fastq_test.cpp
- test/unit/io/sequence_file/sequence_file_input_test.cpp
- test/unit/io/sequence_file/sequence_file_output_test.cpp
just renaming and moving around
> [INTERNAL] rename sequence/file* to sequence_file/*

- include/seqan3/io/alignment_file/all.hpp
- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/header.hpp
- include/seqan3/io/alignment_file/input_options.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/alignment_file/output_format_concept.hpp
- include/seqan3/io/alignment_file/output_options.hpp
- include/seqan3/io/alignment_file/sam_tag_dictionary.hpp
- include/seqan3/io/detail/misc.hpp
- include/seqan3/io/detail/record.hpp
- include/seqan3/io/exception.hpp
- include/seqan3/io/record.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/output.hpp
- test/snippet/io/alignment_file/begin_iterator.cpp
- test/snippet/io/alignment_file/emplace_back.cpp
- test/snippet/io/alignment_file/output.cpp
- test/snippet/io/alignment_file/push_back_record.cpp
- test/snippet/io/alignment_file/push_back_tuple.cpp
- test/snippet/io/alignment_file/record_based_writing.cpp
- test/snippet/io/alignment_file/record_based_writing2.cpp
- test/unit/io/alignment_file/CMakeLists.txt
- test/unit/io/alignment_file/alignment_file_output_test.cpp
- test/unit/io/alignment_file/format_sam_test.cpp
- test/unit/io/alignment_file/sam_tag_dictionary_test.cpp
This is the raw version to discuss design decisions and semantic errors.
> [FEATURE] The alignment_file_out class and SAM format

- include/seqan3/search/algorithm/all.hpp
- include/seqan3/search/algorithm/configuration/all.hpp
- include/seqan3/search/algorithm/configuration/max_error.hpp
- include/seqan3/search/algorithm/configuration/max_error_rate.hpp
- include/seqan3/search/algorithm/configuration/mode.hpp
- include/seqan3/search/algorithm/configuration/output.hpp
- include/seqan3/search/algorithm/configuration/utility.hpp
- include/seqan3/search/algorithm/detail/search.hpp
- include/seqan3/search/algorithm/detail/search_trivial.hpp
- include/seqan3/search/algorithm/search.hpp
- include/seqan3/search/all.hpp
- include/seqan3/search/fm_index/detail/fm_index_iterator.hpp
- include/seqan3/search/fm_index/fm_index_iterator.hpp
- test/unit/search/CMakeLists.txt
- test/unit/search/search_configuration_test.cpp
- test/unit/search/search_test.cpp
Do not ~review or~ merge yet. Work in progress.
> Search module

- include/seqan3/io/stream/debug_stream.hpp
Fixes precedence issue with const & and forwarding-ref in debug stream.
Fixes #458
> [FIX] Fixes const precedence issue in debug stream.

- include/seqan3/alignment/pairwise/alignment_selector.hpp
- test/unit/alignment/pairwise/alignment_selector_test.cpp
> [FIX] align_result should give a std::pair

- include/seqan3/io/stream/debug_stream.hpp
> Revert "[FIX] Fixes const precedence issue in debug stream."

- include/seqan3/core/algorithm/configuration.hpp
- test/unit/core/algorithm/configuration_test.cpp
> [FIX] Fixes pipe with empty configuration onf left hand side.

- include/seqan3/io/alignment_file/output.hpp
> [DOC] correct ingroup for alignment_file_out.

- include/seqan3/io/stream/debug_stream.hpp
- test/unit/io/stream/CMakeLists.txt
- test/unit/io/stream/debug_stream_test.cpp
Fixes printing of:
* 0-terminated strings
* io manipulators that are implemented as functions templates
* const ranges
> fix the debug stream

- include/seqan3/alignment/all.hpp
- include/seqan3/alignment/configuration/all.hpp
- include/seqan3/alignment/matrix/all.hpp
- include/seqan3/alignment/pairwise/all.hpp
- include/seqan3/alphabet/adaptation/all.hpp
- include/seqan3/alphabet/aminoacid/all.hpp
- include/seqan3/alphabet/composition/all.hpp
- include/seqan3/argument_parser/all.hpp
- include/seqan3/core/all.hpp
- include/seqan3/core/detail/all.hpp
- include/seqan3/core/metafunction/all.hpp
- include/seqan3/io/all.hpp
- include/seqan3/io/stream/all.hpp
- include/seqan3/io/structure_file/all.hpp
- include/seqan3/range/container/all.hpp
- include/seqan3/range/view/all.hpp
Fixes #467 and #466 and several other includes.
> [FIX] Fix all.hpp header inclusion.

- include/seqan3/core/platform.hpp
> Raise cplusplus minimal version number to 201703.

- include/seqan3/io/detail/in_file_iterator.hpp
- include/seqan3/io/detail/out_file_iterator.hpp
- include/seqan3/range/view/detail.hpp
- include/seqan3/range/view/persist.hpp
- test/unit/io/sequence_file/CMakeLists.txt
- test/unit/io/sequence_file/sequence_file_integration_test.cpp
- test/unit/io/sequence_file/sequence_file_output_test.cpp
> some fixes file iterators and views, new tests

- test/snippet/argument_parser/argument_parser_1.cpp
- test/snippet/argument_parser/argument_parser_2.cpp
- test/snippet/argument_parser/argument_parser_3.cpp
- test/snippet/argument_parser/validators_1.cpp
- test/snippet/argument_parser/validators_2.cpp
- test/snippet/argument_parser/validators_3.cpp
- test/snippet/argument_parser/validators_4.cpp
One fix for after user meeting feedback #471
> [SNIPPETS] Fix code example to add newline after printing the exception message.

- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/input_options.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/alignment_file/output_options.hpp
> [FIX] various fixes for alignment_file

- include/seqan3/search/algorithm/configuration/all.hpp
- include/seqan3/search/algorithm/configuration/max_error.hpp
- include/seqan3/search/algorithm/configuration/max_error_common.hpp
- include/seqan3/search/algorithm/configuration/max_error_rate.hpp
- include/seqan3/search/algorithm/search.hpp
- include/seqan3/search/all.hpp
- test/unit/search/search_test.cpp
Please do not review or merge yet.
> Some improvements to the search module.

- include/seqan3/search/algorithm/detail/search.hpp
- include/seqan3/search/algorithm/detail/search_trivial.hpp
- include/seqan3/search/algorithm/search.hpp
- include/seqan3/search/fm_index/bi_fm_index_iterator.hpp
- include/seqan3/search/fm_index/fm_index_iterator.hpp
> [FIX] Added missing return values in search module. Fixes #494

- include/seqan3/io/sequence_file/format_fasta.hpp
- include/seqan3/io/sequence_file/format_fastq.hpp
- include/seqan3/io/structure_file/format_vienna.hpp
- include/seqan3/std/iterator
> factor out the use of ranges::back_insert_iterator

- include/seqan3/core/platform.hpp
- include/seqan3/range/view/detail.hpp
- include/seqan3/range/view/persist.hpp
- include/seqan3/range/view/take.hpp
- include/seqan3/range/view/take_line.hpp
- include/seqan3/range/view/take_until.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- include/seqan3/std/iterator
- include/seqan3/std/type_traits
- test/unit/range/view/view_persist_test.cpp
Updates range-v3 to 0.4.0
diverse set of changes, I recommend going by individual commits.
Possibly introduces an ICE in concatenated_sequence with GCC8, I am investigating that.
> Update to rangev3 to 0.4.0

- include/seqan3/core/algorithm/configuration.hpp
- include/seqan3/search/algorithm/search.hpp
- test/unit/core/algorithm/configuration_test.cpp
> [FIX] Piping const configuration object into empty configuration object

- include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp
- include/seqan3/alignment/matrix/alignment_score_matrix.hpp
- include/seqan3/alignment/matrix/alignment_trace_matrix.hpp
- include/seqan3/alignment/matrix/all.hpp
- include/seqan3/alignment/matrix/matrix_concept.hpp
- include/seqan3/alignment/matrix/row_wise_matrix.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- test/unit/alignment/matrix/alignment_matrix_formatter_test.cpp
@h-2 as promised I addressed all points in your code review from #431
Can you have a second look?
Can you squash merge this if done?
> Review edit distance

- include/seqan3/io/alignment_file/output.hpp
> [fix] doxygen warning in alignment_file

- .travis.yml
* switch from Ubuntu 14.0.4 to 16.04
* add a GCC8 test
* remove test of benchmark in debug
> move travis from ubuntu14.04 to ubuntu16.04, add GCC8

- include/seqan3/alignment/exception.hpp
`std::logic_error` needs `<stdexcept>`
> add head file

- test/seqan3-test.cmake
Allows to use googlemock features.
> [NOP] Adds googlemock.

- include/seqan3/argument_parser/exceptions.hpp
- include/seqan3/io/alignment_file/header.hpp
- include/seqan3/io/structure_file/output_format_concept.hpp
- test/header/CMakeLists.txt
> Fixes header includes.

- include/seqan3/io/stream/debug_stream.hpp
- test/unit/io/stream/debug_stream_test.cpp
> [FIX] Prevent recursive instantiation in debug_stream

- include/seqan3/search/algorithm/all.hpp
- include/seqan3/search/algorithm/configuration/max_error.hpp
- include/seqan3/search/algorithm/configuration/max_error_rate.hpp
- include/seqan3/search/algorithm/detail/search.hpp
- include/seqan3/search/algorithm/detail/search_common.hpp
- include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp
- include/seqan3/search/algorithm/detail/search_scheme_precomputed.hpp
- include/seqan3/search/algorithm/detail/search_trivial.hpp
- include/seqan3/search/algorithm/search.hpp
- test/unit/search/CMakeLists.txt
- test/unit/search/bi_fm_index_iterator_test.cpp
- test/unit/search/fm_index_iterator_test.cpp
- test/unit/search/helper.hpp
- test/unit/search/helper_search_scheme.hpp
- test/unit/search/search_scheme_algorithm_test.cpp
- test/unit/search/search_scheme_test.cpp
- test/unit/search/search_test.cpp
~Do not review or merge yet!~ :)
> [FEATURE] Search Schemes

- include/seqan3/range/container/aligned_allocator.hpp
On macos glibc does not implement aligned_alloc 😖 so we need to fallback to posix_memalign.
> [FIX] Fixes missing aligned_alloc on mac os

- test/unit/alignment/configuration/align_config_gap_test.cpp
- test/unit/alignment/configuration/align_config_score_test.cpp
- test/unit/alignment/configuration/align_config_sequence_ends_test.cpp
- test/unit/io/structure_file/format_vienna_test.cpp
- test/unit/io/structure_file/structure_file_input_test.cpp
- test/unit/io/structure_file/structure_file_output_test.cpp
> Removes Doxygen documentation for test files.

- include/seqan3/search/algorithm/all.hpp
- include/seqan3/search/algorithm/detail/search.hpp
- include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp
- include/seqan3/search/algorithm/detail/search_scheme_precomputed.hpp
- include/seqan3/search/algorithm/detail/search_trivial.hpp
- include/seqan3/search/algorithm/search.hpp
> Address Remaining Search Schemes Review

- include/seqan3/alignment/exception.hpp
- include/seqan3/argument_parser/exceptions.hpp
- include/seqan3/core/metafunction/transformation_trait_or.hpp
- include/seqan3/io/alignment_file/header.hpp
- include/seqan3/io/structure_file/input_options.hpp
- include/seqan3/io/structure_file/output_options.hpp
- include/seqan3/range/container/aligned_allocator.hpp
- include/seqan3/range/container/constexpr_string.hpp
- include/seqan3/range/decorator/all.hpp
- include/seqan3/version.hpp
- test/header/CMakeLists.txt
Fixes #564.
I see also #568 from @marehr. Can you explain this one? Maybe I can also put that in this pull request.
> [TEST] Add the check for platform.hpp, and resolve errors.

- test/unit/argument_parser/CMakeLists.txt
- test/unit/argument_parser/detail/CMakeLists.txt
- test/unit/argument_parser/detail/format_help_test.cpp
- test/unit/argument_parser/detail/format_html_test.cpp
More commits incoming with format_html.hpp and format_man.hpp
Pull request isn't completed yet, will assign reviewer when I'm ready!
> [INFRA,TEST] Include new tests for format_help.hpp to improve code coverage

- include/seqan3/alphabet/aminoacid/aa20.hpp
- include/seqan3/alphabet/aminoacid/aa27.hpp
- include/seqan3/alphabet/aminoacid/aminoacid_base.hpp
- include/seqan3/alphabet/aminoacid/concept.hpp
- include/seqan3/alphabet/aminoacid/translation_details.hpp
- test/snippet/alignment/scoring/aminoacid_scoring_scheme.cpp
- test/snippet/alphabet/aminoacid/aa20.cpp
- test/snippet/alphabet/aminoacid/aa27.cpp
- test/snippet/alphabet/aminoacid/is_aminoacid.cpp
- test/snippet/alphabet/structure/structured_aa.cpp
- test/unit/alignment/configuration/align_config_score_test.cpp
- test/unit/alignment/scoring_scheme_test.cpp
- test/unit/alphabet/aminoacid/aa20_test.cpp
- test/unit/alphabet/aminoacid/aa27_test.cpp
- test/unit/alphabet/aminoacid/aminoacid_conversion_integration_test.cpp
- test/unit/alphabet/aminoacid/aminoacid_test_template.hpp
- test/unit/alphabet/aminoacid/aminoacid_translation_integration_test.cpp
- test/unit/alphabet/composition/cartesian_composition_test.cpp
- test/unit/alphabet/composition/composition_test.cpp
- test/unit/io/stream/parse_condition_test.cpp
> Char literal for amino acids, removal of enum interface and introduction of is_aminoacid metafunction

- include/seqan3/std/iterator
Fixes the WeaklyIncrementable by adding the proposed iter_difference_t metafunction and the incrementable_traits class.
> [FIX] Adapts the weakly incrementable concept according to current standard draft.

- test/performance/alignment/CMakeLists.txt
- test/performance/alignment/affine_alignment_benchmark.cpp
Adds the first benchmark test for the alignment module:
Preliminary results for score only:
```
--------------------------------------------------------------
Benchmark                       Time           CPU Iterations
--------------------------------------------------------------
seqan3_affine_dna4         613038 ns     612646 ns       1015
seqan2_affine_dna4         590937 ns     590440 ns       1169
seqan3_affine_dna4_set   59400658 ns   59376083 ns         12
seqan2_affine_dna4_set   59811930 ns   59782583 ns         12
```
> [FEATURE] Adds performance test for affine alignment.

- include/seqan3/std/charconv
- include/seqan3/std/charconv_detail.hpp
Fixes linkage for these two functions.
(We didn't notice because we don't use these functions yet, but we have PRs that'll use them)
> [FIX] Make charconv functions inline

- include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
- include/seqan3/alphabet/gap/gapped.hpp
- include/seqan3/range/decorator/all.hpp
- include/seqan3/range/decorator/gap_decorator_anchor_set.hpp
- include/seqan3/range/detail/enable_view.hpp
- include/seqan3/std/ranges
- test/unit/alignment/aligned_sequence_test.cpp
- test/unit/alignment/aligned_sequence_test_template.hpp
- test/unit/alphabet/gap/gapped_test.cpp
- test/unit/range/decorator/CMakeLists.txt
- test/unit/range/decorator/gap_decorator_anchor_set_test.cpp
This supersedes #726 
This is to take some work load of marie.
> The Anchor Set Gap decorator

- include/seqan3/range/decorator/all.hpp
- include/seqan3/range/decorator/gap_decorator_anchor_set.hpp
The gap_decorator2 branch replaces gap_decorator.
> Gap decorator with anchor set structure.

- include/seqan3/io/structure_file/format_vienna.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
- test/unit/io/structure_file/structure_file_input_test.cpp
- test/unit/io/structure_file/structure_file_output_test.cpp
> [FEATURE] Compression and decompression for structure files

- test/performance/alignment/affine_alignment_benchmark.cpp
See [Failing nightly on cdash](http://cdash.seqan.de/testDetails.php?test=54617632&build=299412)
> [FIX] Assign rank from valid values in alignment benchmark

- .jenkinsfile
Fixes #711
Controls job execution inside of pipeline
Adds cleanup step for docker executions
> Improves jenkins pipeline by using scripted pipeline syntax

- include/seqan3/argument_parser/validators.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/all.hpp
- include/seqan3/io/detail/misc.hpp
- include/seqan3/io/detail/misc_input.hpp
- include/seqan3/io/detail/misc_output.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
- include/seqan3/search/fm_index/bi_fm_index.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- include/seqan3/std/filesystem
- test/include/seqan3/test/tmp_filename.hpp
- test/snippet/argument_parser/validators_file_existance.cpp
- test/snippet/io/alignment_file/begin_iterator.cpp
- test/snippet/io/alignment_file/emplace_back.cpp
- test/snippet/io/alignment_file/output.cpp
- test/snippet/io/alignment_file/push_back_record.cpp
- test/snippet/io/alignment_file/push_back_tuple.cpp
- test/snippet/io/alignment_file/record_based_writing.cpp
- test/snippet/io/alignment_file/record_based_writing2.cpp
- test/unit/argument_parser/format_parse_validators_test.cpp
- test/unit/io/stream/debug_stream_test.cpp
- test/unit/test/tmp_filename_test.cpp
and refactor seqan3/io/filesystem.hpp to seqan3/std/filesystem.
> [MISC] Alias std::experimental::filesystem to std::filesystem 

- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/detail/format_help.hpp
- include/seqan3/argument_parser/detail/format_html.hpp
- include/seqan3/argument_parser/detail/format_man.hpp
- include/seqan3/argument_parser/exceptions.hpp
- test/snippet/argument_parser/argument_parser_1.cpp
- test/snippet/argument_parser/argument_parser_2.cpp
- test/snippet/argument_parser/argument_parser_3.cpp
- test/snippet/argument_parser/validators_1.cpp
- test/snippet/argument_parser/validators_2.cpp
- test/snippet/argument_parser/validators_3.cpp
- test/snippet/argument_parser/validators_4.cpp
- test/snippet/argument_parser/validators_chaining.cpp
- test/snippet/argument_parser/validators_file_existance.cpp
- test/unit/argument_parser/detail/format_help_test.cpp
- test/unit/argument_parser/detail/format_html_test.cpp
- test/unit/argument_parser/format_parse_validators_test.cpp
instead of throwing seqan3::parser_interruption on special requests.
> [MISC] Refactor argument_parser to exit

- test/documentation/seqan3_doxygen_cfg.in
Adds image path to doxygen file and adds hint box for assignments.
Part of #698
> [DOC] Add image path to doxygen and add hint box for assignments.

- include/seqan3/core/metafunction/basic.hpp
- include/seqan3/range/view/get.hpp
- test/unit/range/view/view_get_test.cpp
> return values of view::get

- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/detail/format_help.hpp
- test/unit/argument_parser/detail/CMakeLists.txt
- test/unit/argument_parser/detail/format_help_test.cpp
> supersedes [FIX] Implement the --copyright flag from @joshuak94

- include/seqan3/alphabet/concept_pre.hpp
This should do what you are asking with little overhead.
> [DOC] fix documentation for Alphabet and Semialphabet

- doc/setup/hello_world.cpp
- doc/setup/index.md
Maybe we should do the directory basically the same way we do the snippets/solutions of the manual?
That is:
- Have one subdirectory per section
- Have CMake fetch all cpp files and prefix them with the section (unique target name)
> [DOC] Setup

- test/coverage/CMakeLists.txt
- test/header/CMakeLists.txt
- test/performance/CMakeLists.txt
- test/seqan3-test.cmake
- test/snippet/CMakeLists.txt
- test/unit/CMakeLists.txt
This PR will reduce some ugily and redundant cmake code.
follow up of #737
> [infra] dry cmake tests by introducing seqan3_test_component

- doc/tutorial/concepts/custom_validator_solution1.cpp
- doc/tutorial/concepts/custom_validator_solution2.cpp
- doc/tutorial/concepts/index.md
- doc/tutorial/concepts/overloading1.cpp
- doc/tutorial/concepts/overloading2.cpp
- doc/tutorial/concepts/overloading_solution1.cpp
- doc/tutorial/concepts/overloading_solution2.cpp
- doc/tutorial/concepts/specialisation.cpp
- test/documentation/DoxygenLayout.xml
This is a standalone tutorial for learning the concepts basics. If we merge this we can remove some concepts stuff from the alphabets tutorial so that gets a little easier.
> concepts tutorial

- doc/tutorial/ranges/index.md
- test/documentation/DoxygenLayout.xml
i will merge this very soonish, but please review in any case so that we can later fix stuff.
All examples are currently inline, I will move them out later.
> ranges tutorial

- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp
This enables the aligned ends configuration for the edit distance algorithm.
> [FEATURE,TEST] Adds aligned ends configuration for edit distance alignment.

- doc/tutorial/sequence_file/index.md
- doc/tutorial/sequence_file/sequence_file_snippets.cpp
- doc/tutorial/sequence_file/sequence_file_solution1.cpp
- doc/tutorial/sequence_file/sequence_file_solution2.cpp
- doc/tutorial/sequence_file/sequence_file_solution3.cpp
- doc/tutorial/sequence_file/sequence_file_solution4.cpp
- doc/tutorial/sequence_file/sequence_file_solution5.cpp
- test/documentation/DoxygenLayout.xml
- test/snippet/io/sequence_file/sequence_file_input.cpp
First Draft. Do not review types yet.
> [DOC] Sequence File Tutorial

- include/seqan3/alignment/configuration/align_config_aligned_ends.hpp
- test/snippet/alignment/configuration/align_cfg_aligned_ends_example.cpp
Updates the doc for aligned ends configuration.
> [DOC] Update the documentation for aligned_ends.

- include/seqan3/alignment/pairwise/alignment_configurator.hpp
Some minor fix to set the default alignment result type in case it is not set from outside.
It basically adds a if constexpr at the beginning of the configure block and add the least required alignment result.
> [FIX] Fixes alignment configuration without result config.

- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
If you handle multiple files this is crucial to know which file cannot be openend
> [MISC] Improve file_open_error message.

- include/seqan3/io/alignment_file/output.hpp
... too many fields to keep track of :see_no_evil:
> [FIX] Fix order of writing SAM fields.

- doc/tutorial/search/cleanup.hpp
- doc/tutorial/search/index.md
- doc/tutorial/search/search_basic_index.cpp
- doc/tutorial/search/search_basic_search.cpp
- doc/tutorial/search/search_small_snippets.cpp
- doc/tutorial/search/search_solution1.cpp
- doc/tutorial/search/search_solution2.cpp
- doc/tutorial/search/search_solution3.cpp
- doc/tutorial/search/search_solution4.cpp
- doc/tutorial/search/search_solution5.cpp
- doc/tutorial/search/search_span.cpp
- include/seqan3/std/ranges
- test/documentation/DoxygenLayout.xml
**Blocked by** #811 
Already cleans up files created by #812 but this PR is not blocked by it
> [DOC] Search tutorial

- doc/tutorial/read_mapper/index.md
- doc/tutorial/read_mapper/read_mapper_indexer_step1.cpp
- doc/tutorial/read_mapper/read_mapper_indexer_step2.cpp
- doc/tutorial/read_mapper/read_mapper_indexer_step3.cpp
- doc/tutorial/read_mapper/read_mapper_step1.cpp
- doc/tutorial/read_mapper/read_mapper_step2.cpp
- doc/tutorial/read_mapper/read_mapper_step3.cpp
- doc/tutorial/read_mapper/read_mapper_step4.cpp
- test/documentation/DoxygenLayout.xml
A question is where to put the example data (reference+queries). They are a whooping 53 KB in size (combined).
**Edit**: It's now on the ftp
> [DOC] Read mapper

- include/seqan3/argument_parser/detail/format_parse.hpp
- include/seqan3/argument_parser/validators.hpp
- test/unit/argument_parser/format_parse_validators_test.cpp
> [MISC] Small output fixes of the argument parser.

- doc/tutorial/concepts/index.md
- doc/tutorial/ranges/index.md
- doc/tutorial/ranges/range_snippets.cpp
- doc/tutorial/ranges/range_solution3.cpp
and move code snippets into files.
> fix problems discovered during the seminar

- include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp
- include/seqan3/range/view/single_pass_input.hpp
- test/unit/range/view/view_single_pass_input_test.cpp
- test/unit/range/view/view_take_line_test.cpp
Fixes construction of single pass input view.
> [Fix] single pass input view

- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/detail/ignore_output_iterator.hpp
- include/seqan3/io/record.hpp
- include/seqan3/io/sequence_file/format_fasta.hpp
- include/seqan3/io/sequence_file/format_fastq.hpp
- include/seqan3/io/stream/debug_stream.hpp
- include/seqan3/io/structure_file/format_vienna.hpp
To fix doxygen warning, part I.
> [MISC] Doxygen Fixes Constructors in IO

- doc/howto/write_a_view/index.md
- doc/howto/write_a_view/solution_iterator.cpp
- doc/howto/write_a_view/solution_view.cpp
- doc/howto/write_a_view/view_exercise1.cpp
- doc/howto/write_a_view/view_exercise2.cpp
- include/seqan3/range/detail/inherited_iterator_base.hpp
- include/seqan3/std/iterator
- include/seqan3/std/ranges
- test/documentation/DoxygenLayout.xml
- test/documentation/seqan3-doxygen.cmake
- test/documentation/seqan3_doxygen_cfg.in
- test/unit/argument_parser/detail/format_html_test.cpp
- test/unit/argument_parser/format_parse_validators_test.cpp
> HowTo write a view

- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/alignment_result.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- include/seqan3/alignment/pairwise/policy/affine_gap_banded_init_policy.hpp
- include/seqan3/alignment/scoring/gap_scheme.hpp
- include/seqan3/alignment/scoring/scoring_scheme_base.hpp
> [MISC] Fix constructor warnings from doxygen alignment II

- doc/setup/index.md
> [FIX,DOC] Revise Setup tutorial

- include/seqan3/alphabet/nucleotide/all.hpp
Resolves #740 
The implementation is correct.
> [FIX,DOC] nucleotide complement table

- include/seqan3/io/sequence_file/format_embl.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/input_options.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/sequence_file/output_options.hpp
- test/unit/io/sequence_file/CMakeLists.txt
- test/unit/io/sequence_file/sequence_file_format_embl_test.cpp
- test/unit/io/sequence_file/sequence_file_input_test.cpp
- test/unit/io/sequence_file/sequence_file_output_test.cpp
> embl format

- include/seqan3/io/alignment_file/all.hpp
- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/header.hpp
- include/seqan3/io/alignment_file/input.hpp
- include/seqan3/io/alignment_file/input_format_concept.hpp
- include/seqan3/io/alignment_file/input_options.hpp
- include/seqan3/io/alignment_file/misc.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/alignment_file/output_format_concept.hpp
- include/seqan3/io/detail/misc_input.hpp
- include/seqan3/io/stream/debug_stream.hpp
- include/seqan3/range/view/char_to.hpp
- test/snippet/io/alignment_file/alignment_file_input.cpp
- test/snippet/io/alignment_file/alignment_file_output.cpp
- test/unit/io/alignment_file/CMakeLists.txt
- test/unit/io/alignment_file/alignment_file_input_test.cpp
- test/unit/io/alignment_file/alignment_file_output_test.cpp
- test/unit/io/alignment_file/format_sam_test.cpp
- test/unit/io/stream/debug_stream_test.cpp
Partial work for #436 
Blocked by ~#623~  ~#777~
> Alignment I/O - SAM format read

- test/unit/alignment/pairwise/policy/affine_gap_banded_init_policy_test.cpp
- test/unit/alignment/pairwise/policy/affine_gap_banded_policy_test.cpp
> [FIX] Fixes construction of mock classes.

- include/seqan3/range/view/translation.hpp
minor bug spotted when using this in lambda
> [FIX] remove explicit and add const-qualification

- include/seqan3/alphabet/nucleotide/dna15.hpp
- include/seqan3/alphabet/nucleotide/dna4.hpp
- include/seqan3/alphabet/nucleotide/dna5.hpp
- include/seqan3/alphabet/nucleotide/nucleotide_base.hpp
- include/seqan3/alphabet/nucleotide/rna15.hpp
- include/seqan3/alphabet/nucleotide/rna4.hpp
- include/seqan3/alphabet/nucleotide/rna5.hpp
- include/seqan3/alphabet/quality/phred42.hpp
- include/seqan3/alphabet/quality/phred63.hpp
- include/seqan3/alphabet/quality/phred68legacy.hpp
- include/seqan3/alphabet/quality/qualified.hpp
- include/seqan3/alphabet/quality/quality_base.hpp
- include/seqan3/alphabet/structure/dot_bracket3.hpp
- include/seqan3/alphabet/structure/dssp9.hpp
- include/seqan3/alphabet/structure/structured_aa.hpp
- include/seqan3/alphabet/structure/structured_rna.hpp
- include/seqan3/alphabet/structure/wuss.hpp
Alphabet part II, as discussed in #872
> [MISC] Doxygen construction warning fix for alphabet II

- include/seqan3/core/algorithm/configuration.hpp
- include/seqan3/core/detail/strong_type.hpp
Doxygen warning fixes in core, when possible (means I got no error while making) I added the noexcept.
> [MISC] Doxygen warning fixes core

- include/seqan3/range/container/aligned_allocator.hpp
- include/seqan3/range/container/bitcompressed_vector.hpp
- include/seqan3/range/detail/inherited_iterator_base.hpp
- include/seqan3/range/view/pairwise_combine.hpp
- include/seqan3/range/view/persist.hpp
- include/seqan3/range/view/take.hpp
- include/seqan3/range/view/take_until.hpp
- include/seqan3/range/view/translation.hpp
Whenever possible I added a noexcept, otherwise just default comment.
> [MISC] doxygen warning for default constructor fix in range

- test/snippet/core/simd/fill.cpp
- test/snippet/core/simd/iota.cpp
- test/snippet/core/simd/simd.cpp
- test/snippet/core/simd/simd_test_utility.cpp
fix some naming issues in simd module.
> [fix] type names in simd snippets

- include/seqan3/argument_parser/argument_parser.hpp
> [FIX] address sanitizer bug in argument_parser.

- include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
- include/seqan3/alignment/aligned_sequence/all.hpp
- include/seqan3/alignment/configuration/align_config_gap.hpp
- include/seqan3/alignment/configuration/align_config_scoring.hpp
- include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp
- include/seqan3/alignment/matrix/alignment_score_matrix.hpp
- include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp
- include/seqan3/alignment/matrix/alignment_trace_matrix.hpp
- include/seqan3/alignment/matrix/matrix_concept.hpp
- include/seqan3/alignment/matrix/row_wise_matrix.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- include/seqan3/alignment/scoring/all.hpp
- include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
- include/seqan3/alignment/scoring/gap_scheme_concept.hpp
- include/seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp
- include/seqan3/alignment/scoring/scoring_scheme_concept.hpp
- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/stream/detail/debug_stream_alignment_matrix.hpp
- include/seqan3/range/decorator/gap_decorator_anchor_set.hpp
- test/unit/alignment/aligned_sequence_test.cpp
- test/unit/alignment/aligned_sequence_test_template.hpp
- test/unit/alignment/gap_scheme_test.cpp
- test/unit/alignment/scoring_scheme_test.cpp
aligned_sequence_concept -> AlignedSequence
matrix_concept -> Matrix
max_errors_concept -> MaxErrors
edit_distance_trait_concept -> EditDistanceTrait
gap_scheme_concept -> GapScheme
scoring_scheme_concept -> ScoringScheme
> Concept renaming alignment

- include/seqan3/alignment/matrix/alignment_coordinate.hpp
- test/include/seqan3/test/pretty_printing.hpp
- test/unit/alignment/matrix/alignment_coordinate_test.cpp
- test/unit/test/pretty_printing_test.cpp
This fixes the ambiguous overload of PrintTo that @joergi-w  encountered.
> [TEST] fix pretty printing; resolves ambiguous PrintTo overload

- doc/tutorial/alphabet/index.md
- doc/tutorial/argument_parser/index.md
- doc/tutorial/concepts/index.md
- doc/tutorial/ranges/index.md
- doc/tutorial/ranges/range_solution4.cpp
- doc/tutorial/sequence_file/index.md
> [FIX,DOC] fix typos and missing solution in tutorials

- test/unit/alignment/pairwise/CMakeLists.txt
- test/unit/alignment/pairwise/edit_distance/CMakeLists.txt
- test/unit/alignment/pairwise/edit_distance/global_edit_distance_max_errors_unbanded_test.cpp
- test/unit/alignment/pairwise/edit_distance/global_edit_distance_unbanded_test.cpp
- test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp
- test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_unbanded_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
This changes the edit_distance test case into a test template.
> split edit distance test cases

- test/unit/io/alignment_file/alignment_file_format_test_template.hpp
- test/unit/io/alignment_file/format_sam_test.cpp
This will help reduce code once I add the BAM tests
> [TEST] Restructure sam test to a test template.

- include/seqan3/core/bit_manipulation.hpp
- include/seqan3/core/detail/all.hpp
- include/seqan3/core/detail/endian.hpp
- test/unit/core/bit_manipulation_test.cpp
Adds endian conversion helper.
> [FEATURE] Add host to little endian conversion.

- include/seqan3/alignment/matrix/trace_directions.hpp
- test/unit/alignment/matrix/trace_directions_test.cpp
> [FIX] don't use char8_t

- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/output.hpp
- test/unit/io/alignment_file/alignment_file_output_test.cpp
- test/unit/io/sequence_file/sequence_file_output_test.cpp
- test/unit/io/structure_file/structure_file_output_test.cpp
I only updated the input file not the output file
> [MISC] Update alignment_file_output to compression streams.

- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/sequence_file/format_embl.hpp
- include/seqan3/io/sequence_file/format_fasta.hpp
- include/seqan3/io/sequence_file/format_fastq.hpp
- include/seqan3/io/sequence_file/format_sam.hpp
- include/seqan3/io/stream/iterator.hpp
- include/seqan3/io/structure_file/format_vienna.hpp
- include/seqan3/std/ranges
- test/snippet/io/alignment_file/alignment_file_input.cpp
- test/unit/std/concept/auxiliary_iterator.hpp
- test/unit/std/concept/iterator_test.cpp
> [MISC] Move ostream iterator out of std/ranges header.

- include/seqan3/range/view/char_to.hpp
- include/seqan3/range/view/complement.hpp
- include/seqan3/range/view/convert.hpp
- include/seqan3/range/view/drop.hpp
- include/seqan3/range/view/get.hpp
- include/seqan3/range/view/interleave.hpp
- include/seqan3/range/view/kmer_hash.hpp
- include/seqan3/range/view/pairwise_combine.hpp
- include/seqan3/range/view/persist.hpp
- include/seqan3/range/view/rank_to.hpp
- include/seqan3/range/view/repeat.hpp
- include/seqan3/range/view/repeat_n.hpp
- include/seqan3/range/view/single_pass_input.hpp
- include/seqan3/range/view/slice.hpp
- include/seqan3/range/view/take.hpp
- include/seqan3/range/view/take_exactly.hpp
- include/seqan3/range/view/take_line.hpp
- include/seqan3/range/view/take_until.hpp
- include/seqan3/range/view/to_char.hpp
- include/seqan3/range/view/to_lower.hpp
- include/seqan3/range/view/to_rank.hpp
- include/seqan3/range/view/to_upper.hpp
- include/seqan3/range/view/translation.hpp
- include/seqan3/range/view/trim.hpp
- include/seqan3/range/view/view_all.hpp
Adding includes to view functions
#895
> [MISC] Include header file in documentation.

- include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
- include/seqan3/alignment/pairwise/align_pairwise.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/alphabet/composite/alphabet_variant.hpp
- include/seqan3/core/algorithm/configuration.hpp
- include/seqan3/core/concept/tuple.hpp
- include/seqan3/core/debug_stream.hpp
- include/seqan3/core/metafunction/range.hpp
- include/seqan3/core/pod_tuple.hpp
- include/seqan3/core/tuple_utility.hpp
- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/record.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/output.hpp
- include/seqan3/range/container/concatenated_sequences.hpp
- include/seqan3/range/view/get.hpp
- include/seqan3/range/view/translation.hpp
- test/snippet/core/metafunction/range.cpp
- test/unit/alignment/pairwise/alignment_result_test.cpp
- test/unit/alphabet/composite/alphabet_tuple_base_test.cpp
- test/unit/core/algorithm/configuration_test.cpp
- test/unit/core/metafunction/range_iterator_test.cpp
- test/unit/core/tuple_utility_test.cpp
- test/unit/io/record_test.cpp
tuple_size_concept -> TupleSize
tuple_get_concept -> TupleGet
tuple_like_concept -> TupleLike
compatible_concept -> Compatbile
> Concept renaming tuple concepts

- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/input.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/alignment_file/output_format_concept.hpp
- include/seqan3/std/algorithm
- test/unit/io/alignment_file/CMakeLists.txt
- test/unit/io/alignment_file/alignment_file_format_test_template.hpp
- test/unit/io/alignment_file/alignment_file_input_test.cpp
- test/unit/io/alignment_file/alignment_file_output_test.cpp
- test/unit/io/alignment_file/format_bam_test.cpp
- test/unit/io/alignment_file/format_sam_test.cpp
**Best reviewed commit by commit.**
Blocked by ~#1009~ and ~#1026~ 
Todos:
> [FEATURE] Alignment file format BAM

- doc/tutorial/concepts/custom_validator_solution1.cpp
- doc/tutorial/concepts/custom_validator_solution2.cpp
- doc/tutorial/concepts/index.md
- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/alphabet/composite/alphabet_variant.hpp
- include/seqan3/alphabet/composite/detail.hpp
- include/seqan3/argument_parser/all.hpp
- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/validators.hpp
- include/seqan3/core/concept/core_language.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/detail/misc_input.hpp
- include/seqan3/io/detail/misc_output.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/stream/char_operations.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
- include/seqan3/range/view/to_lower.hpp
- include/seqan3/range/view/to_upper.hpp
- test/unit/argument_parser/format_parse_validators_test.cpp
alphabet_tuple_base_concept -> AlphabetTupleBase
validator_concept -> Validator
char_concept -> Char
> Concept renaming

- .travis.yml
- doc/tutorial/argument_parser/disable_version_check.cpp
- doc/tutorial/argument_parser/index.md
- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/auxiliary.hpp
- include/seqan3/argument_parser/detail/format_parse.hpp
- include/seqan3/argument_parser/detail/version_check.hpp
- include/seqan3/io/detail/safe_filesystem_entry.hpp
- test/unit/argument_parser/detail/CMakeLists.txt
- test/unit/argument_parser/detail/format_help_test.cpp
- test/unit/argument_parser/detail/format_html_test.cpp
- test/unit/argument_parser/detail/version_check_debug_test.cpp
- test/unit/argument_parser/detail/version_check_release_test.cpp
- test/unit/argument_parser/detail/version_check_test.hpp
- test/unit/argument_parser/format_parse_test.cpp
- test/unit/argument_parser/format_parse_validators_test.cpp
Resolves #748 
Still WIP.
Todos:
> [FEATURE] Argument parser version check

- doc/tutorial/argument_parser/index.md
- doc/tutorial/pairwise_alignment/index.md
- doc/tutorial/ranges/index.md
- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/argument_parser/validators.hpp
- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/input_format_concept.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/structure_file/input_format_concept.hpp
- include/seqan3/io/structure_file/output_format_concept.hpp
- include/seqan3/range/container/small_vector.hpp
- include/seqan3/range/view/take.hpp
Fixing documentation with old concept names.
> Fixing doc with wrong concept names

- include/seqan3/io/alignment_file/input_format_concept.hpp
- include/seqan3/io/alignment_file/input_options.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
- include/seqan3/io/structure_file/output_format_concept.hpp
- test/snippet/io/structure_file/structure_file_input.cpp
- test/snippet/io/structure_file/structure_file_output.cpp
- test/unit/io/alignment_file/alignment_file_output_test.cpp
- test/unit/io/detail/in_file_iterator_test.cpp
- test/unit/io/detail/out_file_iterator_test.cpp
- test/unit/io/structure_file/structure_file_input_test.cpp
- test/unit/io/structure_file/structure_file_output_test.cpp
> Rename structure file input and output

- test/seqan3-test.cmake
> [INFRA] fix #281: CMake generator "Ninja" does not work

- include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp
- test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
> [FIX] front coordinate for semi-global edit distance alignment

- doc/tutorial/introduction/index.md
- include/seqan3/core/pod_tuple.hpp
- include/seqan3/core/simd/detail/default_simd_length.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/header.hpp
- include/seqan3/io/alignment_file/input.hpp
- include/seqan3/io/alignment_file/input_format_concept.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/sequence_file/input_format_concept.hpp
- include/seqan3/io/stream/concept.hpp
- include/seqan3/io/structure_file/input_format_concept.hpp
Some more fixes for documentation
> Doco fixes

- include/seqan3/search/algorithm/all.hpp
- include/seqan3/search/algorithm/configuration/all.hpp
- include/seqan3/search/algorithm/configuration/max_error.hpp
- include/seqan3/search/algorithm/configuration/max_error_rate.hpp
- include/seqan3/search/algorithm/configuration/mode.hpp
- include/seqan3/search/algorithm/configuration/output.hpp
- include/seqan3/search/algorithm/search.hpp
- include/seqan3/search/all.hpp
- include/seqan3/search/fm_index/all.hpp
- include/seqan3/search/fm_index/bi_fm_index.hpp
- include/seqan3/search/fm_index/concept.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- test/snippet/search/bi_fm_index.cpp
- test/snippet/search/bi_fm_index_collection.cpp
- test/snippet/search/configuration_default.cpp
- test/snippet/search/configuration_error.cpp
- test/snippet/search/configuration_error_rate.cpp
- test/snippet/search/configuration_modes.cpp
- test/snippet/search/configuration_output.cpp
I banished all the todo I couldn't readily answer into the dev docs.
In particular run times and space consumptions since this is also very poorly documented in the SDSL.
> [DOC] Improve search docs

- .jenkinsfile
> [FIX] Redirect home directory on docker builds wo build specific workspace.

- .jenkinsfile
- include/seqan3/argument_parser/detail/version_check.hpp
- test/unit/argument_parser/detail/version_check_debug_test.cpp
- test/unit/argument_parser/detail/version_check_release_test.cpp
- test/unit/argument_parser/detail/version_check_test.hpp
> [INFRA] Stops active builds if superseded by new one.

- include/seqan3/alphabet/nucleotide/rna15.hpp
- include/seqan3/alphabet/nucleotide/rna5.hpp
Resolves #1114 
(Snippets compile and run on macOS+Linux gcc-8.3.0 Release and Debug)
> [FIX] Fix structure file snippets for gcc8

- .github/issue_template/bug_report.md
- .github/issue_template/feature_request.md
- .github/issue_template/question.md
- .github/issue_template/task.md
> [DOC] add issue template

- include/seqan3/range/view/deep.hpp
- include/seqan3/range/view/detail.hpp
Who let me get away with making classes without constructors?
> [FIX] add constructors

- include/seqan3/io/detail/misc_input.hpp
- test/unit/io/sequence_file/sequence_file_input_test.cpp
> [FIX] Adds possible gz extension detection when detecting bgzf stream.

- doc/tutorial/read_mapper/read_mapper_step2.cpp
- doc/tutorial/read_mapper/read_mapper_step3.cpp
- doc/tutorial/read_mapper/read_mapper_step4.cpp
- doc/tutorial/search/search_small_snippets.cpp
- doc/tutorial/search/search_solution1.cpp
- include/seqan3/search/fm_index/bi_fm_index.hpp
- include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
- include/seqan3/search/fm_index/concept.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- test/unit/search/fm_index/bi_fm_index_aa27_test.cpp
- test/unit/search/fm_index/bi_fm_index_char_test.cpp
- test/unit/search/fm_index/bi_fm_index_dna4_test.cpp
- test/unit/search/fm_index/fm_index_collection_test_template.hpp
- test/unit/search/fm_index/fm_index_dna4_test.cpp
- test/unit/search/fm_index/fm_index_test_template.hpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test.cpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_test.cpp
- test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp
- test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp
- test/unit/search/search_collection_test.cpp
- test/unit/search/search_test.cpp
> [MISC] Change bool to strong enum in index template parameter

- include/seqan3/io/stream/iterator.hpp
> [MSIC] Improve istreambuf_iterator for disc input.

- include/seqan3/argument_parser/detail/version_check.hpp
fix a line introduced by #1090
> [FIX] there is no #elseif

- test/unit/range/detail/random_access_iterator_test.cpp
- test/unit/range/iterator_test_template.hpp
- test/unit/range/view/view_istreambuf_test.cpp
As a follow up, all views/container/decorators should be tested with this template.
> [TEST] Add iterator test template.

- doc/tutorial/argument_parser/index.md
> [DOC] Add full solution at the end of the argument parser tutorial.

- .jenkinsfile
Enables the step view per node on blue ocean view in jenkins.
> [INFRA] Make steps view visible again in blue ocean.

- include/seqan3/range/decorator/gap_decorator.hpp
- test/unit/range/decorator/gap_decorator_test.cpp
This will provide random access iterators that are *not guaranteed to operate in constant time*.
> [FEATURE] begin_ra() and end_ra() for the gap_decorator.

- include/seqan3/std/iterator
- include/seqan3/std/ranges
- include/seqan3/std/span
Adapts the proposal [p1394r3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1394r3.pdf) to add  range based constructor.
> [MISC] Add range based constructor to span

- include/seqan3/contrib/stream/bgzf_istream.hpp
- include/seqan3/contrib/stream/bgzf_stream_util.hpp
- include/seqan3/io/detail/magic_header.hpp
- include/seqan3/io/detail/misc_input.hpp
- test/unit/io/alignment_file/alignment_file_input_test.cpp
- test/unit/io/alignment_file/alignment_file_output_test.cpp
- test/unit/io/alignment_file/format_bam_test.cpp
Fixes #1106 
Blocked by ~~#1224~~
> Fix issues with missing zlib

- include/seqan3/alignment/pairwise/alignment_result.hpp
Some follow up of a comment in #1236 already merged in #1229.
> [DOC] Small improvements to documentation of the alignment result class.

- include/seqan3/range/views/char_to.hpp
- include/seqan3/range/views/complement.hpp
- include/seqan3/range/views/rank_to.hpp
- include/seqan3/range/views/to_char.hpp
- include/seqan3/range/views/to_lower.hpp
- include/seqan3/range/views/to_rank.hpp
- include/seqan3/range/views/to_upper.hpp
- include/seqan3/range/views/trim.hpp
> [DOC] Fix deep views documentation.

- include/seqan3/std/algorithm
- include/seqan3/std/charconv
- include/seqan3/std/concepts
- include/seqan3/std/filesystem
- include/seqan3/std/iterator
- include/seqan3/std/new
- include/seqan3/std/ranges
- include/seqan3/std/type_traits
> [MISC] Add c++ shebang

- doc/howto/porting/index.md
> [DOC] Update howto porting with differences in the version check feature.

- include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
- include/seqan3/search/fm_index/fm_index_cursor.hpp
- test/unit/search/search_collection_test.cpp
- test/unit/search/search_test.cpp
> [FEATURE] Allow convertible queries in search

- include/seqan3/core/simd/view_to_simd.hpp
- include/seqan3/range/views/char_to.hpp
- include/seqan3/range/views/complement.hpp
- include/seqan3/range/views/convert.hpp
- include/seqan3/range/views/drop.hpp
- include/seqan3/range/views/get.hpp
- include/seqan3/range/views/interleave.hpp
- include/seqan3/range/views/istreambuf.hpp
- include/seqan3/range/views/pairwise_combine.hpp
- include/seqan3/range/views/persist.hpp
- include/seqan3/range/views/rank_to.hpp
- include/seqan3/range/views/repeat.hpp
- include/seqan3/range/views/repeat_n.hpp
- include/seqan3/range/views/single_pass_input.hpp
- include/seqan3/range/views/slice.hpp
- include/seqan3/range/views/take.hpp
- include/seqan3/range/views/take_exactly.hpp
- include/seqan3/range/views/take_line.hpp
- include/seqan3/range/views/take_until.hpp
- include/seqan3/range/views/to_char.hpp
- include/seqan3/range/views/to_lower.hpp
- include/seqan3/range/views/to_rank.hpp
- include/seqan3/range/views/to_upper.hpp
- include/seqan3/range/views/translate.hpp
- include/seqan3/range/views/translate_join.hpp
- include/seqan3/range/views/trim.hpp
- include/seqan3/range/views/view_all.hpp
- include/seqan3/search/algorithm/search.hpp
- test/documentation/seqan3_doxygen_cfg.in
> [DOC] Add header_file doxygen command.

- include/seqan3/alphabet/alphabet_base.hpp
- include/seqan3/alphabet/aminoacid/aminoacid_base.hpp
- include/seqan3/alphabet/cigar/cigar.hpp
- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/alphabet/composite/alphabet_variant.hpp
- include/seqan3/alphabet/concept.hpp
- include/seqan3/alphabet/detail/alphabet_proxy.hpp
- include/seqan3/alphabet/detail/hash.hpp
- include/seqan3/alphabet/nucleotide/nucleotide_base.hpp
- include/seqan3/alphabet/quality/qualified.hpp
- test/snippet/alphabet/cigar/cigar.cpp
- test/snippet/alphabet/cigar/cigar_op.cpp
- test/unit/alphabet/cigar/cigar_test.cpp
- test/unit/alphabet/cigar/debug_stream_cigar_test.cpp
- test/unit/alphabet/composite/composite_integration_test.cpp
- test/unit/alphabet/detail/alphabet_proxy_test.cpp
fixes #1268 
I recommend reviewing commit-wise.
> Resolve open Alphabet TODOs

- include/seqan3/search/fm_index/bi_fm_index.hpp
- include/seqan3/search/fm_index/concept.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- include/seqan3/search/fm_index/fm_index_cursor.hpp
- test/unit/search/fm_index/fm_index_collection_test_template.hpp
- test/unit/search/fm_index/fm_index_test_template.hpp
> [FIX] visibility errors on gcc - search

- include/seqan3/core/detail/pack_algorithm.hpp
> [FIX] visibility errors on gcc - core

- include/seqan3/alignment/configuration/detail.hpp
- test/unit/alignment/configuration/align_config_common_test.cpp
> Alignment Configurations for vectorisation and parallel

- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
> [FIX] visibility errors on gcc - io

- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/alphabet/concept.hpp
- include/seqan3/alphabet/detail/alphabet_proxy.hpp
- include/seqan3/alphabet/nucleotide/concept.hpp
- include/seqan3/alphabet/quality/concept.hpp
- include/seqan3/alphabet/structure/concept.hpp
- test/unit/alphabet/composite/alphabet_variant_test.cpp
- test/unit/alphabet/detail/alphabet_proxy_test.cpp
- test/unit/alphabet/nucleotide/sam_dna16_test.cpp
> [FIX] visibility errors on gcc - alphabet

- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/core/detail/test_accessor.hpp
- test/unit/argument_parser/detail/version_check_test.hpp
> [FIX] visibility errors on gcc - argument_parser

- include/seqan3/alignment/configuration/align_config_result.hpp
- test/snippet/alignment/configuration/align_cfg_result_example.cpp
- test/unit/alignment/configuration/align_config_common_test.cpp
- test/unit/alignment/configuration/align_config_result_test.cpp
> [MISC] Add score type template argument to align_cfg::result.

- include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
- include/seqan3/alignment/matrix/detail/alignment_score_matrix_one_column_banded.hpp
- include/seqan3/alignment/matrix/edit_distance_score_matrix_full.hpp
- include/seqan3/alignment/matrix/edit_distance_trace_matrix_full.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp
- include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp
- include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
- include/seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp
- include/seqan3/alignment/scoring/scoring_scheme_base.hpp
- include/seqan3/alignment/scoring/scoring_scheme_concept.hpp
- test/unit/alignment/pairwise/policy/affine_gap_policy_test.cpp
> [FIX] visibility errors on gcc - alignment

- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/detail/alignment_algorithm_state.hpp
- include/seqan3/alignment/pairwise/policy/affine_gap_init_policy.hpp
- include/seqan3/alignment/pairwise/policy/affine_gap_policy.hpp
- include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp
- include/seqan3/alignment/pairwise/policy/all.hpp
- include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp
- test/unit/alignment/pairwise/policy/affine_gap_init_policy_test.cpp
- test/unit/alignment/pairwise/policy/affine_gap_policy_test.cpp
* Removes a lot of duplicated code from the alignment algorithm.
* Uses sequence instead of range in the interface naming
* Makes code more readable
* Removes unnecessary if checks and make code more stable
> [MISC] Some general clean up of the alignment algorithm.

- include/seqan3/io/alignment_file/format_sam.hpp
@smehringer I made you first and last reviewer 😉  . I don't think someone else needs to review this first.
> [MISC] Minor refactorisation of transfer_soft_clipping_to to make it more readable.

- doc/tutorial/alphabet/alphabet_main.cpp
- include/seqan3/range/container/bitcompressed_vector.hpp
- include/seqan3/range/container/concatenated_sequences.hpp
- include/seqan3/range/container/dynamic_bitset.hpp
- include/seqan3/range/container/small_string.hpp
- include/seqan3/range/container/small_vector.hpp
- include/seqan3/range/decorator/gap_decorator.hpp
- include/seqan3/range/views/pairwise_combine.hpp
- include/seqan3/range/views/translate_join.hpp
- test/performance/range/gap_decorator_helper.hpp
- test/performance/range/gap_decorator_rand_write_benchmark.cpp
- test/snippet/alignment/matrix/detail/alignment_matrix_column_major_range_base.cpp
- test/unit/range/container/small_vector_test.cpp
- test/unit/range/decorator/gap_decorator_test.cpp
- test/unit/range/views/view_enforce_random_access_test.cpp
> [FIX] visibility errors on gcc - range

- include/seqan3/alignment/pairwise/detail/concept.hpp
- include/seqan3/alignment/pairwise/edit_distance_algorithm.hpp
> [FEATURE] Adds range aware operator to edit distance algorithm.

- include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp
> [MISC] Merge constructors by making exec policy optional parameter.

- include/seqan3/alignment/matrix/alignment_optimum.hpp
- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/detail/alignment_algorithm_state.hpp
- include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp
- include/seqan3/core/simd/simd_algorithm.hpp
- test/unit/alignment/matrix/alignment_optimum_test.cpp
* Adapts the alignment optimum to work for vectorised alignments.
* Adapts the alignment algorithm state to work for vectorised alignments.
> [FEATURE] Make some internal data structures simd aware.

- include/seqan3/argument_parser/detail/format_base.hpp
- include/seqan3/core/algorithm/configuration.hpp
- include/seqan3/core/pod_tuple.hpp
- include/seqan3/core/tuple_utility.hpp
- include/seqan3/core/type_list/traits.hpp
- include/seqan3/core/type_traits/transformation_trait_or.hpp
- include/seqan3/io/alignment_file/input.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/detail/misc.hpp
- include/seqan3/io/detail/record.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
- test/unit/alignment/scoring_scheme_test.cpp
- test/unit/alphabet/aminoacid/aminoacid_conversion_integration_test.cpp
- test/unit/alphabet/nucleotide/nucleotide_conversion_integration_test.cpp
- test/unit/alphabet/quality/quality_conversion_integration_test.cpp
- test/unit/core/type_list_test.cpp
- test/unit/core/type_traits/range_iterator_test.cpp
This isn't done yet, but I thought I'd upload it in case you wanted to start reviewing.
Fixes #1247.
Blocked by ~~#1214~~ and ~~#1273~~.
> [INTERNAL] Remove meta from our code.

- include/seqan3/alphabet/concept.hpp
> [MISC] Improve error message of alphabet with typeid.

- include/seqan3/alignment/all.hpp
- include/seqan3/alignment/pairwise/align_pairwise.hpp
- include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp
- test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/global_affine_unbanded_collection_test.cpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
Resolves #1336
Signed-off-by: Lydia Buntrock <lydia.buntrock@fu-berlin.de>
> [FEATURE] Apply vectorise and parallel configurations (#1336)

- include/seqan3/core/parallel/detail/spin_delay.hpp
Partially addresses https://github.com/seqan/seqan3/issues/1381
> [FIX] support spins on armel armhf arm64

- include/seqan3/core/parallel/detail/spin_delay.hpp
> [FIX] explicit spin op for armel

- .editorconfig
> [MISC] basic editorconfig

- doc/tutorial/alignment_file/alignment_file_snippets.cpp
- doc/tutorial/alignment_file/alignment_file_solution2.cpp
- doc/tutorial/introduction/introduction_align.cpp
- doc/tutorial/sequence_file/sequence_file_snippets.cpp
- doc/tutorial/sequence_file/sequence_file_solution1.cpp
- doc/tutorial/sequence_file/sequence_file_solution2.cpp
- doc/tutorial/sequence_file/sequence_file_solution3.cpp
- doc/tutorial/sequence_file/sequence_file_solution4.cpp
- doc/tutorial/sequence_file/sequence_file_solution5.cpp
- test/include/seqan3/test/tmp_filename.hpp
- test/unit/test/tmp_filename_test.cpp
Resolves #1292 
Also see [this card](https://github.com/orgs/seqan/projects/4#card-27661279)
> [FIX] Remove temporary files

- test/unit/core/simd/simd_test.cpp
fix some issues with simd tests on other platforms (see #1381) and I also removed the namespace seqan3.
> [TEST] fix some issues with simd tests on other platforms

- include/seqan3/core/simd/detail/simd_algorithm_sse4.hpp
- include/seqan3/core/simd/simd_algorithm.hpp
Fixes line length and a small typo.
> [DOC] fix simd algorithms documentation

- .jenkinsfile
- include/seqan3/io/detail/misc_input.hpp
> [INFRA] Enable catalina g++-9 builds.

- include/seqan3/core/simd/simd_algorithm.hpp
This takes one step towards making simd buildable on all architectures (see #1381) for gcc.
> [MISC] simd algorithms: make fallbacks available for all simd implementations

- include/seqan3/alignment/configuration/align_config_debug.hpp
- include/seqan3/alignment/configuration/align_config_parallel.hpp
- include/seqan3/alignment/pairwise/align_result_selector.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- include/seqan3/core/algorithm/configuration_element_debug_mode.hpp
- include/seqan3/core/algorithm/configuration_element_parallel_mode.hpp
- include/seqan3/search/configuration/all.hpp
- include/seqan3/search/configuration/detail.hpp
- include/seqan3/search/configuration/parallel.hpp
- test/snippet/search/configuration_parallel.cpp
- test/unit/search/search_configuration_test.cpp
> [MISC, FEATURE] Introduce global parallel config and add search_cfg::parallel

- build_system/seqan3-config.cmake
This partially supersedes #1386
> [INFRA] make submodule search customizable

- doc/howto/subcommand_argument_parser/subcommand_arg_parse.cpp
- doc/howto/write_a_view/solution_iterator.cpp
- doc/howto/write_a_view/solution_view.cpp
- doc/howto/write_a_view/view_exercise1.cpp
- doc/howto/write_a_view/view_exercise2.cpp
- doc/setup/quickstart_cmake/hello_world.cpp
(&& replace std::endl)
resolves #1442
Signed-off-by: Lydia Buntrock <lydia.buntrock@fu-berlin.de>
> [DOC] remove 'using namespace seqan3' from seqan3/doc

- include/seqan3/io/alignment_file/format_sam_base.hpp
- test/unit/io/alignment_file/format_sam_test.cpp
Resolves #1457
To the diff: I reallt just transolcated the parsing of the header inside the while loop.. but translocations and git don't go together nicely :woman_shrugging:
> [FIX] Make @HD line in SAM format optional.

- include/seqan3/io/record.hpp
> [MISC] Make deprecated values valid for usage within io.

- include/seqan3/search/algorithm/detail/search_traits.hpp
> [FEATURE] Adds search traits for easy access to static configuration information.

- include/seqan3/io/alignment_file/format_bam.hpp
> [FIX] Fixes problem when reading core bam record when stream ends unexpected.

- include/seqan3/search/algorithm/detail/search.hpp
- include/seqan3/search/algorithm/search.hpp
> [MISC] Some internal refactoring of the search algorithm.

- test/unit/CMakeLists.txt
This PR makes googletests more verbose:
before:
```
core/char_operations % ctest
Test project /home/marehr/develope/seqan3-build/gcc-9-debug/core/char_operations
Start 1: core/char_operations/char_predicate_test
1/1 Test #1: core/char_operations/char_predicate_test ...   Passed    0.00 sec
100% tests passed, 0 tests failed out of 1
```
after this pr:
```
core/char_operations % ctest
Test project /home/marehr/develope/seqan3-build/gcc-9-debug/core/char_operations
Start  1: core/char_operations/char_predicate_test::char_predicate_.basic
1/37 Test  #1: core/char_operations/char_predicate_test::char_predicate_.basic .........................   Passed    0.00 sec
Start  2: core/char_operations/char_predicate_test::char_predicate_.char_predicate_msg
2/37 Test  #2: …
```
> [TEST] ctest: use gtest_discover_tests

- include/seqan3/version.hpp
Version bump that should have followed the 3.0.0 release
blocked by #1507
> [NOP] Version bump 3.0.1

- .github/ISSUE_TEMPLATE/release-checklist.md
@seqan/core Did we forget anything?
> [MISC] Add release checklist issue template.

- CHANGELOG.md
@seqan/all Please check the Changelog and tell me if I missed any feature or notable bug fix.
@marehr Can you write one or two sentences about the build system changes?
@rrahn What should I write about the state of the vectorisation?
> [DOC] Update Changelog.md

- test/documentation/CMakeLists.txt
- test/documentation/seqan3_doxygen_cfg.in
Display the version number next to the seqan header.
> [DOC] Add SeqAn version in doxygen output

- include/seqan3/version.hpp
> [MISC] Version bump 3.0.2

- test/unit/io/detail/safe_filesystem_entry_test.cpp
> [FIX] safe filesystem entry test on jenkins

- test/performance/alignment/edit_distance_unbanded_benchmark.cpp
- test/performance/alignment/global_affine_alignment_benchmark.cpp
- test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp
- test/performance/alignment/local_affine_alignment_benchmark.cpp
- test/performance/core/simd/simd_algorithm_benchmark.cpp
- test/performance/core/simd/view_to_simd_chunk_benchmark.cpp
- test/performance/io/format_fasta_benchmark.cpp
- test/performance/io/format_vienna_benchmark.cpp
- test/performance/io/stream_input_benchmark.cpp
- test/performance/io/stream_output_benchmark.cpp
- test/performance/search/search_benchmark.cpp
> [NOP] Remove using namespace seqan3/test performance (without /range)

- test/seqan3-test.cmake
- test/unit/argument_parser/detail/CMakeLists.txt
- test/unit/argument_parser/detail/format_help_test.cpp
> [INFRA] Support vendoring of dependency headers

- include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
Seems like we don't have any tests for debug printing. Printing the alignment at least was broken.
I don't have time to add tests, but its maybe something to keep track of.
> [FIX] alignment pretty printing

- include/seqan3/alignment/scoring/all.hpp
- test/unit/argument_parser/detail/format_man_test.cpp
- test/unit/search/search_scheme_algorithm_test.cpp
All tests ran probably. It's my first PR so please give me feedback on every little thing. :)
Resolves #1505
> [TEST] Resolves issue #1505 by removing trailing white-spaces, changing indentation and changing string initialization.

- test/documentation/seqan3_doxygen_cfg.in
- test/documentation/seqan3_footer.html
- test/documentation/version.js
- test/documentation/version.php
Try it live https://docs.seqan.de/seqan/dev_script/
This would require a rebuild of the versioned documentations (3.0.0 and 3.0.1).
> [DOC] Add version selector to doxygen

- test/unit/range/container/aligned_allocator_test.cpp
> [FIX] Not valid to deference end of list iterator

- .github/ISSUE_TEMPLATE/release-checklist.md
> [DOC] Update release check list.

- test/documentation/version.php
> [DOC] Exclude index.html from version selector

- CHANGELOG.md
belongs to PR #1500
Signed-off-by: Lydia Buntrock <lydia.buntrock@fu-berlin.de>
> [DOC] change changelog for Doxygen version 1.8.17

- .github/workflows/documentation.yaml
> [DOC] Add github documentation action

- .github/workflows/documentation.yaml
> [FIX] Directory in github action

- .gitpod.yml
> [INFRA] add .gitpod.yml to checkout and build seqan3 in an online editor

- test/unit/core/add_enum_bitwise_operators_test.cpp
- test/unit/core/algorithm/bound_test.cpp
- test/unit/core/algorithm/configuration_test.cpp
- test/unit/core/algorithm/pipeable_config_element_test.cpp
- test/unit/core/char_operations/char_predicate_test.cpp
- test/unit/core/concept/cereal_test.cpp
- test/unit/core/debug_stream_test.cpp
- test/unit/core/detail/int_types_test.cpp
- test/unit/core/detail/pack_algorithm_test.cpp
- test/unit/core/detail/strong_type_test.cpp
- test/unit/core/parallel/detail/reader_writer_manager_test.cpp
- test/unit/core/pod_tuple_test.cpp
- test/unit/core/simd/debug_stream_simd_test.cpp
- test/unit/core/simd/detail/builtin_simd_test.cpp
- test/unit/core/simd/detail/default_simd_backend_test.cpp
- test/unit/core/simd/detail/default_simd_length_builtin_simd_test.cpp
- test/unit/core/simd/simd_algorithm_test.cpp
- test/unit/core/simd/view_to_simd_test.cpp
- test/unit/core/tuple_utility_test.cpp
- test/unit/core/type_list_test.cpp
- test/unit/core/type_traits/basic_test.cpp
- test/unit/core/type_traits/deferred_crtp_base_test.cpp
- test/unit/core/type_traits/lazy_test.cpp
- test/unit/core/type_traits/range_iterator_test.cpp
- test/unit/core/type_traits/template_inspection_test.cpp
- test/unit/core/type_traits/transformation_trait_or_test.cpp
> [MISC] Remove 'using namespace seqan3' from test/unit/core.

- include/seqan3/core/debug_stream.hpp
> [FIX] debug_stream needs to include <iostream>

- include/seqan3/io/sequence_file/format_embl.hpp
- include/seqan3/io/sequence_file/format_fasta.hpp
- include/seqan3/io/sequence_file/format_fastq.hpp
- include/seqan3/io/stream/iterator.hpp
- test/performance/io/CMakeLists.txt
- test/performance/io/lowlevel_stream_output_benchmark.cpp
- test/snippet/io/detail/iterator_write_range.cpp
- test/unit/io/stream/CMakeLists.txt
- test/unit/io/stream/fast_streambuf_iterator_test.cpp
Analoguesly to the fast_istreambuf_iterator, this ostreambuf iterator does less virtual function calls.
Still WIP!
Resolves #1570
> [FEATURE] fast ostream buf iterator

- include/seqan3/search/algorithm/search.hpp
- test/snippet/search/algorithm/search.cpp
Adds a snippet to search, to make doc easier understandable.
> [DOC] Add snippet to search

- include/seqan3/io/record.hpp
This increases performance since we avoid new memory allocation when default constructing a new sequence container. Additionally, if the sequence length for each record does not change, push_back is more efficient because it never has to resize the container.
Resolves #1579
> [FEATURE] Improve performance by calling clear() on containers in a record.

- include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
- test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
> [FIX] IBF Issues

- doc/setup/quickstart_cmake/index.md
Include all files and their extensions.
> [DOC] Correct directory structure

- doc/tutorial/introduction/index.md
- doc/tutorial/introduction/introduction_align.cpp
Fixes https://github.com/seqan/seqan3/issues/1608 1.0.1 and 1.1.1
The changes in the snippet code focus on making the header includes more explicit and replace specific includes with the "all" header, where appropriate.
> [DOC] Improve tutorial; section "First steps"

- include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
- include/seqan3/search/fm_index/fm_index_cursor.hpp
> [MISC] Replace template parameter csa-type

- include/seqan3/argument_parser/validators.hpp
- test/unit/argument_parser/format_parse_validators_test.cpp
> [FIX] Fix value_list_validator type deduction for char.

- include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp
- include/seqan3/search/algorithm/detail/search_trivial.hpp
- include/seqan3/search/fm_index/bi_fm_index.hpp
- include/seqan3/search/fm_index/concept.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- test/snippet/search/bi_fm_index.cpp
- test/snippet/search/bi_fm_index_collection.cpp
- test/snippet/search/bi_fm_index_cursor_cycle.cpp
- test/snippet/search/bi_fm_index_cursor_extend_left_seq.cpp
- test/snippet/search/bi_fm_index_cursor_to_fwd_cursor.cpp
- test/snippet/search/bi_fm_index_cursor_to_rev_cursor.cpp
- test/snippet/search/bi_fm_index_cursor_to_rev_cursor_collection.cpp
- test/snippet/search/fm_index.cpp
- test/snippet/search/fm_index_collection.cpp
- test/snippet/search/fm_index_cursor.cpp
- test/unit/search/fm_index/fm_index_collection_test_template.hpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_test_template.hpp
- test/unit/search/search_scheme_algorithm_test.cpp
> [MISC] Rename `.begin()` on the the indexes to `.cursor()`

- test/unit/range/container/aligned_allocator_test.cpp
- test/unit/range/container/container_concept_test.cpp
- test/unit/range/container/container_of_container_test.cpp
- test/unit/range/container/container_test.cpp
- test/unit/range/container/debug_stream_container_of_container_test.cpp
- test/unit/range/container/debug_stream_container_test.cpp
- test/unit/range/container/dynamic_bitset_test.cpp
- test/unit/range/container/small_vector_test.cpp
> [MISC] Remove 'using namespace seqan3' from test/unit/range/container.

- include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- include/seqan3/search/fm_index/fm_index_cursor.hpp
Some minor improvements while debugging some search related code.
> [MISC] Some small improvements for stable search.

- include/seqan3/io/alignment_file/input.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/sequence_file/input.hpp
- include/seqan3/io/sequence_file/output.hpp
- include/seqan3/io/structure_file/input.hpp
- include/seqan3/io/structure_file/output.hpp
This makes it also visible that we might want a CRTP base class for files since I had to copy and paste quite some code..
> [FEATURE] Increase I/O performance by using a larger buffer when reading from file.

- include/seqan3/io/sequence_file/input_format_concept.hpp
- test/performance/io/format_vienna_benchmark.cpp
- test/snippet/io/structure_file/structure_file_input_mod_traits.cpp
This does not implicitly include
* dna4
* dna15
* rna5
* rna15
> [MISC] limit includes in input_format_concept.hpp

- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/alignment_result_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
- test/unit/alignment/pairwise/execution/execution_handler_parallel_test.cpp
- test/unit/alignment/pairwise/execution/execution_handler_sequential_test.cpp
- test/unit/alignment/pairwise/execution/execution_handler_template.hpp
- test/unit/alignment/pairwise/fixture/alignment_fixture.hpp
- test/unit/alignment/pairwise/fixture/global_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/global_affine_unbanded.hpp
- test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp
- test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp
- test/unit/alignment/pairwise/fixture/local_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/local_affine_unbanded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_affine_unbanded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
- test/unit/alignment/pairwise/global_affine_unbanded_collection_simd_test.cpp
- test/unit/alignment/pairwise/global_affine_unbanded_collection_test.cpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
- test/unit/alignment/pairwise/policy/affine_gap_init_policy_test.cpp
- test/unit/alignment/pairwise/policy/affine_gap_policy_test.cpp
> [MISC] remove 'using namespace seqan3' from test/unit/alignment/pairwise

- doc/tutorial/concepts/index.md
Small fix in task description of 'Exercise: Static polymorphism with alphabets II'.
Fixes  1.3.1 of https://github.com/seqan/seqan3/issues/1608
> [DOC] tutorial/concepts: grammar fix

- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/argument_parser/detail/format_help.hpp
- include/seqan3/argument_parser/validators.hpp
- include/seqan3/core/detail/pack_algorithm.hpp
- include/seqan3/io/detail/misc.hpp
- test/unit/argument_parser/detail/format_html_test.cpp
- test/unit/argument_parser/format_parse_validators_test.cpp
- test/unit/test/seqan2_test.cpp
> [MISC] remove unnecessary includes

- include/seqan3/std/span
> [FIX] Add missing front and back member function to span

- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/detail/misc.hpp
- test/performance/io/format_vienna_benchmark.cpp
- test/snippet/io/structure_file/structure_file_input_mod_traits.cpp
> [MISC] io: move include from io/detail/misc to io/alignment_file/format_sam

- include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp
- include/seqan3/alignment/pairwise/align_result_selector.hpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
Fixes #1598: pairwise alignment does not work for some ranges
> Fixes #1598: pairwise alignment does not work for some ranges

- test/unit/range/views/adaptor_base_test.cpp
- test/unit/range/views/view_async_input_buffer_test.cpp
- test/unit/range/views/view_char_to_test.cpp
- test/unit/range/views/view_complement_test.cpp
- test/unit/range/views/view_convert_test.cpp
- test/unit/range/views/view_deep_test.cpp
- test/unit/range/views/view_drop_test.cpp
- test/unit/range/views/view_enforce_random_access_test.cpp
- test/unit/range/views/view_get_test.cpp
- test/unit/range/views/view_interleave_test.cpp
- test/unit/range/views/view_istreambuf_test.cpp
- test/unit/range/views/view_persist_test.cpp
- test/unit/range/views/view_rank_to_test.cpp
- test/unit/range/views/view_repeat_n_test.cpp
- test/unit/range/views/view_repeat_test.cpp
- test/unit/range/views/view_single_pass_input_test.cpp
- test/unit/range/views/view_slice_test.cpp
- test/unit/range/views/view_take_line_test.cpp
- test/unit/range/views/view_take_test.cpp
- test/unit/range/views/view_take_until_test.cpp
- test/unit/range/views/view_to_char_test.cpp
- test/unit/range/views/view_to_lower_test.cpp
- test/unit/range/views/view_to_rank_test.cpp
- test/unit/range/views/view_to_upper_test.cpp
- test/unit/range/views/view_translate_join_test.cpp
- test/unit/range/views/view_translate_test.cpp
- test/unit/range/views/view_trim_test.cpp
- test/unit/range/views/view_type_reduce_test.cpp
> [MISC] Remove 'using namespace seqan3' from test/unit/range/views.

- test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test.cpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_test.cpp
- test/unit/search/fm_index_cursor/bi_fm_index_cursor_test_template.hpp
- test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp
- test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp
- test/unit/search/fm_index_cursor/fm_index_cursor_test.cpp
- test/unit/search/fm_index_cursor/fm_index_cursor_test_template.hpp
Resolves https://github.com/seqan/seqan3/issues/1611
> [Test] Refactor index cursor tests

- include/seqan3/range/views/kmer_hash.hpp
- test/unit/range/views/view_kmer_hash_test.cpp
> [FIX] kmer_hash works for too small ranges

- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
Makes the code more readable in the alignment and the first step to make the edit distance algorithm use the alignment traits class.
> [MISC] Add bool constants in alignment traits to express what should be computed by the alignment.

- include/seqan3/search/detail/search.hpp
The following code change is completely equivalent to the one before but with redundant code removed.
> [MISC] Simplify redundant code.

- include/seqan3/search/detail/search.hpp
- include/seqan3/search/search.hpp
Best reviewed commit-by-commit!
> [MISC] Some small refactoring that removes the public function search_all.

- doc/tutorial/argument_parser/solution1.cpp
> [DOC] Update tutorial solution snippet argument_parser

- include/seqan3/alphabet/alphabet_base.hpp
- include/seqan3/alphabet/aminoacid/aminoacid_base.hpp
- include/seqan3/alphabet/aminoacid/translation.hpp
- include/seqan3/alphabet/composite/alphabet_variant.hpp
- include/seqan3/alphabet/detail/alphabet_proxy.hpp
- include/seqan3/alphabet/nucleotide/nucleotide_base.hpp
- include/seqan3/alphabet/quality/quality_base.hpp
- include/seqan3/core/algorithm/configuration.hpp
- include/seqan3/core/char_operations/predicate.hpp
- include/seqan3/core/char_operations/predicate_detail.hpp
- include/seqan3/core/detail/debug_stream_alphabet.hpp
- include/seqan3/core/detail/debug_stream_tuple.hpp
- include/seqan3/core/pod_tuple.hpp
- include/seqan3/core/type_traits/iterator.hpp
- include/seqan3/core/type_traits/range.hpp
- include/seqan3/core/type_traits/template_inspection.hpp
- include/seqan3/range/detail/inherited_iterator_base.hpp
- include/seqan3/range/detail/random_access_iterator.hpp
- include/seqan3/range/views/deep.hpp
- include/seqan3/range/views/repeat.hpp
- include/seqan3/std/span
This fix is part of seqan/product_backlog#53.
> requires clauses must be primary expressions

- test/unit/alignment/aligned_sequence_test.cpp
- test/unit/alignment/aligned_sequence_test_template.hpp
- test/unit/alignment/band/static_band_test.cpp
- test/unit/alignment/debug_stream_aligned_sequence_test.cpp
- test/unit/alignment/scoring/gap_scheme_test.cpp
- test/unit/alignment/scoring/scoring_scheme_test.cpp
- test/unit/alignment/scoring/simd_match_mismatch_scoring_scheme_test.cpp
- test/unit/alignment/scoring/simd_matrix_scoring_scheme_test.cpp
> [MISC] Remove 'using namespace seqan3' from test/unit/alignment/*.

- test/unit/alignment/matrix/detail/alignment_score_matrix_one_column_test.cpp
- test/unit/alignment/matrix/detail/trace_iterator_banded_test.cpp
- test/unit/alignment/matrix/detail/trace_iterator_test.cpp
- test/unit/contrib/parallel/buffer_queue_base_test.cpp
- test/unit/contrib/parallel/buffer_queue_parallel_test.cpp
- test/unit/core/bit_manipulation_test.cpp
- test/unit/core/char_operations/char_predicate_test.cpp
- test/unit/core/parallel/detail/latch_test.cpp
- test/unit/range/decorator/gap_decorator_test.cpp
- test/unit/range/detail/inherited_iterator_base_test.cpp
- test/unit/range/iterator_test_template.hpp
- test/unit/range/views/view_istreambuf_test.cpp
- test/unit/range/views/view_translate_join_test.cpp
- test/unit/test/tmp_filename_test.cpp
Last cleanup for test/unit/*.
Resolves #1576
> [MISC] Remove 'using namespace seqan3' from test/unit/*.

- include/seqan3/range/container/concatenated_sequences.hpp
- test/unit/range/container/container_of_container_test.cpp
> [FIX] use std::ranges::range_value_t

- include/seqan3/io/alignment_file/input.hpp
> [FIX] requires is missing a ;

- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp
The optimised alignment implements the naive global alignment with affine gap costs without encapsulating any functionality into policies.
This is the most performant implementation that could be measured for this kind of alignment.
It only computes global alignment and is not vectorised yet.
It also will already start with the new algorithm implementation which will be step-by-step refactored and put into the correct module structure.
This is a baseline implementation and the core function as it is placed there won't be there for long. But it allows to follow the refactoring process and always go back to a working version. So if not all variables have a proper name maybe that can be handled not too strict. 😄
> [FEATURE] Add new optimised dynamic alignment algorithm.

- include/seqan3/range/container/concatenated_sequences.hpp
This could have been the fix for #1731, but I just recently saw this
technique in the standard library. This solution should be a lot less
janky than the previous one. I tested it with gcc7, 8, 9 and 10 and it
worked without a problem.
I wanted to finish #1549 and after changing the definition of
`dimension_v` the previous construction of #1731 broke, so had to
rethink a solution for this.
> [FIX] a better fix for concatenated sequences?!

- test/documentation/version.js
This cleans up the js a bit and introduces the functionality to change versions while staying on the same page.
Examples (You can only switch once since this is `develop_` stuff and won't show up in the version selector of the main documentation):
The page exists in other versions - stay on page and switch version:
https://docs.seqan.de/seqan/develop_improved_version_select/tutorial_pairwise_alignment.html
The page does not exist in other versions - redirect to main page of selected version:
https://docs.seqan.de/seqan/develop_improved_version_select/tutorial_pairwise_alignment2.html
**Follow up Todo**:
Replace the `version.js` in the versioned documentation.
> [DOC] Improve version selector

- include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp
- include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp
- include/seqan3/argument_parser/detail/format_parse.hpp
- test/documentation/CMakeLists.txt
E.g. in:
https://docs.seqan.de/seqan/3-master-dev/classseqan3_1_1detail_1_1format__parse.html
https://docs.seqan.de/seqan/3-master-dev/classseqan3_1_1detail_1_1two__dimensional__matrix_1_1iterator__type.html
https://docs.seqan.de/seqan/3-master-dev/classseqan3_1_1detail_1_1two__dimensional__matrix__iterator__base.html
Properly fails:
> [FEATURE,DOC] Detect requires in doxygen output

- doc/tutorial/ranges/index.md
- doc/tutorial/ranges/range_snippets.cpp
- doc/tutorial/ranges/range_solution1.cpp
- doc/tutorial/ranges/range_solution3.cpp
Resolves part of #1608 (1.5)
Kept as separate commits for readability.
> Improvements to the Ranges section of the tutorial

- doc/tutorial/alignment_file/index.md
- doc/tutorial/search/index.md
> [DOC] fix typos tutorial

- include/seqan3/range/views/minimiser.hpp
- test/unit/range/views/view_minimiser_test.cpp
> [FIX] Make views::minimiser work on non-arithmetic values.

- test/unit/range/iterator_test_template.hpp
Before we always enabled a test if the iterator tag was "equal to" the bidirectional tag, but the test needs to be enabled also if it is the random access tag. Instead of testing for equality, we can use `std::derived_from`.
> [FIX] enable bidirectional tests for random_access iterators.

- include/seqan3/core/type_traits/iterator.hpp
- include/seqan3/core/type_traits/pre.hpp
- include/seqan3/core/type_traits/range.hpp
> [MISC] Deprecate type_traits range and iterator

- include/seqan3/core/simd/view_to_simd.hpp
- test/unit/core/simd/view_to_simd_test.cpp
In the old design we assumed that calling begin and end on the underlying range is always valid.
But this assumption does not necessarily hold in all cases.
This change ensures that empty slots in the batch are initialised correctly.
part of #1804
> [FIX] Fixes handling of non full batches in the to_simd view

- test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
some minor fixes for test and benchmark
> Optimise alignment/part2 fix tests and benchmarks

- CHANGELOG.md
Sorry, I forgot about that in the actual PR #1706
> [NOP] Add Changelog entry for the seqan3::search_result.

- include/seqan3/range/views/convert.hpp
- include/seqan3/range/views/take_until.hpp
> [FIX,DOC] Footnotes in view documentation

- .travis.yml
Fixes #1877
Blocked by #1879 and #1878
> [INFRA] travis: add gcc-10 -std=17

- include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp
- include/seqan3/alignment/pairwise/detail/policy_scoring_scheme.hpp
Adds a policy for simd affine gap recursion and to store the configured scoring scheme.
> Optimise alignment/part2 simd affine gap recursion and scoring scheme policy

- include/seqan3/range/views/take_until.hpp
- test/unit/range/views/view_kmer_hash_test.cpp
- test/unit/range/views/view_take_until_test.cpp
Resolves #1754 and restructures take_until a bit for better readability.
> Fix take until

- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp
- include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
Resolves https://github.com/seqan/product_backlog/issues/71
> [FEATURE] alignment improvement refactorisation - free end gap initialisation

- include/seqan3/range/views/async_input_buffer.hpp
- include/seqan3/range/views/enforce_random_access.hpp
- include/seqan3/range/views/kmer_hash.hpp
- include/seqan3/range/views/minimiser.hpp
- include/seqan3/range/views/pairwise_combine.hpp
- include/seqan3/range/views/single_pass_input.hpp
- include/seqan3/range/views/translate.hpp
- include/seqan3/range/views/translate_join.hpp
- include/seqan3/std/ranges
Part of https://github.com/seqan/product_backlog/issues/124
> [FIX] use std::ranges::ref_view instead of ranges one

- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/format_sam_base.hpp
- include/seqan3/io/sequence_file/format_genbank.hpp
- include/seqan3/io/stream/iterator.hpp
- include/seqan3/io/structure_file/format_vienna.hpp
- include/seqan3/std/iterator
- test/unit/std/concept/auxiliary_iterator.hpp
- test/unit/std/concept/iterator_test.cpp
>  [FIX] use std::cpp20::ostream[buf]_iterator instead of seqan3::ostream[buf]_iterator

- include/seqan3/alignment/matrix/detail/affine_cell_proxy.hpp
- include/seqan3/core/detail/debug_stream_range.hpp
Part three of https://github.com/seqan/seqan3/pull/1735.
> [FIX] cxx20: requires requires primary expressions

- doc/cookbook/custom_dna4.cpp
- doc/cookbook/index.md
- include/seqan3/alphabet/nucleotide/all.hpp
- include/seqan3/alphabet/nucleotide/dna4.hpp
- test/snippet/alphabet/nucleotide/dna4.cpp
A custom dna4 alphabet that converts all unknown characters to `A`.
See #1864 for the feature request.
> Cookbook: A custom dna4 alphabet

- include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
- test/performance/search/dream_index/interleaved_bloom_filter_benchmark.cpp
- test/snippet/search/dream_index/interleaved_bloom_filter_increase_bin_number_to.cpp
- test/snippet/search/dream_index/membership_agent_bulk_contains.cpp
- test/snippet/search/dream_index/membership_agent_construction.cpp
- test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/78
> [FEATURE] Allow concurrent calls to bulk_contains

- .travis.yml
- include/seqan3/alignment/matrix/detail/alignment_matrix_column_major_range_base.hpp
Part of  seqan/product_backlog#61
> [INFRA] Add gcc-10 -std=c++2a support; fixes seqan/product_backlog#61

- include/seqan3/range/views/pairwise_combine.hpp
- test/unit/range/views/view_pairwise_combine_test.cpp
> [FIX] Fixes empty pairwise combine view.

- test/performance/io/CMakeLists.txt
- test/performance/io/format_sam_benchmark.cpp
> [TEST] sam read benchmark.

- CHANGELOG.md
- doc/tutorial/read_mapper/read_mapper_step3.cpp
- doc/tutorial/read_mapper/read_mapper_step4.cpp
- doc/tutorial/search/search_solution3.cpp
- doc/tutorial/search/search_solution5.cpp
- include/seqan3/search/configuration/all.hpp
- include/seqan3/search/configuration/default_configuration.hpp
- include/seqan3/search/configuration/detail.hpp
- include/seqan3/search/configuration/output.hpp
- include/seqan3/search/detail/policy_search_result_builder.hpp
- include/seqan3/search/detail/search_configurator.hpp
- include/seqan3/search/detail/search_traits.hpp
- include/seqan3/search/search_result.hpp
- test/snippet/search/configuration_default.cpp
- test/snippet/search/configuration_output.cpp
- test/unit/search/search_collection_test.cpp
- test/unit/search/search_configuration_test.cpp
- test/unit/search/search_test.cpp
> [MISC] Rename reference_begin_pos to .._position.

- include/seqan3/alignment/all.hpp
- include/seqan3/alignment/band/all.hpp
- include/seqan3/search/configuration/all.hpp
Solves part of https://github.com/seqan/seqan3/issues/1027.
- add landing page description for band (Alignment)
- fix configuration table layout
> [DOC] Fix documentation issues

- test/performance/io/format_sam_benchmark.cpp
Resolves https://github.com/seqan/product_backlog/issues/157
> [FIX] Timeout in SAM benchmark

- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
- include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp
- include/seqan3/alignment/pairwise/detail/policy_optimum_tracker_simd.hpp
- include/seqan3/core/concept/tuple.hpp
Renames member variables of policy_optimum_tracker.
Uses binary update operation to compare and update the optimum.
Updates the configurator to choose the correct policy.
Updates the pairwise alignment algorithm to reflect the changes.
extracted from #1804
> [FEATURE] Adds simd optimum tracker policy.

- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
- include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp
- include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp
- test/unit/alignment/pairwise/semi_global_affine_banded_test.cpp
part of #1908 
Enables the free end gaps feature for banded alignments in new optimised alignment code.
> Optimise alignment/part5 banded alignment with free end gaps

- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/argument_parser/detail/format_base.hpp
- include/seqan3/argument_parser/detail/format_parse.hpp
fixes https://github.com/seqan/product_backlog/issues/81
> [DOC] Fix small issue in doc of argument parser.

- test/include/seqan3/test/performance/sequence_generator.hpp
- test/performance/io/lowlevel_stream_output_benchmark.cpp
SeqAn2 could do chunked output already, but SeqAn3's implementation is ~5% faster.
> [TEST] add seqan2 chunked output to benchmark

- CHANGELOG.md
- include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp
- include/seqan3/alignment/aligned_sequence/debug_stream_alignment.hpp
- include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp
- include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp
- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/range/decorator/gap_decorator.hpp
- test/performance/range/gap_decorator_rand_write_benchmark.cpp
Part of https://github.com/seqan/product_backlog/issues/60
> [FEATURE] Add seqan3::writable_sequence_concept.

- include/seqan3/core/simd/concept.hpp
- include/seqan3/core/simd/detail/builtin_simd.hpp
- include/seqan3/core/simd/simd_traits.hpp
- test/unit/core/simd/detail/builtin_simd_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/108
> [FEATURE] core - add simd trait: rebind

- include/seqan3/range/views/minimiser_hash.hpp
- test/snippet/range/views/minimiser_hash.cpp
- test/unit/range/views/view_minimiser_hash_test.cpp
Use reserve strand in minimiser hash view.
> [FEATURE] use reserve strand in minimiser hash view

- include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
- test/snippet/search/dream_index/counting_vector.cpp
- test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
Resolves https://github.com/seqan/product_backlog/issues/77
> [FEATURE] Counting vector

- include/seqan3/range/views/kmer_hash.hpp
- test/unit/range/views/view_kmer_hash_test.cpp
- test/unit/range/views/view_minimiser_test.cpp
Resolves https://github.com/seqan/seqan3/issues/1988
Closes https://github.com/seqan/product_backlog/issues/161
> [FIX] Preserve common_range in kmer_hash_view

- test/include/seqan3/test/pretty_printing.hpp
- test/unit/search/search_scheme_algorithm_test.cpp
Part of https://github.com/seqan/product_backlog/issues/167
> avoid including complete debug_stream in tests

- include/seqan3/core/type_traits/range.hpp
- test/unit/core/type_traits/range_iterator_test.cpp
This PR contains functionality needed to implement https://github.com/seqan/product_backlog/issues/168
> [FEATURE] add detail::maybe_const_(range_t|iterator_t|sentinel_t)

- doc/howto/subcommand_argument_parser/subcommand_arg_parse.cpp
- doc/tutorial/concepts/custom_validator_solution2.cpp
- doc/tutorial/introduction/introduction_file_input.cpp
- doc/tutorial/ranges/range_solution4.cpp
- include/seqan3/core/detail/to_string.hpp
- test/include/seqan3/test/pretty_printing.hpp
- test/unit/alignment/matrix/debug_stream_trace_directions_test.cpp
- test/unit/range/container/dynamic_bitset_test.cpp
- test/unit/search/kmer_index/shape_test.cpp
Fixes seqan/product_backlog#167
> [TEST] debug_stream_type is enough and remove unnecessary includes

- include/seqan3/range/detail/inherited_iterator_base.hpp
- include/seqan3/range/views/enforce_random_access.hpp
- include/seqan3/range/views/take.hpp
- include/seqan3/range/views/take_until.hpp
- test/unit/range/views/view_enforce_random_access_test.cpp
This is part of seqan/product_backlog#62
> [MISC] make inherited_iterator_base::base public (formerly named this_to_base)

- doc/tutorial/sequence_file/sequence_file_solution3.cpp
> [FIX] gcc10.2: workaround for snippets

- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/range/views/take_until.hpp
- include/seqan3/std/concepts
Fixes https://github.com/seqan/product_backlog/issues/190
> Simplify seqan3/std/concepts

- test/documentation/seqan3_footer.html
Follow-up for #2015
Main change: `doxygen.png` -> `doxygen.svg`
> [DOC] Update doxygen footer

- include/seqan3/alphabet/composite/alphabet_variant.hpp
- include/seqan3/argument_parser/argument_parser.hpp
- include/seqan3/core/concept/core_language.hpp
- include/seqan3/io/detail/ignore_output_iterator.hpp
- include/seqan3/io/detail/out_file_iterator.hpp
- include/seqan3/range/container/aligned_allocator.hpp
- include/seqan3/range/container/concept.hpp
- include/seqan3/range/decorator/gap_decorator.hpp
Resolves https://github.com/seqan/product_backlog/issues/197
> [DOC] Fix broken cppreference links

- test/unit/test/seqan2_test.cpp
Blocked by https://github.com/seqan/seqan/pull/2435
Blocked by https://github.com/seqan/seqan3/pull/2014
> [FIX] SeqAn2-enabled tests

- include/seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp
- include/seqan3/alignment/pairwise/detail/policy_alignment_matrix.hpp
- include/seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp
Extracted from #2032 
Only the last commit is relevant
> [Alignment Configuration] Enable free end gap config of method_global in policies.

- include/seqan3/alignment/pairwise/alignment_result.hpp
- include/seqan3/argument_parser/detail/format_base.hpp
- include/seqan3/core/platform.hpp
- include/seqan3/search/search_result.hpp
Part of https://github.com/seqan/product_backlog/issues/106
> gcc-11 support

- .github/workflows/ci.yml
- .travis.yml
- test/unit/CMakeLists.txt
Also see https://github.com/seqan/seqan3/pull/2083#discussion_r480000565
> [INFRA] Add option to disable verbose testing

- .travis.yml
Resolves https://github.com/seqan/seqan3/issues/1482
> [INFRA] Run travis as nightly on multiple CPU archs

- include/seqan3/alignment/all.hpp
- include/seqan3/alignment/pairwise/align_result_selector.hpp
- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/alignment_result.hpp
- include/seqan3/alignment/pairwise/detail/policy_alignment_result_builder.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- test/unit/alignment/configuration/align_config_common_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/alignment_result_debug_stream_test.cpp
- test/unit/alignment/pairwise/alignment_result_test.cpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_callback_test_template.hpp
resolves seqan/product_backlog#191
> Align cfg output/sequence ids

- .travis.yml
Currently looks like this, if we want text messages, we need to use a bot.
> [FIX,INFRA] travis syntax and notifications

- test/unit/range/container/container_of_container_test.cpp
fixes https://github.com/seqan/product_backlog/issues/136
> [MISC] Remove diagnostics to ignore deprecation warning of ranges library.

- test/unit/argument_parser/detail/version_check_test.hpp
Resolves https://github.com/seqan/product_backlog/issues/203
> [FIX] use of invalidated pointers

- test/snippet/io/alignment_file/sam_flags.cpp
> [FIX] Repair Snippet for SAM/BAM bitflag

- include/seqan3/io/record.hpp
> [DOC] Remove wrong seq_qual checkmarks from table

- include/seqan3/argument_parser/validators.hpp
Resolves https://github.com/seqan/product_backlog/issues/152
> [DOC] Add detailed documentation to the validator concept.

- .github/workflows/ci.yml
- .github/workflows/documentation.yaml
Sometimes CI fails because some download did not work, usually the sourceforge link.
> [INFRA] Retry downloads

- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
Fixes seqan/product_backlog#213 ... the issue with accessing invalid memory in the banded semi global alignment.
The problem was that the upper diagonal of the band ended before the actual end of the first sequence. 
Within the current implementation this would then try to access elements from the second sequence that are behind the end. To fix this, the first sequence is trimmed, such that the last cell of the band also represents the last cell in the "trimmed" matrix and then reaches the end of the first sequence to stop the alignment.
> [FIX] address issue in banded semi global alignment.

- include/seqan3/search/configuration/result_type.hpp
- include/seqan3/search/detail/search_configurator.hpp
- include/seqan3/search/detail/search_traits.hpp
- test/unit/search/search_configuration_test.cpp
> [MISC] Update search_cfg::detail::result_type to recent config design changes.

- include/seqan3/search/configuration/output.hpp
- include/seqan3/search/detail/search_traits.hpp
- test/snippet/search/configuration_output.cpp
- test/unit/search/search_configuration_test.cpp
- test/unit/search/search_scheme_algorithm_test.cpp
> [MISC] Update search_cfg::output_index_cursor to recent config design changes.

- include/seqan3/search/configuration/hit.hpp
- include/seqan3/search/detail/search_scheme_algorithm.hpp
- include/seqan3/search/detail/unidirectional_search_algorithm.hpp
- test/unit/search/configuration/hit_test.cpp
> [MISC] Update search_cfg::strata to recent config design changes.

- doc/tutorial/read_mapper/read_mapper_step2.cpp
- doc/tutorial/read_mapper/read_mapper_step3.cpp
- doc/tutorial/read_mapper/read_mapper_step4.cpp
- doc/tutorial/search/search_solution4.cpp
- doc/tutorial/search/search_solution5.cpp
- include/seqan3/search/configuration/hit.hpp
- include/seqan3/search/detail/search_configurator.hpp
- include/seqan3/search/detail/search_traits.hpp
- test/snippet/search/dynamic_hit_configuration_example.cpp
- test/snippet/search/hit_configuration_examples.cpp
- test/unit/search/configuration/hit_test.cpp
- test/unit/search/search_test.cpp
> [MISC] Update search_cfg::hit_all_best to recent config design changes.

- include/seqan3/alignment/configuration/align_config_vectorised.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
- test/snippet/alignment/configuration/align_cfg_vectorised_example.cpp
- test/unit/alignment/configuration/align_config_common_test.cpp
- test/unit/alignment/configuration/align_config_vectorised_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/global_affine_unbanded_collection_simd_test.cpp
part of  Left seqan/product_backlog#217
> [MISC] Update align_cfg::vectorised to recent config design changes.

- include/seqan3/alignment/configuration/align_config_min_score.hpp
> [MISC] Update align_cfg::min_score to recent config design changes.

- include/seqan3/alignment/configuration/align_config_band.hpp
- include/seqan3/alignment/matrix/detail/alignment_score_matrix_one_column_banded.hpp
- include/seqan3/alignment/matrix/detail/alignment_trace_matrix_full_banded.hpp
- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/detail/policy_alignment_matrix.hpp
- include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp
- test/unit/alignment/configuration/align_config_band_test.cpp
- test/unit/alignment/pairwise/global_affine_banded_test.cpp
Part of seqan/product_backlog#217
fixes seqan/product_backlog#202
> [MISC] Make the align_cfg::band_fixed_size member as builtin types.

- include/seqan3/alignment/configuration/align_config_gap_cost_affine.hpp
> [MISC] Use int32_t as member types.

- include/seqan3/search/configuration/default_configuration.hpp
- include/seqan3/search/configuration/output.hpp
- include/seqan3/search/detail/search_configurator.hpp
- include/seqan3/search/detail/search_traits.hpp
- test/snippet/search/configuration_default.cpp
- test/snippet/search/configuration_output.cpp
- test/unit/search/search_configuration_test.cpp
> [MISC] Update search_cfg::output_reference_begin_position to recent config design changes.

- include/seqan3/alignment/configuration/align_config_scoring_scheme.hpp
- include/seqan3/alignment/pairwise/alignment_algorithm.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/policy_scoring_scheme.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/unit/alignment/configuration/align_config_edit_test.cpp
- test/unit/alignment/configuration/align_config_scoring_test.cpp
Part of seqan/product_backlog#217
> [MISC] Adapt align_cfg scoring scheme to new config design.

- doc/tutorial/search/search_solution4.cpp
- include/seqan3/search/configuration/default_configuration.hpp
- include/seqan3/search/configuration/hit.hpp
- include/seqan3/search/detail/search_configurator.hpp
- include/seqan3/search/detail/search_traits.hpp
- test/snippet/search/configuration_default.cpp
- test/snippet/search/dynamic_hit_configuration_example.cpp
- test/snippet/search/hit_configuration_examples.cpp
- test/unit/search/configuration/hit_test.cpp
- test/unit/search/search_scheme_algorithm_test.cpp
- test/unit/search/search_test.cpp
> [MISC] Update search_cfg::hit_all to recent config design changes.

- include/seqan3/search/configuration/max_error.hpp
- include/seqan3/search/detail/policy_max_error.hpp
- test/unit/search/search_configuration_test.cpp
> [MISC] Update search_cfg::max_error_insertion to recent config design changes.

- include/seqan3/alignment/configuration/align_config_score_type.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
- test/snippet/alignment/configuration/align_cfg_score_type.cpp
- test/unit/alignment/configuration/align_config_score_type_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
> [MISC] Update align_cfg::score_type to recent config design changes.

- include/seqan3/search/configuration/max_error.hpp
- include/seqan3/search/detail/policy_max_error.hpp
- test/unit/search/search_configuration_test.cpp
> [MISC] Update search_cfg::max_error_deletion to recent config design changes.

- include/seqan3/alignment/configuration/align_config_output.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/snippet/alignment/configuration/align_cfg_output_sequence2_id.cpp
- test/unit/alignment/configuration/align_config_output_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_callback_test_template.hpp
> [MISC] Update align_cfg::output_sequence2_id to recent config design changes.

- doc/tutorial/introduction/introduction_align.cpp
- doc/tutorial/pairwise_alignment/pairwise_alignment_solution_4.cpp
- doc/tutorial/pairwise_alignment/pairwise_alignment_solution_5.cpp
- doc/tutorial/read_mapper/read_mapper_step3.cpp
- doc/tutorial/read_mapper/read_mapper_step4.cpp
- doc/tutorial/search/search_solution5.cpp
- include/seqan3/alignment/configuration/align_config_output.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/performance/alignment/global_affine_alignment_benchmark.cpp
- test/performance/alignment/global_affine_alignment_parallel_benchmark.cpp
- test/performance/alignment/local_affine_alignment_benchmark.cpp
- test/performance/io/format_sam_benchmark.cpp
- test/snippet/alignment/configuration/align_cfg_output_alignment.cpp
- test/snippet/alignment/configuration/align_cfg_output_examples.cpp
- test/unit/alignment/configuration/align_config_output_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
> [MISC] Update align_cfg::output_alignment to recent config design changes.

- include/seqan3/search/configuration/max_error.hpp
- include/seqan3/search/detail/policy_max_error.hpp
- test/unit/search/search_configuration_test.cpp
> [MISC] Update search_cfg::max_error_total to recent config design changes.

- doc/tutorial/pairwise_alignment/pairwise_alignment_solution_4.cpp
- doc/tutorial/pairwise_alignment/pairwise_alignment_solution_5.cpp
- doc/tutorial/read_mapper/read_mapper_step4.cpp
- include/seqan3/alignment/configuration/align_config_output.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/performance/io/format_sam_benchmark.cpp
- test/snippet/alignment/configuration/align_cfg_output_begin_position.cpp
- test/unit/alignment/configuration/align_config_output_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
> [MISC] Update align_cfg::output_begin_position to recent config design changes.

- include/seqan3/alignment/configuration/align_config_debug.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
> [MISC] Update align_cfg::detail::debug to recent config design changes.

- include/seqan3/alignment/configuration/align_config_result_type.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/performance/alignment/edit_distance_unbanded_benchmark.cpp
- test/unit/alignment/configuration/align_config_common_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
> [MISC] Update align_cfg::detail::result_type to recent config design changes.

- doc/tutorial/pairwise_alignment/pairwise_alignment_solution_4.cpp
- doc/tutorial/pairwise_alignment/pairwise_alignment_solution_5.cpp
- include/seqan3/alignment/configuration/align_config_output.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
- test/snippet/alignment/configuration/align_cfg_output_end_position.cpp
- test/unit/alignment/configuration/align_config_output_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
> [MISC] Update align_cfg::output_end_position to recent config design changes.

- doc/tutorial/pairwise_alignment/index.md
- include/seqan3/alignment/configuration/align_config_method.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- include/seqan3/alignment/pairwise/policy/affine_gap_init_policy.hpp
- include/seqan3/alignment/pairwise/policy/find_optimum_policy.hpp
- include/seqan3/alignment/pairwise/policy/simd_find_optimum_policy.hpp
- include/seqan3/alignment/scoring/detail/simd_match_mismatch_scoring_scheme.hpp
- include/seqan3/alignment/scoring/detail/simd_matrix_scoring_scheme.hpp
- test/performance/alignment/local_affine_alignment_benchmark.cpp
- test/snippet/alignment/configuration/align_cfg_method_local.cpp
- test/unit/alignment/configuration/align_config_common_test.cpp
- test/unit/alignment/configuration/align_config_method_test.cpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/alignment/pairwise/fixture/local_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/local_affine_unbanded.hpp
- test/unit/alignment/scoring/simd_match_mismatch_scoring_scheme_test.cpp
- test/unit/alignment/scoring/simd_matrix_scoring_scheme_test.cpp
> [MISC] Update align_cfg::method_local to recent config design changes.

- include/seqan3/alignment/configuration/align_config_output.hpp
- include/seqan3/alignment/pairwise/alignment_configurator.hpp
- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- test/snippet/alignment/configuration/align_cfg_output_sequence1_id.cpp
- test/unit/alignment/configuration/align_config_output_test.cpp
- test/unit/alignment/pairwise/align_pairwise_test.cpp
- test/unit/alignment/pairwise/align_result_selector_test.cpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_callback_test_template.hpp
> [MISC] Update align_cfg::output_sequence1_id to recent config design changes.

- test/performance/alignment/global_affine_alignment_simd_benchmark.cpp
Analogous to https://github.com/seqan/seqan3/pull/2109
> [FIX] Timeout in debug nightlies

- test/performance/search/search_benchmark.cpp
Cherry-pick from master branch
Part of https://github.com/seqan/product_backlog/issues/204
> [TEST] Force compiler to actually execute the search algorithm

- include/seqan3/core/algorithm/configuration_element_debug_mode.hpp
- test/unit/alignment/configuration/align_config_common_test.cpp
> [MISC] Add constructors to debug mode configuration.

- include/seqan3/alignment/configuration/align_config_min_score.hpp
> [MISC] Make config_min_score a class.

- include/seqan3/search/configuration/max_error.hpp
> [MISC] Make max error configurations real classes.

- include/seqan3/alignment/configuration/align_config_on_result.hpp
> [MISC] Make on_result config a class.

- include/seqan3/alignment/configuration/align_config_band.hpp
> [MISC] remove unnecessary base declaration.

- include/seqan3/alignment/configuration/align_config_result_type.hpp
> [MISC] Add constructors to result_type alignment configuration.

- include/seqan3/search/configuration/hit.hpp
> [MISC] Add constructors to hit search configurations.

- include/seqan3/alignment/configuration/align_config_gap_cost_affine.hpp
> [MISC] Make affine config gap cost affine a class.

- include/seqan3/alignment/configuration/align_config_output.hpp
> [MISC] Add constructors to align_cfg::output configurations.

- include/seqan3/search/configuration/output.hpp
> [MISC] Add construtors to output search configurations.

- include/seqan3/alignment/configuration/align_config_score_type.hpp
> [MISC] Add constructors to score_type alignment configuration.

- include/seqan3/alignment/configuration/align_config_vectorised.hpp
> [MISC] Add constructors to vectorised alignment configuration.

- include/seqan3/search/configuration/on_result.hpp
> [MISC] Make on result search configuration a real class.

- include/seqan3/search/configuration/result_type.hpp
> [MISC] Add constructor to result_type search configuration.

- include/seqan3/alignment/configuration/align_config_method.hpp
> [MISC] Add constructors to method local

- include/seqan3/core/algorithm/pipeable_config_element.hpp
- test/snippet/core/algorithm/configuration_get_or.cpp
- test/snippet/core/algorithm/configuration_setup.cpp
- test/unit/core/algorithm/configuration_mock.hpp
The pipeable config elemen will not store the value of the config anymore.
config/remove_value_based_pipeable_config
> [MISC] Remove unused pipeable config element.

- test/unit/range/views/view_slice_test.cpp
> [TEST] Add throw test for slice view to increase code coverage

- include/seqan3/io/sequence_file/format_fastq.hpp
> [MISC] Delete unreachable if in fastq format

- test/include/seqan3/test/performance/thread_utility.hpp
This is a building block for other changes.
> [TEST] add thread utility header

- doc/tutorial/pairwise_alignment/index.md
Adapts the tutorial at some places to better discuss the refined configurations.
> [DOC] Correct the alignment tutorial.

- doc/tutorial/search/index.md
- doc/tutorial/search/search_small_snippets.cpp
- doc/tutorial/search/search_solution3.cpp
- doc/tutorial/search/search_solution4.cpp
- doc/tutorial/search/search_solution5.cpp
Adapts the tutorial at some places to better discuss the refined configurations.
> [DOC] Correct the search tutorial.

- .github/workflows/ci.yml
- .travis.yml
Resolves https://github.com/seqan/product_backlog/issues/230
> [INFRA] Unify if/then/else syntax

- test/performance/alignment/edit_distance_benchmark_template.hpp
This adds benchmarks (not used yet) for the direct call to the edit distance algorithm.
> [TEST] add edit distance alignment benchmark template

- include/seqan3/io/alignment_file/format_sam.hpp
- test/performance/io/format_sam_benchmark.cpp
Resolves https://github.com/seqan/seqan3/issues/2225
(yes, it works in debug mode)
> [FIX] wrong usage of SAM interface

- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/format_sam_base.hpp
This PR does the following:
* use our fast streambuf iterators instead of regular ones
* avoid repeated calls to `std::ranges::begin()` (instead creates iterator once and uses that)
* replaces some very long `if`-`if else`-chains with `switch`-`case`.
This improves performance of my real-world use-case by at least 25%.
See also https://github.com/seqan/product_backlog/issues/227
> [MISC] optimisations and clean-up

- include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp
- include/seqan3/search/fm_index/fm_index.hpp
Part of https://github.com/seqan/product_backlog/issues/184
> [FIX,DOC] Use fully qualified namespace in copydoc

- include/seqan3/io/sequence_file/format_fasta.hpp
- test/unit/io/sequence_file/sequence_file_format_fasta_test.cpp
> [TEST] Add coverage to sequence file format fasta test

- test/performance/search/search_benchmark.cpp
This PR fixes https://github.com/seqan/seqan3/issues/2209. 
The main problem was that constructing the following with `stddev = 0` results in undefined behaviour. 
```c++
std::normal_distribution<> dis_error_count{static_cast<double>(simulated_errors), stddev};
```
The code was written in a way that it never executed `dis_error_count` while `stddev = 0`, so we never encountered any real problems.
> [FIX] search_benchmark test failure (#2209)

- test/unit/range/views/view_minimiser_test.cpp
> [TEST] Increase coverage of minimiser view by adding test for a throw.

- include/seqan3/alignment/matrix/detail/combined_score_and_trace_matrix.hpp
- include/seqan3/alignment/matrix/detail/trace_matrix_full.hpp
- test/unit/alignment/matrix/detail/trace_matrix_full_test.cpp
Adds functionality to get the trace path from the traceback matrix given an alignment coordinate.
> Optimise alignment/final alignment computation master

- .github/workflows/ci.yml
- .github/workflows/documentation.yaml
I stumbled across this. If you just set it as default you cannot forget to set it for some step :)
> [INFRA] Use defaults.run to set shell

- doc/tutorial/alignment_file/index.md
- doc/tutorial/pairwise_alignment/index.md
- doc/tutorial/ranges/index.md
- doc/tutorial/ranges/views/minimiser/index.md
- doc/tutorial/ranges/views/minimiser/minimiser_snippets.cpp
Fixes #2253 and some minor phrasing errors
> [DOC] Tutorial improvements

- include/seqan3/core/platform.hpp
- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/format_sam_base.hpp
- include/seqan3/io/exception.hpp
- include/seqan3/range/container/concept.hpp
- test/unit/range/container/container_concept_test.cpp
> [FIX] #2244: basic support for _GLIBCXX_USE_CXX11_ABI=0

- include/seqan3/alignment/pairwise/alignment_configurator.hpp
This enables the computation of the begin position within the refactored alignment.
> [FEATURE] Enable computation of the begin positions in the new alignment algorithm.

- include/seqan3/utility/type_traits/function_traits.hpp
Fixes header test on gcc10 https://cdash.seqan.de/viewBuildError.php?buildid=81458
> [FIX] missing header

- include/seqan3/contrib/stream/bgzf_istream.hpp
- include/seqan3/core/debug_stream.hpp
- include/seqan3/core/detail/debug_stream_alphabet.hpp
- include/seqan3/core/detail/debug_stream_range.hpp
- include/seqan3/core/simd/view_to_simd.hpp
- include/seqan3/utility/tuple/concept.hpp
- test/snippet/core/detail/is_class_template_declarable_with.cpp
Part of https://github.com/seqan/product_backlog/issues/264
> [MISC] Remove unecessary includes

- include/seqan3/range/views/kmer_hash.hpp
- include/seqan3/range/views/minimiser_hash.hpp
- include/seqan3/search/kmer_index/shape.hpp
- test/documentation/seqan3_doxygen_cfg.in
Resolves https://github.com/seqan/product_backlog/issues/265
> [DOC] Add experimental tag to shape

- include/seqan3/contrib/parallel/buffer_queue.hpp
Applies the patch from https://github.com/seqan/seqan3/issues/2282
> [FIX] non-terminating tests

- test/unit/test/pretty_printing_test.cpp
See https://github.com/seqan/seqan3/issues/2234#issuecomment-720476694
> [FIX] #2234: support latest googletest

- include/seqan3/range/views/kmer_hash.hpp
- include/seqan3/range/views/minimiser_hash.hpp
- include/seqan3/search/kmer_index/shape.hpp
- test/documentation/api-stability.js
- test/documentation/seqan3.css
- test/documentation/seqan3_doxygen_cfg.in
- test/documentation/seqan3_footer.html
<details><summary>old (click)</summary>
</details>
> [DOC] Doxygen api stability documentation

- include/seqan3/alignment/matrix/trace_directions.hpp
- include/seqan3/core/add_enum_bitwise_operators.hpp
- include/seqan3/core/detail/debug_stream_type.hpp
- include/seqan3/core/detail/strong_type.hpp
- include/seqan3/io/alignment_file/misc.hpp
- include/seqan3/range/views/translate.hpp
Resolves https://github.com/seqan/product_backlog/issues/260
> [DOC] Change doc for add_enum_bitwise_operators

- doc/howto/use_cereal/load.hpp
- doc/howto/use_cereal/store.hpp
- doc/tutorial/introduction/introduction_align.cpp
- include/seqan3/alphabet/all.hpp
- include/seqan3/contrib/stream/bz2_ostream.hpp
- include/seqan3/contrib/stream/gz_ostream.hpp
Just fixes a few little docu bugs I stumbled across.
> [DOC] Fixes some misspellings, and other small documentation issues.

- include/seqan3/core/platform.hpp
- include/seqan3/version.hpp
- test/header/CMakeLists.txt
Change dependency of version.hpp and core/platform.hpp.
This change will inverse the dependency and make core/platform.hpp
include version.hpp.
> [MISC] remove includes from version.hpp

- doc/tutorial/alphabet/alphabet_main.cpp
- doc/tutorial/alphabet/index.md
- include/seqan3/alphabet/quality/all.hpp
- include/seqan3/alphabet/quality/phred42.hpp
- include/seqan3/alphabet/quality/phred63.hpp
- include/seqan3/alphabet/quality/phred94.hpp
- include/seqan3/alphabet/quality/quality_base.hpp
- test/snippet/alphabet/quality/phred42.cpp
- test/snippet/alphabet/quality/phred63.cpp
- test/snippet/alphabet/quality/phred94.cpp
This is the last part, and so it 
Resolves https://github.com/seqan/product_backlog/issues/266
> [DOC] Add a tutorial for the phred score alphabet

- include/seqan3/alphabet/adaptation/char.hpp
- include/seqan3/alphabet/adaptation/uint.hpp
- include/seqan3/alphabet/alphabet_base.hpp
- include/seqan3/alphabet/aminoacid/aa10li.hpp
- include/seqan3/alphabet/aminoacid/aminoacid_base.hpp
- test/snippet/alphabet/aminoacid/aa10li.cpp
- test/snippet/alphabet/cigar/cigar_value_assignment.cpp
- test/snippet/alphabet/cigar/cigar_value_construction.cpp
This was decided in the Core-Meeting 2021-02-10
> alphabet: first things that are marked stable / experimental.

- test/documentation/api-stability.js
> [FIX] API badge missing in some typedefs

- test/documentation/api-stability.js
- test/documentation/seqan3.css
> [DOC] Add API badge to detailed description

- CHANGELOG.md
- include/seqan3/range/views/kmer_hash.hpp
- test/unit/range/views/kmer_hash_test.cpp
> [FIX] kmer_hash combined with reverse

- doc/fragments/cigar_operation_table.hpp
- doc/fragments/readme.hpp
- include/seqan3/alphabet/cigar/all.hpp
This is a workaround for https://github.com/doxygen/doxygen/issues/8390
> [DOC] make documentation-fragments shareable

- include/seqan3/io/alignment_file/all.hpp
- include/seqan3/io/alignment_file/detail.hpp
- include/seqan3/io/alignment_file/format_bam.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- include/seqan3/io/alignment_file/format_sam_base.hpp
- include/seqan3/io/alignment_file/header.hpp
- include/seqan3/io/alignment_file/input.hpp
- include/seqan3/io/alignment_file/input_format_concept.hpp
- include/seqan3/io/alignment_file/input_options.hpp
- include/seqan3/io/alignment_file/misc.hpp
- include/seqan3/io/alignment_file/output.hpp
- include/seqan3/io/alignment_file/output_format_concept.hpp
- include/seqan3/io/alignment_file/output_options.hpp
- include/seqan3/io/alignment_file/sam_tag_dictionary.hpp
Part of many small rename PRs, tackles https://github.com/seqan/product_backlog/issues/290.
> [DOC] rename def/ingroup to io_sam_file

- doc/tutorial/sam_file/index.md
- doc/tutorial/sequence_file/index.md
- include/seqan3/io/alignment_file/all.hpp
- include/seqan3/io/alignment_file/format_sam.hpp
- test/documentation/DoxygenLayout.xml
Part of many small rename PRs, tackles https://github.com/seqan/product_backlog/issues/290.
> [DOC] tutorial_{alignment => sam}_file

- build_system/seqan3-config.cmake
> [FIX] SeqAn3 cmake not working with -Werror

- test/unit/io/sam_file/format_bam_test.cpp
Part of seqan/product_backlog#83.
> [TEST] use EXPECT_RANGE_EQ in format_bam_test.cpp

- test/snippet/argument_parser/validators_output_directory.cpp
Doesn't do what it's suppossed to when copy/pasting :)
> [FIX] Use correct validator in snippet

- include/seqan3/alphabet/structure/concept.hpp
> [MISC] use new CPO-way to define seqan3::pseudoknot_id

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::to_char

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::assign_char_strictly_to.

- include/seqan3/alphabet/structure/concept.hpp
> [MISC] use new CPO-way to define seqan3::is_pair_open

- include/seqan3/argument_parser/auxiliary.hpp
> [MISC] use new CPO-way to define seqan3::enumeration_names

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::char_is_valid_for

- include/seqan3/alphabet/aminoacid/concept.hpp
> [MISC] use new CPO-way to define seqan3::enable_aminoacid

- include/seqan3/alphabet/nucleotide/all.hpp
- include/seqan3/utility/char_operations/pretty_print.hpp
See https://github.com/doxygen/doxygen/issues/8441
> [FIX,DOC] escape single quotes in single backticks

- include/seqan3/alignment/pairwise/detail/alignment_algorithm_state.hpp
- test/unit/alignment/pairwise/edit_distance_unbanded_test_template.hpp
- test/unit/alignment/pairwise/fixture/alignment_fixture.hpp
- test/unit/alignment/pairwise/fixture/global_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/global_affine_unbanded.hpp
- test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp
- test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp
- test/unit/alignment/pairwise/fixture/local_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/local_affine_unbanded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_affine_banded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_affine_unbanded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp
- test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
- test/unit/alignment/pairwise/pairwise_alignment_collection_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_callback_test_template.hpp
- test/unit/alignment/pairwise/pairwise_alignment_single_test_template.hpp
Part of https://github.com/seqan/product_backlog/issues/282
> [MISC] deprecate seqan3::alignment_coordinate

- include/seqan3/alphabet/structure/concept.hpp
> [MISC] use new CPO-way to define seqan3::max_pseudoknot_depth

- include/seqan3/alphabet/structure/concept.hpp
> [MISC] use new CPO-way to define seqan3::is_unpaired

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::alphabet_size

- include/seqan3/alphabet/structure/concept.hpp
> [MISC] use new CPO-way to define seqan3::is_pair_close

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::to_rank

- include/seqan3/alphabet/quality/concept.hpp
> [MISC] use new CPO-way to define seqan3::to_phred

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::assign_char_to

- include/seqan3/alphabet/concept.hpp
> [MISC] use new CPO-way to define seqan3::assign_rank_to

- doc/cookbook/index.md
- doc/setup/quickstart_cmake/hello_world.cpp
- doc/setup/quickstart_cmake/index.md
- test/documentation/seqan3.css
- test/documentation/seqan3_doxygen_cfg.in
- test/external_project/CMakeLists.txt
- test/external_project/seqan3_setup_tutorial/CMakeLists.txt
Resolves https://github.com/seqan/product_backlog/issues/139
Todo:
> [DOC] Setup guide renewal✨

- include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
- test/unit/search/dream_index/interleaved_bloom_filter_test.cpp
> [MISC] Properly wrap sdsl::bit_vector within binning_bitvector

- include/seqan3/core/add_enum_bitwise_operators.hpp
https://cdash.seqan.de/testDetails.php?test=40229999&build=135410
> [FIX,DOC] Mismatching template parameters

- .github/workflows/ci.yml
See https://github.com/Homebrew/discussions/discussions/691
> [FIX,INFRA] Use up-to-date homebrew on macOs

- include/seqan3/std/charconv
- test/unit/std/charconv_float_test.cpp
- test/unit/std/charconv_int_test.cpp
> [FIX#2352] charconv code broken in GCC10

- include/seqan3/range/views/deep.hpp
This will make seqan3 compile with gcc-11 (my build is from 20210408).
> [FIX] gcc-11: seqan3::views::deep: std::transform::views can't handle const &&

- include/seqan3/alignment/pairwise/detail/type_traits.hpp
- include/seqan3/range/views/chunk.hpp
- include/seqan3/utility/views/chunk.hpp
- test/unit/alignment/pairwise/alignment_configurator_test.cpp
- test/unit/core/algorithm/detail/execution_handler_template.hpp
Resolves: https://github.com/seqan/product_backlog/issues/347
> [MISC] Move seqan3::views::chunk to seqan3/utility/views/

- include/seqan3/alphabet/aminoacid/concept.hpp
- include/seqan3/alphabet/concept.hpp
- include/seqan3/alphabet/nucleotide/concept.hpp
- include/seqan3/alphabet/quality/concept.hpp
- include/seqan3/alphabet/structure/concept.hpp
- include/seqan3/argument_parser/auxiliary.hpp
resolves https://github.com/seqan/product_backlog/issues/298#issuecomment-805964030
> https://github.com/seqan/product_backlog/issues/298 follow-up

- include/seqan3/core/platform.hpp
- include/seqan3/range/container/concept.hpp
resolves https://github.com/seqan/product_backlog/issues/321
> [MISC] proper workaround for gcc issue 83328

- .github/ISSUE_TEMPLATE/api_cron_template.md
- .github/workflows/api.yml
- .github/workflows/scripts/process_compiler_error_log.py
Resolves https://github.com/seqan/product_backlog/issues/366
Will look like https://github.com/eseiler/seqan3/issues/12
> [INFRA] Process error log for API cron

- include/seqan3/alignment/band/static_band.hpp
- include/seqan3/alignment/configuration/align_config_min_score.hpp
- include/seqan3/argument_parser/detail/version_check.hpp
- include/seqan3/io/record.hpp
part of https://github.com/seqan/product_backlog/issues/106
> make snippets and header work for gcc-11.1.0

- include/seqan3/range/container/bitcompressed_vector.hpp
- test/unit/range/container/bitcompressed_vector_test.cpp
Fixes https://github.com/seqan/product_backlog/issues/371
> [FIX] gcc-11: satisfaction of atomic constraint depends on itself

- include/seqan3/core/platform.hpp
- include/seqan3/utility/views/pairwise_combine.hpp
resolves https://github.com/seqan/product_backlog/issues/369
> Update to latest range-v3 version

- .github/ISSUE_TEMPLATE/latest_libs_cron_template.md
- .github/workflows/latest_libraries.yml
- test/performance/range/views/view_take_until_benchmark.cpp
Resolves https://github.com/seqan/product_backlog/issues/373
https://github.com/eseiler/seqan3/actions/runs/807164984
Luckily I got a kill signal, so the issue creation also works: https://github.com/eseiler/seqan3/issues/13
> [INFRA] Add cron for latest libraries

- doc/tutorial/argument_parser/solution3.cpp
- doc/tutorial/argument_parser/solution4.cpp
- doc/tutorial/argument_parser/solution5.cpp
- doc/tutorial/argument_parser/solution6.cpp
- doc/tutorial/sequence_file/sequence_file_snippets.cpp
- include/seqan3/alignment/aligned_sequence/debug_stream_alignment.hpp
- include/seqan3/io/sequence_file/format_genbank.hpp
- include/seqan3/range/views/to.hpp
- include/seqan3/std/ranges
- include/seqan3/utility/views/interleave.hpp
- include/seqan3/utility/views/join_with.hpp
- test/api_stability/3.0.2/0025-NOAPI-INCLUDE-seqan3-std-ranges-must-be-included-bef.patch
- test/performance/io/format_fasta_benchmark.cpp
- test/snippet/alignment/scoring/aminoacid_scoring_scheme.cpp
- test/snippet/alignment/scoring/nucleotide_scoring_scheme.cpp
- test/unit/alignment/matrix/alignment_coordinate_test.cpp
- test/unit/alignment/scoring/scoring_scheme_test.cpp
- test/unit/core/algorithm/algorithm_result_generator_range_test.cpp
- test/unit/core/configuration/configuration_test.cpp
- test/unit/io/sequence_file/sequence_file_output_test.cpp
- test/unit/io/structure_file/structure_file_output_test.cpp
- test/unit/range/container/container_of_container_test.cpp
- test/unit/range/container/debug_stream_container_of_container_test.cpp
- test/unit/range/container/debug_stream_container_test.cpp
- test/unit/std/concept/range_test.cpp
- test/unit/std/ranges_test.cpp
- test/unit/utility/views/pairwise_combine_test.cpp
resolves https://github.com/seqan/product_backlog/issues/372
resolves https://github.com/seqan/seqan3/issues/2580
part of https://github.com/seqan/product_backlog/issues/124
> [FIX] gcc-10: missing RANGES_DEEP_STL_INTEGRATION

- test/include/seqan3/test/tmp_directory.hpp
https://cdash.seqan.de/viewBuildError.php?buildid=147500
> [FIX] missing include

- test/include/seqan3/test/tmp_directory.hpp
> [FIX] Latest Libraries Failure header on gcc11

- test/api_stability/3.0.2/0028-NOAPI-INCLUDE-bitcompressed_vector_test.cpp-and-dyna.patch
> [FIX] API Stability Failure on gcc9/11

- include/seqan3/alignment/configuration/detail.hpp
- include/seqan3/alignment/pairwise/detail/policy_scoring_scheme.hpp
- include/seqan3/core/configuration/configuration.hpp
- include/seqan3/core/configuration/detail/concept.hpp
- include/seqan3/core/configuration/detail/configuration_utility.hpp
- include/seqan3/search/configuration/detail.hpp
- test/unit/core/configuration/configuration_mock.hpp
-----
This is one of the commits that survived the rebase of https://github.com/seqan/seqan3/pull/2198.
> [MISC] Cleanup configuration utility.

- .github/ISSUE_TEMPLATE/release-checklist.md
- CHANGELOG.md
- test/scripts/link_check.sh
See also https://github.com/seqan/www.seqan.de/pull/59
> [DOC,FIX] Check links

- test/api_stability/3.0.2/0035-NOAPI-DETAIL-MISC-Remove-template-argument-from-pipe.patch
- test/api_stability/3.0.2/0036-NOAPI-INCLUDE-MISC-Cleanup-configuration-utility.patch
fixes https://github.com/seqan/seqan3/issues/2630
fixes https://github.com/seqan/seqan3/issues/2632
fixes https://github.com/seqan/seqan3/issues/2629
> [FIX] [CRON] API Stability Failure on gcc9-11

- include/seqan3/core/detail/strong_type.hpp
- test/snippet/core/detail/strong_type_adding_skills.cpp
- test/snippet/core/detail/strong_type_error_window.cpp
- test/snippet/core/detail/strong_type_new_usage.cpp
- test/snippet/core/detail/strong_type_usage.cpp
I used it as explanation on strong types and found some typos and "old style" snippets.
> [DOC] Update strong_type documentation

- include/seqan3/utility/type_list/traits.hpp
- test/unit/alignment/configuration/align_config_band_test.cpp
- test/unit/alignment/configuration/align_config_common_test.cpp
- test/unit/alignment/configuration/align_config_method_test.cpp
- test/unit/alignment/configuration/align_config_on_result_test.cpp
- test/unit/alignment/configuration/align_config_output_test.cpp
- test/unit/alignment/configuration/align_config_parallel_test.cpp
- test/unit/alignment/configuration/align_config_score_type_test.cpp
- test/unit/core/configuration/pipeable_config_element_test.cpp
- test/unit/core/configuration/pipeable_config_element_test_template.hpp
- test/unit/search/configuration/CMakeLists.txt
- test/unit/search/configuration/hit_test.cpp
- test/unit/search/configuration/on_result_test.cpp
- test/unit/search/configuration/parallel_test.cpp
- test/unit/search/configuration/search_config_common_test.cpp
- test/unit/utility/type_list/type_list_traits_test.cpp
-----
This is one of the commits that survived the rebase of https://github.com/seqan/seqan3/pull/2198.
> rework tests for configuration

- test/api_stability/3.0.2/0037-NOAPI-BREAKAGE-re-introduce-seqan3-detail-iterator_c.patch
Fixes https://github.com/seqan/seqan3/issues/2654
https://github.com/seqan/seqan3/pull/2652 didn't completely resolve it, this one does :)
> [FIX] [CRON] API Stability Failure on gcc11

- include/seqan3/core/platform.hpp
Part of release cycle https://github.com/seqan/seqan3/issues/2334
> [INFRA] update platform.hpp

- test/seqan3-test.cmake
Added flags of https://github.com/seqan/seqan3/issues/2620#issuecomment-838482217
> [INFRA] add -DCMAKE_BUILD_TYPE=FEDORA to simulate fedora builds

- CHANGELOG.md
Added list of renamed or moved headers. I wasn't quite sure how to order them.
> Check changelog links and add header changes.

- doc/about/api/index.md
- include/seqan3/core/platform.hpp
Fixes https://github.com/seqan/seqan3/issues/2244#issuecomment-739883821
> [DOC] add documentation for CentOS 7 / RHEL 7

- CHANGELOG.md
- include/seqan3/io/sam_file/detail/format_sam_base.hpp
- include/seqan3/io/sam_file/format_bam.hpp
- include/seqan3/io/sam_file/format_sam.hpp
- test/api_stability/3.0.2/0039-API-FIX-SAM-header-parsing-relax-that-unknown-tags-t.patch
- test/unit/io/sam_file/format_sam_test.cpp
> [FIX] Handle unsupported tags

- test/include/seqan3/test/range/container_test_template.hpp
> [FIX] guard against gtest macro

- test/api_stability/3.0.3/0001-NOAPI-Disable-Werror.patch
- test/api_stability/3.0.3/0002-NOAPI-INCLUDE-MISC-remove-seqan3-detail-take_fn.patch
- test/api_stability/CMakeLists.txt
- test/cmake/seqan3_require_benchmark.cmake
Resolves #2689
Resolves #2690
Resolves #2691
git does not allow empty directories, hence we need to create a dummy file.
> [FIX] API-Stability

- .github/workflows/latest_libraries.yml
Fixes #2713
Fixes #2714
Fixes #2715
Fixes #2716
Fixes #2717
Fixes #2718
Fixes #2719
Fixes #2720
Fixes #2721
Fixes #2722
> [FIX] gbenchmark branch name

- include/seqan3/argument_parser/all.hpp
- include/seqan3/argument_parser/exceptions.hpp
Part of https://github.com/seqan/product_backlog/issues/393
> [FIX,DOC] argument_parser docs

- include/seqan3/search/all.hpp
- include/seqan3/search/detail/search_common.hpp
- include/seqan3/search/detail/search_scheme_algorithm.hpp
- include/seqan3/search/detail/search_scheme_precomputed.hpp
- include/seqan3/search/detail/unidirectional_search_algorithm.hpp
- include/seqan3/search/dream_index/all.hpp
- include/seqan3/search/dream_index/interleaved_bloom_filter.hpp
- include/seqan3/search/fm_index/all.hpp
- include/seqan3/search/fm_index/bi_fm_index.hpp
- include/seqan3/search/fm_index/bi_fm_index_cursor.hpp
- include/seqan3/search/fm_index/concept.hpp
- include/seqan3/search/fm_index/detail/fm_index_cursor.hpp
- include/seqan3/search/fm_index/fm_index.hpp
- include/seqan3/search/fm_index/fm_index_cursor.hpp
- include/seqan3/search/kmer_index/all.hpp
- include/seqan3/search/kmer_index/shape.hpp
- include/seqan3/search/search.hpp
- include/seqan3/search/views/all.hpp
- include/seqan3/search/views/kmer_hash.hpp
- include/seqan3/search/views/minimiser.hpp
- include/seqan3/search/views/minimiser_hash.hpp
Part of https://github.com/seqan/product_backlog/issues/393
> [FIX,DOC] search docs

- include/seqan3/io/detail/misc_output.hpp
- include/seqan3/io/structure_file/input.hpp
Fixes https://github.com/seqan/seqan3/issues/2726, fixes https://github.com/seqan/seqan3/issues/2725 and  fixes https://github.com/seqan/seqan3/issues/2724
> [FIX] missing includes

- doc/cookbook/compression_threads.cpp
- include/seqan3/contrib/stream/bgzf_istream.hpp
- include/seqan3/contrib/stream/bgzf_ostream.hpp
- include/seqan3/contrib/stream/bgzf_stream_util.hpp
- include/seqan3/contrib/stream/bz2_istream.hpp
- include/seqan3/contrib/stream/bz2_ostream.hpp
- include/seqan3/contrib/stream/gz_istream.hpp
- include/seqan3/contrib/stream/gz_ostream.hpp
- include/seqan3/io/detail/magic_header.hpp
- include/seqan3/io/detail/misc_input.hpp
- include/seqan3/io/detail/misc_output.hpp
- test/performance/io/stream_input_benchmark.cpp
- test/performance/io/stream_output_benchmark.cpp
- test/unit/io/detail/misc_output_test.cpp
- test/unit/io/sam_file/sam_file_input_test.cpp
- test/unit/io/sam_file/sam_file_output_test.cpp
- test/unit/io/sequence_file/sequence_file_input_test.cpp
- test/unit/io/sequence_file/sequence_file_output_test.cpp
- test/unit/io/structure_file/structure_file_input_test.cpp
- test/unit/io/structure_file/structure_file_output_test.cpp
Same as https://github.com/seqan/seqan3/pull/2740#issuecomment-857018166, but this time correct target branch :(
> Header test

- include/seqan3/utility/char_operations/predicate.hpp
See https://cdash.seqan.de/testDetails.php?test=51999369&build=176475
> [FIX,DOC] Escape #

- include/seqan3/io/sam_file/detail/format_sam_base.hpp
- include/seqan3/io/sam_file/format_bam.hpp
- include/seqan3/io/sam_file/format_sam.hpp
```
/seqan3/include/seqan3/io/sam_file/format_bam.hpp:420:5: error: no matching member function for call to 'read_field'
read_field(stream_view | detail::take_exactly_or_throw(core.l_read_name - 1), id); // field::id
^~~~~~~~~~
```
The problem is that clang can't inherit constrained functions, see https://bugs.llvm.org/show_bug.cgi?id=51544.
The fix is to give all `read_field` functions unique names, this arguably makes it also easier to understand which "parsing" algorithm is being called.
> [FIX] clang+gcc9: error: no matching member function for call to 'read_field'

- .github/workflows/ci_misc.yml
- .github/workflows/documentation.yaml
- CHANGELOG.md
- test/documentation/.vercel/install.sh
Resolves https://github.com/seqan/product_backlog/issues/303
(coverage is confused by stuff that is on master)
> [INFRA] Bump doxygen

- include/seqan3/alignment/matrix/detail/score_matrix_single_column.hpp
- include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp
- include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
- include/seqan3/alphabet/composite/alphabet_tuple_base.hpp
- include/seqan3/alphabet/views/translate_join.hpp
- include/seqan3/contrib/parallel/buffer_queue.hpp
- include/seqan3/io/views/async_input_buffer.hpp
- include/seqan3/search/detail/search_scheme_algorithm.hpp
- include/seqan3/utility/views/interleave.hpp
> Serveral cases where template redeclaration is different

- include/seqan3/utility/container/aligned_allocator.hpp
```
/seqan3/include/seqan3/utility/container/aligned_allocator.hpp:180:13: error: no matching function for call to 'operator delete'
::operator delete(p, bytes_to_deallocate);
^~~~~~~~~~
```
https://github.com/pybind/pybind11/issues/1604#issuecomment-459796241 shows how to enable this.
> [FIX] clang+gcc9: aligned_allocator: clang does not support __cpp_sized_deallocation by default

- include/seqan3/alignment/matrix/all.hpp
- include/seqan3/alignment/matrix/detail/all.hpp
- include/seqan3/utility/parallel/all.hpp
Part of https://github.com/seqan/seqan3/issues/2685
> [DOC] make some sub-modules DEV only

- include/seqan3/io/views/detail/take_exactly_view.hpp
- test/unit/io/views/detail/take_exactly_view_test.cpp
part of https://github.com/seqan/product_backlog/issues/127
~~blocked by https://github.com/seqan/seqan3/pull/2802~~
> [TEST] take_exactly_view_test: use range test template

- test/snippet/CMakeLists.txt
This PR adds an option to disable overwriting files in the source directory.
> [TEST] add option for seqan3_generate_snippets

- include/seqan3/alphabet/cigar/cigar.hpp
- test/unit/alphabet/cigar/cigar_test.cpp
> constexpr char literal for cigar

- CHANGELOG.md
- test/api_stability/3.0.3/0008-NOAPI-FIX-TEST-seqan3-views-single_pass_input-iterat.patch
> [FIX#2746] API-Stability cron

- test/snippet/release/3.0.0_complement-and-translate-without-copying.cpp
Fixes https://github.com/seqan/seqan3/issues/2821
> [FIX] release note code did not do the right thing for gcc7

- .github/workflows/api.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_misc.yml
- .github/workflows/documentation.yaml
- .github/workflows/latest_libraries.yml
- .github/workflows/ram_usage.yml
- .github/workflows/scripts/install_via_brew.sh
See commit messages.
clang install does work:
https://github.com/eseiler/seqan3/runs/3698326784?check_suite_focus=true
It won't compile, of course :)
In the example, it fails because of gtest, but this is fixed on gtest-master.
> [INFRA] CI Updates

- doc/about/api/index.md
A first try. Please review.
Resolves https://github.com/seqan/product_backlog/issues/279
> [DOC] Update api stability documentation.

- include/seqan3/core/semiregular_box.hpp
- include/seqan3/utility/simd/simd.hpp
> [DOC] fix broken links

- include/seqan3/argument_parser/argument_parser.hpp
> [NOP] Remove unused include in argument parser.

- include/seqan3/core/detail/persist_view.hpp
While working on the IO library @h-2 pointed out some small fixes that I'll push for him.
> [MISC] Remove unused include.

- .github/workflows/ci_linux.yml
- .github/workflows/scripts/README.md
- .github/workflows/scripts/gcov.sh
- test/coverage/CMakeLists.txt
- test/seqan3-test.cmake
> [INFRA] Update codecov action

- test/coverage/CMakeLists.txt
- test/header/CMakeLists.txt
- test/macro_benchmark/CMakeLists.txt
- test/performance/CMakeLists.txt
- test/snippet/CMakeLists.txt
- test/unit/CMakeLists.txt
https://cmake.org/cmake/help/v3.22/policy/CMP0128.html
This is a developer warning that one might encounter when trying to do some debugging
> [INFRA] Acknowledge CMake 3.22 policy change

- CHANGELOG.md
- doc/cookbook/index.md
- doc/tutorial/argument_parser/index.md
- doc/tutorial/search/index.md
With nightly doxygen.
Only 2nd commit is interesting
https://cdash.seqan.de/testDetails.php?test=61010785&build=216979
> [FIX,DOC] Broken refs

- include/seqan3/core/platform.hpp
- test/include/seqan3/test/fixture/io/sam_file/simple_three_verbose_reads_fixture.hpp
- test/include/seqan3/test/fixture/io/sequence_file/standard_fixture.hpp
https://github.com/seqan/product_backlog/issues/402#issuecomment-1031287532
[GCC bugreport](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100252)
> [MISC] Add workaround for gcc12 ICE

- test/cmake/seqan3_require_benchmark.cmake
`export.h` is now generated, so we need to use the proper include directory (`${PROJECT_BINARY_DIR}/include/`) instead of the git checkout.
`BENCHMARK_MAIN` is no longer defined in the macro. It is only declared. The definition is provided by `benchmark_main`.
This only affects the fallback when not using fetchcontent.
Resolves #2747
> [FIX] Building google benchmark on main

- test/snippet/core/detail/persist_view.cpp
Note that views::persist is detail
This should be it :)
> [FIX] gcc12: persist view snippet

- .gitmodules
- test/include/seqan3/test/seqan2.hpp
- test/unit/alignment/decorator/gap_decorator_test.cpp
- test/unit/utility/views/elements_test.cpp
- test/unit/utility/views/single_pass_input_test.cpp
As per https://github.com/seqan/product_backlog/issues/124#issuecomment-1031288913
We will work in the following weeks to become independent of range-v3 completely and get rid of the fork again.
> [INFRA] Switch to range-v3 fork

- test/documentation/seqan3-doxygen-layout.cmake
Auto-generated cmake-format changes
> [CRON] cmake-format

- include/seqan3/contrib/stream/bz2_ostream.hpp
https://cdash.seqan.de/viewBuildError.php?buildid=46560
> [FIX] gcc13: missing header

- .github/workflows/clang_format.yml
Seems to work :)
https://github.com/eseiler/seqan3/pull/37
> [INFRA] Make clang-format independent of branchpoint

- test/documentation/seqan3-doxygen.cmake
> [DOC] Update cppreference-doxygen-web.tag.xml

- .github/workflows/ci_macos.yml
> [INFRA] Add macOS gcc12

- include/seqan3/io/stream/detail/fast_ostreambuf_iterator.hpp
- test/performance/utility/simd/views/iota_simd_benchmark.cpp
The nightlies (https://cdash.seqan.de/index.php?project=SeqAn3) revealed two more missing includes.
Resolves #2905 
Resolves #2747
> [FIX] includes

- include/seqan3/version.hpp
> [MISC] Bump version

- doc/setup/library_tests/index.md
- doc/setup/quickstart_cmake/index.md
I chose to promote gcc-11 over gcc-10 because gcc-11 usually has a better performance.
> [DOC] Update setup tutorial

- .github/workflows/api.yml
- include/seqan3/core/algorithm/algorithm_result_generator_range.hpp
- include/seqan3/core/platform.hpp
- test/api_stability/3.1.0/0001-API-BREAKAGE-views-to-ranges-to.patch
- test/api_stability/3.1.0/0002-NOAPI-DETAIL-Remove-STL-tests.patch
- test/api_stability/3.1.0/0003-NOAPI-DETAIL-Remove-range-v3.patch
- test/api_stability/3.1.0/0004-NOAPI-DETAIL-Concept-definitions.patch
- test/api_stability/3.1.0/0005-NOAPI-DETAIL-Unused-variables.patch
- test/api_stability/3.1.0/0006-NOAPI-DETAIL-Include-md-instead-of-hpp.patch
- test/api_stability/3.1.0/0007-NOAPI-DETAIL-container-concept.patch
- test/api_stability/3.1.0/0008-API-FIX-flags-must-be-false.patch
- test/api_stability/3.1.0/0009-NOAPI-DETAIL-Update-copyright-year.patch
- test/api_stability/3.1.0/0010-API-BREAKGE-FASTA-ID-parsing.patch
- test/api_stability/3.1.0/0011-API-FIX-single_pass_input-output_range.patch
- test/api_stability/CMakeLists.txt
There is currently one API breakage:
* `seqan3::views::to` -> `seqan3::ranges::to` (not a view anymore)
> [FIX] API tests

- include/seqan3/alphabet/hash.hpp
Resolves https://github.com/seqan/seqan3/issues/3015
> [FIX] gcc13: specialization after instantiation

- test/documentation/DoxygenLayout.xml
Follow up Fix of https://github.com/seqan/seqan3/pull/3020
> [DOC] Add hard coded docu page on Changelog, Copyright, Code of Conduct and Contributing Guide.

- CHANGELOG.md
- include/seqan3/utility/views/chunk.hpp
> [DOC] Update changelog

- test/api_stability/CMakeLists.txt
> [INFRA] Update API tests to 3.2.0

- test/cmake/seqan3_require_benchmark.cmake
> [INFRA] Ignore warnings in gbenchmark

- include/seqan3/alphabet/detail/convert.hpp
> [MISC] fix clang-format on detail

- include/seqan3/alphabet/aminoacid/aa10li.hpp
- include/seqan3/alphabet/aminoacid/aa10murphy.hpp
- include/seqan3/alphabet/aminoacid/aa20.hpp
- include/seqan3/alphabet/aminoacid/aa27.hpp
- include/seqan3/alphabet/aminoacid/aminoacid_base.hpp
> [MISC] fix clang-format on aminoacid

- include/seqan3/alphabet/quality/phred42.hpp
- include/seqan3/alphabet/quality/phred63.hpp
- include/seqan3/alphabet/quality/phred68solexa.hpp
- include/seqan3/alphabet/quality/phred94.hpp
- include/seqan3/alphabet/quality/phred_base.hpp
- include/seqan3/alphabet/quality/qualified.hpp
> [MISC] fix clang-format on qualities

- .github/workflows/scripts/install_via_brew.sh
- include/seqan3/core/platform.hpp
> [FIX,INFRA] missing brew flag

- include/seqan3/contrib/stream/bgzf.hpp
- include/seqan3/contrib/stream/bgzf_stream_util.hpp
- include/seqan3/io/detail/misc_input.hpp
- include/seqan3/io/detail/misc_output.hpp
Resolves https://github.com/seqan/seqan3/issues/3041
> [FIX] bgzf_thread_count definition

- test/unit/io/sam_file/sam_file_format_test_template.hpp
while working on the test I noticed that the expected values were all in the test fixtures EXCEPT the initialization of the `seqan3::tag_dictionary`.
This PR fixes it.
> [TEST] Move initialisation of tag_dictiornary to test fixture.

- test/unit/io/sam_file/sam_file_format_test_template.hpp
This moves the initialization of the expected simple three reads that are tested in the SAM/BAM tests into the fixture. This can avoid errors when changing something.
> [TEST] Move initialisation of cigar string to test fixture.

- .github/workflows/api.yml
- .github/workflows/avx2.yml
- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_misc.yml
- .github/workflows/clang_format.yml
- .github/workflows/cmake_format.yml
- .github/workflows/documentation.yaml
- .github/workflows/latest_libraries.yml
- .github/workflows/ram_usage.yml
> [INFRA] Update CI

- .github/workflows/api.yml
- .github/workflows/avx2.yml
- .github/workflows/clang_format.yml
- .github/workflows/cmake_format.yml
- .github/workflows/latest_libraries.yml
- .github/workflows/ram_usage.yml
> [INFRA] Update actions

- include/seqan3/search/views/kmer_hash.hpp
- include/seqan3/search/views/minimiser.hpp
- include/seqan3/utility/views/interleave.hpp
- include/seqan3/utility/views/single_pass_input.hpp
Resolves https://github.com/seqan/product_backlog/issues/383
> [MISC] Make all view ctors explicit

- test/cmake/seqan3_require_benchmark.cmake
- test/cmake/seqan3_require_test.cmake
- test/unit/test/pretty_printing_test.cpp
> [INFRA] Bump google{test,benchmark}

- .gitpod.yml
Allows to follow the tutorial without doing all the setup
> [INFRA] Update .gitpod.yml

- doc/setup/quickstart_cmake/index.md
Resolves https://github.com/seqan/seqan3/issues/1203
I don't think there is enough to talk about to warrant a new page (see resolution in linked issue).
> [DOC] Add CMake snippet to setup

- doc/setup/quickstart_cmake/index.md
This adds a remark on how to set CC and CXX.
Also, added a comment about failing to find SDSL even though the problem lies with apple clang. see https://github.com/seqan/seqan3/issues/3046
> [DOC] add remark about how to set CC and CXX vars

- build_system/seqan3-config.cmake
- doc/setup/quickstart_cmake/index.md
- include/seqan3/core/platform.hpp
- include/seqan3/utility/views/join_with.hpp
- include/seqan3/utility/views/zip.hpp
~~Blocked by https://github.com/seqan/seqan3/pull/3079~~
> [INFRA] Compilercheck

- include/seqan3/alignment/matrix/detail/matrix_concept.hpp
- include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp
- include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp
- include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp
- include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_concept.hpp
- include/seqan3/alphabet/aminoacid/aminoacid_base.hpp
- include/seqan3/alphabet/nucleotide/nucleotide_base.hpp
- include/seqan3/alphabet/quality/phred_base.hpp
- include/seqan3/core/range/detail/inherited_iterator_base.hpp
- include/seqan3/core/range/detail/random_access_iterator.hpp
See nightlies: https://cdash.seqan.de/test/5002562
> [DOC] More doxygen 1.9.6 fixes

- include/seqan3/core/platform.hpp
Closes https://github.com/seqan/seqan3/issues/2746
> [FIX] -Werror=endif-labels

- .github/workflows/api.yml
- .github/workflows/avx2.yml
- .github/workflows/latest_libraries.yml
Tested on my fork: https://github.com/eseiler/seqan3/issues/39
> [INFRA] use multiline syntax for cron

- include/seqan3/core/platform.hpp
> [INFRA] Re-enable gcc12 compiler check

- .github/workflows/update_cookbook.yml
- test/scripts/add_snippets_to_cookbook.sh
Only runs on push, thus merge after CI passes.
> [INFRA] Add action for updating cookbook

- test/snippet/search/dream_index/interleaved_bloom_filter_constructor_uncompress.cpp
```
Assertion `bin.get() < bins' failed.
```
> [FIX] IBF snippet

- test/api_stability/3.2.0/0001-NOAPI-DETAIL-Remove-seqan3-detail-persist.patch
- test/api_stability/README.md
> [TEST] API: persist view

- .codecov.yml
- .github/workflows/ci_coverage.yml
> [INFRA] Update codecov config

- include/seqan3/alphabet/structure/dssp9.hpp
https://cdash.seqan.de/test/24113657
> [DOC,FIX] Doxygen warning

- include/seqan3/alignment/aligned_sequence/all.hpp
- include/seqan3/alignment/all.hpp
- include/seqan3/alignment/cigar_conversion/all.hpp
- include/seqan3/alignment/configuration/all.hpp
- include/seqan3/alignment/decorator/all.hpp
- include/seqan3/alignment/pairwise/all.hpp
Sweep over the alignment module
> [DOC] Improve alignment module documentation.

- .github/workflows/api.yml
- test/api_stability/3.2.0/0001-NOAPI-DETAIL-Remove-seqan3-detail-persist.patch
- test/api_stability/3.2.0/0002-NOAPI-Fix-wrong-alignment-score.patch
- test/api_stability/3.2.0/0003-API-BREAKAGE-Remove-field-alignment-offset-and-impro.patch
- test/api_stability/README.md
Resolves https://github.com/seqan/seqan3/issues/2746
https://github.com/eseiler/seqan3/actions/runs/3874626990
It builds, but it fails because it cannot find the issue on my fork.
> [TEST] Fix API tests

- .github/workflows/ci_coverage.yml
- test/coverage/CMakeLists.txt
> [INFRA] Simplify coverage CMake

- test/cmake/seqan3_require_test.cmake
> [INFRA] Bump googletest

- .github/workflows/scripts/install_doxygen.sh
- test/documentation/.vercel/install.sh
> [FIX] changed doxygen server

- .github/workflows/clang_format.yml
- .github/workflows/scripts/configure_apt.sh
> [INFRA] Update lint and apt

- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_misc.yml
> [INFRA] Install ccache via apt

- include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp
- include/seqan3/core/range/detail/random_access_iterator.hpp
> [FIX] more invalid friend declarations

- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
- include/seqan3/core/platform.hpp
> [FIX] gcc13 release build errors

- .github/workflows/ci_macos.yml
- include/seqan3/io/views/detail/take_until_view.hpp
- include/seqan3/search/views/kmer_hash.hpp
- include/seqan3/search/views/minimiser.hpp
- include/seqan3/utility/views/chunk.hpp
- include/seqan3/utility/views/enforce_random_access.hpp
- include/seqan3/utility/views/pairwise_combine.hpp
- test/unit/alignment/matrix/detail/coordinate_matrix_test.cpp
CPP23 mode for GCC13 is currently not compiling
> [FIX] gcc13 cpp23

- include/seqan3/io/views/detail/take_exactly_view.hpp
https://cdash.seqan.de/index.php?project=SeqAn3
> [FIX] cpp23

- .github/workflows/documentation.yaml
- test/documentation/version.php
We should split seqan2 and seqan3 docs on the server :)
Edit: Did that. Added rewrite rules in `.htaccess` and symlinks on filesystem
> [INFRA] Update version.php

- .github/workflows/api.yml
- .github/workflows/avx2.yml
- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_misc.yml
- .github/workflows/latest_libraries.yml
- .github/workflows/ram_usage.yml
> [INFRA] Add gcc13 CI

- test/cmake/seqan3_require_benchmark.cmake
> [INFRA] Bump google benchmark

- include/seqan3/alphabet/quality/phred_base.hpp
- test/performance/search/index_construction_benchmark.cpp
> [FIX] gcc14

- .github/ISSUE_TEMPLATE/release-checklist.md
> [MISC] Update release template

- include/seqan3/version.hpp
> [INFRA] Bump RC Version

- test/documentation/seqan3-doxygen.cmake
> [INFRA] Update cppreference tags

- test/cmake/seqan3_require_benchmark.cmake
> [INFRA] Update dependencies

- build_system/seqan3-config.cmake
- include/seqan3/core/platform.hpp
> [INFRA] Update compiler support

- .github/workflows/ram_usage.yml
> [INFRA] Fix RAM usage workflow

- test/external_project/CMakeLists.txt
- test/external_project/install-sharg.cmake
> [TEST] Use Sharg 1.1.0 for integration test

- test/external_project/CMakeLists.txt
- test/external_project/install-sharg.cmake
> [INFRA] Try Sharg 1.1.1-rc.1

- test/documentation/seqan3-doxygen.cmake
> [FIX] SEQAN3_DOXYGEN_STD_TAGFILE

- include/seqan3/version.hpp
> [MISC] Set version to release

- .github/workflows/deploy_documentation.yaml
> [INFRA] Update documentation directory

- .github/workflows/license_check.yaml
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- test/scripts/check_markdown_doxygen.sh
> [INFRA] Check markdown files for doxygen

- include/seqan3/alignment/configuration/detail.hpp
- include/seqan3/search/configuration/detail.hpp
Two more places after rerunning gcc-trunk nightlies :)
> [MISC] gcc 14 workaorund

- include/seqan3/io/sam_file/detail/format_sam_base.hpp
> [DOC] unknown tags will not throw

- include/seqan3/contrib/std/LICENSE.md
- include/seqan3/contrib/std/LICENSES/BSD-3-Clause.txt
- include/seqan3/contrib/std/LICENSES/CC-BY-4.0.txt
- include/seqan3/contrib/std/LICENSES/CC0-1.0.txt
- include/seqan3/contrib/std/README.md
- include/seqan3/contrib/std/chunk_by_view.hpp
- include/seqan3/contrib/std/concepts.hpp
- include/seqan3/contrib/std/detail/movable_box.hpp
- include/seqan3/contrib/std/pair.hpp
- include/seqan3/contrib/std/tuple.hpp
- include/seqan3/contrib/std/zip_view.hpp
- test/documentation/seqan3_doxygen_cfg.in
> [INFRA] Update contrib/std

- CHANGELOG.md
- include/seqan3/alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
- include/seqan3/core/platform.hpp
> [INFRA] Nightly fixes

- .github/workflows/cron_avx2.yml
- .github/workflows/cron_latest_libraries.yml
> [FIX,INFRA] Cron: Always create comment body

- .github/workflows/ci_cpm.yml
- cmake/package-lock.cmake
- test/seqan3-test.cmake
> [INFRA] CPM find_package and package update cron

- include/seqan3/version.hpp
> [INFRA] Bump RC

- CHANGELOG.md
- README.md
- doc/setup/quickstart_cmake/index.md
> [DOC] Update

- .github/workflows/cron_latest_libraries.yml
> [FIX] Cron sed command

- .github/workflows/cron_latest_libraries.yml
> [INFRA,FIX] latest library sed

- .github/config/codechecker.yml
- .github/workflows/cron_codechecker.yml
> [INFRA] Update codechecker

- include/seqan3/contrib/sdsl-lite.hpp
> [MISC] Update sdsl to latest master

- include/seqan3/version.hpp
> [INFRA] Bump version
